/* LubaNote – Español · PATCH 676A */
window.LubaNoteLanguagePacks = window.LubaNoteLanguagePacks || [];

(() => {
  const anglicky = window.LubaNoteLanguagePacks.find((balicek) => balicek.id === "en") || { preklady: {}, texty: {} };

  window.LubaNoteLanguagePacks.push({
    id: "es",
    nazev: "Español",
    kratkyNazev: "ES",
    vlajka: "🇪🇸",
    locale: "es-ES",

    // Nejdřív bezpečný anglický fallback; přeložené produkční UI ho přepisuje níže.
    preklady: {
      ...anglicky.preklady,
      "language.label": "Idioma",
      "language.choose": "Elegir idioma",
      "login.splashSubtitle": "Notas • Plan • Documentos",
      "login.loading": "LubaNote se está cargando",
      "login.title": "Iniciar sesión",
      "login.registerTitle": "Registro",
      "login.modeSignIn": "Iniciar sesión",
      "login.modeRegister": "Registro",
      "login.email": "Correo electrónico",
      "login.password": "Contraseña",
      "login.passwordAgain": "Repite la contraseña",
      "login.submit": "Iniciar sesión",
      "login.registerSubmit": "Registrarse",
      "login.checkStatus": "Comprobar estado",
      "login.modeAria": "Iniciar sesión o registrarse",
      "login.downloadMyData": "Descargar mis datos",
      "login.deleteMyData": "Eliminar mis datos",
      "login.clearThisDevice": "Borrar este dispositivo",
      "login.deleteMyDataTitle": "¿Eliminar mis datos?",
      "login.clearThisDeviceTitle": "¿Borrar este dispositivo?",
      "login.clearWithoutBackup": "Borrar sin copia de seguridad",
      "login.pendingTitle": "La cuenta espera aprobación",
      "login.pendingText": "El registro está completo. LubaNote se desbloqueará cuando un administrador apruebe la cuenta.",
      "login.rejectedTitle": "El registro no fue aprobado",
      "login.rejectedText": "Esta cuenta no fue aprobada. Si se trata de un error, contacta con el administrador de LubaNote.",
      "login.suspendedTitle": "Cuenta suspendida",
      "login.suspendedText": "El acceso a LubaNote está suspendido temporalmente.",
      "login.unavailableTitle": "Cuenta no disponible",
      "login.unavailableText": "No se pudo verificar el acceso a la cuenta. Inténtalo de nuevo.",
      "login.enterCredentials": "Introduce el correo y la contraseña.",
      "login.enterRegistration": "Introduce el correo, la contraseña y repítela.",
      "login.passwordMismatch": "Las contraseñas no coinciden.",
      "login.passwordTooShort": "La contraseña debe tener al menos 8 caracteres.",
      "login.registrationOnline": "El registro requiere conexión a internet.",
      "login.registering": "Registrando…",
      "login.registrationCreated": "El registro se ha creado. Confirma tu correo y después inicia sesión.",
      "login.emailConfirmed": "Correo confirmado. Ya puedes iniciar sesión.",
      "login.emailLinkInvalid": "El enlace de confirmación ya se utilizó o ha caducado. Si tu correo está confirmado, inicia sesión.",
      "login.stillPending": "La cuenta sigue esperando aprobación.",
      "login.alreadyRegistered": "Este correo ya está registrado. Usa Iniciar sesión.",
      "login.registrationFailed": "El registro ha fallado. Comprueba el correo, la contraseña y la conexión.",
      "login.registrationRateLimited": "Se han enviado demasiados correos de confirmación. Intenta registrarte más tarde.",
      "login.signingIn": "Iniciando sesión…",
      "login.signInFailed": "No se pudo iniciar sesión. Comprueba el correo, la contraseña y la conexión.",
      "login.emailNotConfirmed": "Tu correo todavía no está confirmado. Abre el enlace de confirmación del correo y vuelve a iniciar sesión.",
      "login.accountCheckFailed": "No se pudo verificar el estado de la cuenta. Inténtalo de nuevo.",
      "login.localOwnerMismatch": "Esta instalación contiene datos locales de otra cuenta de LubaNote. Por seguridad, no se pueden mezclar cuentas en la misma instalación.",
      "login.demoExpiredTitle": "La demo ha terminado",
      "login.demoExpiredText": "Tu Demo terminó el {date}. Todos tus datos siguen guardados de forma segura. Se necesitará acceso completo a LubaNote para seguir usando la aplicación.",
      "login.fullExpiredTitle": "El acceso completo ha terminado",
      "login.fullExpiredText": "Tus datos siguen guardados de forma segura. LubaNote se desbloqueará de nuevo cuando se renueve el acceso completo.",
      "account.demoUntil": "Demo hasta {date}",
      "limits.notesTitle": "Se alcanzó el límite de notas",
      "limits.notesText": "Tu plan permite hasta {limit} notas. Ahora no se puede guardar una nota nueva de forma segura. Tus datos existentes se conservan.",
      "nav.quick": "Navegación rápida",
      "nav.tools": "Herramientas",
      "nav.home": "Inicio",
      "nav.allNotes": "Todas las notas",
      "nav.favorites": "Favoritos",
      "nav.tags": "Etiquetas",
      "nav.settings": "Ajustes",
      "nav.backup": "Copia de seguridad y restauración",
      "modules.aria": "Secciones principales de LubaNote",
      "modules.notes": "Notas",
      "storageScope.cloud": "Sincronizado",
      "storageScope.local": "Este dispositivo",
      "storageScope.menu": "Almacenamiento",
      "storageScope.choose": "¿Dónde deben guardarse las notas?",
      "storageScope.localTitle": "Solo este dispositivo",
      "storageScope.localWarning": "Las notas de este espacio no se sincronizan. Si el dispositivo se pierde o se borra, no podrán restaurarse desde la nube. Se recomiendan copias de seguridad periódicas.",
      "storageScope.shareTitle": "Solo este dispositivo",
      "storageScope.shareBlocked": "Compartir requiere almacenamiento sincronizado. Esta nota permanece solo en este dispositivo.",
      "modules.planner": "Plan",
      "modules.documents": "Documentos",
      "documents.eyebrow": "Documentos V1",
      "documents.title": "Documentos",
      "documents.addFile": "＋ Añadir archivo",
      "documents.folders": "Carpetas",
      "documents.newFolder": "Nueva carpeta",
      "documents.files": "Archivos",
      "documents.allFiles": "Todos los archivos",
      "documents.searchPlaceholder": "Buscar…",
      "documents.searchAria": "Buscar archivos",
      "documents.clearSearch": "Borrar búsqueda",
      "documents.filterAria": "Filtro de documentos",
      "documents.filterAll": "Todos",
      "documents.trash": "Papelera",
      "documents.folderFallback": "Carpeta",
      "documents.localAndroid": "Guardado localmente en este dispositivo Android",
      "documents.localBrowser": "Guardado localmente en este navegador",
      "documents.fileCount.one": "{count} archivo",
      "documents.fileCount.other": "{count} archivos",
      "plannerTabs.calendar": "Calendario",
      "modules.reminders": "Recordatorios",
      "sync.synced": "✓ Sincronizado",
      "sync.syncing": "⟳ Sincronizando…",
      "sync.pending": "⏳ Pendiente de sincronización",
      "sync.localOnly": "📱 Solo este dispositivo",
      "sync.authExpired": "⚠ La sesión ha caducado",
      "sync.conflict": "⚠ Conflicto",
      "search.placeholder": "Buscar…",
      "search.aria": "Buscar notas",
      "search.clear": "Borrar búsqueda",
      "search.view": "Cambiar diseño de tarjetas",
      "search.menu": "Menú principal",
      "sort.labelNewest": "Tarjetas nuevas: arriba",
      "sort.labelOldest": "Tarjetas nuevas: abajo",
      "sort.title": "Posición de tarjetas nuevas",
      "sort.newest": "Tarjetas nuevas arriba",
      "sort.oldest": "Tarjetas nuevas abajo",
      "search.none": "No se encontraron notas.",
      "menu.manageTags": "Gestionar etiquetas",
      "menu.about": "Acerca de",
      "menu.logout": "Cerrar sesión",
      "filter.aria": "Filtros de notas",
      "filter.all": "Todas",
      "filter.work": "Trabajo",
      "filter.private": "Privadas",
      "filter.favorite": "Notas favoritas",
      "filter.secret": "Notas secretas",
      "filter.finishSelection": "Finalizar selección",
      "calendar.previousMonth": "Mes anterior",
      "calendar.nextMonth": "Mes siguiente",
      "calendar.selectedDay": "Día seleccionado",
      "calendar.addSelected": "Añadir tarea al día seleccionado",
      "calendar.back": "Volver al calendario",
      "calendar.addDay": "Añadir tarea a este día",
      "calendar.week": "semana",
      "calendar.weekNumber": "Semana {value}",
      "weekday.mo": "Lun",
      "weekday.tu": "Mar",
      "weekday.we": "Mié",
      "weekday.th": "Jue",
      "weekday.fr": "Vie",
      "weekday.sa": "Sáb",
      "weekday.su": "Dom",
      "recurring.title": "Recurrentes",
      "recurring.back": "Volver a recordatorios",
      "recurring.show": "Mostrar tareas recurrentes",
      "recurring.none": "No hay tareas recurrentes.",
      "recurring.repeat": "Se repite",
      "recurring.next": "Siguiente: {value}",
      "recurring.noNext": "Esta serie no tiene una siguiente aparición.",
      "reminders.overdue": "Vencidos",
      "reminders.active": "Activos",
      "reminders.today": "Hoy",
      "reminders.none": "No hay recordatorios.",
      "reminders.noneOverdue": "No hay recordatorios vencidos.",
      "reminders.tomorrow": "Mañana",
      "reminders.later": "Más tarde",
      "reminders.label": "Recordatorio",
      "reminders.untitled": "Sin título",
      "reminders.close": "Cerrar",
      "reminders.tomorrow8": "Mañana 8:00",
      "reminders.date": "Fecha",
      "reminders.time": "Hora",
      "reminders.selectDate": "Elegir fecha del recordatorio",
      "reminders.selectTime": "Elegir hora del recordatorio",
      "reminders.done": "Hecho",
      "reminders.delete": "Eliminar",
      "reminders.openNote": "Abrir nota",
      "reminders.turnOff": "Desactivar recordatorio",
      "editor.find": "Buscar",
      "editor.findInNote": "Buscar en esta nota",
      "editor.findPrevious": "Resultado anterior",
      "editor.findNext": "Resultado siguiente",
      "editor.findClose": "Cerrar búsqueda",
      "editor.openTools": "Abrir herramientas de edición",
      "editor.formatting": "Formato de la nota",
      "editor.moreTools": "Más herramientas de la nota",
      "editor.undo": "Deshacer",
      "editor.redo": "Rehacer",
      "editor.bold": "Negrita",
      "editor.italic": "Cursiva",
      "editor.underline": "Subrayado",
      "editor.fontSize": "Tamaño de fuente",
      "editor.textStyle": "Estilo de texto",
      "editor.textColor": "Color de texto",
      "editor.white": "Texto blanco",
      "editor.black": "Texto negro",
      "editor.align": "Alineación del texto",
      "editor.alignLeft": "Alinear a la izquierda",
      "editor.alignCenter": "Centrar",
      "editor.alignRight": "Alinear a la derecha",
      "editor.insertImage": "Insertar imagen",
      "editor.insertWebLink": "Insertar enlace web",
      "editor.webLink": "Enlace web",
      "editor.openDocument": "Abrir documento",
      "editor.saveAs": "Guardar como",
      "editor.bullets": "Lista con viñetas",
      "editor.date": "Fecha",
      "editor.time": "Hora",
      "editor.selectDate": "Elegir fecha",
      "editor.selectTime": "Elegir hora",
      "editor.pin": "Fijar nota",
      "editor.reminder": "Recordatorio",
      "editor.backLink": "Volver a la nota enlazada anterior",
      "editor.titleAria": "Título de la nota",
      "editor.titlePlaceholder": "Título de la nota",
      "editor.secret": "Nota secreta",
      "editor.tags": "Etiquetas",
      "editor.newTag": "Nueva etiqueta",
      "editor.cancelNewTag": "Cancelar nueva etiqueta",
      "editor.saveClose": "Guardar y cerrar",
      "editor.area": "Área de la nota",
      "editor.priority": "Prioridad",
      "editor.color": "Color",
      "editor.planSelection": "Planificar texto seleccionado",
      "editor.addTodo": "Añadir elemento TODO",
      "editor.deleteNote": "Eliminar nota",
      "backlinks.aria": "Enlaces a esta nota",
      "backlinks.title": "Enlaces a esta nota ({count})",
      "backlinks.none": "No hay enlaces a esta nota",
      "actions.save": "Guardar",
      "actions.discard": "No guardar",
      "actions.ok": "OK",
      "status.done": "Hecho",
      "secret.mainPassword": "Contraseña principal",
      "secret.passwordAgain": "Repite la contraseña",
      "secret.enterMain": "Introduce la contraseña principal.",
      "actions.term": "Fecha límite",
      "actions.pin": "Fijar",
      "actions.delete": "Eliminar",
      "actions.more": "Más acciones",
      "actions.cancel": "Cancelar",
      "actions.create": "Crear",
      "message.notice": "Aviso",
      "editor.notePlaceholder": "Escribe una nota…",
      "tags.name": "Nombre de la etiqueta",
      "tags.add": "Añadir",
      "deleteNote.message": "¿Seguro que quieres eliminar esta nota?",
      "deleteNote.title": "¿Eliminar nota?",
      "timePicker.title": "Elegir hora",
      "timePicker.close": "Cerrar selector de hora",
      "timePicker.clock": "Esfera del selector de hora",
      "repeat.title": "Repetir",
      "repeat.aria": "Repetición de tarea",
      "repeat.no": "No",
      "repeat.daily": "Diariamente",
      "repeat.weekly": "Semanalmente",
      "repeat.twoWeeks": "2 semanas",
      "repeat.monthly": "Mensualmente",
      "repeat.none": "No repetir",
      "planner.plan": "Planificar",
      "planner.close": "Cerrar planificación",
      "planner.selectDate": "Elegir fecha de la tarea planificada",
      "planner.selectTime": "Elegir hora de la tarea planificada",
      "sharing.settingsTitle": "Compartir",
      "sharing.usernameLabel": "Nombre de usuario",
      "sharing.usernameUnset": "Configurar",
      "sharing.usernameModalTitle": "Nombre de usuario para compartir",
      "sharing.usernameDescription": "Otras personas solo pueden encontrarte por tu @nombre de usuario exacto. Tu correo nunca se muestra al compartir.",
      "sharing.usernamePlaceholder": "p. ej. Lubomir",
      "sharing.usernameSave": "Guardar",
      "sharing.usernameCancel": "Cancelar",
      "sharing.usernameInvalid": "Usa entre 3 y 30 caracteres: letras, números, punto, guion o guion bajo.",
      "sharing.usernameTaken": "Este @nombre de usuario ya lo usa otra persona.",
      "sharing.usernameOffline": "Configurar un @nombre de usuario requiere conexión a internet.",
      "sharing.usernameSaving": "Guardando…",
      "sharing.usernameSaveFailed": "No se pudo guardar el nombre de usuario.",
      "sharing.usernameRequiredTitle": "Crea tu @nombre de usuario",
      "sharing.usernameRequiredDescription": "Antes de usar LubaNote, crea un @nombre de usuario público para compartir y chatear. Otras personas solo pueden encontrarte por el @nombre exacto; tu correo no se muestra.",
      "sharing.usernameRequiredSave": "Crear y continuar",
      "sharing.shareButton": "Compartir",
      "sharing.invitationsAria": "Invitaciones para compartir",
      "sharing.shareModalTitle": "Compartir nota",
      "sharing.shareModalDescription": "Invita a un usuario introduciendo su @nombre de usuario exacto.",
      "sharing.shareInputPlaceholder": "p. ej. LubaNoteDemo",
      "sharing.shareSend": "Enviar invitación",
      "sharing.shareSending": "Enviando…",
      "sharing.shareSendSuccess": "Invitación enviada.",
      "sharing.shareSendFailed": "No se pudo enviar la invitación.",
      "sharing.shareInvalidUsername": "Introduce un @nombre de usuario válido.",
      "sharing.shareOffline": "Compartir requiere conexión a internet.",
      "sharing.shareUsernameMissing": "Primero configura tu propio @nombre de usuario en Ajustes.",
      "sharing.shareUserNotFound": "No se encontró ningún usuario con ese @nombre exacto.",
      "sharing.shareSelf": "No puedes compartir una nota contigo mismo.",
      "sharing.shareAlreadyCollaborator": "Este usuario ya colabora en la nota.",
      "sharing.shareAlreadyPending": "Ya hay una invitación pendiente para este usuario.",
      "sharing.shareSecretBlocked": "Las notas secretas todavía no se pueden compartir.",
      "sharing.shareNewNoteBlocked": "Guarda primero la nota y después podrás compartirla.",
      "sharing.collaboratorsTitle": "Colaboradores",
      "sharing.collaboratorsEmpty": "Aún no hay colaboradores.",
      "sharing.pendingTitle": "Invitaciones pendientes",
      "sharing.pendingEmpty": "No hay invitaciones pendientes.",
      "sharing.cancelInvitation": "Cancelar",
      "sharing.cancelFailed": "No se pudo cancelar la invitación.",
      "sharing.cancel": "Cancelar",
      "sharing.removeCollaborator": "Eliminar",
      "sharing.removeCollaboratorConfirm": "¿Eliminar a {username} del uso compartido?",
      "sharing.removeCollaboratorSuccess": "Colaborador eliminado.",
      "sharing.removeCollaboratorFailed": "No se pudo eliminar al colaborador.",
      "sharing.removeCollaboratorMissing": "Este usuario ya no comparte la nota.",
      "sharing.manageNotOwner": "Solo el propietario de la nota puede realizar esta acción.",
      "sharing.manageModalUnavailable": "No se pudo abrir el cuadro de confirmación.",
      "sharing.leaveSharedNote": "Dejar de compartir",
      "sharing.leaveConfirm": "¿Dejar de compartir esta nota?",
      "sharing.leaveSuccess": "Has dejado de compartir.",
      "sharing.leaveFailed": "No se pudo dejar de compartir.",
      "sharing.ownerCannotLeave": "El propietario no puede dejar de compartir. Transfiere primero la propiedad.",
      "sharing.ownerRole": "Propietario",
      "sharing.editorRole": "Editor",
      "sharing.invitationsTitle": "Invitaciones para compartir",
      "sharing.invitationsEmpty": "No tienes invitaciones pendientes.",
      "sharing.invitedBy": "Invitado por {username}",
      "sharing.accept": "Aceptar",
      "sharing.decline": "Rechazar",
      "sharing.responding": "Procesando…",
      "sharing.invitationAccepted": "Invitación aceptada.",
      "sharing.invitationDeclined": "Invitación rechazada.",
      "sharing.invitationResponseFailed": "No se pudo procesar la invitación.",
      "sharing.refresh": "Actualizar",
      "sharing.close": "Cerrar",
      "sharing.loading": "Cargando…",
      "sharing.loadFailed": "No se pudieron cargar los datos compartidos.",
      "sharing.sharedUntitled": "Sin título",
      "sharing.sharedCardMeta": "Compartida · {owner}",
      "sharing.readOnlyTitle": "Nota compartida",
      "sharing.readOnlyMeta": "{owner} · nota compartida",
      "sharing.readOnlyTodos": "Tareas",
      "sharing.editShared": "Editar",
      "sharing.sharedEditorOffline": "Una nota compartida solo se puede editar estando en línea.",
      "sharing.sharedEditorBusy": "{username} está editando esta nota ahora mismo. Por ahora solo puedes leerla.",
      "sharing.sharedEditorOpening": "Abriendo editor compartido…",
      "sharing.sharedEditorSaveFailed": "No se pudo guardar de forma segura la nota compartida. El editor permanece abierto.",
      "sharing.sharedEditorConflict": "Existe una versión más reciente de la nota en el servidor. El editor permanece abierto; ciérralo sin guardar y vuelve a abrir la nota.",
      "sharing.sharedEditorLockLost": "El bloqueo del editor ya no es válido. El editor compartido se cerró de forma segura.",
      "sharing.sharedEditorSaved": "Nota compartida guardada.",
      "chat.buttonAria": "Mensajes",
      "chat.contactsTitle": "Mensajes",
      "chat.contactsEmpty": "Aún no tienes contactos de chat. Se crea un contacto después de aceptar una invitación para compartir una nota.",
      "chat.writeMessage": "Escribir mensaje",
      "chat.trustedContact": "Contacto de uso compartido",
      "chat.ready": "Podéis enviaros mensajes",
      "chat.lastMessageAt": "Último mensaje {time}",
      "chat.messagePlaceholder": "Escribe un mensaje…",
      "chat.send": "Enviar",
      "chat.sending": "Enviando…",
      "chat.sent": "Enviado",
      "chat.read": "Leído",
      "chat.messagesEmpty": "Aún no hay mensajes.",
      "chat.deletedPlaceholder": "El mensaje fue eliminado",
      "chat.deleteMessage": "Eliminar mensaje",
      "chat.deleteTitle": "¿Eliminar mensaje?",
      "chat.deleteText": "El mensaje se eliminará para ambos participantes y solo quedará un aviso de mensaje eliminado.",
      "chat.deleteForBoth": "Eliminar para ambos",
      "chat.deleting": "Eliminando…",
      "chat.deleteFailed": "No se pudo eliminar el mensaje.",
      "chat.sendFailed": "No se pudo enviar el mensaje.",
      "chat.loadFailed": "No se pudo cargar el chat.",
      "chat.loadMessagesFailed": "No se pudieron cargar los mensajes.",
      "chat.loading": "Cargando…",
      "chat.offline": "El chat requiere conexión a internet.",
      "chat.blocked": "El chat está bloqueado",
      "chat.contactNotFound": "El contacto del chat aún no está disponible.",
      "chat.tooLong": "El mensaje es demasiado largo.",
      "chat.close": "Cerrar",
      "chat.back": "Atrás",
      "chat.cancel": "Cancelar",
      "chat.threadAria": "Chat",
      "settings.personalDictionary": "Mi diccionario",
      "settings.languageLearning": "Aprendizaje de idiomas",
      "settings.manageDictionary": "Gestionar",
      "settings.openLearning": "Abrir",
      "settings.wordsCount.one": "{count} palabra",
      "settings.wordsCount.other": "{count} palabras",
      "settings.plannerReminderDefault": "Recordar automáticamente al planificar",
      "settings.enabled": "Activado",
      "settings.disabled": "Desactivado",
      "settings.planning": "Planificación",
      "settings.automaticReminder": "Recordatorio automático",
      "settings.title": "Ajustes",
      "settings.close": "Cerrar ajustes",
      "settings.appearance": "Apariencia",
      "settings.fontSize": "Tamaño de fuente",
      "settings.decreaseFont": "Reducir tamaño de fuente",
      "settings.increaseFont": "Aumentar tamaño de fuente",
      "settings.theme": "Tema de color",
      "settings.iconStyle": "Estilo de iconos",
      "settings.keyboard": "Teclado del editor",
      "settings.keyboardTitle": "Teclado del editor",
      "settings.keyboardLuba": "LubaKeyboard (predeterminado)",
      "settings.keyboardSystem": "Sistema",
      "settings.keyboardSystemLong": "Teclado del sistema (Gboard / iOS)",
      "settings.reminders": "Recordatorios",
      "settings.quickDelay": "Posponer rápido",
      "settings.configure": "Configurar",
      "settings.overdueRetention": "Eliminar vencidos después de",
      "settings.overdueNever": "Nunca",
      "settings.overdueDays": "{count} días",
      "settings.overdueConfirm": "confirmar",
      "settings.data": "Datos",
      "settings.noteOpenPosition": "Al abrir una nota",
      "settings.noteOpenStart": "Inicio",
      "settings.noteOpenEnd": "Final",
      "settings.export": "Exportar copia de seguridad",
      "settings.import": "Importar copia de seguridad",
      "settings.about": "Acerca de",
      "settings.version": "Versión",
      "settings.appInfo": "Información de la aplicación",
      "settings.open": "Abrir",
      "theme.light": "Claro",
      "theme.dark": "Oscuro",
      "icons.classic": "Iconos clásicos",
      "icons.svg": "Iconos SVG",
      "about.close": "Cerrar información de la aplicación",
      "about.description": "Notas, tareas, planificación y recordatorios en un solo lugar.",
      "addNote": "Añadir nota",
      "tags.new": "Nueva etiqueta",
      "tags.newSecret": "Nueva etiqueta secreta",
      "tags.manage": "Gestionar etiquetas",
      "tags.closeManage": "Cerrar gestión de etiquetas",
      "tags.deleteTitle": "¿Eliminar etiqueta?",
      "secret.saveSecret": "Guardar como secreto",
      "secret.saveNormal": "Guardar normalmente",
      "secret.mode": "Modo secreto",
      "secret.close": "Cerrar modo secreto",
      "secret.fingerprint": "Desbloquear con huella",
      "secret.nextFingerprint": "🫆 Usar huella la próxima vez",
      "secret.thisDevice": "Solo en este dispositivo",
      "secret.unlock": "Desbloquear",
      "secret.tags": "Etiquetas secretas",
      "secret.createTag": "Crear etiqueta secreta",
      "secret.disableFingerprint": "Desactivar desbloqueo con huella",
      "secret.lock": "Bloquear modo secreto",
      "selection.cut": "Cortar",
      "selection.copy": "Copiar",
      "selection.paste": "Pegar",
      "selection.all": "Todo",
      "selection.dictionary": "Diccionario",
      "selection.translate": "Traducir",
      "noteLinks.noMatch": "No hay ninguna nota coincidente",
      "noteLinks.create": "+ Crear nota “{value}”",
      "noteLinks.deleted": "⚠ Nota eliminada",
      "noteLinks.unavailable": "La nota de destino ya no está disponible.",
      "noteLinks.previous": "Nota anterior",
      "noteLinks.createFailed": "No se pudo crear de forma segura la nota enlazada.",
      "noteLinks.ariaTarget": "Enlace interno a la nota {value}",
      "noteLinks.ariaMissing": "Enlace interno a una nota no disponible",
      "noteLinks.dialogTitle": "Enlace interno",
      "trash.title": "Papelera",
      "trash.secretTitle": "Papelera secreta",
      "trash.close": "Cerrar Papelera",
      "trash.autoDeleteInfo": "Las notas se eliminan permanentemente de forma automática después de 30 días.",
      "trash.empty": "La Papelera está vacía.",
      "trash.untitled": "Sin título",
      "trash.noPreview": "Sin vista previa",
      "trash.moved": "En la Papelera desde",
      "trash.daysLeft": "Eliminación permanente en {count} días",
      "trash.restore": "Restaurar",
      "trash.deleteForever": "Eliminar permanentemente",
      "trash.deleteForeverTitle": "¿Eliminar permanentemente?",
      "trash.deleteConfirm": "Esta nota se eliminará permanentemente y no se podrá restaurar.",
      "trash.moveTitle": "¿Mover a la Papelera?",
      "trash.moveMessage": "La nota se moverá a la Papelera y podrá restaurarse más tarde.",
      "trash.moveAction": "Mover a la Papelera",
      "trash.moveManyMessage": "¿Mover {count} notas seleccionadas a la Papelera?",
      "trash.movedMany": "Movidas a la Papelera: {count} notas",
      "trash.normalTab": "Normal",
      "trash.secretTab": "Secretas 🔒",
      "trash.typeTabsLabel": "Tipo de Papelera",
      "trash.selectAll": "Seleccionar todo",
      "trash.clearSelection": "Borrar selección",
      "trash.deleteSelected": "Eliminar permanentemente ({count})",
      "trash.deleteManyNormalConfirm": "¿Eliminar permanentemente {count} elementos de la Papelera normal? Esta acción no se puede deshacer.",
      "trash.deleteManySecretConfirm": "¿Eliminar permanentemente {count} elementos de la Papelera secreta? Esta acción no se puede deshacer.",
      "trash.bulkDeletePreparing": "Preparando eliminación…",
      "trash.bulkDeleting": "Eliminando…",
      "trash.bulkDeleteProgress": "Eliminando elementos… {done} / {total}",
      "trash.bulkDeleteSyncing": "Sincronizando cambios…",
      "trash.bulkDeleteDoneAction": "Hecho",
      "trash.bulkDeletePending": "Eliminado en este dispositivo. La sincronización terminará automáticamente.",
      "trash.bulkDeleteOffline": "Eliminado en este dispositivo. La sincronización se ejecutará cuando vuelvas a estar en línea.",
      "trash.bulkDeleteFailed": "No se pudo completar la eliminación de forma segura. Los elementos permanecieron en la Papelera.",
      "actions.apply": "Aplicar",
      "actions.close": "Cerrar",
      "actions.edit": "Editar",
      "actions.next": "Siguiente",
      "actions.open": "Abrir",
      "actions.previous": "Anterior",
      "actions.rename": "Renombrar",
      "actions.update": "Actualizar",
      "calendar.chooseMonth": "Elegir mes",
      "choice.enterValue": "Introduce un valor",
      "choice.maximum": "Máximo: {value}",
      "choice.minimum": "Mínimo: {value}",
      "choice.selectOption": "Elige una opción",
      "choice.validNumber": "Introduce un número válido.",
      "choice.value": "Valor",
      "datePicker.today": "Hoy",
      "dictionary.add": "Añadir",
      "dictionary.addOwn": "Añadir palabra propia…",
      "dictionary.empty": "El diccionario está vacío.",
      "dictionary.language": "Idioma del diccionario",
      "dictionary.search": "Buscar en el diccionario…",
      "documents.addDocument": "Añadir documento",
      "documents.cannotOpenType": "Este tipo de archivo aún no se puede abrir.",
      "documents.chooseFileType": "Elige un tipo de archivo. El documento permanecerá solo en este dispositivo.",
      "documents.closeDocument": "Cerrar documento",
      "documents.contentUnsafe": "No se puede cargar el contenido del archivo de forma segura.",
      "documents.copyFailedLongPress": "No se pudo copiar. Intenta seleccionar el texto con una pulsación larga.",
      "documents.copySqlAria": "Copiar todo el script SQL",
      "documents.createFolderFailed": "No se pudo crear la carpeta.",
      "documents.deleteEmptyFolder": "La carpeta «{name}» está vacía. Solo se eliminará la carpeta.",
      "documents.deleteFolder": "Eliminar carpeta",
      "documents.deleteFolderFailed": "No se pudo eliminar la carpeta de forma segura.",
      "documents.deleteFolderTitle": "¿Eliminar carpeta?",
      "documents.deleteFolderWithFiles": "La carpeta «{name}» contiene {count}. Los documentos NO se eliminarán: se moverán a «Todos los archivos». Después se eliminará solo la carpeta.",
      "documents.deleteForeverFailed": "No se pudo eliminar el documento permanentemente.",
      "documents.deleteForeverMessage": "«{name}» se eliminará permanentemente de este dispositivo. Esta acción no se puede deshacer.",
      "documents.deleteForeverTitle": "¿Eliminar documento permanentemente?",
      "documents.docDescription": "lectura local del texto del formato antiguo",
      "documents.docInvalid": "El archivo no es un Word DOC válido.",
      "documents.docNoReadableText": "El DOC no contiene texto legible o usa una variante que el visor aún no admite.",
      "documents.docNotLegacy": "El archivo no es un Word DOC antiguo (OLE/CFB).",
      "documents.docOldUnsupported": "Este primer visor DOC admite Word 97–2003. Word 6/95 más antiguo aún no es compatible.",
      "documents.docOpenFailed": "No se pudo abrir el DOC. Se admite Word 97–2003 y esta primera versión conserva principalmente el texto legible.",
      "documents.docReadOnly": "DOC · SOLO LECTURA",
      "documents.docTooLarge": "El DOC es demasiado grande. El tamaño máximo es 24 MB.",
      "documents.docTooLarge24": "El DOC es demasiado grande. El tamaño máximo es 24 MB.",
      "documents.docUnsupported": "El archivo no es un Word DOC compatible.",
      "documents.document": "Documento",
      "documents.docxDescription": "se abre en modo de solo lectura en Documentos",
      "documents.docxOpenFailed": "No se pudo abrir el DOCX. El archivo puede estar dañado o usar un elemento que este visor aún no admite.",
      "documents.docxReadOnly": "DOCX · SOLO LECTURA",
      "documents.docxTooLarge": "El DOCX es demasiado grande. El tamaño máximo es 20 MB.",
      "documents.dragReorder": "Arrastra para cambiar el orden",
      "documents.dragToFolder": "Arrastra a la carpeta de destino",
      "documents.dropInto": "Soltar en «{name}»",
      "documents.emptyDoc": "Aún no hay ningún DOC",
      "documents.emptyDocument": "Aún no hay ningún documento",
      "documents.emptyDocx": "Aún no hay ningún DOCX",
      "documents.emptyEpub": "Aún no hay ningún libro EPUB",
      "documents.emptyHint": "Añade tu primer PDF, DOCX, DOC, EPUB o SQL. SQL se abre localmente en modo de solo lectura.",
      "documents.emptyPdf": "Aún no hay ningún PDF",
      "documents.emptySql": "Aún no hay ningún archivo SQL",
      "documents.epubBook": "Libro electrónico EPUB",
      "documents.epubDescription": "se abre en el LubaReader local",
      "documents.epubEncryptedUnsupported": "Los EPUB cifrados no son compatibles.",
      "documents.epubInvalid": "El archivo no es un EPUB válido.",
      "documents.epubMissingPackage": "El EPUB no contiene una ruta al paquete OPF.",
      "documents.epubNoChapters": "El EPUB no tiene una secuencia de capítulos legible.",
      "documents.epubOpenFailed": "No se pudo abrir el EPUB. El libro puede estar dañado o protegido por DRM.",
      "documents.epubReaderMissing": "El lector EPUB no está cargado.",
      "documents.epubTooLarge100": "El EPUB es demasiado grande. El tamaño máximo es 100 MB.",
      "documents.epubWebViewUnsupported": "Este WebView no puede descomprimir EPUB.",
      "documents.fileActions": "Acciones del archivo",
      "documents.fileActionsNamed": "Acciones del archivo {name}",
      "documents.fileName": "Nombre del archivo",
      "documents.fileTooLarge20": "El archivo es demasiado grande. El tamaño máximo es 20 MB.",
      "documents.fileUnavailable": "El archivo ya no está disponible.",
      "documents.folderActions": "Acciones de la carpeta",
      "documents.folderActionsNamed": "Acciones de la carpeta {name}",
      "documents.folderExists": "La carpeta «{name}» ya existe.",
      "documents.folderLocalHint": "La carpeta está por ahora solo en este dispositivo.",
      "documents.folderLocalMeta": "{count} · local en el dispositivo",
      "documents.folderName": "Nombre de la carpeta",
      "documents.folderOrderFailed": "No se pudo guardar el orden de las carpetas.",
      "documents.inTrashTitle": "Documento en la papelera",
      "documents.libraryLoadFailed": "No se pudo cargar la biblioteca local de documentos.",
      "documents.loadFailed": "No se pudo cargar el documento.",
      "documents.longPressMoveTitle": "Mantén pulsado y arrastra para mover",
      "documents.longPressReorderTitle": "Mantén pulsado y arrastra para reordenar",
      "documents.lubanoteNote": "Nota de LubaNote",
      "documents.metadataFallback": "No se pudieron cargar los metadatos del documento LubaNote; se usará una importación HTML normal.",
      "documents.moveFailed": "No se pudo mover el archivo.",
      "documents.newDocument": "Nuevo documento",
      "documents.noDisplayableContent": "El documento no contiene contenido que se pueda mostrar.",
      "documents.noFolders": "Aún no tienes ninguna carpeta.",
      "documents.noReadableText": "El documento no contiene texto legible.",
      "documents.nothingFound": "No encontramos nada",
      "documents.nothingToCopy": "No hay nada que copiar.",
      "documents.openDocument": "Abrir documento",
      "documents.openFailed": "No se pudo abrir el archivo.",
      "documents.openNamed": "Abrir {name}",
      "documents.openPdf": "Abrir PDF",
      "documents.openingDoc": "Abriendo DOC…",
      "documents.openingDocument": "Abriendo documento…",
      "documents.openingDocx": "Abriendo DOCX…",
      "documents.openingSql": "Abriendo SQL…",
      "documents.pdfDescription": "se abre en el visor PDF existente",
      "documents.pdfDisplayFailed": "No se pudo mostrar el PDF. El archivo puede estar dañado o protegido con contraseña.",
      "documents.pdfOpenFailed": "No se pudo abrir el PDF.",
      "documents.pdfTooLarge": "El PDF es demasiado grande. El tamaño máximo es 100 MB.",
      "documents.pdfTooLargeWeb": "El PDF es demasiado grande. El tamaño máximo en la versión web es 100 MB.",
      "documents.pdfViewerUnavailable": "El visor PDF no está disponible.",
      "documents.renameDocument": "Renombrar documento",
      "documents.renameDocumentHint": "Solo cambiará el nombre en la biblioteca de LubaNote. El contenido del documento no cambiará.",
      "documents.renameFailed": "No se pudo renombrar el documento.",
      "documents.renameFolder": "Renombrar carpeta",
      "documents.renameFolderFailed": "No se pudo renombrar la carpeta.",
      "documents.renameFolderHint": "Solo cambiará el nombre de la carpeta. Los documentos que contiene no cambiarán.",
      "documents.renameType": "Renombrar {type}",
      "documents.renameTypeHint": "Solo cambiará el nombre en la biblioteca de LubaNote. El contenido de {type} no cambiará.",
      "documents.restoreFailed": "No se pudo restaurar el documento.",
      "documents.restoreFromTrash": "Restaurar de la papelera",
      "documents.saveAs": "Guardar como",
      "documents.saveFailed": "No se pudo guardar el documento.",
      "documents.saveHtml": "HTML – conservar formato",
      "documents.savePdf": "PDF – documento final",
      "documents.saveTxt": "TXT – texto sin formato",
      "documents.searchEmpty": "No hay ningún documento que coincida con «{query}».",
      "documents.secretExternalOpenBlocked": "Los documentos externos no están disponibles en el modo Secret. Secret permanece separado.",
      "documents.secretExternalSaveBlocked": "Una nota Secret no se puede guardar en un documento externo. El modo Secret permanece separado.",
      "documents.secretExternalSaveBlockedShort": "Una nota Secret no se puede guardar en un documento externo.",
      "documents.sqlCopied": "Se copió todo el script SQL.",
      "documents.sqlDescription": "se abre localmente en modo de solo lectura como código fuente",
      "documents.sqlEmpty": "El archivo SQL está vacío.",
      "documents.sqlOpenFailed": "No se pudo abrir el SQL.",
      "documents.sqlReadFailed": "No se pudo leer el SQL.",
      "documents.sqlReadOnly": "SQL · SOLO LECTURA",
      "documents.sqlScript": "Script SQL",
      "documents.sqlTooLarge": "El SQL es demasiado grande. El tamaño máximo es 10 MB.",
      "documents.targetFolderUnavailable": "La carpeta de destino ya no está disponible.",
      "documents.textDocument": "Documento de texto",
      "documents.trashEmpty": "La papelera está vacía",
      "documents.trashEmptyHint": "Los documentos movidos a la papelera aparecerán aquí y se podrán restaurar o eliminar permanentemente.",
      "documents.trashMoveFailed": "No se pudo mover el documento a la papelera.",
      "documents.unsafeElement": "El documento contiene un elemento que Core V2 no puede importar de forma segura. Los datos no se modificaron.",
      "documents.unsupportedType": "Este tipo de archivo aún no es compatible. Elige PDF, DOCX, DOC, EPUB o SQL.",
      "documents.wordReadOnly": "WORD · SOLO LECTURA",
      "editor.tasks": "Tareas",
      "learning.addWord": "Añadir palabra",
      "learning.addWordLanguage": "Añadir palabra · {language}",
      "learning.addWordLanguageDot": "Añadir palabra · {language}",
      "learning.alreadyInDictionary": "Esta palabra ya está en tu diccionario de estudio.",
      "learning.changeLanguage": "Cambiar idioma",
      "learning.close": "Cerrar Aprendizaje de idiomas",
      "learning.closeTranslation": "Cerrar traducción",
      "learning.contextOptional": "Contexto (opcional)",
      "learning.dictionary": "Diccionario",
      "learning.dontKnow": "No sé",
      "learning.duplicate": "Ya tienes esta palabra en este idioma.",
      "learning.editWord": "Editar palabra",
      "learning.empty": "Aún no hay palabras.",
      "learning.enterOrSelectTerm": "Primero escribe o selecciona una palabra o frase.",
      "learning.errorDifferentLanguages": "Los idiomas de origen y destino deben ser distintos.",
      "learning.errorOnlineRequired": "La traducción requiere conexión a Internet.",
      "learning.errorSelectTerm": "Selecciona una palabra o frase.",
      "learning.errorShorterTerm": "Selecciona una palabra o frase más corta para traducir.",
      "learning.errorTranslateAuto": "No se pudo obtener la traducción automática. Puedes escribirla manualmente.",
      "learning.errorTranslateUnavailable": "La traducción en línea no está disponible ahora. Puedes escribirla manualmente.",
      "learning.fillOrTranslate": "Escribe la traducción o toca Traducir.",
      "learning.fillTerm": "Introduce una palabra o frase.",
      "learning.fillTranslation": "Escribe la traducción o toca Traducir.",
      "learning.fillTranslationFirst": "Primero introduce la traducción.",
      "learning.know": "Sé",
      "learning.languageLearningLanguage": "Aprendizaje de idiomas · {language}",
      "learning.manualAdd": "Añadir palabra",
      "learning.noMistakesYet": "Aún no hay errores",
      "learning.onlineTranslationPrivacy": "Traducción en línea · {direction} · solo se envía el término seleccionado.",
      "learning.playPronunciation": "Reproducir pronunciación",
      "learning.playPronunciationLanguage": "Reproducir pronunciación · {language}",
      "learning.playPronunciationTerm": "Reproducir pronunciación de la palabra",
      "learning.practiceEmpty": "No hay nada que practicar.",
      "learning.practiceLanguage": "Practicar {language}",
      "learning.practiceLanguageAria": "Practicar el idioma {language}",
      "learning.practiceWrongOnly": "Practicar solo las palabras que no sé",
      "learning.saveChanges": "Guardar cambios",
      "learning.saveFailed": "No se pudo guardar la palabra.",
      "learning.saveToDictionary": "＋ Guardar en el diccionario",
      "learning.savedToLearning": "Guardado en Aprendizaje de idiomas.",
      "learning.search": "Buscar palabra…",
      "learning.showTranslation": "Mostrar traducción",
      "learning.sourceManual": "Añadido manualmente",
      "learning.sourceNote": "Nota",
      "learning.sourceOptional": "Fuente (opcional)",
      "learning.sourceSeed": "Conjunto de prueba de LubaNote",
      "learning.statsDue": "Pendientes de práctica",
      "learning.statsMastered": "Dominadas",
      "learning.statsReviews": "Repasos",
      "learning.statsSaved": "Guardadas",
      "learning.tabPractice": "Práctica",
      "learning.tabStats": "Estadísticas",
      "learning.tabWords": "Palabras",
      "learning.termOrPhrase": "Palabra / frase",
      "learning.trainingAllOk": "Práctica terminada 🥳 Todas las palabras estaban bien.",
      "learning.translate": "Traducir",
      "learning.translateFailed": "No se pudo obtener la traducción.",
      "learning.translating": "Traduciendo…",
      "learning.translatingDirection": "Traduciendo · {direction}…",
      "learning.translation": "Traducción",
      "learning.translationDictionary": "Traducción y diccionario",
      "learning.translationDirection": "Traducción · {direction}",
      "learning.translationEditable": "Puedes editar la traducción antes de guardarla.",
      "learning.translationPlaceholder": "Traducción…",
      "learning.updateInDictionary": "Actualizar en el diccionario",
      "learning.wordUpdated": "Palabra actualizada.",
      "pdf.androidPickerHint": "Android solo abrirá el selector del archivo de destino.",
      "pdf.chooseAndroidDestination": "Después de confirmar, elegirás la ubicación de destino en Android.",
      "pdf.chooseFileName": "Elige el nombre del archivo PDF.",
      "pdf.chooseOtherLocation": "Elegir otra ubicación…",
      "pdf.close": "Cerrar PDF",
      "pdf.directCreateFailed": "No se pudo crear el PDF directo.",
      "pdf.directDownloadInfoHtml": "El PDF se guardará sin otra ventana en <strong>Descargas/LubaNote</strong>.",
      "pdf.directSaveHint": "Se guardará de inmediato, sin otra ventana del sistema.",
      "pdf.directSaveNoPreview": "El PDF se guardará directamente en Descargas/LubaNote sin la vista previa de impresión del sistema.",
      "pdf.directTest": "PDF directo TEST",
      "pdf.directTestHint": "El mismo motor de impresión de Android, pero sin vista previa del sistema.",
      "pdf.document": "Documento PDF",
      "pdf.doubleTapFullscreen": "Doble toque → pantalla completa",
      "pdf.doubleTapFullscreenHint": "El doble toque alterna la vista máxima del PDF.",
      "pdf.exitMaxView": "Salir de la vista máxima",
      "pdf.fitWidth": "Ajustar al ancho",
      "pdf.fitWidthAria": "Ajustar PDF al ancho",
      "pdf.fullscreen": "Pantalla completa",
      "pdf.generatingTest": "Generando PDF TEST…",
      "pdf.landscape": "Horizontal",
      "pdf.loading": "Cargando PDF…",
      "pdf.maxView": "Vista máxima de PDF",
      "pdf.nextPage": "Página siguiente",
      "pdf.pageDisplayFailed": "No se pudo mostrar la página.",
      "pdf.portrait": "Vertical",
      "pdf.preview": "Vista previa",
      "pdf.previewFailed": "No se pudo crear la vista previa del PDF.",
      "pdf.previewNamed": "Vista previa • {name}",
      "pdf.previousPage": "Página anterior",
      "pdf.rememberZoom": "Recordar el último zoom",
      "pdf.rememberZoomHint": "El siguiente PDF se abrirá con el mismo zoom.",
      "pdf.saveCopy": "Guardar copia del PDF",
      "pdf.saveFailed": "No se pudo guardar el PDF.",
      "pdf.savePdf": "Guardar PDF",
      "pdf.savePreview": "Guardar vista previa del PDF",
      "pdf.savedChosenLocation": "PDF guardado en la ubicación seleccionada.",
      "pdf.savedDirect": "PDF guardado directamente en Descargas/LubaNote.",
      "pdf.savedDownloads": "PDF guardado en Descargas/LubaNote.",
      "pdf.settings": "Ajustes de PDF",
      "pdf.settingsHint": "Se aplica al visor de PDF de LubaNote.",
      "pdf.systemPreviewShouldNotOpen": "La vista previa del sistema no debería abrirse.",
      "pdf.viewer": "Visor de PDF",
      "pdf.whereSave": "Dónde guardar el PDF",
      "pdf.whereSaveShort": "Dónde guardar",
      "pdf.zoomIn": "Ampliar PDF",
      "pdf.zoomOut": "Reducir PDF",
      "planner.changeFutureFirst": "Primero cambia la fecha de la tarea a una fecha futura.",
      "planner.futureRequired": "La fecha debe estar en el futuro.",
      "planner.reminderOff": "Recordatorio: desactivado",
      "planner.reminderOn": "Recordatorio: activado",
      "reader.addBookmarkHere": "Añadir marcador aquí",
      "reader.addNote": "Añadir nota",
      "reader.airy": "Amplio",
      "reader.alignment": "Alineación",
      "reader.background": "Fondo",
      "reader.book": "Libro",
      "reader.bookmarks": "Marcadores",
      "reader.bookmarksHighlights": "Marcadores y resaltados",
      "reader.chapterEmpty": "El capítulo no contiene texto que se pueda mostrar.",
      "reader.chapterNumber": "Capítulo {count}",
      "reader.closeBook": "Cerrar libro",
      "reader.closeContents": "Cerrar contenido",
      "reader.closeSettings": "Cerrar ajustes",
      "reader.contents": "Contenido",
      "reader.contentsAria": "Contenido del libro",
      "reader.dark": "Oscuro",
      "reader.decreaseFont": "Reducir fuente",
      "reader.deleteBookmark": "Eliminar marcador",
      "reader.deleteHighlight": "Eliminar resaltado",
      "reader.editNote": "Editar nota",
      "reader.font": "Fuente",
      "reader.fontSize": "Tamaño de fuente",
      "reader.highlight": "Resaltado",
      "reader.highlightBlue": "Resaltado azul",
      "reader.highlightColor": "Color de resaltado",
      "reader.highlightGreen": "Resaltado verde",
      "reader.highlightNote": "Nota del resaltado",
      "reader.highlightViolet": "Resaltado violeta",
      "reader.highlightYellow": "Resaltado amarillo",
      "reader.highlights": "Resaltados",
      "reader.increaseFont": "Aumentar fuente",
      "reader.justify": "Justificado",
      "reader.left": "Izquierda",
      "reader.light": "Claro",
      "reader.lineHeight": "Interlineado",
      "reader.margins": "Márgenes del texto",
      "reader.narrow": "Estrecho",
      "reader.noBookmarks": "Aún no hay marcadores.",
      "reader.noHighlights": "Aún no hay resaltados.",
      "reader.normal": "Normal",
      "reader.note": "Nota",
      "reader.notePlaceholder": "Escribe tu propia nota…",
      "reader.openingEpub": "Abriendo EPUB…",
      "reader.preparingBook": "Preparando libro…",
      "reader.preparingBookCount": "Preparando libro… {current} / {total}",
      "reader.removeHighlight": "Quitar resaltado",
      "reader.resetDefaults": "Restaurar valores predeterminados",
      "reader.sans": "Sin serifas",
      "reader.sepia": "Sepia",
      "reader.serif": "Con serifas",
      "reader.settings": "Ajustes de lectura",
      "reader.smaller": "Más pequeño",
      "reader.tapRemoveHighlight": "Toca para quitar el resaltado",
      "reader.wide": "Ancho",
      "reader.withNote": "Con nota",
      "recurring.nextOccurrence": "Siguiente ocurrencia",
      "recurring.nextScheduled": "Siguiente repetición programada",
      "recurring.previousOccurrence": "Ocurrencia anterior",
      "recurring.ruleAt": "{rule} a las {time}",
      "recurring.start": "Inicio de repetición",
      "recurring.turnOff": "Desactivar repetición",
      "reminders.channelDescription": "Notificaciones de notas y tareas programadas",
      "reminders.channelName": "Recordatorios de LubaNote",
      "reminders.deletePlannedTitle": "¿Eliminar tarea programada?",
      "reminders.deletePlannerTaskTitle": "¿Eliminar tarea del plan?",
      "reminders.deleteReminderTitle": "¿Eliminar recordatorio?",
      "reminders.disabled": "Recordatorio desactivado",
      "reminders.enabled": "Recordatorio activado",
      "reminders.exactMessage": "Permite alarmas exactas en Android; de lo contrario, el sistema puede retrasar la notificación.",
      "reminders.exactTitle": "Recordatorios exactos",
      "reminders.futureRequired": "El recordatorio debe estar en el futuro.",
      "reminders.noteCompleted": "Nota completada",
      "reminders.remind": "Recordar",
      "reminders.removeNoteFromPlanTitle": "¿Quitar nota del plan?",
      "reminders.turnOffFailed": "No se pudo desactivar el recordatorio de forma segura.",
      "reminders.turnOffShort": "Desactivar",
      "reminders.turningOff": "Desactivando recordatorio…",
      "settings.choice1": "1.ª opción",
      "settings.choice2": "2.ª opción",
      "settings.choice3": "3.ª opción",
      "settings.choice4": "4.ª opción",
      "settings.snoozeHours": "{count} h",
      "settings.snoozeMinutes": "{count} min",
      "status.preparing": "Preparando…",
      "status.saved": "Guardado ✓",
      "status.savedCheck": "Guardado ✓",
      "status.updated": "Actualizado ✓",
      "tags.duplicate": "Ya existe una etiqueta con este nombre.",
      "tags.maxTwo": "Una nota puede tener como máximo 2 etiquetas. Quita una primero.",
      "timePicker.now": "Ahora",
      "timePicker.set": "Establecer",
      "secret.deviceUnlockTitle": "Desbloquea este dispositivo",
      "secret.createMainTitle": "Crea la contraseña principal",
      "secret.unlockContinue": "Desbloquear y continuar",
      "secret.createContinue": "Crear y continuar",
      "secret.deviceUnlockDescription": "Esta cuenta ya tiene una contraseña principal. Introdúcela una vez para que LubaNote pueda preparar de forma segura el modo secreto y las fotos E2E en este dispositivo. La sincronización comenzará después.",
      "secret.createMainDescription": "Antes de empezar a usar LubaNote, crea una contraseña principal. Protege el modo secreto y las fotos cifradas E2E. No es tu contraseña de inicio de sesión y LubaNote no la guarda en la nube.",
      "secret.unlockMode": "Desbloquear modo secreto",
      "secret.createMainForNotes": "Crea una contraseña principal para las notas secretas.",
      "secret.createPassword": "Crear contraseña",
      "tags.deleting": "Eliminando etiqueta…",
      "tags.savingShort": "Guardando…",
      "tags.saving": "Guardando etiqueta…",
      "tags.moveUp": "Mover etiquetas hacia arriba",
      "tags.moveDown": "Mover etiquetas hacia abajo",
      "tags.orderSaveFailed": "No se pudo guardar el orden de las etiquetas.",
      "tags.savingOrder": "Guardando el orden de las etiquetas…",
      "tags.colorAria": "Color de la etiqueta {name}",
      "tags.setColorAria": "Establecer el color de la etiqueta en {color}",
      "tags.renameAria": "Cambiar el nombre de la etiqueta {name}",
      "tags.renaming": "Cambiando el nombre de la etiqueta…",
      "tags.deleteAria": "Eliminar etiqueta {name}",
      "tags.deleteConfirm": "¿Seguro que quieres eliminar la etiqueta «{name}»?",
      "tags.unlockFirst": "Primero desbloquea el modo secreto.",
      "tags.newSaveFailed": "No se pudo guardar la nueva etiqueta.",
      "tags.newLocalSaveFailed": "No se pudo guardar la nueva etiqueta local.",
      "tags.newSaveFailedConnection": "No se pudo guardar la nueva etiqueta. Comprueba la conexión e inténtalo de nuevo.",
      "tags.longPressWorks": "La pulsación larga funciona.",
      "tags.assignedMany": "Etiqueta «{name}» asignada a {count} tarjetas",
      "tags.color.cervena": "Rojo",
      "tags.color.oranzova": "Naranja",
      "tags.color.zluta": "Amarillo",
      "tags.color.zelena": "Verde",
      "tags.color.tyrkysova": "Turquesa",
      "tags.color.modra": "Azul",
      "tags.color.fialova": "Violeta",
      "tags.color.ruzova": "Rosa",
      "documents.addedType": "Añadido: {type} «{name}».",
      "documents.addFailed": "No se pudo añadir el documento.",
      "documents.selectedNotType": "El archivo seleccionado no es {type}.",
      "documents.addFailedType": "No se pudo añadir {type}.",
      "documents.selectedNotLegacyDoc": "El archivo seleccionado no es un Word DOC antiguo."
    },

    texty: {
      ...anglicky.texty,
      "Přihlášení vypršelo. Přihlas se znovu, aby mohla pokračovat synchronizace. Tvoje lokální data zůstala zachována.": "Tu sesión ha caducado. Inicia sesión de nuevo para que la sincronización pueda continuar. Tus datos locales se han conservado.",
      "Nepodařilo se připojit k synchronizaci. Zkus to znovu po připojení k internetu.": "No se pudo conectar con la sincronización. Inténtalo de nuevo cuando tengas conexión a internet.",
      "Ověření přihlášení se nepodařilo.": "No se pudo verificar el inicio de sesión.",
      "První přihlášení vyžaduje připojení k internetu.": "El primer inicio de sesión requiere conexión a internet.",
      "Ověřuji přihlášení…": "Verificando inicio de sesión…",
      "Vyplň e-mail i heslo.": "Introduce el correo y la contraseña.",
      "Přihlášení vyžaduje internet. Lokální aplikace funguje offline až po prvním úspěšném přihlášení.": "El inicio de sesión requiere internet. El modo sin conexión está disponible después del primer inicio de sesión correcto.",
      "Přihlašuji…": "Iniciando sesión…",
      "Přihlášení se nezdařilo. Zkontroluj e-mail, heslo a připojení.": "No se pudo iniciar sesión. Comprueba el correo, la contraseña y la conexión.",
      "Světlý": "Claro",
      "Tmavý": "Oscuro",
      "Původní ikony": "Iconos clásicos",
      "SVG ikony": "Iconos SVG",
      "Pracovní": "Trabajo",
      "Soukromé": "Privadas",
      "Bez názvu": "Sin título",
      "Žádná odpovídající poznámka": "No hay ninguna nota coincidente",
      "⚠ Smazaná poznámka": "⚠ Nota eliminada",
      "Tajný režim": "Modo secreto",
      "Tajný režim byl zamčen.": "El modo secreto se ha bloqueado.",
      "Tajný režim byl automaticky zamčen.": "El modo secreto se ha bloqueado automáticamente.",
      "Tajný režim je odemčený.": "El modo secreto está desbloqueado.",
      "Tajný režim se nepodařilo odemknout.": "No se pudo desbloquear el modo secreto.",
      "Tajný režim není odemčený.": "El modo secreto no está desbloqueado.",
      "Zadej hlavní heslo.": "Introduce la contraseña principal.",
      "Hlavní heslo není správné.": "La contraseña principal no es correcta.",
      "Hlavní heslo musí mít alespoň 8 znaků.": "La contraseña principal debe tener al menos 8 caracteres.",
      "Hlavní heslo se nepodařilo vytvořit.": "No se pudo crear la contraseña principal.",
      "Upozornění": "Aviso",
      "Nový štítek": "Nueva etiqueta",
      "Název štítku": "Nombre de la etiqueta",
      "+ Nový štítek": "+ Nueva etiqueta",
      "Nový tajný štítek": "Nueva etiqueta secreta",
    }
  });
})();
