/* LubaNote – Polski · PATCH 676A */
window.LubaNoteLanguagePacks = window.LubaNoteLanguagePacks || [];

(() => {
  const anglicky = window.LubaNoteLanguagePacks.find((balicek) => balicek.id === "en") || { preklady: {}, texty: {} };

  window.LubaNoteLanguagePacks.push({
    id: "pl",
    nazev: "Polski",
    kratkyNazev: "PL",
    vlajka: "🇵🇱",
    locale: "pl-PL",

    // Nejdřív bezpečný anglický fallback; přeložené produkční UI ho přepisuje níže.
    preklady: {
      ...anglicky.preklady,
      "language.label": "Język",
      "language.choose": "Wybierz język",
      "login.splashSubtitle": "Notatki • Plan • Dokumenty",
      "login.loading": "LubaNote się ładuje",
      "login.title": "Logowanie",
      "login.registerTitle": "Rejestracja",
      "login.modeSignIn": "Logowanie",
      "login.modeRegister": "Rejestracja",
      "login.email": "E-mail",
      "login.password": "Hasło",
      "login.passwordAgain": "Powtórz hasło",
      "login.submit": "Zaloguj się",
      "login.registerSubmit": "Zarejestruj się",
      "login.checkStatus": "Sprawdź status",
      "login.modeAria": "Logowanie lub rejestracja",
      "login.downloadMyData": "Pobierz moje dane",
      "login.deleteMyData": "Usuń moje dane",
      "login.clearThisDevice": "Wyczyść to urządzenie",
      "login.deleteMyDataTitle": "Usunąć moje dane?",
      "login.clearThisDeviceTitle": "Wyczyścić to urządzenie?",
      "login.clearWithoutBackup": "Wyczyść bez kopii zapasowej",
      "login.pendingTitle": "Konto oczekuje na zatwierdzenie",
      "login.pendingText": "Rejestracja została zakończona. LubaNote odblokuje się po zatwierdzeniu konta przez administratora.",
      "login.rejectedTitle": "Rejestracja nie została zatwierdzona",
      "login.rejectedText": "To konto nie zostało zatwierdzone. Jeśli to pomyłka, skontaktuj się z administratorem LubaNote.",
      "login.suspendedTitle": "Konto zawieszone",
      "login.suspendedText": "Dostęp do LubaNote został tymczasowo zawieszony.",
      "login.unavailableTitle": "Konto niedostępne",
      "login.unavailableText": "Nie udało się zweryfikować dostępu do konta. Spróbuj ponownie.",
      "login.enterCredentials": "Wpisz e-mail i hasło.",
      "login.enterRegistration": "Wpisz e-mail, hasło i powtórz hasło.",
      "login.passwordMismatch": "Hasła nie są takie same.",
      "login.passwordTooShort": "Hasło musi mieć co najmniej 8 znaków.",
      "login.registrationOnline": "Rejestracja wymaga połączenia z internetem.",
      "login.registering": "Rejestrowanie…",
      "login.registrationCreated": "Rejestracja została utworzona. Potwierdź e-mail, a następnie się zaloguj.",
      "login.emailConfirmed": "E-mail został potwierdzony. Możesz się teraz zalogować.",
      "login.emailLinkInvalid": "Link potwierdzający został już użyty lub wygasł. Jeśli e-mail jest potwierdzony, zaloguj się.",
      "login.stillPending": "Konto nadal oczekuje na zatwierdzenie.",
      "login.alreadyRegistered": "Ten e-mail jest już zarejestrowany. Użyj Logowania.",
      "login.registrationFailed": "Rejestracja nie powiodła się. Sprawdź e-mail, hasło i połączenie.",
      "login.registrationRateLimited": "Wysłano zbyt wiele wiadomości potwierdzających. Spróbuj zarejestrować się później.",
      "login.signingIn": "Logowanie…",
      "login.signInFailed": "Logowanie nie powiodło się. Sprawdź e-mail, hasło i połączenie.",
      "login.emailNotConfirmed": "Twój e-mail nie został jeszcze potwierdzony. Otwórz link potwierdzający w wiadomości i zaloguj się ponownie.",
      "login.accountCheckFailed": "Nie udało się zweryfikować statusu konta. Spróbuj ponownie.",
      "login.localOwnerMismatch": "Ta instalacja zawiera lokalne dane innego konta LubaNote. Ze względów bezpieczeństwa nie można mieszać kont w jednej instalacji.",
      "login.demoExpiredTitle": "Demo zakończone",
      "login.demoExpiredText": "Twoje Demo zakończyło się {date}. Wszystkie dane pozostają bezpiecznie zapisane. Do dalszego korzystania z aplikacji będzie wymagany pełny dostęp do LubaNote.",
      "login.fullExpiredTitle": "Pełny dostęp wygasł",
      "login.fullExpiredText": "Twoje dane pozostają bezpiecznie zapisane. LubaNote odblokuje się ponownie po odnowieniu pełnego dostępu.",
      "account.demoUntil": "Demo do {date}",
      "limits.notesTitle": "Osiągnięto limit notatek",
      "limits.notesText": "Twój plan pozwala na maksymalnie {limit} notatek. Nowej notatki nie można teraz bezpiecznie zapisać. Istniejące dane pozostają zachowane.",
      "nav.quick": "Szybka nawigacja",
      "nav.tools": "Narzędzia",
      "nav.home": "Strona główna",
      "nav.allNotes": "Wszystkie notatki",
      "nav.favorites": "Ulubione",
      "nav.tags": "Etykiety",
      "nav.settings": "Ustawienia",
      "nav.backup": "Kopia zapasowa i przywracanie",
      "modules.aria": "Główne sekcje LubaNote",
      "modules.notes": "Notatki",
      "storageScope.cloud": "Synchronizowane",
      "storageScope.local": "To urządzenie",
      "storageScope.menu": "Pamięć",
      "storageScope.choose": "Gdzie zapisywać notatki?",
      "storageScope.localTitle": "Tylko to urządzenie",
      "storageScope.localWarning": "Notatki w tej przestrzeni nie są synchronizowane. Po utracie lub wymazaniu urządzenia nie można ich przywrócić z chmury. Zalecamy regularne kopie zapasowe.",
      "storageScope.shareTitle": "Tylko to urządzenie",
      "storageScope.shareBlocked": "Udostępnianie wymaga synchronizowanej pamięci. Ta notatka pozostaje tylko na tym urządzeniu.",
      "modules.planner": "Plan",
      "modules.documents": "Dokumenty",
      "documents.eyebrow": "Dokumenty V1",
      "documents.title": "Dokumenty",
      "documents.addFile": "＋ Dodaj plik",
      "documents.folders": "Foldery",
      "documents.newFolder": "Nowy folder",
      "documents.files": "Pliki",
      "documents.allFiles": "Wszystkie pliki",
      "documents.searchPlaceholder": "Szukaj…",
      "documents.searchAria": "Szukaj plików",
      "documents.clearSearch": "Wyczyść wyszukiwanie",
      "documents.filterAria": "Filtr dokumentów",
      "documents.filterAll": "Wszystkie",
      "documents.trash": "Kosz",
      "documents.folderFallback": "Folder",
      "documents.localAndroid": "Lokalnie na tym urządzeniu z Androidem",
      "documents.localBrowser": "Lokalnie w tej przeglądarce",
      "documents.fileCount.one": "{count} plik",
      "documents.fileCount.few": "{count} pliki",
      "documents.fileCount.many": "{count} plików",
      "documents.fileCount.other": "{count} pliku",
      "plannerTabs.calendar": "Kalendarz",
      "modules.reminders": "Przypomnienia",
      "sync.synced": "✓ Zsynchronizowano",
      "sync.syncing": "⟳ Synchronizowanie…",
      "sync.pending": "⏳ Oczekuje na synchronizację",
      "sync.localOnly": "📱 Tylko to urządzenie",
      "sync.authExpired": "⚠ Logowanie wygasło",
      "sync.conflict": "⚠ Konflikt",
      "search.placeholder": "Szukaj…",
      "search.aria": "Szukaj notatek",
      "search.clear": "Wyczyść wyszukiwanie",
      "search.view": "Zmień układ kart",
      "search.menu": "Menu główne",
      "sort.labelNewest": "Nowe karty: u góry",
      "sort.labelOldest": "Nowe karty: na dole",
      "sort.title": "Położenie nowej karty",
      "sort.newest": "Nowe karty u góry",
      "sort.oldest": "Nowe karty na dole",
      "search.none": "Nie znaleziono notatek.",
      "menu.manageTags": "Zarządzaj etykietami",
      "menu.about": "O aplikacji",
      "menu.logout": "Wyloguj się",
      "filter.aria": "Filtry notatek",
      "filter.all": "Wszystkie",
      "filter.work": "Praca",
      "filter.private": "Prywatne",
      "filter.favorite": "Ulubione notatki",
      "filter.secret": "Tajne notatki",
      "filter.finishSelection": "Zakończ zaznaczanie",
      "calendar.previousMonth": "Poprzedni miesiąc",
      "calendar.nextMonth": "Następny miesiąc",
      "calendar.selectedDay": "Wybrany dzień",
      "calendar.addSelected": "Dodaj zadanie na wybrany dzień",
      "calendar.back": "Wróć do kalendarza",
      "calendar.addDay": "Dodaj zadanie na ten dzień",
      "calendar.week": "tydzień",
      "calendar.weekNumber": "Tydzień {value}",
      "weekday.mo": "Pon",
      "weekday.tu": "Wt",
      "weekday.we": "Śr",
      "weekday.th": "Czw",
      "weekday.fr": "Pt",
      "weekday.sa": "Sob",
      "weekday.su": "Nd",
      "recurring.title": "Cykliczne",
      "recurring.back": "Wróć do przypomnień",
      "recurring.show": "Pokaż zadania cykliczne",
      "recurring.none": "Brak zadań cyklicznych.",
      "recurring.repeat": "Powtarza się",
      "recurring.next": "Następne: {value}",
      "recurring.noNext": "Ta seria nie ma następnego wystąpienia.",
      "reminders.overdue": "Po terminie",
      "reminders.active": "Aktywne",
      "reminders.today": "Dzisiaj",
      "reminders.none": "Brak przypomnień.",
      "reminders.noneOverdue": "Brak zaległych przypomnień.",
      "reminders.tomorrow": "Jutro",
      "reminders.later": "Później",
      "reminders.label": "Przypomnienie",
      "reminders.untitled": "Bez tytułu",
      "reminders.close": "Zamknij",
      "reminders.tomorrow8": "Jutro 8:00",
      "reminders.date": "Data",
      "reminders.time": "Czas",
      "reminders.selectDate": "Wybierz datę przypomnienia",
      "reminders.selectTime": "Wybierz godzinę przypomnienia",
      "reminders.done": "Gotowe",
      "reminders.delete": "Usuń",
      "reminders.openNote": "Otwórz notatkę",
      "reminders.turnOff": "Wyłącz przypomnienie",
      "editor.find": "Szukaj",
      "editor.findInNote": "Szukaj w tej notatce",
      "editor.findPrevious": "Poprzedni wynik",
      "editor.findNext": "Następny wynik",
      "editor.findClose": "Zamknij wyszukiwanie",
      "editor.openTools": "Otwórz narzędzia edycji",
      "editor.formatting": "Formatowanie notatki",
      "editor.moreTools": "Więcej narzędzi notatki",
      "editor.undo": "Cofnij",
      "editor.redo": "Ponów",
      "editor.bold": "Pogrubienie",
      "editor.italic": "Kursywa",
      "editor.underline": "Podkreślenie",
      "editor.fontSize": "Rozmiar czcionki",
      "editor.textStyle": "Styl tekstu",
      "editor.textColor": "Kolor tekstu",
      "editor.white": "Biały tekst",
      "editor.black": "Czarny tekst",
      "editor.align": "Wyrównanie tekstu",
      "editor.alignLeft": "Wyrównaj do lewej",
      "editor.alignCenter": "Wyśrodkuj",
      "editor.alignRight": "Wyrównaj do prawej",
      "editor.insertImage": "Wstaw obraz",
      "editor.insertWebLink": "Wstaw link internetowy",
      "editor.webLink": "Link internetowy",
      "editor.openDocument": "Otwórz dokument",
      "editor.saveAs": "Zapisz jako",
      "editor.bullets": "Lista punktowana",
      "editor.date": "Data",
      "editor.time": "Czas",
      "editor.selectDate": "Wybierz datę",
      "editor.selectTime": "Wybierz godzinę",
      "editor.pin": "Przypnij notatkę",
      "editor.reminder": "Przypomnienie",
      "editor.backLink": "Wróć do poprzedniej powiązanej notatki",
      "editor.titleAria": "Tytuł notatki",
      "editor.titlePlaceholder": "Tytuł notatki",
      "editor.secret": "Tajna notatka",
      "editor.tags": "Etykiety",
      "editor.newTag": "Nowa etykieta",
      "editor.cancelNewTag": "Anuluj nową etykietę",
      "editor.saveClose": "Zapisz i zamknij",
      "editor.area": "Obszar notatki",
      "editor.priority": "Priorytet",
      "editor.color": "Kolor",
      "editor.planSelection": "Zaplanuj zaznaczony tekst",
      "editor.addTodo": "Dodaj pozycję TODO",
      "editor.deleteNote": "Usuń notatkę",
      "backlinks.aria": "Linki do tej notatki",
      "backlinks.title": "Linki do tej notatki ({count})",
      "backlinks.none": "Brak linków do tej notatki",
      "actions.save": "Zapisz",
      "actions.discard": "Nie zapisuj",
      "actions.ok": "OK",
      "status.done": "Gotowe",
      "secret.mainPassword": "Hasło główne",
      "secret.passwordAgain": "Powtórz hasło",
      "secret.enterMain": "Wpisz hasło główne.",
      "actions.term": "Termin",
      "actions.pin": "Przypnij",
      "actions.delete": "Usuń",
      "actions.more": "Więcej działań",
      "actions.cancel": "Anuluj",
      "actions.create": "Utwórz",
      "message.notice": "Uwaga",
      "editor.notePlaceholder": "Napisz notatkę…",
      "tags.name": "Nazwa etykiety",
      "tags.add": "Dodaj",
      "deleteNote.message": "Czy na pewno chcesz usunąć tę notatkę?",
      "deleteNote.title": "Usunąć notatkę?",
      "timePicker.title": "Wybierz godzinę",
      "timePicker.close": "Zamknij wybór czasu",
      "timePicker.clock": "Tarcza wyboru czasu",
      "repeat.title": "Powtarzanie",
      "repeat.aria": "Powtarzanie zadania",
      "repeat.no": "Nie",
      "repeat.daily": "Codziennie",
      "repeat.weekly": "Co tydzień",
      "repeat.twoWeeks": "2 tygodnie",
      "repeat.monthly": "Co miesiąc",
      "repeat.none": "Nie powtarzaj",
      "planner.plan": "Zaplanuj",
      "planner.close": "Zamknij planowanie",
      "planner.selectDate": "Wybierz datę planowanego zadania",
      "planner.selectTime": "Wybierz godzinę planowanego zadania",
      "sharing.settingsTitle": "Udostępnianie",
      "sharing.usernameLabel": "Nazwa użytkownika",
      "sharing.usernameUnset": "Ustaw",
      "sharing.usernameModalTitle": "Nazwa użytkownika do udostępniania",
      "sharing.usernameDescription": "Inni mogą znaleźć Cię tylko po dokładnej @nazwie użytkownika. Twój e-mail nigdy nie jest pokazywany podczas udostępniania.",
      "sharing.usernamePlaceholder": "np. Lubomir",
      "sharing.usernameSave": "Zapisz",
      "sharing.usernameCancel": "Anuluj",
      "sharing.usernameInvalid": "Użyj 3–30 znaków: liter, cyfr, kropki, myślnika lub podkreślenia.",
      "sharing.usernameTaken": "Ta @nazwa użytkownika jest już używana przez kogoś innego.",
      "sharing.usernameOffline": "Ustawienie @nazwy użytkownika wymaga połączenia z internetem.",
      "sharing.usernameSaving": "Zapisywanie…",
      "sharing.usernameSaveFailed": "Nie udało się zapisać nazwy użytkownika.",
      "sharing.usernameRequiredTitle": "Utwórz swoją @nazwę użytkownika",
      "sharing.usernameRequiredDescription": "Zanim zaczniesz używać LubaNote, utwórz publiczną @nazwę użytkownika do udostępniania i czatu. Inni mogą znaleźć Cię tylko po dokładnej @nazwie; Twój e-mail nie jest wyświetlany.",
      "sharing.usernameRequiredSave": "Utwórz i kontynuuj",
      "sharing.shareButton": "Udostępnij",
      "sharing.invitationsAria": "Zaproszenia do udostępniania",
      "sharing.shareModalTitle": "Udostępnij notatkę",
      "sharing.shareModalDescription": "Zaproś użytkownika, wpisując jego dokładną @nazwę użytkownika.",
      "sharing.shareInputPlaceholder": "np. LubaNoteDemo",
      "sharing.shareSend": "Wyślij zaproszenie",
      "sharing.shareSending": "Wysyłanie…",
      "sharing.shareSendSuccess": "Zaproszenie wysłane.",
      "sharing.shareSendFailed": "Nie udało się wysłać zaproszenia.",
      "sharing.shareInvalidUsername": "Wpisz prawidłową @nazwę użytkownika.",
      "sharing.shareOffline": "Udostępnianie wymaga połączenia z internetem.",
      "sharing.shareUsernameMissing": "Najpierw ustaw własną @nazwę użytkownika w Ustawieniach.",
      "sharing.shareUserNotFound": "Nie znaleziono użytkownika o dokładnie tej @nazwie.",
      "sharing.shareSelf": "Nie możesz udostępnić notatki samemu sobie.",
      "sharing.shareAlreadyCollaborator": "Ten użytkownik już współpracuje przy notatce.",
      "sharing.shareAlreadyPending": "Zaproszenie dla tego użytkownika już oczekuje.",
      "sharing.shareSecretBlocked": "Tajnych notatek nie można jeszcze udostępniać.",
      "sharing.shareNewNoteBlocked": "Najpierw zapisz notatkę, a potem możesz ją udostępnić.",
      "sharing.collaboratorsTitle": "Współpracownicy",
      "sharing.collaboratorsEmpty": "Brak współpracowników.",
      "sharing.pendingTitle": "Oczekujące zaproszenia",
      "sharing.pendingEmpty": "Brak oczekujących zaproszeń.",
      "sharing.cancelInvitation": "Anuluj",
      "sharing.cancelFailed": "Nie udało się anulować zaproszenia.",
      "sharing.cancel": "Anuluj",
      "sharing.removeCollaborator": "Usuń",
      "sharing.removeCollaboratorConfirm": "Usunąć {username} z udostępniania?",
      "sharing.removeCollaboratorSuccess": "Współpracownik usunięty.",
      "sharing.removeCollaboratorFailed": "Nie udało się usunąć współpracownika.",
      "sharing.removeCollaboratorMissing": "Ten użytkownik nie udostępnia już notatki.",
      "sharing.manageNotOwner": "Tylko właściciel notatki może wykonać tę czynność.",
      "sharing.manageModalUnavailable": "Nie udało się otworzyć okna potwierdzenia.",
      "sharing.leaveSharedNote": "Opuść udostępnianie",
      "sharing.leaveConfirm": "Opuścić udostępnianie tej notatki?",
      "sharing.leaveSuccess": "Udostępnianie zostało opuszczone.",
      "sharing.leaveFailed": "Nie udało się opuścić udostępniania.",
      "sharing.ownerCannotLeave": "Właściciel nie może opuścić udostępniania. Najpierw przenieś własność.",
      "sharing.ownerRole": "Właściciel",
      "sharing.editorRole": "Edytor",
      "sharing.invitationsTitle": "Zaproszenia do udostępniania",
      "sharing.invitationsEmpty": "Nie masz oczekujących zaproszeń.",
      "sharing.invitedBy": "Zaprosił(a) {username}",
      "sharing.accept": "Akceptuj",
      "sharing.decline": "Odrzuć",
      "sharing.responding": "Przetwarzanie…",
      "sharing.invitationAccepted": "Zaproszenie zaakceptowane.",
      "sharing.invitationDeclined": "Zaproszenie odrzucone.",
      "sharing.invitationResponseFailed": "Nie udało się przetworzyć zaproszenia.",
      "sharing.refresh": "Odśwież",
      "sharing.close": "Zamknij",
      "sharing.loading": "Ładowanie…",
      "sharing.loadFailed": "Nie udało się wczytać danych udostępniania.",
      "sharing.sharedUntitled": "Bez tytułu",
      "sharing.sharedCardMeta": "Udostępnione · {owner}",
      "sharing.readOnlyTitle": "Udostępniona notatka",
      "sharing.readOnlyMeta": "{owner} · udostępniona notatka",
      "sharing.readOnlyTodos": "Zadania",
      "sharing.editShared": "Edytuj",
      "sharing.sharedEditorOffline": "Udostępnioną notatkę można edytować tylko online.",
      "sharing.sharedEditorBusy": "{username} właśnie edytuje tę notatkę. Na razie możesz ją tylko czytać.",
      "sharing.sharedEditorOpening": "Otwieranie edytora udostępnionej notatki…",
      "sharing.sharedEditorSaveFailed": "Nie udało się bezpiecznie zapisać udostępnionej notatki. Edytor pozostaje otwarty.",
      "sharing.sharedEditorConflict": "Na serwerze istnieje nowsza wersja notatki. Edytor pozostaje otwarty; zamknij go bez zapisywania i otwórz notatkę ponownie.",
      "sharing.sharedEditorLockLost": "Blokada edytora nie jest już ważna. Edytor udostępnionej notatki został bezpiecznie zamknięty.",
      "sharing.sharedEditorSaved": "Udostępniona notatka zapisana.",
      "chat.buttonAria": "Wiadomości",
      "chat.contactsTitle": "Wiadomości",
      "chat.contactsEmpty": "Nie masz jeszcze kontaktów na czacie. Kontakt powstaje po zaakceptowaniu zaproszenia do udostępniania notatki.",
      "chat.writeMessage": "Napisz wiadomość",
      "chat.trustedContact": "Kontakt z udostępniania",
      "chat.ready": "Możecie do siebie pisać",
      "chat.lastMessageAt": "Ostatnia wiadomość {time}",
      "chat.messagePlaceholder": "Napisz wiadomość…",
      "chat.send": "Wyślij",
      "chat.sending": "Wysyłanie…",
      "chat.sent": "Wysłano",
      "chat.read": "Przeczytano",
      "chat.messagesEmpty": "Brak wiadomości.",
      "chat.deletedPlaceholder": "Wiadomość została usunięta",
      "chat.deleteMessage": "Usuń wiadomość",
      "chat.deleteTitle": "Usunąć wiadomość?",
      "chat.deleteText": "Wiadomość zostanie usunięta dla obu uczestników, a pozostanie jedynie informacja o usuniętej wiadomości.",
      "chat.deleteForBoth": "Usuń dla obu",
      "chat.deleting": "Usuwanie…",
      "chat.deleteFailed": "Nie udało się usunąć wiadomości.",
      "chat.sendFailed": "Nie udało się wysłać wiadomości.",
      "chat.loadFailed": "Nie udało się wczytać czatu.",
      "chat.loadMessagesFailed": "Nie udało się wczytać wiadomości.",
      "chat.loading": "Ładowanie…",
      "chat.offline": "Czat wymaga połączenia z internetem.",
      "chat.blocked": "Czat jest zablokowany",
      "chat.contactNotFound": "Kontakt na czacie nie jest jeszcze dostępny.",
      "chat.tooLong": "Wiadomość jest za długa.",
      "chat.close": "Zamknij",
      "chat.back": "Wstecz",
      "chat.cancel": "Anuluj",
      "chat.threadAria": "Czat",
      "settings.personalDictionary": "Mój słownik",
      "settings.languageLearning": "Nauka języków",
      "settings.manageDictionary": "Zarządzaj",
      "settings.openLearning": "Otwórz",
      "settings.wordsCount.one": "{count} słowo",
      "settings.wordsCount.few": "{count} słowa",
      "settings.wordsCount.many": "{count} słów",
      "settings.wordsCount.other": "{count} słowa",
      "settings.plannerReminderDefault": "Automatycznie przypominaj podczas planowania",
      "settings.enabled": "Włączone",
      "settings.disabled": "Wyłączone",
      "settings.planning": "Planowanie",
      "settings.automaticReminder": "Automatyczne przypomnienie",
      "settings.title": "Ustawienia",
      "settings.close": "Zamknij ustawienia",
      "settings.appearance": "Wygląd",
      "settings.fontSize": "Rozmiar czcionki",
      "settings.decreaseFont": "Zmniejsz czcionkę",
      "settings.increaseFont": "Zwiększ czcionkę",
      "settings.theme": "Motyw kolorystyczny",
      "settings.iconStyle": "Styl ikon",
      "settings.keyboard": "Klawiatura edytora",
      "settings.keyboardTitle": "Klawiatura edytora",
      "settings.keyboardLuba": "LubaKeyboard (domyślna)",
      "settings.keyboardSystem": "Systemowa",
      "settings.keyboardSystemLong": "Klawiatura systemowa (Gboard / iOS)",
      "settings.reminders": "Przypomnienia",
      "settings.quickDelay": "Szybka drzemka",
      "settings.configure": "Ustaw",
      "settings.overdueRetention": "Usuń zaległe po",
      "settings.overdueNever": "Nigdy",
      "settings.overdueDays": "{count} dni",
      "settings.overdueConfirm": "potwierdź",
      "settings.data": "Dane",
      "settings.noteOpenPosition": "Po otwarciu notatki",
      "settings.noteOpenStart": "Początek",
      "settings.noteOpenEnd": "Koniec",
      "settings.export": "Eksportuj kopię zapasową",
      "settings.import": "Importuj kopię zapasową",
      "settings.about": "O aplikacji",
      "settings.version": "Wersja",
      "settings.appInfo": "Informacje o aplikacji",
      "settings.open": "Otwórz",
      "theme.light": "Jasny",
      "theme.dark": "Ciemny",
      "icons.classic": "Klasyczne ikony",
      "icons.svg": "Ikony SVG",
      "about.close": "Zamknij informacje o aplikacji",
      "about.description": "Notatki, zadania, planowanie i przypomnienia w jednym miejscu.",
      "addNote": "Dodaj notatkę",
      "tags.new": "Nowa etykieta",
      "tags.newSecret": "Nowa tajna etykieta",
      "tags.manage": "Zarządzaj etykietami",
      "tags.closeManage": "Zamknij zarządzanie etykietami",
      "tags.deleteTitle": "Usunąć etykietę?",
      "secret.saveSecret": "Zapisz jako tajne",
      "secret.saveNormal": "Zapisz normalnie",
      "secret.mode": "Tryb tajny",
      "secret.close": "Zamknij tryb tajny",
      "secret.fingerprint": "Odblokuj odciskiem palca",
      "secret.nextFingerprint": "🫆 Następnym razem użyj odcisku palca",
      "secret.thisDevice": "Tylko na tym urządzeniu",
      "secret.unlock": "Odblokuj",
      "secret.tags": "Tajne etykiety",
      "secret.createTag": "Utwórz tajną etykietę",
      "secret.disableFingerprint": "Wyłącz odblokowanie odciskiem palca",
      "secret.lock": "Zablokuj tryb tajny",
      "selection.cut": "Wytnij",
      "selection.copy": "Kopiuj",
      "selection.paste": "Wklej",
      "selection.all": "Wszystko",
      "noteLinks.noMatch": "Brak pasującej notatki",
      "noteLinks.create": "+ Utwórz notatkę „{value}”",
      "noteLinks.deleted": "⚠ Usunięta notatka",
      "noteLinks.unavailable": "Notatka docelowa nie jest już dostępna.",
      "noteLinks.previous": "Poprzednia notatka",
      "noteLinks.createFailed": "Nie udało się bezpiecznie utworzyć powiązanej notatki.",
      "noteLinks.ariaTarget": "Wewnętrzny link do notatki {value}",
      "noteLinks.ariaMissing": "Wewnętrzny link do niedostępnej notatki",
      "noteLinks.dialogTitle": "Link wewnętrzny",
      "trash.title": "Kosz",
      "trash.secretTitle": "Tajny kosz",
      "trash.close": "Zamknij Kosz",
      "trash.autoDeleteInfo": "Notatki są automatycznie trwale usuwane po 30 dniach.",
      "trash.empty": "Kosz jest pusty.",
      "trash.untitled": "Bez tytułu",
      "trash.noPreview": "Brak podglądu",
      "trash.moved": "W koszu od",
      "trash.daysLeft": "Trwałe usunięcie za {count} dni",
      "trash.restore": "Przywróć",
      "trash.deleteForever": "Usuń trwale",
      "trash.deleteForeverTitle": "Usunąć trwale?",
      "trash.deleteConfirm": "Ta notatka zostanie trwale usunięta i nie będzie można jej przywrócić.",
      "trash.moveTitle": "Przenieść do Kosza?",
      "trash.moveMessage": "Notatka zostanie przeniesiona do Kosza i będzie można ją później przywrócić.",
      "trash.moveAction": "Przenieś do Kosza",
      "trash.moveManyMessage": "Przenieść {count} zaznaczonych notatek do Kosza?",
      "trash.movedMany": "Przeniesiono do Kosza: {count} notatek",
      "trash.normalTab": "Zwykłe",
      "trash.secretTab": "Tajne 🔒",
      "trash.typeTabsLabel": "Typ Kosza",
      "trash.selectAll": "Zaznacz wszystko",
      "trash.clearSelection": "Wyczyść zaznaczenie",
      "trash.deleteSelected": "Usuń trwale ({count})",
      "trash.deleteManyNormalConfirm": "Trwale usunąć {count} elementów ze zwykłego Kosza? Tej operacji nie można cofnąć.",
      "trash.deleteManySecretConfirm": "Trwale usunąć {count} elementów z Tajnego kosza? Tej operacji nie można cofnąć.",
      "trash.bulkDeletePreparing": "Przygotowywanie usuwania…",
      "trash.bulkDeleting": "Usuwanie…",
      "trash.bulkDeleteProgress": "Usuwanie elementów… {done} / {total}",
      "trash.bulkDeleteSyncing": "Synchronizowanie zmian…",
      "trash.bulkDeleteDoneAction": "Gotowe",
      "trash.bulkDeletePending": "Usunięto na tym urządzeniu. Synchronizacja zakończy się automatycznie.",
      "trash.bulkDeleteOffline": "Usunięto na tym urządzeniu. Synchronizacja rozpocznie się po powrocie online.",
      "trash.bulkDeleteFailed": "Nie udało się bezpiecznie zakończyć usuwania. Elementy pozostały w Koszu.",
      "actions.apply": "Zastosuj",
      "actions.close": "Zamknij",
      "actions.edit": "Edytuj",
      "actions.next": "Dalej",
      "actions.open": "Otwórz",
      "actions.previous": "Poprzedni",
      "actions.rename": "Zmień nazwę",
      "actions.update": "Aktualizuj",
      "calendar.chooseMonth": "Wybierz miesiąc",
      "choice.enterValue": "Wprowadź wartość",
      "choice.maximum": "Maksimum: {value}",
      "choice.minimum": "Minimum: {value}",
      "choice.selectOption": "Wybierz opcję",
      "choice.validNumber": "Wprowadź prawidłową liczbę.",
      "choice.value": "Wartość",
      "datePicker.today": "Dzisiaj",
      "dictionary.add": "Dodaj",
      "dictionary.addOwn": "Dodaj własne słowo…",
      "dictionary.empty": "Słownik jest pusty.",
      "dictionary.language": "Język słownika",
      "dictionary.search": "Szukaj w słowniku…",
      "documents.addDocument": "Dodaj dokument",
      "documents.cannotOpenType": "Tego typu pliku nie można jeszcze otworzyć.",
      "documents.chooseFileType": "Wybierz typ pliku. Dokument pozostanie tylko na tym urządzeniu.",
      "documents.closeDocument": "Zamknij dokument",
      "documents.contentUnsafe": "Nie można bezpiecznie wczytać zawartości pliku.",
      "documents.copyFailedLongPress": "Kopiowanie nie powiodło się. Spróbuj zaznaczyć tekst długim naciśnięciem.",
      "documents.copySqlAria": "Kopiuj cały skrypt SQL",
      "documents.createFolderFailed": "Nie udało się utworzyć folderu.",
      "documents.deleteEmptyFolder": "Folder „{name}” jest pusty. Zostanie usunięty tylko folder.",
      "documents.deleteFolder": "Usuń folder",
      "documents.deleteFolderFailed": "Nie udało się bezpiecznie usunąć folderu.",
      "documents.deleteFolderTitle": "Usunąć folder?",
      "documents.deleteFolderWithFiles": "Folder „{name}” zawiera {count}. Dokumenty NIE zostaną usunięte — zostaną przeniesione do „Wszystkie pliki”. Następnie zostanie usunięty tylko folder.",
      "documents.deleteForeverFailed": "Nie udało się trwale usunąć dokumentu.",
      "documents.deleteForeverMessage": "„{name}” zostanie trwale usunięty z tego urządzenia. Tej operacji nie można cofnąć.",
      "documents.deleteForeverTitle": "Trwale usunąć dokument?",
      "documents.docDescription": "lokalny odczyt tekstu starego formatu",
      "documents.docInvalid": "Plik nie jest prawidłowym dokumentem Word DOC.",
      "documents.docNoReadableText": "DOC nie zawiera czytelnego tekstu albo używa wariantu, którego przeglądarka jeszcze nie obsługuje.",
      "documents.docNotLegacy": "Plik nie jest starym dokumentem Word DOC (OLE/CFB).",
      "documents.docOldUnsupported": "Ta pierwsza wersja przeglądarki DOC obsługuje Word 97–2003. Starszy Word 6/95 nie jest jeszcze obsługiwany.",
      "documents.docOpenFailed": "Nie udało się otworzyć DOC. Obsługiwany jest Word 97–2003, a pierwsza wersja zachowuje głównie czytelny tekst.",
      "documents.docReadOnly": "DOC · TYLKO DO ODCZYTU",
      "documents.docTooLarge": "DOC jest zbyt duży. Maksymalny rozmiar to 24 MB.",
      "documents.docTooLarge24": "DOC jest zbyt duży. Maksymalny rozmiar to 24 MB.",
      "documents.docUnsupported": "Plik nie jest obsługiwanym dokumentem Word DOC.",
      "documents.document": "Dokument",
      "documents.docxDescription": "otworzy się tylko do odczytu w Dokumentach",
      "documents.docxOpenFailed": "Nie udało się otworzyć DOCX. Plik może być uszkodzony albo zawierać element, którego ta przeglądarka jeszcze nie obsługuje.",
      "documents.docxReadOnly": "DOCX · TYLKO DO ODCZYTU",
      "documents.docxTooLarge": "DOCX jest zbyt duży. Maksymalny rozmiar to 20 MB.",
      "documents.dragReorder": "Przeciągnij, aby zmienić kolejność",
      "documents.dragToFolder": "Przeciągnij do folderu docelowego",
      "documents.dropInto": "Upuść do „{name}”",
      "documents.emptyDoc": "Nie ma jeszcze żadnego DOC",
      "documents.emptyDocument": "Nie ma jeszcze żadnego dokumentu",
      "documents.emptyDocx": "Nie ma jeszcze żadnego DOCX",
      "documents.emptyEpub": "Nie ma jeszcze żadnej książki EPUB",
      "documents.emptyHint": "Dodaj pierwszy plik PDF, DOCX, DOC, EPUB lub SQL. SQL otworzy się lokalnie tylko do odczytu.",
      "documents.emptyPdf": "Nie ma jeszcze żadnego PDF",
      "documents.emptySql": "Nie ma jeszcze żadnego pliku SQL",
      "documents.epubBook": "Książka elektroniczna EPUB",
      "documents.epubDescription": "otworzy się w lokalnym LubaReaderze",
      "documents.epubEncryptedUnsupported": "Zaszyfrowany EPUB nie jest obsługiwany.",
      "documents.epubInvalid": "Plik nie jest prawidłowym EPUB.",
      "documents.epubMissingPackage": "EPUB nie zawiera ścieżki do pakietu OPF.",
      "documents.epubNoChapters": "EPUB nie ma czytelnej sekwencji rozdziałów.",
      "documents.epubOpenFailed": "Nie udało się otworzyć EPUB. Książka może być uszkodzona lub chroniona DRM.",
      "documents.epubReaderMissing": "Czytnik EPUB nie jest załadowany.",
      "documents.epubTooLarge100": "EPUB jest zbyt duży. Maksymalny rozmiar to 100 MB.",
      "documents.epubWebViewUnsupported": "Ten WebView nie potrafi rozpakować EPUB.",
      "documents.fileActions": "Akcje pliku",
      "documents.fileActionsNamed": "Akcje pliku {name}",
      "documents.fileName": "Nazwa pliku",
      "documents.fileTooLarge20": "Plik jest zbyt duży. Maksymalny rozmiar to 20 MB.",
      "documents.fileUnavailable": "Plik nie jest już dostępny.",
      "documents.folderActions": "Akcje folderu",
      "documents.folderActionsNamed": "Akcje folderu {name}",
      "documents.folderExists": "Folder „{name}” już istnieje.",
      "documents.folderLocalHint": "Folder znajduje się na razie tylko na tym urządzeniu.",
      "documents.folderLocalMeta": "{count} · lokalnie na urządzeniu",
      "documents.folderName": "Nazwa folderu",
      "documents.folderOrderFailed": "Nie udało się zapisać kolejności folderów.",
      "documents.inTrashTitle": "Dokument w koszu",
      "documents.libraryLoadFailed": "Nie udało się wczytać lokalnej biblioteki dokumentów.",
      "documents.loadFailed": "Nie udało się wczytać dokumentu.",
      "documents.longPressMoveTitle": "Przytrzymaj i przeciągnij, aby przenieść",
      "documents.longPressReorderTitle": "Przytrzymaj i przeciągnij, aby zmienić kolejność",
      "documents.lubanoteNote": "Notatka LubaNote",
      "documents.metadataFallback": "Nie udało się wczytać metadanych dokumentu LubaNote, zostanie użyty zwykły import HTML.",
      "documents.moveFailed": "Nie udało się przenieść pliku.",
      "documents.newDocument": "Nowy dokument",
      "documents.noDisplayableContent": "Dokument nie zawiera treści do wyświetlenia.",
      "documents.noFolders": "Nie masz jeszcze żadnego folderu.",
      "documents.noReadableText": "Dokument nie zawiera czytelnego tekstu.",
      "documents.nothingFound": "Nic nie znaleziono",
      "documents.nothingToCopy": "Nie ma czego kopiować.",
      "documents.openDocument": "Otwórz dokument",
      "documents.openFailed": "Nie udało się otworzyć pliku.",
      "documents.openNamed": "Otwórz {name}",
      "documents.openPdf": "Otwórz PDF",
      "documents.openingDoc": "Otwieranie DOC…",
      "documents.openingDocument": "Otwieranie dokumentu…",
      "documents.openingDocx": "Otwieranie DOCX…",
      "documents.openingSql": "Otwieranie SQL…",
      "documents.pdfDescription": "otworzy się w istniejącej przeglądarce PDF",
      "documents.pdfDisplayFailed": "Nie udało się wyświetlić PDF. Plik może być uszkodzony lub chroniony hasłem.",
      "documents.pdfOpenFailed": "Nie udało się otworzyć PDF.",
      "documents.pdfTooLarge": "PDF jest zbyt duży. Maksymalny rozmiar to 100 MB.",
      "documents.pdfTooLargeWeb": "PDF jest zbyt duży. Maksymalny rozmiar w wersji webowej to 100 MB.",
      "documents.pdfViewerUnavailable": "Przeglądarka PDF jest niedostępna.",
      "documents.renameDocument": "Zmień nazwę dokumentu",
      "documents.renameDocumentHint": "Zmieni się tylko nazwa w bibliotece LubaNote. Zawartość dokumentu pozostanie bez zmian.",
      "documents.renameFailed": "Nie udało się zmienić nazwy dokumentu.",
      "documents.renameFolder": "Zmień nazwę folderu",
      "documents.renameFolderFailed": "Nie udało się zmienić nazwy folderu.",
      "documents.renameFolderHint": "Zmieni się tylko nazwa folderu. Dokumenty w środku pozostaną bez zmian.",
      "documents.renameType": "Zmień nazwę {type}",
      "documents.renameTypeHint": "Zmieni się tylko nazwa w bibliotece LubaNote. Zawartość {type} pozostanie bez zmian.",
      "documents.restoreFailed": "Nie udało się przywrócić dokumentu.",
      "documents.restoreFromTrash": "Przywróć z kosza",
      "documents.saveAs": "Zapisz jako",
      "documents.saveFailed": "Nie udało się zapisać dokumentu.",
      "documents.saveHtml": "HTML – zachowaj formatowanie",
      "documents.savePdf": "PDF – gotowy dokument",
      "documents.saveTxt": "TXT – zwykły tekst",
      "documents.searchEmpty": "Nie znaleziono dokumentu pasującego do „{query}”.",
      "documents.secretExternalOpenBlocked": "Dokumenty zewnętrzne są niedostępne w trybie Secret. Secret pozostaje oddzielny.",
      "documents.secretExternalSaveBlocked": "Notatki Secret nie można zapisać do zewnętrznego dokumentu. Tryb Secret pozostaje oddzielny.",
      "documents.secretExternalSaveBlockedShort": "Notatki Secret nie można zapisać do zewnętrznego dokumentu.",
      "documents.sqlCopied": "Cały skrypt SQL został skopiowany.",
      "documents.sqlDescription": "otworzy się lokalnie tylko do odczytu jako kod źródłowy",
      "documents.sqlEmpty": "Plik SQL jest pusty.",
      "documents.sqlOpenFailed": "Nie udało się otworzyć SQL.",
      "documents.sqlReadFailed": "Nie udało się odczytać SQL.",
      "documents.sqlReadOnly": "SQL · TYLKO DO ODCZYTU",
      "documents.sqlScript": "Skrypt SQL",
      "documents.sqlTooLarge": "SQL jest zbyt duży. Maksymalny rozmiar to 10 MB.",
      "documents.targetFolderUnavailable": "Folder docelowy nie jest już dostępny.",
      "documents.textDocument": "Dokument tekstowy",
      "documents.trashEmpty": "Kosz jest pusty",
      "documents.trashEmptyHint": "Dokumenty przeniesione do kosza pojawią się tutaj i będzie można je przywrócić lub trwale usunąć.",
      "documents.trashMoveFailed": "Nie udało się przenieść dokumentu do kosza.",
      "documents.unsafeElement": "Dokument zawiera element, którego Core V2 nie potrafi bezpiecznie zaimportować. Dane nie zostały zmienione.",
      "documents.unsupportedType": "Ten typ pliku nie jest jeszcze obsługiwany. Wybierz PDF, DOCX, DOC, EPUB lub SQL.",
      "documents.wordReadOnly": "WORD · TYLKO DO ODCZYTU",
      "editor.tasks": "Zadania",
      "learning.addWord": "Dodaj słowo",
      "learning.addWordLanguage": "Dodaj słowo · {language}",
      "learning.addWordLanguageDot": "Dodaj słowo · {language}",
      "learning.alreadyInDictionary": "To słowo jest już w słowniku do nauki.",
      "learning.changeLanguage": "Zmień język",
      "learning.close": "Zamknij Naukę języków",
      "learning.closeTranslation": "Zamknij tłumaczenie",
      "learning.contextOptional": "Kontekst (opcjonalnie)",
      "learning.dictionary": "Słownik",
      "learning.dontKnow": "Nie umiem",
      "learning.duplicate": "Masz już takie słowo w tym języku.",
      "learning.editWord": "Edytuj słowo",
      "learning.empty": "Nie ma jeszcze żadnych słów.",
      "learning.enterOrSelectTerm": "Najpierw wpisz lub wybierz słowo albo frazę.",
      "learning.errorDifferentLanguages": "Język źródłowy i docelowy muszą być różne.",
      "learning.errorOnlineRequired": "Tłumaczenie wymaga połączenia z internetem.",
      "learning.errorSelectTerm": "Wybierz słowo lub frazę.",
      "learning.errorShorterTerm": "Do tłumaczenia wybierz krótsze słowo lub frazę.",
      "learning.errorTranslateAuto": "Nie udało się pobrać automatycznego tłumaczenia. Możesz wpisać je ręcznie.",
      "learning.errorTranslateUnavailable": "Tłumaczenie online jest teraz niedostępne. Możesz wpisać je ręcznie.",
      "learning.fillOrTranslate": "Uzupełnij tłumaczenie lub stuknij Tłumacz.",
      "learning.fillTerm": "Wpisz słowo lub frazę.",
      "learning.fillTranslation": "Uzupełnij tłumaczenie lub stuknij Tłumacz.",
      "learning.fillTranslationFirst": "Najpierw uzupełnij tłumaczenie.",
      "learning.know": "Umiem",
      "learning.languageLearningLanguage": "Nauka języków · {language}",
      "learning.manualAdd": "Dodaj słowo",
      "learning.noMistakesYet": "Na razie bez błędów",
      "learning.onlineTranslationPrivacy": "Tłumaczenie online · {direction} · wysyłane jest tylko wybrane wyrażenie.",
      "learning.playPronunciation": "Odtwórz wymowę",
      "learning.playPronunciationLanguage": "Odtwórz wymowę · {language}",
      "learning.playPronunciationTerm": "Odtwórz wymowę słowa",
      "learning.practiceEmpty": "Nie ma czego ćwiczyć.",
      "learning.practiceLanguage": "Ćwicz {language}",
      "learning.practiceLanguageAria": "Ćwicz język {language}",
      "learning.practiceWrongOnly": "Ćwicz tylko słowa, których nie umiem",
      "learning.saveChanges": "Zapisz zmiany",
      "learning.saveFailed": "Nie udało się zapisać słowa.",
      "learning.saveToDictionary": "＋ Zapisz w słowniku",
      "learning.savedToLearning": "Zapisano w Nauce języków.",
      "learning.search": "Szukaj słowa…",
      "learning.showTranslation": "Pokaż tłumaczenie",
      "learning.sourceManual": "Dodano ręcznie",
      "learning.sourceNote": "Notatka",
      "learning.sourceOptional": "Źródło (opcjonalnie)",
      "learning.sourceSeed": "Zestaw testowy LubaNote",
      "learning.statsDue": "Do powtórki",
      "learning.statsMastered": "Umiem",
      "learning.statsReviews": "Powtórki",
      "learning.statsSaved": "Zapisane",
      "learning.tabPractice": "Trening",
      "learning.tabStats": "Statystyki",
      "learning.tabWords": "Słówka",
      "learning.termOrPhrase": "Słowo / fraza",
      "learning.trainingAllOk": "Trening zakończony 🥳 Wszystkie słowa były OK.",
      "learning.translate": "Tłumacz",
      "learning.translateFailed": "Nie udało się pobrać tłumaczenia.",
      "learning.translating": "Tłumaczenie…",
      "learning.translatingDirection": "Tłumaczenie · {direction}…",
      "learning.translation": "Tłumaczenie",
      "learning.translationDictionary": "Tłumaczenie i słownik",
      "learning.translationDirection": "Tłumaczenie · {direction}",
      "learning.translationEditable": "Możesz edytować tłumaczenie przed zapisaniem.",
      "learning.translationPlaceholder": "Tłumaczenie…",
      "learning.updateInDictionary": "Aktualizuj w słowniku",
      "learning.wordUpdated": "Słowo zostało zaktualizowane.",
      "pdf.androidPickerHint": "Android otworzy tylko wybór pliku docelowego.",
      "pdf.chooseAndroidDestination": "Po potwierdzeniu wybierzesz miejsce docelowe w Androidzie.",
      "pdf.chooseFileName": "Wybierz nazwę pliku PDF.",
      "pdf.chooseOtherLocation": "Wybierz inne miejsce…",
      "pdf.close": "Zamknij PDF",
      "pdf.directCreateFailed": "Nie udało się utworzyć bezpośredniego PDF.",
      "pdf.directDownloadInfoHtml": "PDF zostanie zapisany bez kolejnego okna w <strong>Pobrane/LubaNote</strong>.",
      "pdf.directSaveHint": "Zostanie zapisany od razu, bez kolejnego okna systemowego.",
      "pdf.directSaveNoPreview": "PDF zostanie zapisany bezpośrednio w Pobrane/LubaNote bez systemowego podglądu wydruku.",
      "pdf.directTest": "Bezpośredni PDF TEST",
      "pdf.directTestHint": "Ten sam silnik drukowania Androida, ale bez podglądu systemowego.",
      "pdf.document": "Dokument PDF",
      "pdf.doubleTapFullscreen": "2× stuknięcie → pełny ekran",
      "pdf.doubleTapFullscreenHint": "Dwukrotne stuknięcie przełącza maksymalny widok PDF.",
      "pdf.exitMaxView": "Wyjdź z widoku maksymalnego",
      "pdf.fitWidth": "Dopasuj do szerokości",
      "pdf.fitWidthAria": "Dopasuj PDF do szerokości",
      "pdf.fullscreen": "Pełny ekran",
      "pdf.generatingTest": "Generowanie PDF TEST…",
      "pdf.landscape": "Poziomo",
      "pdf.loading": "Ładowanie PDF…",
      "pdf.maxView": "Maksymalny widok PDF",
      "pdf.nextPage": "Następna strona",
      "pdf.pageDisplayFailed": "Nie udało się wyświetlić strony.",
      "pdf.portrait": "Pionowo",
      "pdf.preview": "Podgląd",
      "pdf.previewFailed": "Nie udało się utworzyć podglądu PDF.",
      "pdf.previewNamed": "Podgląd • {name}",
      "pdf.previousPage": "Poprzednia strona",
      "pdf.rememberZoom": "Zapamiętaj ostatnie powiększenie",
      "pdf.rememberZoomHint": "Następny PDF otworzy się z tym samym powiększeniem.",
      "pdf.saveCopy": "Zapisz kopię PDF",
      "pdf.saveFailed": "Nie udało się zapisać PDF.",
      "pdf.savePdf": "Zapisz PDF",
      "pdf.savePreview": "Zapisz podgląd PDF",
      "pdf.savedChosenLocation": "PDF zapisano w wybranym miejscu.",
      "pdf.savedDirect": "PDF zapisano bezpośrednio w Pobrane/LubaNote.",
      "pdf.savedDownloads": "PDF zapisano w Pobrane/LubaNote.",
      "pdf.settings": "Ustawienia PDF",
      "pdf.settingsHint": "Dotyczy przeglądarki PDF w LubaNote.",
      "pdf.systemPreviewShouldNotOpen": "Podgląd systemowy nie powinien się otworzyć.",
      "pdf.viewer": "Przeglądarka PDF",
      "pdf.whereSave": "Gdzie zapisać PDF",
      "pdf.whereSaveShort": "Gdzie zapisać",
      "pdf.zoomIn": "Powiększ PDF",
      "pdf.zoomOut": "Pomniejsz PDF",
      "planner.changeFutureFirst": "Najpierw ustaw termin zadania w przyszłości.",
      "planner.futureRequired": "Termin musi być ustawiony w przyszłości.",
      "planner.reminderOff": "Przypomnienie: wyłączone",
      "planner.reminderOn": "Przypomnienie: włączone",
      "reader.addBookmarkHere": "Dodaj zakładkę tutaj",
      "reader.addNote": "Dodaj notatkę",
      "reader.airy": "Przestronne",
      "reader.alignment": "Wyrównanie",
      "reader.background": "Tło",
      "reader.book": "Książka",
      "reader.bookmarks": "Zakładki",
      "reader.bookmarksHighlights": "Zakładki i zaznaczenia",
      "reader.chapterEmpty": "Rozdział nie zawiera tekstu do wyświetlenia.",
      "reader.chapterNumber": "Rozdział {count}",
      "reader.closeBook": "Zamknij książkę",
      "reader.closeContents": "Zamknij spis treści",
      "reader.closeSettings": "Zamknij ustawienia",
      "reader.contents": "Spis treści",
      "reader.contentsAria": "Spis treści książki",
      "reader.dark": "Ciemne",
      "reader.decreaseFont": "Zmniejsz czcionkę",
      "reader.deleteBookmark": "Usuń zakładkę",
      "reader.deleteHighlight": "Usuń zaznaczenie",
      "reader.editNote": "Edytuj notatkę",
      "reader.font": "Czcionka",
      "reader.fontSize": "Rozmiar czcionki",
      "reader.highlight": "Zaznaczenie",
      "reader.highlightBlue": "Niebieskie zaznaczenie",
      "reader.highlightColor": "Kolor zaznaczenia",
      "reader.highlightGreen": "Zielone zaznaczenie",
      "reader.highlightNote": "Notatka do zaznaczenia",
      "reader.highlightViolet": "Fioletowe zaznaczenie",
      "reader.highlightYellow": "Żółte zaznaczenie",
      "reader.highlights": "Zaznaczenia",
      "reader.increaseFont": "Zwiększ czcionkę",
      "reader.justify": "Wyjustuj",
      "reader.left": "Do lewej",
      "reader.light": "Jasne",
      "reader.lineHeight": "Interlinia",
      "reader.margins": "Marginesy tekstu",
      "reader.narrow": "Wąskie",
      "reader.noBookmarks": "Brak zakładek.",
      "reader.noHighlights": "Brak zaznaczeń.",
      "reader.normal": "Normalne",
      "reader.note": "Notatka",
      "reader.notePlaceholder": "Napisz własną notatkę…",
      "reader.openingEpub": "Otwieranie EPUB…",
      "reader.preparingBook": "Przygotowywanie książki…",
      "reader.preparingBookCount": "Przygotowywanie książki… {current} / {total}",
      "reader.removeHighlight": "Usuń zaznaczenie",
      "reader.resetDefaults": "Przywróć domyślne",
      "reader.sans": "Bezszeryfowa",
      "reader.sepia": "Sepia",
      "reader.serif": "Szeryfowa",
      "reader.settings": "Ustawienia czytania",
      "reader.smaller": "Mniejsze",
      "reader.tapRemoveHighlight": "Stuknij, aby usunąć zaznaczenie",
      "reader.wide": "Szerokie",
      "reader.withNote": "Z notatką",
      "recurring.nextOccurrence": "Następne wystąpienie",
      "recurring.nextScheduled": "Zaplanowano następne powtórzenie",
      "recurring.previousOccurrence": "Poprzednie wystąpienie",
      "recurring.ruleAt": "{rule} o {time}",
      "recurring.start": "Początek powtarzania",
      "recurring.turnOff": "Wyłącz powtarzanie",
      "reminders.channelDescription": "Powiadomienia o zaplanowanych notatkach i zadaniach",
      "reminders.channelName": "Przypomnienia LubaNote",
      "reminders.deletePlannedTitle": "Usunąć zaplanowane zadanie?",
      "reminders.deletePlannerTaskTitle": "Usunąć zadanie z planu?",
      "reminders.deleteReminderTitle": "Usunąć przypomnienie?",
      "reminders.disabled": "Przypomnienie wyłączone",
      "reminders.enabled": "Przypomnienie włączone",
      "reminders.exactMessage": "Zezwól w Androidzie na dokładne alarmy, inaczej system może opóźnić powiadomienie.",
      "reminders.exactTitle": "Dokładne przypomnienia",
      "reminders.futureRequired": "Przypomnienie musi być ustawione w przyszłości.",
      "reminders.noteCompleted": "Notatka ukończona",
      "reminders.remind": "Przypomnij",
      "reminders.removeNoteFromPlanTitle": "Usunąć notatkę z planu?",
      "reminders.turnOffFailed": "Nie udało się bezpiecznie wyłączyć przypomnienia.",
      "reminders.turnOffShort": "Wyłącz",
      "reminders.turningOff": "Wyłączanie przypomnienia…",
      "settings.choice1": "1. opcja",
      "settings.choice2": "2. opcja",
      "settings.choice3": "3. opcja",
      "settings.choice4": "4. opcja",
      "settings.snoozeHours": "{count} godz.",
      "settings.snoozeMinutes": "{count} min",
      "status.preparing": "Przygotowywanie…",
      "status.saved": "Zapisano ✓",
      "status.savedCheck": "Zapisano ✓",
      "status.updated": "Zaktualizowano ✓",
      "tags.duplicate": "Etykieta o tej nazwie już istnieje.",
      "tags.maxTwo": "Notatka może mieć maksymalnie 2 etykiety. Najpierw usuń jedną.",
      "timePicker.now": "Teraz",
      "timePicker.set": "Ustaw",
      "secret.deviceUnlockTitle": "Odblokuj to urządzenie",
      "secret.createMainTitle": "Utwórz hasło główne",
      "secret.unlockContinue": "Odblokuj i kontynuuj",
      "secret.createContinue": "Utwórz i kontynuuj",
      "secret.deviceUnlockDescription": "To konto ma już hasło główne. Wpisz je raz, aby LubaNote mogła bezpiecznie przygotować tryb tajny i zdjęcia E2E na tym urządzeniu. Dopiero potem rozpocznie się synchronizacja.",
      "secret.createMainDescription": "Zanim zaczniesz używać LubaNote, utwórz hasło główne. Chroni ono tryb tajny i zdjęcia szyfrowane E2E. Nie jest to hasło logowania i LubaNote nie zapisuje go w chmurze.",
      "secret.unlockMode": "Odblokuj tryb tajny",
      "secret.createMainForNotes": "Utwórz hasło główne dla tajnych notatek.",
      "secret.createPassword": "Utwórz hasło",
      "tags.deleting": "Usuwanie etykiety…",
      "tags.savingShort": "Zapisywanie…",
      "tags.saving": "Zapisywanie etykiety…",
      "tags.moveUp": "Przesuń etykiety w górę",
      "tags.moveDown": "Przesuń etykiety w dół",
      "tags.orderSaveFailed": "Nie udało się zapisać kolejności etykiet.",
      "tags.savingOrder": "Zapisywanie kolejności etykiet…",
      "tags.colorAria": "Kolor etykiety {name}",
      "tags.setColorAria": "Ustaw kolor etykiety na {color}",
      "tags.renameAria": "Zmień nazwę etykiety {name}",
      "tags.renaming": "Zmienianie nazwy etykiety…",
      "tags.deleteAria": "Usuń etykietę {name}",
      "tags.deleteConfirm": "Czy na pewno chcesz usunąć etykietę „{name}”?",
      "tags.unlockFirst": "Najpierw odblokuj tryb tajny.",
      "tags.newSaveFailed": "Nie udało się zapisać nowej etykiety.",
      "tags.newLocalSaveFailed": "Nie udało się zapisać nowej lokalnej etykiety.",
      "tags.newSaveFailedConnection": "Nie udało się zapisać nowej etykiety. Sprawdź połączenie i spróbuj ponownie.",
      "tags.longPressWorks": "Długie przytrzymanie działa.",
      "tags.assignedMany": "Etykietę „{name}” przypisano do {count} kart",
      "tags.color.cervena": "Czerwony",
      "tags.color.oranzova": "Pomarańczowy",
      "tags.color.zluta": "Żółty",
      "tags.color.zelena": "Zielony",
      "tags.color.tyrkysova": "Turkusowy",
      "tags.color.modra": "Niebieski",
      "tags.color.fialova": "Fioletowy",
      "tags.color.ruzova": "Różowy",
      "documents.addedType": "Dodano: {type} „{name}”.",
      "documents.addFailed": "Nie udało się dodać dokumentu.",
      "documents.selectedNotType": "Wybrany plik nie jest plikiem {type}.",
      "documents.addFailedType": "Nie udało się dodać {type}.",
      "documents.selectedNotLegacyDoc": "Wybrany plik nie jest starym plikiem Word DOC."
    },

    texty: {
      ...anglicky.texty,
      "Přihlášení vypršelo. Přihlas se znovu, aby mohla pokračovat synchronizace. Tvoje lokální data zůstala zachována.": "Logowanie wygasło. Zaloguj się ponownie, aby synchronizacja mogła być kontynuowana. Twoje lokalne dane zostały zachowane.",
      "Nepodařilo se připojit k synchronizaci. Zkus to znovu po připojení k internetu.": "Nie udało się połączyć z synchronizacją. Spróbuj ponownie po połączeniu z internetem.",
      "Ověření přihlášení se nepodařilo.": "Nie udało się zweryfikować logowania.",
      "První přihlášení vyžaduje připojení k internetu.": "Pierwsze logowanie wymaga połączenia z internetem.",
      "Ověřuji přihlášení…": "Weryfikowanie logowania…",
      "Vyplň e-mail i heslo.": "Wpisz e-mail i hasło.",
      "Přihlášení vyžaduje internet. Lokální aplikace funguje offline až po prvním úspěšném přihlášení.": "Logowanie wymaga internetu. Tryb offline działa po pierwszym udanym logowaniu.",
      "Přihlašuji…": "Logowanie…",
      "Přihlášení se nezdařilo. Zkontroluj e-mail, heslo a připojení.": "Logowanie nie powiodło się. Sprawdź e-mail, hasło i połączenie.",
      "Světlý": "Jasny",
      "Tmavý": "Ciemny",
      "Původní ikony": "Klasyczne ikony",
      "SVG ikony": "Ikony SVG",
      "Pracovní": "Praca",
      "Soukromé": "Prywatne",
      "Bez názvu": "Bez tytułu",
      "Žádná odpovídající poznámka": "Brak pasującej notatki",
      "⚠ Smazaná poznámka": "⚠ Usunięta notatka",
      "Tajný režim": "Tryb tajny",
      "Tajný režim byl zamčen.": "Tryb tajny został zablokowany.",
      "Tajný režim byl automaticky zamčen.": "Tryb tajny został automatycznie zablokowany.",
      "Tajný režim je odemčený.": "Tryb tajny jest odblokowany.",
      "Tajný režim se nepodařilo odemknout.": "Nie udało się odblokować trybu tajnego.",
      "Tajný režim není odemčený.": "Tryb tajny nie jest odblokowany.",
      "Zadej hlavní heslo.": "Wpisz hasło główne.",
      "Hlavní heslo není správné.": "Hasło główne jest nieprawidłowe.",
      "Hlavní heslo musí mít alespoň 8 znaků.": "Hasło główne musi mieć co najmniej 8 znaków.",
      "Hlavní heslo se nepodařilo vytvořit.": "Nie udało się utworzyć hasła głównego.",
      "Upozornění": "Uwaga",
      "Nový štítek": "Nowa etykieta",
      "Název štítku": "Nazwa etykiety",
      "+ Nový štítek": "+ Nowa etykieta",
      "Nový tajný štítek": "Nowa tajna etykieta",
    }
  });
})();
