/* LubaNote – Español · PATCH 676A */
window.LubaNoteLanguagePacks = window.LubaNoteLanguagePacks || [];

(() => {
  const anglicky = window.LubaNoteLanguagePacks.find((balicek) => balicek.id === "en") || { preklady: {}, texty: {} };

  window.LubaNoteLanguagePacks.push({
    id: "es",
    nazev: "Español",
    kratkyNazev: "ES",
    vlajka: "🇪🇸",
    locale: "es-ES",

    // Nejdřív bezpečný anglický fallback; přeložené produkční UI ho přepisuje níže.
    preklady: {
      ...anglicky.preklady,
      "language.label": "Idioma",
      "language.choose": "Elegir idioma",
      "login.splashSubtitle": "Notas • Plan • Documentos",
      "login.loading": "LubaNote se está cargando",
      "login.title": "Iniciar sesión",
      "login.registerTitle": "Registro",
      "login.modeSignIn": "Iniciar sesión",
      "login.modeRegister": "Registro",
      "login.email": "Correo electrónico",
      "login.password": "Contraseña",
      "login.passwordAgain": "Repite la contraseña",
      "login.submit": "Iniciar sesión",
      "login.registerSubmit": "Registrarse",
      "login.checkStatus": "Comprobar estado",
      "login.modeAria": "Iniciar sesión o registrarse",
      "login.downloadMyData": "Descargar mis datos",
      "login.deleteMyData": "Eliminar mis datos",
      "login.clearThisDevice": "Borrar este dispositivo",
      "login.deleteMyDataTitle": "¿Eliminar mis datos?",
      "login.clearThisDeviceTitle": "¿Borrar este dispositivo?",
      "login.clearWithoutBackup": "Borrar sin copia de seguridad",
      "login.pendingTitle": "La cuenta espera aprobación",
      "login.pendingText": "El registro está completo. LubaNote se desbloqueará cuando un administrador apruebe la cuenta.",
      "login.rejectedTitle": "El registro no fue aprobado",
      "login.rejectedText": "Esta cuenta no fue aprobada. Si se trata de un error, contacta con el administrador de LubaNote.",
      "login.suspendedTitle": "Cuenta suspendida",
      "login.suspendedText": "El acceso a LubaNote está suspendido temporalmente.",
      "login.unavailableTitle": "Cuenta no disponible",
      "login.unavailableText": "No se pudo verificar el acceso a la cuenta. Inténtalo de nuevo.",
      "login.enterCredentials": "Introduce el correo y la contraseña.",
      "login.enterRegistration": "Introduce el correo, la contraseña y repítela.",
      "login.passwordMismatch": "Las contraseñas no coinciden.",
      "login.passwordTooShort": "La contraseña debe tener al menos 8 caracteres.",
      "login.registrationOnline": "El registro requiere conexión a internet.",
      "login.registering": "Registrando…",
      "login.registrationCreated": "El registro se ha creado. Confirma tu correo y después inicia sesión.",
      "login.emailConfirmed": "Correo confirmado. Ya puedes iniciar sesión.",
      "login.emailLinkInvalid": "El enlace de confirmación ya se utilizó o ha caducado. Si tu correo está confirmado, inicia sesión.",
      "login.stillPending": "La cuenta sigue esperando aprobación.",
      "login.alreadyRegistered": "Este correo ya está registrado. Usa Iniciar sesión.",
      "login.registrationFailed": "El registro ha fallado. Comprueba el correo, la contraseña y la conexión.",
      "login.registrationRateLimited": "Se han enviado demasiados correos de confirmación. Intenta registrarte más tarde.",
      "login.signingIn": "Iniciando sesión…",
      "login.signInFailed": "No se pudo iniciar sesión. Comprueba el correo, la contraseña y la conexión.",
      "login.emailNotConfirmed": "Tu correo todavía no está confirmado. Abre el enlace de confirmación del correo y vuelve a iniciar sesión.",
      "login.accountCheckFailed": "No se pudo verificar el estado de la cuenta. Inténtalo de nuevo.",
      "login.localOwnerMismatch": "Esta instalación contiene datos locales de otra cuenta de LubaNote. Por seguridad, no se pueden mezclar cuentas en la misma instalación.",
      "login.demoExpiredTitle": "La demo ha terminado",
      "login.demoExpiredText": "Tu Demo terminó el {date}. Todos tus datos siguen guardados de forma segura. Se necesitará acceso completo a LubaNote para seguir usando la aplicación.",
      "login.fullExpiredTitle": "El acceso completo ha terminado",
      "login.fullExpiredText": "Tus datos siguen guardados de forma segura. LubaNote se desbloqueará de nuevo cuando se renueve el acceso completo.",
      "account.demoUntil": "Demo hasta {date}",
      "limits.notesTitle": "Se alcanzó el límite de notas",
      "limits.notesText": "Tu plan permite hasta {limit} notas. Ahora no se puede guardar una nota nueva de forma segura. Tus datos existentes se conservan.",
      "nav.quick": "Navegación rápida",
      "nav.tools": "Herramientas",
      "nav.home": "Inicio",
      "nav.allNotes": "Todas las notas",
      "nav.favorites": "Favoritos",
      "nav.tags": "Etiquetas",
      "nav.settings": "Ajustes",
      "nav.backup": "Copia de seguridad y restauración",
      "modules.aria": "Secciones principales de LubaNote",
      "modules.notes": "Notas",
      "storageScope.cloud": "Sincronizado",
      "storageScope.local": "Este dispositivo",
      "storageScope.menu": "Almacenamiento",
      "storageScope.choose": "¿Dónde deben guardarse las notas?",
      "storageScope.localTitle": "Solo este dispositivo",
      "storageScope.localWarning": "Las notas de este espacio no se sincronizan. Si el dispositivo se pierde o se borra, no podrán restaurarse desde la nube. Se recomiendan copias de seguridad periódicas.",
      "storageScope.shareTitle": "Solo este dispositivo",
      "storageScope.shareBlocked": "Compartir requiere almacenamiento sincronizado. Esta nota permanece solo en este dispositivo.",
      "modules.planner": "Plan",
      "modules.documents": "Documentos",
      "documents.eyebrow": "Documentos V1",
      "documents.title": "Documentos",
      "documents.addFile": "＋ Añadir archivo",
      "documents.folders": "Carpetas",
      "documents.newFolder": "Nueva carpeta",
      "documents.files": "Archivos",
      "documents.allFiles": "Todos los archivos",
      "documents.searchPlaceholder": "Buscar…",
      "documents.searchAria": "Buscar archivos",
      "documents.clearSearch": "Borrar búsqueda",
      "documents.filterAria": "Filtro de documentos",
      "documents.filterAll": "Todos",
      "documents.trash": "Papelera",
      "documents.folderFallback": "Carpeta",
      "documents.localAndroid": "Guardado localmente en este dispositivo Android",
      "documents.localBrowser": "Guardado localmente en este navegador",
      "documents.fileCount.one": "{count} archivo",
      "documents.fileCount.other": "{count} archivos",
      "plannerTabs.calendar": "Calendario",
      "modules.reminders": "Recordatorios",
      "sync.synced": "✓ Sincronizado",
      "sync.syncing": "⟳ Sincronizando…",
      "sync.pending": "⏳ Pendiente de sincronización",
      "sync.localOnly": "📱 Solo este dispositivo",
      "sync.authExpired": "⚠ La sesión ha caducado",
      "sync.conflict": "⚠ Conflicto",
      "search.placeholder": "Buscar…",
      "search.aria": "Buscar notas",
      "search.clear": "Borrar búsqueda",
      "search.view": "Cambiar diseño de tarjetas",
      "search.menu": "Menú principal",
      "sort.labelNewest": "Tarjetas nuevas: arriba",
      "sort.labelOldest": "Tarjetas nuevas: abajo",
      "sort.title": "Posición de tarjetas nuevas",
      "sort.newest": "Tarjetas nuevas arriba",
      "sort.oldest": "Tarjetas nuevas abajo",
      "search.none": "No se encontraron notas.",
      "menu.manageTags": "Gestionar etiquetas",
      "menu.about": "Acerca de",
      "menu.logout": "Cerrar sesión",
      "filter.aria": "Filtros de notas",
      "filter.all": "Todas",
      "filter.work": "Trabajo",
      "filter.private": "Privadas",
      "filter.favorite": "Notas favoritas",
      "filter.secret": "Notas secretas",
      "filter.finishSelection": "Finalizar selección",
      "calendar.previousMonth": "Mes anterior",
      "calendar.nextMonth": "Mes siguiente",
      "calendar.selectedDay": "Día seleccionado",
      "calendar.addSelected": "Añadir tarea al día seleccionado",
      "calendar.back": "Volver al calendario",
      "calendar.addDay": "Añadir tarea a este día",
      "calendar.week": "semana",
      "calendar.weekNumber": "Semana {value}",
      "weekday.mo": "Lun",
      "weekday.tu": "Mar",
      "weekday.we": "Mié",
      "weekday.th": "Jue",
      "weekday.fr": "Vie",
      "weekday.sa": "Sáb",
      "weekday.su": "Dom",
      "recurring.title": "Recurrentes",
      "recurring.back": "Volver a recordatorios",
      "recurring.show": "Mostrar tareas recurrentes",
      "recurring.none": "No hay tareas recurrentes.",
      "recurring.repeat": "Se repite",
      "recurring.next": "Siguiente: {value}",
      "recurring.noNext": "Esta serie no tiene una siguiente aparición.",
      "reminders.overdue": "Vencidos",
      "reminders.active": "Activos",
      "reminders.today": "Hoy",
      "reminders.none": "No hay recordatorios.",
      "reminders.noneOverdue": "No hay recordatorios vencidos.",
      "reminders.tomorrow": "Mañana",
      "reminders.later": "Más tarde",
      "reminders.label": "Recordatorio",
      "reminders.untitled": "Sin título",
      "reminders.close": "Cerrar",
      "reminders.tomorrow8": "Mañana 8:00",
      "reminders.date": "Fecha",
      "reminders.time": "Hora",
      "reminders.selectDate": "Elegir fecha del recordatorio",
      "reminders.selectTime": "Elegir hora del recordatorio",
      "reminders.done": "Hecho",
      "reminders.delete": "Eliminar",
      "reminders.openNote": "Abrir nota",
      "reminders.turnOff": "Desactivar recordatorio",
      "editor.find": "Buscar",
      "editor.findInNote": "Buscar en esta nota",
      "editor.findPrevious": "Resultado anterior",
      "editor.findNext": "Resultado siguiente",
      "editor.findClose": "Cerrar búsqueda",
      "editor.openTools": "Abrir herramientas de edición",
      "editor.formatting": "Formato de la nota",
      "editor.moreTools": "Más herramientas de la nota",
      "editor.undo": "Deshacer",
      "editor.redo": "Rehacer",
      "editor.bold": "Negrita",
      "editor.italic": "Cursiva",
      "editor.underline": "Subrayado",
      "editor.fontSize": "Tamaño de fuente",
      "editor.textStyle": "Estilo de texto",
      "editor.textColor": "Color de texto",
      "editor.white": "Texto blanco",
      "editor.black": "Texto negro",
      "editor.align": "Alineación del texto",
      "editor.alignLeft": "Alinear a la izquierda",
      "editor.alignCenter": "Centrar",
      "editor.alignRight": "Alinear a la derecha",
      "editor.insertImage": "Insertar imagen",
      "editor.insertWebLink": "Insertar enlace web",
      "editor.webLink": "Enlace web",
      "editor.openDocument": "Abrir documento",
      "editor.saveAs": "Guardar como",
      "editor.bullets": "Lista con viñetas",
      "editor.date": "Fecha",
      "editor.time": "Hora",
      "editor.selectDate": "Elegir fecha",
      "editor.selectTime": "Elegir hora",
      "editor.pin": "Fijar nota",
      "editor.reminder": "Recordatorio",
      "editor.backLink": "Volver a la nota enlazada anterior",
      "editor.titleAria": "Título de la nota",
      "editor.titlePlaceholder": "Título de la nota",
      "editor.secret": "Nota secreta",
      "editor.tags": "Etiquetas",
      "editor.newTag": "Nueva etiqueta",
      "editor.cancelNewTag": "Cancelar nueva etiqueta",
      "editor.saveClose": "Guardar y cerrar",
      "editor.area": "Área de la nota",
      "editor.priority": "Prioridad",
      "editor.color": "Color",
      "editor.planSelection": "Planificar texto seleccionado",
      "editor.addTodo": "Añadir elemento TODO",
      "editor.deleteNote": "Eliminar nota",
      "backlinks.aria": "Enlaces a esta nota",
      "backlinks.title": "Enlaces a esta nota ({count})",
      "backlinks.none": "No hay enlaces a esta nota",
      "actions.save": "Guardar",
      "actions.discard": "No guardar",
      "actions.ok": "OK",
      "status.done": "Hecho",
      "secret.mainPassword": "Contraseña principal",
      "secret.passwordAgain": "Repite la contraseña",
      "secret.enterMain": "Introduce la contraseña principal.",
      "actions.term": "Fecha límite",
      "actions.pin": "Fijar",
      "actions.delete": "Eliminar",
      "actions.more": "Más acciones",
      "actions.cancel": "Cancelar",
      "actions.create": "Crear",
      "message.notice": "Aviso",
      "editor.notePlaceholder": "Escribe una nota…",
      "tags.name": "Nombre de la etiqueta",
      "tags.add": "Añadir",
      "deleteNote.message": "¿Seguro que quieres eliminar esta nota?",
      "deleteNote.title": "¿Eliminar nota?",
      "timePicker.title": "Elegir hora",
      "timePicker.close": "Cerrar selector de hora",
      "timePicker.clock": "Esfera del selector de hora",
      "repeat.title": "Repetir",
      "repeat.aria": "Repetición de tarea",
      "repeat.no": "No",
      "repeat.daily": "Diariamente",
      "repeat.weekly": "Semanalmente",
      "repeat.twoWeeks": "2 semanas",
      "repeat.monthly": "Mensualmente",
      "repeat.none": "No repetir",
      "planner.plan": "Planificar",
      "planner.close": "Cerrar planificación",
      "planner.selectDate": "Elegir fecha de la tarea planificada",
      "planner.selectTime": "Elegir hora de la tarea planificada",
      "sharing.settingsTitle": "Compartir",
      "sharing.usernameLabel": "Nombre de usuario",
      "sharing.usernameUnset": "Configurar",
      "sharing.usernameModalTitle": "Nombre de usuario para compartir",
      "sharing.usernameDescription": "Otras personas solo pueden encontrarte por tu @nombre de usuario exacto. Tu correo nunca se muestra al compartir.",
      "sharing.usernamePlaceholder": "p. ej. Lubomir",
      "sharing.usernameSave": "Guardar",
      "sharing.usernameCancel": "Cancelar",
      "sharing.usernameInvalid": "Usa entre 3 y 30 caracteres: letras, números, punto, guion o guion bajo.",
      "sharing.usernameTaken": "Este @nombre de usuario ya lo usa otra persona.",
      "sharing.usernameOffline": "Configurar un @nombre de usuario requiere conexión a internet.",
      "sharing.usernameSaving": "Guardando…",
      "sharing.usernameSaveFailed": "No se pudo guardar el nombre de usuario.",
      "sharing.usernameRequiredTitle": "Crea tu @nombre de usuario",
      "sharing.usernameRequiredDescription": "Antes de usar LubaNote, crea un @nombre de usuario público para compartir y chatear. Otras personas solo pueden encontrarte por el @nombre exacto; tu correo no se muestra.",
      "sharing.usernameRequiredSave": "Crear y continuar",
      "sharing.shareButton": "Compartir",
      "sharing.invitationsAria": "Invitaciones para compartir",
      "sharing.shareModalTitle": "Compartir nota",
      "sharing.shareModalDescription": "Invita a un usuario introduciendo su @nombre de usuario exacto.",
      "sharing.shareInputPlaceholder": "p. ej. LubaNoteDemo",
      "sharing.shareSend": "Enviar invitación",
      "sharing.shareSending": "Enviando…",
      "sharing.shareSendSuccess": "Invitación enviada.",
      "sharing.shareSendFailed": "No se pudo enviar la invitación.",
      "sharing.shareInvalidUsername": "Introduce un @nombre de usuario válido.",
      "sharing.shareOffline": "Compartir requiere conexión a internet.",
      "sharing.shareUsernameMissing": "Primero configura tu propio @nombre de usuario en Ajustes.",
      "sharing.shareUserNotFound": "No se encontró ningún usuario con ese @nombre exacto.",
      "sharing.shareSelf": "No puedes compartir una nota contigo mismo.",
      "sharing.shareAlreadyCollaborator": "Este usuario ya colabora en la nota.",
      "sharing.shareAlreadyPending": "Ya hay una invitación pendiente para este usuario.",
      "sharing.shareSecretBlocked": "Las notas secretas todavía no se pueden compartir.",
      "sharing.shareNewNoteBlocked": "Guarda primero la nota y después podrás compartirla.",
      "sharing.collaboratorsTitle": "Colaboradores",
      "sharing.collaboratorsEmpty": "Aún no hay colaboradores.",
      "sharing.pendingTitle": "Invitaciones pendientes",
      "sharing.pendingEmpty": "No hay invitaciones pendientes.",
      "sharing.cancelInvitation": "Cancelar",
      "sharing.cancelFailed": "No se pudo cancelar la invitación.",
      "sharing.cancel": "Cancelar",
      "sharing.removeCollaborator": "Eliminar",
      "sharing.removeCollaboratorConfirm": "¿Eliminar a {username} del uso compartido?",
      "sharing.removeCollaboratorSuccess": "Colaborador eliminado.",
      "sharing.removeCollaboratorFailed": "No se pudo eliminar al colaborador.",
      "sharing.removeCollaboratorMissing": "Este usuario ya no comparte la nota.",
      "sharing.manageNotOwner": "Solo el propietario de la nota puede realizar esta acción.",
      "sharing.manageModalUnavailable": "No se pudo abrir el cuadro de confirmación.",
      "sharing.leaveSharedNote": "Dejar de compartir",
      "sharing.leaveConfirm": "¿Dejar de compartir esta nota?",
      "sharing.leaveSuccess": "Has dejado de compartir.",
      "sharing.leaveFailed": "No se pudo dejar de compartir.",
      "sharing.ownerCannotLeave": "El propietario no puede dejar de compartir. Transfiere primero la propiedad.",
      "sharing.ownerRole": "Propietario",
      "sharing.editorRole": "Editor",
      "sharing.invitationsTitle": "Invitaciones para compartir",
      "sharing.invitationsEmpty": "No tienes invitaciones pendientes.",
      "sharing.invitedBy": "Invitado por {username}",
      "sharing.accept": "Aceptar",
      "sharing.decline": "Rechazar",
      "sharing.responding": "Procesando…",
      "sharing.invitationAccepted": "Invitación aceptada.",
      "sharing.invitationDeclined": "Invitación rechazada.",
      "sharing.invitationResponseFailed": "No se pudo procesar la invitación.",
      "sharing.refresh": "Actualizar",
      "sharing.close": "Cerrar",
      "sharing.loading": "Cargando…",
      "sharing.loadFailed": "No se pudieron cargar los datos compartidos.",
      "sharing.sharedUntitled": "Sin título",
      "sharing.sharedCardMeta": "Compartida · {owner}",
      "sharing.readOnlyTitle": "Nota compartida",
      "sharing.readOnlyMeta": "{owner} · nota compartida",
      "sharing.readOnlyTodos": "Tareas",
      "sharing.editShared": "Editar",
      "sharing.sharedEditorOffline": "Una nota compartida solo se puede editar estando en línea.",
      "sharing.sharedEditorBusy": "{username} está editando esta nota ahora mismo. Por ahora solo puedes leerla.",
      "sharing.sharedEditorOpening": "Abriendo editor compartido…",
      "sharing.sharedEditorSaveFailed": "No se pudo guardar de forma segura la nota compartida. El editor permanece abierto.",
      "sharing.sharedEditorConflict": "Existe una versión más reciente de la nota en el servidor. El editor permanece abierto; ciérralo sin guardar y vuelve a abrir la nota.",
      "sharing.sharedEditorLockLost": "El bloqueo del editor ya no es válido. El editor compartido se cerró de forma segura.",
      "sharing.sharedEditorSaved": "Nota compartida guardada.",
      "chat.buttonAria": "Mensajes",
      "chat.contactsTitle": "Mensajes",
      "chat.contactsEmpty": "Aún no tienes contactos de chat. Se crea un contacto después de aceptar una invitación para compartir una nota.",
      "chat.writeMessage": "Escribir mensaje",
      "chat.trustedContact": "Contacto de uso compartido",
      "chat.ready": "Podéis enviaros mensajes",
      "chat.lastMessageAt": "Último mensaje {time}",
      "chat.messagePlaceholder": "Escribe un mensaje…",
      "chat.send": "Enviar",
      "chat.sending": "Enviando…",
      "chat.sent": "Enviado",
      "chat.read": "Leído",
      "chat.messagesEmpty": "Aún no hay mensajes.",
      "chat.deletedPlaceholder": "El mensaje fue eliminado",
      "chat.deleteMessage": "Eliminar mensaje",
      "chat.deleteTitle": "¿Eliminar mensaje?",
      "chat.deleteText": "El mensaje se eliminará para ambos participantes y solo quedará un aviso de mensaje eliminado.",
      "chat.deleteForBoth": "Eliminar para ambos",
      "chat.deleting": "Eliminando…",
      "chat.deleteFailed": "No se pudo eliminar el mensaje.",
      "chat.sendFailed": "No se pudo enviar el mensaje.",
      "chat.loadFailed": "No se pudo cargar el chat.",
      "chat.loadMessagesFailed": "No se pudieron cargar los mensajes.",
      "chat.loading": "Cargando…",
      "chat.offline": "El chat requiere conexión a internet.",
      "chat.blocked": "El chat está bloqueado",
      "chat.contactNotFound": "El contacto del chat aún no está disponible.",
      "chat.tooLong": "El mensaje es demasiado largo.",
      "chat.close": "Cerrar",
      "chat.back": "Atrás",
      "chat.cancel": "Cancelar",
      "chat.threadAria": "Chat",
      "settings.personalDictionary": "Mi diccionario",
      "settings.languageLearning": "Aprendizaje de idiomas",
      "settings.manageDictionary": "Gestionar",
      "settings.openLearning": "Abrir",
      "settings.wordsCount.one": "{count} palabra",
      "settings.wordsCount.other": "{count} palabras",
      "settings.plannerReminderDefault": "Recordar automáticamente al planificar",
      "settings.enabled": "Activado",
      "settings.disabled": "Desactivado",
      "settings.planning": "Planificación",
      "settings.automaticReminder": "Recordatorio automático",
      "settings.title": "Ajustes",
      "settings.close": "Cerrar ajustes",
      "settings.appearance": "Apariencia",
      "settings.fontSize": "Tamaño de fuente",
      "settings.decreaseFont": "Reducir tamaño de fuente",
      "settings.increaseFont": "Aumentar tamaño de fuente",
      "settings.theme": "Tema de color",
      "settings.iconStyle": "Estilo de iconos",
      "settings.keyboard": "Teclado del editor",
      "settings.keyboardTitle": "Teclado del editor",
      "settings.keyboardLuba": "LubaKeyboard (predeterminado)",
      "settings.keyboardSystem": "Sistema",
      "settings.keyboardSystemLong": "Teclado del sistema (Gboard / iOS)",
      "settings.reminders": "Recordatorios",
      "settings.quickDelay": "Posponer rápido",
      "settings.configure": "Configurar",
      "settings.overdueRetention": "Eliminar vencidos después de",
      "settings.overdueNever": "Nunca",
      "settings.overdueDays": "{count} días",
      "settings.overdueConfirm": "confirmar",
      "settings.data": "Datos",
      "settings.noteOpenPosition": "Al abrir una nota",
      "settings.noteOpenStart": "Inicio",
      "settings.noteOpenEnd": "Final",
      "settings.export": "Exportar copia de seguridad",
      "settings.import": "Importar copia de seguridad",
      "settings.about": "Acerca de",
      "settings.version": "Versión",
      "settings.appInfo": "Información de la aplicación",
      "settings.open": "Abrir",
      "theme.light": "Claro",
      "theme.dark": "Oscuro",
      "icons.classic": "Iconos clásicos",
      "icons.svg": "Iconos SVG",
      "about.close": "Cerrar información de la aplicación",
      "about.description": "Notas, tareas, planificación y recordatorios en un solo lugar.",
      "addNote": "Añadir nota",
      "tags.new": "Nueva etiqueta",
      "tags.newSecret": "Nueva etiqueta secreta",
      "tags.manage": "Gestionar etiquetas",
      "tags.closeManage": "Cerrar gestión de etiquetas",
      "tags.deleteTitle": "¿Eliminar etiqueta?",
      "secret.saveSecret": "Guardar como secreto",
      "secret.saveNormal": "Guardar normalmente",
      "secret.mode": "Modo secreto",
      "secret.close": "Cerrar modo secreto",
      "secret.fingerprint": "Desbloquear con huella",
      "secret.nextFingerprint": "🫆 Usar huella la próxima vez",
      "secret.thisDevice": "Solo en este dispositivo",
      "secret.unlock": "Desbloquear",
      "secret.tags": "Etiquetas secretas",
      "secret.createTag": "Crear etiqueta secreta",
      "secret.disableFingerprint": "Desactivar desbloqueo con huella",
      "secret.lock": "Bloquear modo secreto",
      "selection.cut": "Cortar",
      "selection.copy": "Copiar",
      "selection.paste": "Pegar",
      "selection.all": "Todo",
      "noteLinks.noMatch": "No hay ninguna nota coincidente",
      "noteLinks.create": "+ Crear nota “{value}”",
      "noteLinks.deleted": "⚠ Nota eliminada",
      "noteLinks.unavailable": "La nota de destino ya no está disponible.",
      "noteLinks.previous": "Nota anterior",
      "noteLinks.createFailed": "No se pudo crear de forma segura la nota enlazada.",
      "noteLinks.ariaTarget": "Enlace interno a la nota {value}",
      "noteLinks.ariaMissing": "Enlace interno a una nota no disponible",
      "noteLinks.dialogTitle": "Enlace interno",
      "trash.title": "Papelera",
      "trash.secretTitle": "Papelera secreta",
      "trash.close": "Cerrar Papelera",
      "trash.autoDeleteInfo": "Las notas se eliminan permanentemente de forma automática después de 30 días.",
      "trash.empty": "La Papelera está vacía.",
      "trash.untitled": "Sin título",
      "trash.noPreview": "Sin vista previa",
      "trash.moved": "En la Papelera desde",
      "trash.daysLeft": "Eliminación permanente en {count} días",
      "trash.restore": "Restaurar",
      "trash.deleteForever": "Eliminar permanentemente",
      "trash.deleteForeverTitle": "¿Eliminar permanentemente?",
      "trash.deleteConfirm": "Esta nota se eliminará permanentemente y no se podrá restaurar.",
      "trash.moveTitle": "¿Mover a la Papelera?",
      "trash.moveMessage": "La nota se moverá a la Papelera y podrá restaurarse más tarde.",
      "trash.moveAction": "Mover a la Papelera",
      "trash.moveManyMessage": "¿Mover {count} notas seleccionadas a la Papelera?",
      "trash.movedMany": "Movidas a la Papelera: {count} notas",
      "trash.normalTab": "Normal",
      "trash.secretTab": "Secretas 🔒",
      "trash.typeTabsLabel": "Tipo de Papelera",
      "trash.selectAll": "Seleccionar todo",
      "trash.clearSelection": "Borrar selección",
      "trash.deleteSelected": "Eliminar permanentemente ({count})",
      "trash.deleteManyNormalConfirm": "¿Eliminar permanentemente {count} elementos de la Papelera normal? Esta acción no se puede deshacer.",
      "trash.deleteManySecretConfirm": "¿Eliminar permanentemente {count} elementos de la Papelera secreta? Esta acción no se puede deshacer.",
      "trash.bulkDeletePreparing": "Preparando eliminación…",
      "trash.bulkDeleting": "Eliminando…",
      "trash.bulkDeleteProgress": "Eliminando elementos… {done} / {total}",
      "trash.bulkDeleteSyncing": "Sincronizando cambios…",
      "trash.bulkDeleteDoneAction": "Hecho",
      "trash.bulkDeletePending": "Eliminado en este dispositivo. La sincronización terminará automáticamente.",
      "trash.bulkDeleteOffline": "Eliminado en este dispositivo. La sincronización se ejecutará cuando vuelvas a estar en línea.",
      "trash.bulkDeleteFailed": "No se pudo completar la eliminación de forma segura. Los elementos permanecieron en la Papelera.",
    },

    texty: {
      ...anglicky.texty,
      "Přihlášení vypršelo. Přihlas se znovu, aby mohla pokračovat synchronizace. Tvoje lokální data zůstala zachována.": "Tu sesión ha caducado. Inicia sesión de nuevo para que la sincronización pueda continuar. Tus datos locales se han conservado.",
      "Nepodařilo se připojit k synchronizaci. Zkus to znovu po připojení k internetu.": "No se pudo conectar con la sincronización. Inténtalo de nuevo cuando tengas conexión a internet.",
      "Ověření přihlášení se nepodařilo.": "No se pudo verificar el inicio de sesión.",
      "První přihlášení vyžaduje připojení k internetu.": "El primer inicio de sesión requiere conexión a internet.",
      "Ověřuji přihlášení…": "Verificando inicio de sesión…",
      "Vyplň e-mail i heslo.": "Introduce el correo y la contraseña.",
      "Přihlášení vyžaduje internet. Lokální aplikace funguje offline až po prvním úspěšném přihlášení.": "El inicio de sesión requiere internet. El modo sin conexión está disponible después del primer inicio de sesión correcto.",
      "Přihlašuji…": "Iniciando sesión…",
      "Přihlášení se nezdařilo. Zkontroluj e-mail, heslo a připojení.": "No se pudo iniciar sesión. Comprueba el correo, la contraseña y la conexión.",
      "Světlý": "Claro",
      "Tmavý": "Oscuro",
      "Původní ikony": "Iconos clásicos",
      "SVG ikony": "Iconos SVG",
      "Pracovní": "Trabajo",
      "Soukromé": "Privadas",
      "Bez názvu": "Sin título",
      "Žádná odpovídající poznámka": "No hay ninguna nota coincidente",
      "⚠ Smazaná poznámka": "⚠ Nota eliminada",
      "Tajný režim": "Modo secreto",
      "Tajný režim byl zamčen.": "El modo secreto se ha bloqueado.",
      "Tajný režim byl automaticky zamčen.": "El modo secreto se ha bloqueado automáticamente.",
      "Tajný režim je odemčený.": "El modo secreto está desbloqueado.",
      "Tajný režim se nepodařilo odemknout.": "No se pudo desbloquear el modo secreto.",
      "Tajný režim není odemčený.": "El modo secreto no está desbloqueado.",
      "Zadej hlavní heslo.": "Introduce la contraseña principal.",
      "Hlavní heslo není správné.": "La contraseña principal no es correcta.",
      "Hlavní heslo musí mít alespoň 8 znaků.": "La contraseña principal debe tener al menos 8 caracteres.",
      "Hlavní heslo se nepodařilo vytvořit.": "No se pudo crear la contraseña principal.",
      "Upozornění": "Aviso",
      "Nový štítek": "Nueva etiqueta",
      "Název štítku": "Nombre de la etiqueta",
      "+ Nový štítek": "+ Nueva etiqueta",
      "Nový tajný štítek": "Nueva etiqueta secreta",
    }
  });
})();
