/* LubaNote – Deutsch · PATCH 676A */
window.LubaNoteLanguagePacks = window.LubaNoteLanguagePacks || [];

(() => {
  const anglicky = window.LubaNoteLanguagePacks.find((balicek) => balicek.id === "en") || { preklady: {}, texty: {} };

  window.LubaNoteLanguagePacks.push({
    id: "de",
    nazev: "Deutsch",
    kratkyNazev: "DE",
    vlajka: "🇩🇪",
    locale: "de-DE",

    // Nejdřív bezpečný anglický fallback; přeložené produkční UI ho přepisuje níže.
    preklady: {
      ...anglicky.preklady,
      "language.label": "Sprache",
      "language.choose": "Sprache auswählen",
      "login.splashSubtitle": "Notizen • Planer • Dokumente",
      "login.loading": "LubaNote wird geladen",
      "login.title": "Anmelden",
      "login.registerTitle": "Registrieren",
      "login.modeSignIn": "Anmelden",
      "login.modeRegister": "Registrieren",
      "login.email": "E-Mail",
      "login.password": "Passwort",
      "login.passwordAgain": "Passwort wiederholen",
      "login.submit": "Anmelden",
      "login.registerSubmit": "Registrieren",
      "login.checkStatus": "Status prüfen",
      "login.modeAria": "Anmelden oder registrieren",
      "login.downloadMyData": "Meine Daten herunterladen",
      "login.deleteMyData": "Meine Daten löschen",
      "login.clearThisDevice": "Dieses Gerät löschen",
      "login.deleteMyDataTitle": "Meine Daten löschen?",
      "login.clearThisDeviceTitle": "Dieses Gerät löschen?",
      "login.clearWithoutBackup": "Ohne Backup löschen",
      "login.pendingTitle": "Konto wartet auf Freigabe",
      "login.pendingText": "Die Registrierung ist abgeschlossen. LubaNote wird freigeschaltet, sobald ein Administrator das Konto genehmigt.",
      "login.rejectedTitle": "Registrierung wurde nicht genehmigt",
      "login.rejectedText": "Dieses Konto wurde nicht genehmigt. Wenn das ein Fehler ist, wende dich an den LubaNote-Administrator.",
      "login.suspendedTitle": "Konto gesperrt",
      "login.suspendedText": "Der Zugriff auf LubaNote ist vorübergehend gesperrt.",
      "login.unavailableTitle": "Konto nicht verfügbar",
      "login.unavailableText": "Der Kontozugriff konnte nicht überprüft werden. Versuche es erneut.",
      "login.enterCredentials": "Gib E-Mail und Passwort ein.",
      "login.enterRegistration": "Gib E-Mail, Passwort und Passwort erneut ein.",
      "login.passwordMismatch": "Die Passwörter stimmen nicht überein.",
      "login.passwordTooShort": "Das Passwort muss mindestens 8 Zeichen lang sein.",
      "login.registrationOnline": "Für die Registrierung ist eine Internetverbindung erforderlich.",
      "login.registering": "Registrierung läuft…",
      "login.registrationCreated": "Die Registrierung wurde erstellt. Bestätige deine E-Mail und melde dich anschließend an.",
      "login.emailConfirmed": "E-Mail bestätigt. Du kannst dich jetzt anmelden.",
      "login.emailLinkInvalid": "Der Bestätigungslink wurde bereits verwendet oder ist abgelaufen. Wenn deine E-Mail bestätigt ist, melde dich an.",
      "login.stillPending": "Das Konto wartet noch auf Freigabe.",
      "login.alreadyRegistered": "Diese E-Mail ist bereits registriert. Verwende Anmelden.",
      "login.registrationFailed": "Registrierung fehlgeschlagen. Prüfe E-Mail, Passwort und Verbindung.",
      "login.registrationRateLimited": "Zu viele Bestätigungs-E-Mails wurden gesendet. Versuche die Registrierung später erneut.",
      "login.signingIn": "Anmeldung läuft…",
      "login.signInFailed": "Anmeldung fehlgeschlagen. Prüfe E-Mail, Passwort und Verbindung.",
      "login.emailNotConfirmed": "Deine E-Mail wurde noch nicht bestätigt. Öffne den Bestätigungslink in deiner E-Mail und melde dich danach erneut an.",
      "login.accountCheckFailed": "Der Kontostatus konnte nicht überprüft werden. Versuche es erneut.",
      "login.localOwnerMismatch": "Diese Installation enthält lokale Daten eines anderen LubaNote-Kontos. Aus Sicherheitsgründen können Konten in derselben Installation nicht gemischt werden.",
      "login.demoExpiredTitle": "Demo beendet",
      "login.demoExpiredText": "Deine Demo endete am {date}. Alle Daten bleiben sicher gespeichert. Für die weitere Nutzung der App ist voller LubaNote-Zugriff erforderlich.",
      "login.fullExpiredTitle": "Vollzugriff beendet",
      "login.fullExpiredText": "Deine Daten bleiben sicher gespeichert. LubaNote wird nach der Verlängerung des Vollzugriffs wieder freigeschaltet.",
      "account.demoUntil": "Demo bis {date}",
      "limits.notesTitle": "Notizlimit erreicht",
      "limits.notesText": "Dein Tarif erlaubt bis zu {limit} Notizen. Eine neue Notiz kann derzeit nicht sicher gespeichert werden. Deine vorhandenen Daten bleiben erhalten.",
      "nav.quick": "Schnellnavigation",
      "nav.tools": "Werkzeuge",
      "nav.home": "Start",
      "nav.allNotes": "Alle Notizen",
      "nav.favorites": "Favoriten",
      "nav.tags": "Tags",
      "nav.settings": "Einstellungen",
      "nav.backup": "Sichern und Wiederherstellen",
      "modules.aria": "LubaNote-Hauptbereiche",
      "modules.notes": "Notizen",
      "storageScope.cloud": "Synchronisiert",
      "storageScope.local": "Dieses Gerät",
      "storageScope.menu": "Speicher",
      "storageScope.choose": "Wo sollen Notizen gespeichert werden?",
      "storageScope.localTitle": "Nur dieses Gerät",
      "storageScope.localWarning": "Notizen in diesem Bereich werden nicht synchronisiert. Bei Verlust oder Löschen des Geräts können sie nicht aus der Cloud wiederhergestellt werden. Regelmäßige Backups werden empfohlen.",
      "storageScope.shareTitle": "Nur dieses Gerät",
      "storageScope.shareBlocked": "Teilen erfordert synchronisierten Speicher. Diese Notiz bleibt nur auf diesem Gerät.",
      "modules.planner": "Planer",
      "modules.documents": "Dokumente",
      "plannerTabs.calendar": "Kalender",
      "modules.reminders": "Erinnerungen",
      "sync.synced": "✓ Synchronisiert",
      "sync.syncing": "⟳ Synchronisiere…",
      "sync.pending": "⏳ Wartet auf Synchronisierung",
      "sync.localOnly": "📱 Nur dieses Gerät",
      "sync.authExpired": "⚠ Anmeldung abgelaufen",
      "sync.conflict": "⚠ Konflikt",
      "search.placeholder": "Suchen…",
      "search.aria": "Notizen durchsuchen",
      "search.clear": "Suche löschen",
      "search.view": "Kartenlayout ändern",
      "search.menu": "Hauptmenü",
      "sort.labelNewest": "Neue Karten: oben",
      "sort.labelOldest": "Neue Karten: unten",
      "sort.title": "Position neuer Karten",
      "sort.newest": "Neue Karten oben",
      "sort.oldest": "Neue Karten unten",
      "search.none": "Keine Notizen gefunden.",
      "menu.manageTags": "Tags verwalten",
      "menu.about": "Über die App",
      "menu.logout": "Abmelden",
      "filter.aria": "Notizfilter",
      "filter.all": "Alle",
      "filter.work": "Arbeit",
      "filter.private": "Privat",
      "filter.favorite": "Favorisierte Notizen",
      "filter.secret": "Geheime Notizen",
      "filter.finishSelection": "Auswahl beenden",
      "calendar.previousMonth": "Vorheriger Monat",
      "calendar.nextMonth": "Nächster Monat",
      "calendar.selectedDay": "Ausgewählter Tag",
      "calendar.addSelected": "Aufgabe für ausgewählten Tag hinzufügen",
      "calendar.back": "Zurück zum Kalender",
      "calendar.addDay": "Aufgabe für diesen Tag hinzufügen",
      "calendar.week": "Woche",
      "calendar.weekNumber": "Woche {value}",
      "weekday.mo": "Mo",
      "weekday.tu": "Di",
      "weekday.we": "Mi",
      "weekday.th": "Do",
      "weekday.fr": "Fr",
      "weekday.sa": "Sa",
      "weekday.su": "So",
      "recurring.title": "Wiederkehrend",
      "recurring.back": "Zurück zu Erinnerungen",
      "recurring.show": "Wiederkehrende Aufgaben anzeigen",
      "recurring.none": "Keine wiederkehrenden Aufgaben.",
      "recurring.repeat": "Wiederholt sich",
      "recurring.next": "Nächste: {value}",
      "recurring.noNext": "Diese Serie hat keinen weiteren Termin.",
      "reminders.overdue": "Überfällig",
      "reminders.active": "Aktiv",
      "reminders.today": "Heute",
      "reminders.none": "Keine Erinnerungen.",
      "reminders.noneOverdue": "Keine überfälligen Erinnerungen.",
      "reminders.tomorrow": "Morgen",
      "reminders.later": "Später",
      "reminders.label": "Erinnerung",
      "reminders.untitled": "Ohne Titel",
      "reminders.close": "Schließen",
      "reminders.tomorrow8": "Morgen 8:00",
      "reminders.date": "Datum",
      "reminders.time": "Uhrzeit",
      "reminders.selectDate": "Datum der Erinnerung wählen",
      "reminders.selectTime": "Uhrzeit der Erinnerung wählen",
      "reminders.done": "Erledigt",
      "reminders.delete": "Löschen",
      "reminders.openNote": "Notiz öffnen",
      "reminders.turnOff": "Erinnerung ausschalten",
      "editor.find": "Suchen",
      "editor.findInNote": "In dieser Notiz suchen",
      "editor.findPrevious": "Vorheriges Ergebnis",
      "editor.findNext": "Nächstes Ergebnis",
      "editor.findClose": "Suche schließen",
      "editor.openTools": "Bearbeitungswerkzeuge öffnen",
      "editor.formatting": "Notiz formatieren",
      "editor.moreTools": "Weitere Notizwerkzeuge",
      "editor.undo": "Rückgängig",
      "editor.redo": "Wiederholen",
      "editor.bold": "Fett",
      "editor.italic": "Kursiv",
      "editor.underline": "Unterstrichen",
      "editor.fontSize": "Schriftgröße",
      "editor.textStyle": "Textstil",
      "editor.textColor": "Textfarbe",
      "editor.white": "Weißer Text",
      "editor.black": "Schwarzer Text",
      "editor.align": "Textausrichtung",
      "editor.alignLeft": "Linksbündig",
      "editor.alignCenter": "Zentriert",
      "editor.alignRight": "Rechtsbündig",
      "editor.insertImage": "Bild einfügen",
      "editor.insertWebLink": "Weblink einfügen",
      "editor.webLink": "Weblink",
      "editor.openDocument": "Dokument öffnen",
      "editor.saveAs": "Speichern unter",
      "editor.bullets": "Aufzählung",
      "editor.date": "Datum",
      "editor.time": "Uhrzeit",
      "editor.selectDate": "Datum wählen",
      "editor.selectTime": "Uhrzeit wählen",
      "editor.pin": "Notiz anheften",
      "editor.reminder": "Erinnerung",
      "editor.backLink": "Zurück zur vorherigen verknüpften Notiz",
      "editor.titleAria": "Notiztitel",
      "editor.titlePlaceholder": "Notiztitel",
      "editor.secret": "Geheime Notiz",
      "editor.tags": "Tags",
      "editor.newTag": "Neuer Tag",
      "editor.cancelNewTag": "Neuen Tag abbrechen",
      "editor.saveClose": "Speichern und schließen",
      "editor.area": "Notizbereich",
      "editor.priority": "Priorität",
      "editor.color": "Farbe",
      "editor.planSelection": "Ausgewählten Text planen",
      "editor.addTodo": "TODO-Eintrag hinzufügen",
      "editor.deleteNote": "Notiz löschen",
      "backlinks.aria": "Links zu dieser Notiz",
      "backlinks.title": "Links zu dieser Notiz ({count})",
      "backlinks.none": "Keine Links zu dieser Notiz",
      "actions.save": "Speichern",
      "actions.discard": "Nicht speichern",
      "actions.ok": "OK",
      "status.done": "Erledigt",
      "secret.mainPassword": "Hauptpasswort",
      "secret.passwordAgain": "Passwort wiederholen",
      "secret.enterMain": "Gib das Hauptpasswort ein.",
      "actions.term": "Fälligkeit",
      "actions.pin": "Anheften",
      "actions.delete": "Löschen",
      "actions.more": "Weitere Aktionen",
      "actions.cancel": "Abbrechen",
      "actions.create": "Erstellen",
      "message.notice": "Hinweis",
      "editor.notePlaceholder": "Notiz schreiben…",
      "tags.name": "Tag-Name",
      "tags.add": "Hinzufügen",
      "deleteNote.message": "Möchtest du diese Notiz wirklich löschen?",
      "deleteNote.title": "Notiz löschen?",
      "timePicker.title": "Uhrzeit wählen",
      "timePicker.close": "Zeitauswahl schließen",
      "timePicker.clock": "Zifferblatt der Zeitauswahl",
      "repeat.title": "Wiederholen",
      "repeat.aria": "Aufgabenwiederholung",
      "repeat.no": "Nein",
      "repeat.daily": "Täglich",
      "repeat.weekly": "Wöchentlich",
      "repeat.twoWeeks": "2 Wochen",
      "repeat.monthly": "Monatlich",
      "repeat.none": "Nicht wiederholen",
      "planner.plan": "Planen",
      "planner.close": "Planung schließen",
      "planner.selectDate": "Datum der geplanten Aufgabe wählen",
      "planner.selectTime": "Uhrzeit der geplanten Aufgabe wählen",
      "sharing.settingsTitle": "Teilen",
      "sharing.usernameLabel": "Benutzername",
      "sharing.usernameUnset": "Einrichten",
      "sharing.usernameModalTitle": "Benutzername zum Teilen",
      "sharing.usernameDescription": "Andere finden dich nur über deinen exakten @Benutzernamen. Deine E-Mail wird beim Teilen nie angezeigt.",
      "sharing.usernamePlaceholder": "z. B. Lubomir",
      "sharing.usernameSave": "Speichern",
      "sharing.usernameCancel": "Abbrechen",
      "sharing.usernameInvalid": "Verwende 3–30 Zeichen: Buchstaben, Zahlen, Punkt, Bindestrich oder Unterstrich.",
      "sharing.usernameTaken": "Dieser @Benutzername wird bereits von jemand anderem verwendet.",
      "sharing.usernameOffline": "Zum Festlegen eines @Benutzernamens ist eine Internetverbindung erforderlich.",
      "sharing.usernameSaving": "Wird gespeichert…",
      "sharing.usernameSaveFailed": "Der Benutzername konnte nicht gespeichert werden.",
      "sharing.usernameRequiredTitle": "Erstelle deinen @Benutzernamen",
      "sharing.usernameRequiredDescription": "Bevor du LubaNote verwendest, erstelle einen öffentlichen @Benutzernamen für Teilen und Chat. Andere finden dich nur über den exakten @Benutzernamen; deine E-Mail wird nicht angezeigt.",
      "sharing.usernameRequiredSave": "Erstellen und fortfahren",
      "sharing.shareButton": "Teilen",
      "sharing.invitationsAria": "Einladungen zum Teilen",
      "sharing.shareModalTitle": "Notiz teilen",
      "sharing.shareModalDescription": "Lade einen Benutzer über seinen exakten @Benutzernamen ein.",
      "sharing.shareInputPlaceholder": "z. B. LubaNoteDemo",
      "sharing.shareSend": "Einladung senden",
      "sharing.shareSending": "Wird gesendet…",
      "sharing.shareSendSuccess": "Einladung gesendet.",
      "sharing.shareSendFailed": "Die Einladung konnte nicht gesendet werden.",
      "sharing.shareInvalidUsername": "Gib einen gültigen @Benutzernamen ein.",
      "sharing.shareOffline": "Teilen erfordert eine Internetverbindung.",
      "sharing.shareUsernameMissing": "Lege zuerst deinen eigenen @Benutzernamen in den Einstellungen fest.",
      "sharing.shareUserNotFound": "Es wurde kein Benutzer mit genau diesem @Benutzernamen gefunden.",
      "sharing.shareSelf": "Du kannst eine Notiz nicht mit dir selbst teilen.",
      "sharing.shareAlreadyCollaborator": "Dieser Benutzer arbeitet bereits an der Notiz mit.",
      "sharing.shareAlreadyPending": "Für diesen Benutzer steht bereits eine Einladung aus.",
      "sharing.shareSecretBlocked": "Geheime Notizen können noch nicht geteilt werden.",
      "sharing.shareNewNoteBlocked": "Speichere die Notiz zuerst, danach kannst du sie teilen.",
      "sharing.collaboratorsTitle": "Mitwirkende",
      "sharing.collaboratorsEmpty": "Noch keine Mitwirkenden.",
      "sharing.pendingTitle": "Ausstehende Einladungen",
      "sharing.pendingEmpty": "Keine ausstehenden Einladungen.",
      "sharing.cancelInvitation": "Abbrechen",
      "sharing.cancelFailed": "Die Einladung konnte nicht abgebrochen werden.",
      "sharing.cancel": "Abbrechen",
      "sharing.removeCollaborator": "Entfernen",
      "sharing.removeCollaboratorConfirm": "{username} vom Teilen entfernen?",
      "sharing.removeCollaboratorSuccess": "Mitwirkender entfernt.",
      "sharing.removeCollaboratorFailed": "Der Mitwirkende konnte nicht entfernt werden.",
      "sharing.removeCollaboratorMissing": "Dieser Benutzer teilt die Notiz nicht mehr.",
      "sharing.manageNotOwner": "Nur der Eigentümer der Notiz kann diese Aktion ausführen.",
      "sharing.manageModalUnavailable": "Der Bestätigungsdialog konnte nicht geöffnet werden.",
      "sharing.leaveSharedNote": "Teilen verlassen",
      "sharing.leaveConfirm": "Das Teilen dieser Notiz verlassen?",
      "sharing.leaveSuccess": "Teilen wurde verlassen.",
      "sharing.leaveFailed": "Teilen konnte nicht verlassen werden.",
      "sharing.ownerCannotLeave": "Der Eigentümer kann das Teilen nicht verlassen. Übertrage zuerst die Eigentümerschaft.",
      "sharing.ownerRole": "Eigentümer",
      "sharing.editorRole": "Bearbeiter",
      "sharing.invitationsTitle": "Einladungen zum Teilen",
      "sharing.invitationsEmpty": "Du hast keine ausstehenden Einladungen.",
      "sharing.invitedBy": "Eingeladen von {username}",
      "sharing.accept": "Annehmen",
      "sharing.decline": "Ablehnen",
      "sharing.responding": "Wird bearbeitet…",
      "sharing.invitationAccepted": "Einladung angenommen.",
      "sharing.invitationDeclined": "Einladung abgelehnt.",
      "sharing.invitationResponseFailed": "Die Einladung konnte nicht verarbeitet werden.",
      "sharing.refresh": "Aktualisieren",
      "sharing.close": "Schließen",
      "sharing.loading": "Wird geladen…",
      "sharing.loadFailed": "Freigabedaten konnten nicht geladen werden.",
      "sharing.sharedUntitled": "Ohne Titel",
      "sharing.sharedCardMeta": "Geteilt · {owner}",
      "sharing.readOnlyTitle": "Geteilte Notiz",
      "sharing.readOnlyMeta": "{owner} · geteilte Notiz",
      "sharing.readOnlyTodos": "Aufgaben",
      "sharing.editShared": "Bearbeiten",
      "sharing.sharedEditorOffline": "Eine geteilte Notiz kann nur online bearbeitet werden.",
      "sharing.sharedEditorBusy": "{username} bearbeitet diese Notiz gerade. Du kannst sie vorerst nur lesen.",
      "sharing.sharedEditorOpening": "Geteilter Editor wird geöffnet…",
      "sharing.sharedEditorSaveFailed": "Die geteilte Notiz konnte nicht sicher gespeichert werden. Der Editor bleibt geöffnet.",
      "sharing.sharedEditorConflict": "Auf dem Server existiert eine neuere Version der Notiz. Der Editor bleibt geöffnet; schließe ihn ohne Speichern und öffne die Notiz erneut.",
      "sharing.sharedEditorLockLost": "Die Editorsperre ist nicht mehr gültig. Der geteilte Editor wurde sicher geschlossen.",
      "sharing.sharedEditorSaved": "Geteilte Notiz gespeichert.",
      "chat.buttonAria": "Nachrichten",
      "chat.contactsTitle": "Nachrichten",
      "chat.contactsEmpty": "Du hast noch keine Chat-Kontakte. Ein Kontakt wird erstellt, nachdem eine Einladung zum Teilen einer Notiz angenommen wurde.",
      "chat.writeMessage": "Nachricht schreiben",
      "chat.trustedContact": "Kontakt aus Freigabe",
      "chat.ready": "Ihr könnt euch Nachrichten senden",
      "chat.lastMessageAt": "Letzte Nachricht {time}",
      "chat.messagePlaceholder": "Nachricht schreiben…",
      "chat.send": "Senden",
      "chat.sending": "Wird gesendet…",
      "chat.sent": "Gesendet",
      "chat.read": "Gelesen",
      "chat.messagesEmpty": "Noch keine Nachrichten.",
      "chat.deletedPlaceholder": "Nachricht wurde gelöscht",
      "chat.deleteMessage": "Nachricht löschen",
      "chat.deleteTitle": "Nachricht löschen?",
      "chat.deleteText": "Die Nachricht wird für beide Teilnehmer gelöscht und nur ein Hinweis auf die gelöschte Nachricht bleibt bestehen.",
      "chat.deleteForBoth": "Für beide löschen",
      "chat.deleting": "Wird gelöscht…",
      "chat.deleteFailed": "Die Nachricht konnte nicht gelöscht werden.",
      "chat.sendFailed": "Die Nachricht konnte nicht gesendet werden.",
      "chat.loadFailed": "Der Chat konnte nicht geladen werden.",
      "chat.loadMessagesFailed": "Nachrichten konnten nicht geladen werden.",
      "chat.loading": "Wird geladen…",
      "chat.offline": "Chat erfordert eine Internetverbindung.",
      "chat.blocked": "Chat ist blockiert",
      "chat.contactNotFound": "Der Chat-Kontakt ist noch nicht verfügbar.",
      "chat.tooLong": "Die Nachricht ist zu lang.",
      "chat.close": "Schließen",
      "chat.back": "Zurück",
      "chat.cancel": "Abbrechen",
      "chat.threadAria": "Chat",
      "settings.title": "Einstellungen",
      "settings.close": "Einstellungen schließen",
      "settings.appearance": "Darstellung",
      "settings.fontSize": "Schriftgröße",
      "settings.decreaseFont": "Schrift verkleinern",
      "settings.increaseFont": "Schrift vergrößern",
      "settings.theme": "Farbschema",
      "settings.iconStyle": "Symbolstil",
      "settings.keyboard": "Editor-Tastatur",
      "settings.keyboardTitle": "Editor-Tastatur",
      "settings.keyboardLuba": "LubaKeyboard (Standard)",
      "settings.keyboardSystem": "System",
      "settings.keyboardSystemLong": "Systemtastatur (Gboard / iOS)",
      "settings.reminders": "Erinnerungen",
      "settings.quickDelay": "Schnell schlummern",
      "settings.configure": "Konfigurieren",
      "settings.overdueRetention": "Überfällige löschen nach",
      "settings.overdueNever": "Nie",
      "settings.overdueDays": "{count} Tage",
      "settings.overdueConfirm": "bestätigen",
      "settings.data": "Daten",
      "settings.noteOpenPosition": "Beim Öffnen einer Notiz",
      "settings.noteOpenStart": "Anfang",
      "settings.noteOpenEnd": "Ende",
      "settings.export": "Backup exportieren",
      "settings.import": "Backup importieren",
      "settings.about": "Über die App",
      "settings.version": "Version",
      "settings.appInfo": "App-Informationen",
      "settings.open": "Öffnen",
      "theme.light": "Hell",
      "theme.dark": "Dunkel",
      "icons.classic": "Klassische Symbole",
      "icons.svg": "SVG-Symbole",
      "about.close": "App-Informationen schließen",
      "about.description": "Notizen, Aufgaben, Planung und Erinnerungen an einem Ort.",
      "addNote": "Notiz hinzufügen",
      "tags.new": "Neuer Tag",
      "tags.newSecret": "Neuer geheimer Tag",
      "tags.manage": "Tags verwalten",
      "tags.closeManage": "Tag-Verwaltung schließen",
      "tags.deleteTitle": "Tag löschen?",
      "secret.saveSecret": "Als geheim speichern",
      "secret.saveNormal": "Normal speichern",
      "secret.mode": "Geheimer Modus",
      "secret.close": "Geheimen Modus schließen",
      "secret.fingerprint": "Mit Fingerabdruck entsperren",
      "secret.nextFingerprint": "🫆 Nächstes Mal Fingerabdruck verwenden",
      "secret.thisDevice": "Nur auf diesem Gerät",
      "secret.unlock": "Entsperren",
      "secret.tags": "Geheime Tags",
      "secret.createTag": "Geheimen Tag erstellen",
      "secret.disableFingerprint": "Fingerabdruck-Entsperrung deaktivieren",
      "secret.lock": "Geheimen Modus sperren",
      "selection.cut": "Ausschneiden",
      "selection.copy": "Kopieren",
      "selection.paste": "Einfügen",
      "selection.all": "Alles",
      "noteLinks.noMatch": "Keine passende Notiz",
      "noteLinks.create": "+ Notiz „{value}“ erstellen",
      "noteLinks.deleted": "⚠ Gelöschte Notiz",
      "noteLinks.unavailable": "Die Zielnotiz ist nicht mehr verfügbar.",
      "noteLinks.previous": "Vorherige Notiz",
      "noteLinks.createFailed": "Die verknüpfte Notiz konnte nicht sicher erstellt werden.",
      "noteLinks.ariaTarget": "Interner Link zur Notiz {value}",
      "noteLinks.ariaMissing": "Interner Link zu nicht verfügbarer Notiz",
      "noteLinks.dialogTitle": "Interner Link",
      "trash.title": "Papierkorb",
      "trash.secretTitle": "Geheimer Papierkorb",
      "trash.close": "Papierkorb schließen",
      "trash.autoDeleteInfo": "Notizen werden nach 30 Tagen automatisch dauerhaft gelöscht.",
      "trash.empty": "Der Papierkorb ist leer.",
      "trash.untitled": "Ohne Titel",
      "trash.noPreview": "Keine Vorschau",
      "trash.moved": "Im Papierkorb seit",
      "trash.daysLeft": "Dauerhaftes Löschen in {count} Tagen",
      "trash.restore": "Wiederherstellen",
      "trash.deleteForever": "Dauerhaft löschen",
      "trash.deleteForeverTitle": "Dauerhaft löschen?",
      "trash.deleteConfirm": "Diese Notiz wird dauerhaft gelöscht und kann nicht wiederhergestellt werden.",
      "trash.moveTitle": "In den Papierkorb verschieben?",
      "trash.moveMessage": "Die Notiz wird in den Papierkorb verschoben und kann später wiederhergestellt werden.",
      "trash.moveAction": "In den Papierkorb",
      "trash.moveManyMessage": "{count} ausgewählte Notizen in den Papierkorb verschieben?",
      "trash.movedMany": "In den Papierkorb verschoben: {count} Notizen",
      "trash.normalTab": "Normal",
      "trash.secretTab": "Geheim 🔒",
      "trash.typeTabsLabel": "Papierkorbtyp",
      "trash.selectAll": "Alle auswählen",
      "trash.clearSelection": "Auswahl aufheben",
      "trash.deleteSelected": "Dauerhaft löschen ({count})",
      "trash.deleteManyNormalConfirm": "{count} Elemente dauerhaft aus dem normalen Papierkorb löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
      "trash.deleteManySecretConfirm": "{count} Elemente dauerhaft aus dem geheimen Papierkorb löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
      "trash.bulkDeletePreparing": "Löschen wird vorbereitet…",
      "trash.bulkDeleting": "Wird gelöscht…",
      "trash.bulkDeleteProgress": "Elemente werden gelöscht… {done} / {total}",
      "trash.bulkDeleteSyncing": "Änderungen werden synchronisiert…",
      "trash.bulkDeleteDoneAction": "Fertig",
      "trash.bulkDeletePending": "Auf diesem Gerät gelöscht. Die Synchronisierung wird automatisch abgeschlossen.",
      "trash.bulkDeleteOffline": "Auf diesem Gerät gelöscht. Die Synchronisierung erfolgt, sobald du wieder online bist.",
      "trash.bulkDeleteFailed": "Das Löschen konnte nicht sicher abgeschlossen werden. Die Elemente blieben im Papierkorb.",
    },

    texty: {
      ...anglicky.texty,
      "Přihlášení vypršelo. Přihlas se znovu, aby mohla pokračovat synchronizace. Tvoje lokální data zůstala zachována.": "Deine Anmeldung ist abgelaufen. Melde dich erneut an, damit die Synchronisierung fortgesetzt werden kann. Deine lokalen Daten bleiben erhalten.",
      "Nepodařilo se připojit k synchronizaci. Zkus to znovu po připojení k internetu.": "Die Synchronisierung konnte nicht verbunden werden. Versuche es erneut, sobald du online bist.",
      "Ověření přihlášení se nepodařilo.": "Die Anmeldung konnte nicht überprüft werden.",
      "První přihlášení vyžaduje připojení k internetu.": "Die erste Anmeldung erfordert eine Internetverbindung.",
      "Ověřuji přihlášení…": "Anmeldung wird überprüft…",
      "Vyplň e-mail i heslo.": "Gib E-Mail und Passwort ein.",
      "Přihlášení vyžaduje internet. Lokální aplikace funguje offline až po prvním úspěšném přihlášení.": "Die Anmeldung erfordert Internet. Der Offline-Modus ist nach der ersten erfolgreichen Anmeldung verfügbar.",
      "Přihlašuji…": "Anmeldung läuft…",
      "Přihlášení se nezdařilo. Zkontroluj e-mail, heslo a připojení.": "Anmeldung fehlgeschlagen. Prüfe E-Mail, Passwort und Verbindung.",
      "Světlý": "Hell",
      "Tmavý": "Dunkel",
      "Původní ikony": "Klassische Symbole",
      "SVG ikony": "SVG-Symbole",
      "Pracovní": "Arbeit",
      "Soukromé": "Privat",
      "Bez názvu": "Ohne Titel",
      "Žádná odpovídající poznámka": "Keine passende Notiz",
      "⚠ Smazaná poznámka": "⚠ Gelöschte Notiz",
      "Tajný režim": "Geheimer Modus",
      "Tajný režim byl zamčen.": "Der geheime Modus wurde gesperrt.",
      "Tajný režim byl automaticky zamčen.": "Der geheime Modus wurde automatisch gesperrt.",
      "Tajný režim je odemčený.": "Der geheime Modus ist entsperrt.",
      "Tajný režim se nepodařilo odemknout.": "Der geheime Modus konnte nicht entsperrt werden.",
      "Tajný režim není odemčený.": "Der geheime Modus ist nicht entsperrt.",
      "Zadej hlavní heslo.": "Gib das Hauptpasswort ein.",
      "Hlavní heslo není správné.": "Das Hauptpasswort ist falsch.",
      "Hlavní heslo musí mít alespoň 8 znaků.": "Das Hauptpasswort muss mindestens 8 Zeichen lang sein.",
      "Hlavní heslo se nepodařilo vytvořit.": "Das Hauptpasswort konnte nicht erstellt werden.",
      "Upozornění": "Hinweis",
      "Nový štítek": "Neuer Tag",
      "Název štítku": "Tag-Name",
      "+ Nový štítek": "+ Neuer Tag",
      "Nový tajný štítek": "Neuer geheimer Tag",
    }
  });
})();
