/* LubaNote – Deutsch · PATCH 676A */
window.LubaNoteLanguagePacks = window.LubaNoteLanguagePacks || [];

(() => {
  const anglicky = window.LubaNoteLanguagePacks.find((balicek) => balicek.id === "en") || { preklady: {}, texty: {} };

  window.LubaNoteLanguagePacks.push({
    id: "de",
    nazev: "Deutsch",
    kratkyNazev: "DE",
    vlajka: "🇩🇪",
    locale: "de-DE",

    // Nejdřív bezpečný anglický fallback; přeložené produkční UI ho přepisuje níže.
    preklady: {
      ...anglicky.preklady,
      "language.label": "Sprache",
      "language.choose": "Sprache auswählen",
      "login.splashSubtitle": "Notizen • Planer • Dokumente",
      "login.loading": "LubaNote wird geladen",
      "login.title": "Anmelden",
      "login.registerTitle": "Registrieren",
      "login.modeSignIn": "Anmelden",
      "login.modeRegister": "Registrieren",
      "login.email": "E-Mail",
      "login.password": "Passwort",
      "login.passwordAgain": "Passwort wiederholen",
      "login.submit": "Anmelden",
      "login.registerSubmit": "Registrieren",
      "login.checkStatus": "Status prüfen",
      "login.modeAria": "Anmelden oder registrieren",
      "login.downloadMyData": "Meine Daten herunterladen",
      "login.deleteMyData": "Meine Daten löschen",
      "login.clearThisDevice": "Dieses Gerät löschen",
      "login.deleteMyDataTitle": "Meine Daten löschen?",
      "login.clearThisDeviceTitle": "Dieses Gerät löschen?",
      "login.clearWithoutBackup": "Ohne Backup löschen",
      "login.pendingTitle": "Konto wartet auf Freigabe",
      "login.pendingText": "Die Registrierung ist abgeschlossen. LubaNote wird freigeschaltet, sobald ein Administrator das Konto genehmigt.",
      "login.rejectedTitle": "Registrierung wurde nicht genehmigt",
      "login.rejectedText": "Dieses Konto wurde nicht genehmigt. Wenn das ein Fehler ist, wende dich an den LubaNote-Administrator.",
      "login.suspendedTitle": "Konto gesperrt",
      "login.suspendedText": "Der Zugriff auf LubaNote ist vorübergehend gesperrt.",
      "login.unavailableTitle": "Konto nicht verfügbar",
      "login.unavailableText": "Der Kontozugriff konnte nicht überprüft werden. Versuche es erneut.",
      "login.enterCredentials": "Gib E-Mail und Passwort ein.",
      "login.enterRegistration": "Gib E-Mail, Passwort und Passwort erneut ein.",
      "login.passwordMismatch": "Die Passwörter stimmen nicht überein.",
      "login.passwordTooShort": "Das Passwort muss mindestens 8 Zeichen lang sein.",
      "login.registrationOnline": "Für die Registrierung ist eine Internetverbindung erforderlich.",
      "login.registering": "Registrierung läuft…",
      "login.registrationCreated": "Die Registrierung wurde erstellt. Bestätige deine E-Mail und melde dich anschließend an.",
      "login.emailConfirmed": "E-Mail bestätigt. Du kannst dich jetzt anmelden.",
      "login.emailLinkInvalid": "Der Bestätigungslink wurde bereits verwendet oder ist abgelaufen. Wenn deine E-Mail bestätigt ist, melde dich an.",
      "login.stillPending": "Das Konto wartet noch auf Freigabe.",
      "login.alreadyRegistered": "Diese E-Mail ist bereits registriert. Verwende Anmelden.",
      "login.registrationFailed": "Registrierung fehlgeschlagen. Prüfe E-Mail, Passwort und Verbindung.",
      "login.registrationRateLimited": "Zu viele Bestätigungs-E-Mails wurden gesendet. Versuche die Registrierung später erneut.",
      "login.signingIn": "Anmeldung läuft…",
      "login.signInFailed": "Anmeldung fehlgeschlagen. Prüfe E-Mail, Passwort und Verbindung.",
      "login.emailNotConfirmed": "Deine E-Mail wurde noch nicht bestätigt. Öffne den Bestätigungslink in deiner E-Mail und melde dich danach erneut an.",
      "login.accountCheckFailed": "Der Kontostatus konnte nicht überprüft werden. Versuche es erneut.",
      "login.localOwnerMismatch": "Diese Installation enthält lokale Daten eines anderen LubaNote-Kontos. Aus Sicherheitsgründen können Konten in derselben Installation nicht gemischt werden.",
      "login.demoExpiredTitle": "Demo beendet",
      "login.demoExpiredText": "Deine Demo endete am {date}. Alle Daten bleiben sicher gespeichert. Für die weitere Nutzung der App ist voller LubaNote-Zugriff erforderlich.",
      "login.fullExpiredTitle": "Vollzugriff beendet",
      "login.fullExpiredText": "Deine Daten bleiben sicher gespeichert. LubaNote wird nach der Verlängerung des Vollzugriffs wieder freigeschaltet.",
      "account.demoUntil": "Demo bis {date}",
      "limits.notesTitle": "Notizlimit erreicht",
      "limits.notesText": "Dein Tarif erlaubt bis zu {limit} Notizen. Eine neue Notiz kann derzeit nicht sicher gespeichert werden. Deine vorhandenen Daten bleiben erhalten.",
      "nav.quick": "Schnellnavigation",
      "nav.tools": "Werkzeuge",
      "nav.home": "Start",
      "nav.allNotes": "Alle Notizen",
      "nav.favorites": "Favoriten",
      "nav.tags": "Tags",
      "nav.settings": "Einstellungen",
      "nav.backup": "Sichern und Wiederherstellen",
      "modules.aria": "LubaNote-Hauptbereiche",
      "modules.notes": "Notizen",
      "storageScope.cloud": "Synchronisiert",
      "storageScope.local": "Dieses Gerät",
      "storageScope.menu": "Speicher",
      "storageScope.choose": "Wo sollen Notizen gespeichert werden?",
      "storageScope.localTitle": "Nur dieses Gerät",
      "storageScope.localWarning": "Notizen in diesem Bereich werden nicht synchronisiert. Bei Verlust oder Löschen des Geräts können sie nicht aus der Cloud wiederhergestellt werden. Regelmäßige Backups werden empfohlen.",
      "storageScope.shareTitle": "Nur dieses Gerät",
      "storageScope.shareBlocked": "Teilen erfordert synchronisierten Speicher. Diese Notiz bleibt nur auf diesem Gerät.",
      "modules.planner": "Planer",
      "modules.documents": "Dokumente",
      "documents.eyebrow": "Dokumente V1",
      "documents.title": "Dokumente",
      "documents.addFile": "＋ Datei hinzufügen",
      "documents.folders": "Ordner",
      "documents.newFolder": "Neuer Ordner",
      "documents.files": "Dateien",
      "documents.allFiles": "Alle Dateien",
      "documents.searchPlaceholder": "Suchen…",
      "documents.searchAria": "Dateien suchen",
      "documents.clearSearch": "Suche löschen",
      "documents.filterAria": "Dokumentfilter",
      "documents.filterAll": "Alle",
      "documents.trash": "Papierkorb",
      "documents.folderFallback": "Ordner",
      "documents.localAndroid": "Lokal auf diesem Android-Gerät",
      "documents.localBrowser": "Lokal in diesem Browser",
      "documents.fileCount.one": "{count} Datei",
      "documents.fileCount.other": "{count} Dateien",
      "plannerTabs.calendar": "Kalender",
      "modules.reminders": "Erinnerungen",
      "sync.synced": "✓ Synchronisiert",
      "sync.syncing": "⟳ Synchronisiere…",
      "sync.pending": "⏳ Wartet auf Synchronisierung",
      "sync.localOnly": "📱 Nur dieses Gerät",
      "sync.authExpired": "⚠ Anmeldung abgelaufen",
      "sync.conflict": "⚠ Konflikt",
      "search.placeholder": "Suchen…",
      "search.aria": "Notizen durchsuchen",
      "search.clear": "Suche löschen",
      "search.view": "Kartenlayout ändern",
      "search.menu": "Hauptmenü",
      "sort.labelNewest": "Neue Karten: oben",
      "sort.labelOldest": "Neue Karten: unten",
      "sort.title": "Position neuer Karten",
      "sort.newest": "Neue Karten oben",
      "sort.oldest": "Neue Karten unten",
      "search.none": "Keine Notizen gefunden.",
      "menu.manageTags": "Tags verwalten",
      "menu.about": "Über die App",
      "menu.logout": "Abmelden",
      "filter.aria": "Notizfilter",
      "filter.all": "Alle",
      "filter.work": "Arbeit",
      "filter.private": "Privat",
      "filter.favorite": "Favorisierte Notizen",
      "filter.secret": "Geheime Notizen",
      "filter.finishSelection": "Auswahl beenden",
      "calendar.previousMonth": "Vorheriger Monat",
      "calendar.nextMonth": "Nächster Monat",
      "calendar.selectedDay": "Ausgewählter Tag",
      "calendar.addSelected": "Aufgabe für ausgewählten Tag hinzufügen",
      "calendar.back": "Zurück zum Kalender",
      "calendar.addDay": "Aufgabe für diesen Tag hinzufügen",
      "calendar.week": "Woche",
      "calendar.weekNumber": "Woche {value}",
      "weekday.mo": "Mo",
      "weekday.tu": "Di",
      "weekday.we": "Mi",
      "weekday.th": "Do",
      "weekday.fr": "Fr",
      "weekday.sa": "Sa",
      "weekday.su": "So",
      "recurring.title": "Wiederkehrend",
      "recurring.back": "Zurück zu Erinnerungen",
      "recurring.show": "Wiederkehrende Aufgaben anzeigen",
      "recurring.none": "Keine wiederkehrenden Aufgaben.",
      "recurring.repeat": "Wiederholt sich",
      "recurring.next": "Nächste: {value}",
      "recurring.noNext": "Diese Serie hat keinen weiteren Termin.",
      "reminders.overdue": "Überfällig",
      "reminders.active": "Aktiv",
      "reminders.today": "Heute",
      "reminders.none": "Keine Erinnerungen.",
      "reminders.noneOverdue": "Keine überfälligen Erinnerungen.",
      "reminders.tomorrow": "Morgen",
      "reminders.later": "Später",
      "reminders.label": "Erinnerung",
      "reminders.untitled": "Ohne Titel",
      "reminders.close": "Schließen",
      "reminders.tomorrow8": "Morgen 8:00",
      "reminders.date": "Datum",
      "reminders.time": "Uhrzeit",
      "reminders.selectDate": "Datum der Erinnerung wählen",
      "reminders.selectTime": "Uhrzeit der Erinnerung wählen",
      "reminders.done": "Erledigt",
      "reminders.delete": "Löschen",
      "reminders.openNote": "Notiz öffnen",
      "reminders.turnOff": "Erinnerung ausschalten",
      "editor.find": "Suchen",
      "editor.findInNote": "In dieser Notiz suchen",
      "editor.findPrevious": "Vorheriges Ergebnis",
      "editor.findNext": "Nächstes Ergebnis",
      "editor.findClose": "Suche schließen",
      "editor.openTools": "Bearbeitungswerkzeuge öffnen",
      "editor.formatting": "Notiz formatieren",
      "editor.moreTools": "Weitere Notizwerkzeuge",
      "editor.undo": "Rückgängig",
      "editor.redo": "Wiederholen",
      "editor.bold": "Fett",
      "editor.italic": "Kursiv",
      "editor.underline": "Unterstrichen",
      "editor.fontSize": "Schriftgröße",
      "editor.textStyle": "Textstil",
      "editor.textColor": "Textfarbe",
      "editor.white": "Weißer Text",
      "editor.black": "Schwarzer Text",
      "editor.align": "Textausrichtung",
      "editor.alignLeft": "Linksbündig",
      "editor.alignCenter": "Zentriert",
      "editor.alignRight": "Rechtsbündig",
      "editor.insertImage": "Bild einfügen",
      "editor.insertWebLink": "Weblink einfügen",
      "editor.webLink": "Weblink",
      "editor.openDocument": "Dokument öffnen",
      "editor.saveAs": "Speichern unter",
      "editor.bullets": "Aufzählung",
      "editor.date": "Datum",
      "editor.time": "Uhrzeit",
      "editor.selectDate": "Datum wählen",
      "editor.selectTime": "Uhrzeit wählen",
      "editor.pin": "Notiz anheften",
      "editor.reminder": "Erinnerung",
      "editor.backLink": "Zurück zur vorherigen verknüpften Notiz",
      "editor.titleAria": "Notiztitel",
      "editor.titlePlaceholder": "Notiztitel",
      "editor.secret": "Geheime Notiz",
      "editor.tags": "Tags",
      "editor.newTag": "Neuer Tag",
      "editor.cancelNewTag": "Neuen Tag abbrechen",
      "editor.saveClose": "Speichern und schließen",
      "editor.area": "Notizbereich",
      "editor.priority": "Priorität",
      "editor.color": "Farbe",
      "editor.planSelection": "Ausgewählten Text planen",
      "editor.addTodo": "TODO-Eintrag hinzufügen",
      "editor.deleteNote": "Notiz löschen",
      "backlinks.aria": "Links zu dieser Notiz",
      "backlinks.title": "Links zu dieser Notiz ({count})",
      "backlinks.none": "Keine Links zu dieser Notiz",
      "actions.save": "Speichern",
      "actions.discard": "Nicht speichern",
      "actions.ok": "OK",
      "status.done": "Erledigt",
      "secret.mainPassword": "Hauptpasswort",
      "secret.passwordAgain": "Passwort wiederholen",
      "secret.enterMain": "Gib das Hauptpasswort ein.",
      "actions.term": "Fälligkeit",
      "actions.pin": "Anheften",
      "actions.delete": "Löschen",
      "actions.more": "Weitere Aktionen",
      "actions.cancel": "Abbrechen",
      "actions.create": "Erstellen",
      "message.notice": "Hinweis",
      "editor.notePlaceholder": "Notiz schreiben…",
      "tags.name": "Tag-Name",
      "tags.add": "Hinzufügen",
      "deleteNote.message": "Möchtest du diese Notiz wirklich löschen?",
      "deleteNote.title": "Notiz löschen?",
      "timePicker.title": "Uhrzeit wählen",
      "timePicker.close": "Zeitauswahl schließen",
      "timePicker.clock": "Zifferblatt der Zeitauswahl",
      "repeat.title": "Wiederholen",
      "repeat.aria": "Aufgabenwiederholung",
      "repeat.no": "Nein",
      "repeat.daily": "Täglich",
      "repeat.weekly": "Wöchentlich",
      "repeat.twoWeeks": "2 Wochen",
      "repeat.monthly": "Monatlich",
      "repeat.none": "Nicht wiederholen",
      "planner.plan": "Planen",
      "planner.close": "Planung schließen",
      "planner.selectDate": "Datum der geplanten Aufgabe wählen",
      "planner.selectTime": "Uhrzeit der geplanten Aufgabe wählen",
      "sharing.settingsTitle": "Teilen",
      "sharing.usernameLabel": "Benutzername",
      "sharing.usernameUnset": "Einrichten",
      "sharing.usernameModalTitle": "Benutzername zum Teilen",
      "sharing.usernameDescription": "Andere finden dich nur über deinen exakten @Benutzernamen. Deine E-Mail wird beim Teilen nie angezeigt.",
      "sharing.usernamePlaceholder": "z. B. Lubomir",
      "sharing.usernameSave": "Speichern",
      "sharing.usernameCancel": "Abbrechen",
      "sharing.usernameInvalid": "Verwende 3–30 Zeichen: Buchstaben, Zahlen, Punkt, Bindestrich oder Unterstrich.",
      "sharing.usernameTaken": "Dieser @Benutzername wird bereits von jemand anderem verwendet.",
      "sharing.usernameOffline": "Zum Festlegen eines @Benutzernamens ist eine Internetverbindung erforderlich.",
      "sharing.usernameSaving": "Wird gespeichert…",
      "sharing.usernameSaveFailed": "Der Benutzername konnte nicht gespeichert werden.",
      "sharing.usernameRequiredTitle": "Erstelle deinen @Benutzernamen",
      "sharing.usernameRequiredDescription": "Bevor du LubaNote verwendest, erstelle einen öffentlichen @Benutzernamen für Teilen und Chat. Andere finden dich nur über den exakten @Benutzernamen; deine E-Mail wird nicht angezeigt.",
      "sharing.usernameRequiredSave": "Erstellen und fortfahren",
      "sharing.shareButton": "Teilen",
      "sharing.invitationsAria": "Einladungen zum Teilen",
      "sharing.shareModalTitle": "Notiz teilen",
      "sharing.shareModalDescription": "Lade einen Benutzer über seinen exakten @Benutzernamen ein.",
      "sharing.shareInputPlaceholder": "z. B. LubaNoteDemo",
      "sharing.shareSend": "Einladung senden",
      "sharing.shareSending": "Wird gesendet…",
      "sharing.shareSendSuccess": "Einladung gesendet.",
      "sharing.shareSendFailed": "Die Einladung konnte nicht gesendet werden.",
      "sharing.shareInvalidUsername": "Gib einen gültigen @Benutzernamen ein.",
      "sharing.shareOffline": "Teilen erfordert eine Internetverbindung.",
      "sharing.shareUsernameMissing": "Lege zuerst deinen eigenen @Benutzernamen in den Einstellungen fest.",
      "sharing.shareUserNotFound": "Es wurde kein Benutzer mit genau diesem @Benutzernamen gefunden.",
      "sharing.shareSelf": "Du kannst eine Notiz nicht mit dir selbst teilen.",
      "sharing.shareAlreadyCollaborator": "Dieser Benutzer arbeitet bereits an der Notiz mit.",
      "sharing.shareAlreadyPending": "Für diesen Benutzer steht bereits eine Einladung aus.",
      "sharing.shareSecretBlocked": "Geheime Notizen können noch nicht geteilt werden.",
      "sharing.shareNewNoteBlocked": "Speichere die Notiz zuerst, danach kannst du sie teilen.",
      "sharing.collaboratorsTitle": "Mitwirkende",
      "sharing.collaboratorsEmpty": "Noch keine Mitwirkenden.",
      "sharing.pendingTitle": "Ausstehende Einladungen",
      "sharing.pendingEmpty": "Keine ausstehenden Einladungen.",
      "sharing.cancelInvitation": "Abbrechen",
      "sharing.cancelFailed": "Die Einladung konnte nicht abgebrochen werden.",
      "sharing.cancel": "Abbrechen",
      "sharing.removeCollaborator": "Entfernen",
      "sharing.removeCollaboratorConfirm": "{username} vom Teilen entfernen?",
      "sharing.removeCollaboratorSuccess": "Mitwirkender entfernt.",
      "sharing.removeCollaboratorFailed": "Der Mitwirkende konnte nicht entfernt werden.",
      "sharing.removeCollaboratorMissing": "Dieser Benutzer teilt die Notiz nicht mehr.",
      "sharing.manageNotOwner": "Nur der Eigentümer der Notiz kann diese Aktion ausführen.",
      "sharing.manageModalUnavailable": "Der Bestätigungsdialog konnte nicht geöffnet werden.",
      "sharing.leaveSharedNote": "Teilen verlassen",
      "sharing.leaveConfirm": "Das Teilen dieser Notiz verlassen?",
      "sharing.leaveSuccess": "Teilen wurde verlassen.",
      "sharing.leaveFailed": "Teilen konnte nicht verlassen werden.",
      "sharing.ownerCannotLeave": "Der Eigentümer kann das Teilen nicht verlassen. Übertrage zuerst die Eigentümerschaft.",
      "sharing.ownerRole": "Eigentümer",
      "sharing.editorRole": "Bearbeiter",
      "sharing.invitationsTitle": "Einladungen zum Teilen",
      "sharing.invitationsEmpty": "Du hast keine ausstehenden Einladungen.",
      "sharing.invitedBy": "Eingeladen von {username}",
      "sharing.accept": "Annehmen",
      "sharing.decline": "Ablehnen",
      "sharing.responding": "Wird bearbeitet…",
      "sharing.invitationAccepted": "Einladung angenommen.",
      "sharing.invitationDeclined": "Einladung abgelehnt.",
      "sharing.invitationResponseFailed": "Die Einladung konnte nicht verarbeitet werden.",
      "sharing.refresh": "Aktualisieren",
      "sharing.close": "Schließen",
      "sharing.loading": "Wird geladen…",
      "sharing.loadFailed": "Freigabedaten konnten nicht geladen werden.",
      "sharing.sharedUntitled": "Ohne Titel",
      "sharing.sharedCardMeta": "Geteilt · {owner}",
      "sharing.readOnlyTitle": "Geteilte Notiz",
      "sharing.readOnlyMeta": "{owner} · geteilte Notiz",
      "sharing.readOnlyTodos": "Aufgaben",
      "sharing.editShared": "Bearbeiten",
      "sharing.sharedEditorOffline": "Eine geteilte Notiz kann nur online bearbeitet werden.",
      "sharing.sharedEditorBusy": "{username} bearbeitet diese Notiz gerade. Du kannst sie vorerst nur lesen.",
      "sharing.sharedEditorOpening": "Geteilter Editor wird geöffnet…",
      "sharing.sharedEditorSaveFailed": "Die geteilte Notiz konnte nicht sicher gespeichert werden. Der Editor bleibt geöffnet.",
      "sharing.sharedEditorConflict": "Auf dem Server existiert eine neuere Version der Notiz. Der Editor bleibt geöffnet; schließe ihn ohne Speichern und öffne die Notiz erneut.",
      "sharing.sharedEditorLockLost": "Die Editorsperre ist nicht mehr gültig. Der geteilte Editor wurde sicher geschlossen.",
      "sharing.sharedEditorSaved": "Geteilte Notiz gespeichert.",
      "chat.buttonAria": "Nachrichten",
      "chat.contactsTitle": "Nachrichten",
      "chat.contactsEmpty": "Du hast noch keine Chat-Kontakte. Ein Kontakt wird erstellt, nachdem eine Einladung zum Teilen einer Notiz angenommen wurde.",
      "chat.writeMessage": "Nachricht schreiben",
      "chat.trustedContact": "Kontakt aus Freigabe",
      "chat.ready": "Ihr könnt euch Nachrichten senden",
      "chat.lastMessageAt": "Letzte Nachricht {time}",
      "chat.messagePlaceholder": "Nachricht schreiben…",
      "chat.send": "Senden",
      "chat.sending": "Wird gesendet…",
      "chat.sent": "Gesendet",
      "chat.read": "Gelesen",
      "chat.messagesEmpty": "Noch keine Nachrichten.",
      "chat.deletedPlaceholder": "Nachricht wurde gelöscht",
      "chat.deleteMessage": "Nachricht löschen",
      "chat.deleteTitle": "Nachricht löschen?",
      "chat.deleteText": "Die Nachricht wird für beide Teilnehmer gelöscht und nur ein Hinweis auf die gelöschte Nachricht bleibt bestehen.",
      "chat.deleteForBoth": "Für beide löschen",
      "chat.deleting": "Wird gelöscht…",
      "chat.deleteFailed": "Die Nachricht konnte nicht gelöscht werden.",
      "chat.sendFailed": "Die Nachricht konnte nicht gesendet werden.",
      "chat.loadFailed": "Der Chat konnte nicht geladen werden.",
      "chat.loadMessagesFailed": "Nachrichten konnten nicht geladen werden.",
      "chat.loading": "Wird geladen…",
      "chat.offline": "Chat erfordert eine Internetverbindung.",
      "chat.blocked": "Chat ist blockiert",
      "chat.contactNotFound": "Der Chat-Kontakt ist noch nicht verfügbar.",
      "chat.tooLong": "Die Nachricht ist zu lang.",
      "chat.close": "Schließen",
      "chat.back": "Zurück",
      "chat.cancel": "Abbrechen",
      "chat.threadAria": "Chat",
      "settings.personalDictionary": "Mein Wörterbuch",
      "settings.languageLearning": "Sprachen lernen",
      "settings.manageDictionary": "Verwalten",
      "settings.openLearning": "Öffnen",
      "settings.wordsCount.one": "{count} Wort",
      "settings.wordsCount.other": "{count} Wörter",
      "settings.plannerReminderDefault": "Beim Planen automatisch erinnern",
      "settings.enabled": "Ein",
      "settings.disabled": "Aus",
      "settings.planning": "Planung",
      "settings.automaticReminder": "Automatisch erinnern",
      "settings.title": "Einstellungen",
      "settings.close": "Einstellungen schließen",
      "settings.appearance": "Darstellung",
      "settings.fontSize": "Schriftgröße",
      "settings.decreaseFont": "Schrift verkleinern",
      "settings.increaseFont": "Schrift vergrößern",
      "settings.theme": "Farbschema",
      "settings.iconStyle": "Symbolstil",
      "settings.keyboard": "Editor-Tastatur",
      "settings.keyboardTitle": "Editor-Tastatur",
      "settings.keyboardLuba": "LubaKeyboard (Standard)",
      "settings.keyboardSystem": "System",
      "settings.keyboardSystemLong": "Systemtastatur (Gboard / iOS)",
      "settings.reminders": "Erinnerungen",
      "settings.quickDelay": "Schnell schlummern",
      "settings.configure": "Konfigurieren",
      "settings.overdueRetention": "Überfällige löschen nach",
      "settings.overdueNever": "Nie",
      "settings.overdueDays": "{count} Tage",
      "settings.overdueConfirm": "bestätigen",
      "settings.data": "Daten",
      "settings.noteOpenPosition": "Beim Öffnen einer Notiz",
      "settings.noteOpenStart": "Anfang",
      "settings.noteOpenEnd": "Ende",
      "settings.export": "Backup exportieren",
      "settings.import": "Backup importieren",
      "settings.about": "Über die App",
      "settings.version": "Version",
      "settings.appInfo": "App-Informationen",
      "settings.open": "Öffnen",
      "theme.light": "Hell",
      "theme.dark": "Dunkel",
      "icons.classic": "Klassische Symbole",
      "icons.svg": "SVG-Symbole",
      "about.close": "App-Informationen schließen",
      "about.description": "Notizen, Aufgaben, Planung und Erinnerungen an einem Ort.",
      "addNote": "Notiz hinzufügen",
      "tags.new": "Neuer Tag",
      "tags.newSecret": "Neuer geheimer Tag",
      "tags.manage": "Tags verwalten",
      "tags.closeManage": "Tag-Verwaltung schließen",
      "tags.deleteTitle": "Tag löschen?",
      "secret.saveSecret": "Als geheim speichern",
      "secret.saveNormal": "Normal speichern",
      "secret.mode": "Geheimer Modus",
      "secret.close": "Geheimen Modus schließen",
      "secret.fingerprint": "Mit Fingerabdruck entsperren",
      "secret.nextFingerprint": "🫆 Nächstes Mal Fingerabdruck verwenden",
      "secret.thisDevice": "Nur auf diesem Gerät",
      "secret.unlock": "Entsperren",
      "secret.tags": "Geheime Tags",
      "secret.createTag": "Geheimen Tag erstellen",
      "secret.disableFingerprint": "Fingerabdruck-Entsperrung deaktivieren",
      "secret.lock": "Geheimen Modus sperren",
      "selection.cut": "Ausschneiden",
      "selection.copy": "Kopieren",
      "selection.paste": "Einfügen",
      "selection.all": "Alles",
      "selection.dictionary": "Wörterbuch",
      "selection.translate": "Übersetzen",
      "noteLinks.noMatch": "Keine passende Notiz",
      "noteLinks.create": "+ Notiz „{value}“ erstellen",
      "noteLinks.deleted": "⚠ Gelöschte Notiz",
      "noteLinks.unavailable": "Die Zielnotiz ist nicht mehr verfügbar.",
      "noteLinks.previous": "Vorherige Notiz",
      "noteLinks.createFailed": "Die verknüpfte Notiz konnte nicht sicher erstellt werden.",
      "noteLinks.ariaTarget": "Interner Link zur Notiz {value}",
      "noteLinks.ariaMissing": "Interner Link zu nicht verfügbarer Notiz",
      "noteLinks.dialogTitle": "Interner Link",
      "trash.title": "Papierkorb",
      "trash.secretTitle": "Geheimer Papierkorb",
      "trash.close": "Papierkorb schließen",
      "trash.autoDeleteInfo": "Notizen werden nach 30 Tagen automatisch dauerhaft gelöscht.",
      "trash.empty": "Der Papierkorb ist leer.",
      "trash.untitled": "Ohne Titel",
      "trash.noPreview": "Keine Vorschau",
      "trash.moved": "Im Papierkorb seit",
      "trash.daysLeft": "Dauerhaftes Löschen in {count} Tagen",
      "trash.restore": "Wiederherstellen",
      "trash.deleteForever": "Dauerhaft löschen",
      "trash.deleteForeverTitle": "Dauerhaft löschen?",
      "trash.deleteConfirm": "Diese Notiz wird dauerhaft gelöscht und kann nicht wiederhergestellt werden.",
      "trash.moveTitle": "In den Papierkorb verschieben?",
      "trash.moveMessage": "Die Notiz wird in den Papierkorb verschoben und kann später wiederhergestellt werden.",
      "trash.moveAction": "In den Papierkorb",
      "trash.moveManyMessage": "{count} ausgewählte Notizen in den Papierkorb verschieben?",
      "trash.movedMany": "In den Papierkorb verschoben: {count} Notizen",
      "trash.normalTab": "Normal",
      "trash.secretTab": "Geheim 🔒",
      "trash.typeTabsLabel": "Papierkorbtyp",
      "trash.selectAll": "Alle auswählen",
      "trash.clearSelection": "Auswahl aufheben",
      "trash.deleteSelected": "Dauerhaft löschen ({count})",
      "trash.deleteManyNormalConfirm": "{count} Elemente dauerhaft aus dem normalen Papierkorb löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
      "trash.deleteManySecretConfirm": "{count} Elemente dauerhaft aus dem geheimen Papierkorb löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
      "trash.bulkDeletePreparing": "Löschen wird vorbereitet…",
      "trash.bulkDeleting": "Wird gelöscht…",
      "trash.bulkDeleteProgress": "Elemente werden gelöscht… {done} / {total}",
      "trash.bulkDeleteSyncing": "Änderungen werden synchronisiert…",
      "trash.bulkDeleteDoneAction": "Fertig",
      "trash.bulkDeletePending": "Auf diesem Gerät gelöscht. Die Synchronisierung wird automatisch abgeschlossen.",
      "trash.bulkDeleteOffline": "Auf diesem Gerät gelöscht. Die Synchronisierung erfolgt, sobald du wieder online bist.",
      "trash.bulkDeleteFailed": "Das Löschen konnte nicht sicher abgeschlossen werden. Die Elemente blieben im Papierkorb.",
      "actions.apply": "Anwenden",
      "actions.close": "Schließen",
      "actions.edit": "Bearbeiten",
      "actions.next": "Weiter",
      "actions.open": "Öffnen",
      "actions.previous": "Zurück",
      "actions.rename": "Umbenennen",
      "actions.update": "Aktualisieren",
      "calendar.chooseMonth": "Monat auswählen",
      "choice.enterValue": "Wert eingeben",
      "choice.maximum": "Maximum: {value}",
      "choice.minimum": "Minimum: {value}",
      "choice.selectOption": "Option auswählen",
      "choice.validNumber": "Gib eine gültige Zahl ein.",
      "choice.value": "Wert",
      "datePicker.today": "Heute",
      "dictionary.add": "Hinzufügen",
      "dictionary.addOwn": "Eigenes Wort hinzufügen…",
      "dictionary.empty": "Das Wörterbuch ist leer.",
      "dictionary.language": "Wörterbuchsprache",
      "dictionary.search": "Wörterbuch durchsuchen…",
      "documents.addDocument": "Dokument hinzufügen",
      "documents.cannotOpenType": "Dieser Dateityp kann noch nicht geöffnet werden.",
      "documents.chooseFileType": "Wähle einen Dateityp. Das Dokument bleibt nur auf diesem Gerät.",
      "documents.closeDocument": "Dokument schließen",
      "documents.contentUnsafe": "Der Dateiinhalt kann nicht sicher geladen werden.",
      "documents.copyFailedLongPress": "Kopieren fehlgeschlagen. Versuche, den Text durch langes Drücken auszuwählen.",
      "documents.copySqlAria": "Gesamtes SQL-Skript kopieren",
      "documents.createFolderFailed": "Der Ordner konnte nicht erstellt werden.",
      "documents.deleteEmptyFolder": "Der Ordner „{name}“ ist leer. Nur der Ordner wird gelöscht.",
      "documents.deleteFolder": "Ordner löschen",
      "documents.deleteFolderFailed": "Der Ordner konnte nicht sicher gelöscht werden.",
      "documents.deleteFolderTitle": "Ordner löschen?",
      "documents.deleteFolderWithFiles": "Der Ordner „{name}“ enthält {count}. Die Dokumente werden NICHT gelöscht, sondern nach „Alle Dateien“ verschoben. Danach wird nur der Ordner gelöscht.",
      "documents.deleteForeverFailed": "Das Dokument konnte nicht dauerhaft gelöscht werden.",
      "documents.deleteForeverMessage": "„{name}“ wird dauerhaft von diesem Gerät entfernt. Diese Aktion kann nicht rückgängig gemacht werden.",
      "documents.deleteForeverTitle": "Dokument dauerhaft löschen?",
      "documents.docDescription": "lokales Lesen des Textes im alten Format",
      "documents.docInvalid": "Die Datei ist kein gültiges Word-DOC.",
      "documents.docNoReadableText": "Das DOC enthält keinen lesbaren Text oder verwendet eine Variante, die der Viewer noch nicht unterstützt.",
      "documents.docNotLegacy": "Die Datei ist kein altes Word-DOC (OLE/CFB).",
      "documents.docOldUnsupported": "Dieser erste DOC-Viewer unterstützt Word 97–2003. Älteres Word 6/95 wird noch nicht unterstützt.",
      "documents.docOpenFailed": "Das DOC konnte nicht geöffnet werden. Word 97–2003 wird unterstützt; diese erste Version bewahrt vor allem lesbaren Text.",
      "documents.docReadOnly": "DOC · NUR LESEN",
      "documents.docTooLarge": "DOC ist zu groß. Die maximale Größe beträgt 24 MB.",
      "documents.docTooLarge24": "DOC ist zu groß. Die maximale Größe beträgt 24 MB.",
      "documents.docUnsupported": "Die Datei ist kein unterstütztes Word-DOC.",
      "documents.document": "Dokument",
      "documents.docxDescription": "wird in Dokumente schreibgeschützt geöffnet",
      "documents.docxOpenFailed": "Das DOCX konnte nicht geöffnet werden. Die Datei ist möglicherweise beschädigt oder enthält ein Element, das dieser Viewer noch nicht unterstützt.",
      "documents.docxReadOnly": "DOCX · NUR LESEN",
      "documents.docxTooLarge": "DOCX ist zu groß. Die maximale Größe beträgt 20 MB.",
      "documents.dragReorder": "Ziehen, um die Reihenfolge zu ändern",
      "documents.dragToFolder": "In den Zielordner ziehen",
      "documents.dropInto": "In „{name}“ ablegen",
      "documents.emptyDoc": "Noch keine DOC-Dateien",
      "documents.emptyDocument": "Noch keine Dokumente",
      "documents.emptyDocx": "Noch keine DOCX-Dateien",
      "documents.emptyEpub": "Noch keine EPUB-Bücher",
      "documents.emptyHint": "Füge die erste PDF-, DOCX-, DOC-, EPUB- oder SQL-Datei hinzu. SQL wird lokal schreibgeschützt geöffnet.",
      "documents.emptyPdf": "Noch keine PDF-Dateien",
      "documents.emptySql": "Noch keine SQL-Dateien",
      "documents.epubBook": "EPUB-E-Book",
      "documents.epubDescription": "wird im lokalen LubaReader geöffnet",
      "documents.epubEncryptedUnsupported": "Verschlüsseltes EPUB wird nicht unterstützt.",
      "documents.epubInvalid": "Die Datei ist kein gültiges EPUB.",
      "documents.epubMissingPackage": "Das EPUB enthält keinen Pfad zum OPF-Paket.",
      "documents.epubNoChapters": "Das EPUB enthält keine lesbare Kapitelreihenfolge.",
      "documents.epubOpenFailed": "Das EPUB konnte nicht geöffnet werden. Das Buch ist möglicherweise beschädigt oder DRM-geschützt.",
      "documents.epubReaderMissing": "Der EPUB-Reader ist nicht geladen.",
      "documents.epubTooLarge100": "EPUB ist zu groß. Die maximale Größe beträgt 100 MB.",
      "documents.epubWebViewUnsupported": "Diese WebView kann EPUB-Dateien nicht entpacken.",
      "documents.fileActions": "Dateiaktionen",
      "documents.fileActionsNamed": "Dateiaktionen für {name}",
      "documents.fileName": "Dateiname",
      "documents.fileTooLarge20": "Die Datei ist zu groß. Die maximale Größe beträgt 20 MB.",
      "documents.fileUnavailable": "Die Datei ist nicht mehr verfügbar.",
      "documents.folderActions": "Ordneraktionen",
      "documents.folderActionsNamed": "Ordneraktionen für {name}",
      "documents.folderExists": "Der Ordner „{name}“ existiert bereits.",
      "documents.folderLocalHint": "Der Ordner befindet sich derzeit nur auf diesem Gerät.",
      "documents.folderLocalMeta": "{count} · lokal auf dem Gerät",
      "documents.folderName": "Ordnername",
      "documents.folderOrderFailed": "Die Ordnerreihenfolge konnte nicht gespeichert werden.",
      "documents.inTrashTitle": "Dokument im Papierkorb",
      "documents.libraryLoadFailed": "Die lokale Dokumentbibliothek konnte nicht geladen werden.",
      "documents.loadFailed": "Das Dokument konnte nicht geladen werden.",
      "documents.longPressMoveTitle": "Lang drücken und ziehen zum Verschieben",
      "documents.longPressReorderTitle": "Lang drücken und ziehen, um neu anzuordnen",
      "documents.lubanoteNote": "LubaNote-Notiz",
      "documents.metadataFallback": "Die Metadaten des LubaNote-Dokuments konnten nicht geladen werden; ein normaler HTML-Import wird verwendet.",
      "documents.moveFailed": "Die Datei konnte nicht verschoben werden.",
      "documents.newDocument": "Neues Dokument",
      "documents.noDisplayableContent": "Das Dokument enthält keinen darstellbaren Inhalt.",
      "documents.noFolders": "Du hast noch keine Ordner.",
      "documents.noReadableText": "Das Dokument enthält keinen lesbaren Text.",
      "documents.nothingFound": "Nichts gefunden",
      "documents.nothingToCopy": "Nichts zu kopieren.",
      "documents.openDocument": "Dokument öffnen",
      "documents.openFailed": "Die Datei konnte nicht geöffnet werden.",
      "documents.openNamed": "{name} öffnen",
      "documents.openPdf": "PDF öffnen",
      "documents.openingDoc": "DOC wird geöffnet…",
      "documents.openingDocument": "Dokument wird geöffnet…",
      "documents.openingDocx": "DOCX wird geöffnet…",
      "documents.openingSql": "SQL wird geöffnet…",
      "documents.pdfDescription": "wird im vorhandenen PDF-Viewer geöffnet",
      "documents.pdfDisplayFailed": "Das PDF konnte nicht angezeigt werden. Die Datei ist möglicherweise beschädigt oder passwortgeschützt.",
      "documents.pdfOpenFailed": "Das PDF konnte nicht geöffnet werden.",
      "documents.pdfTooLarge": "PDF ist zu groß. Die maximale Größe beträgt 100 MB.",
      "documents.pdfTooLargeWeb": "PDF ist zu groß. Die maximale Größe in der Webversion beträgt 100 MB.",
      "documents.pdfViewerUnavailable": "Der PDF-Viewer ist nicht verfügbar.",
      "documents.renameDocument": "Dokument umbenennen",
      "documents.renameDocumentHint": "Nur der Name in der LubaNote-Bibliothek wird geändert. Der Dokumentinhalt bleibt unverändert.",
      "documents.renameFailed": "Das Dokument konnte nicht umbenannt werden.",
      "documents.renameFolder": "Ordner umbenennen",
      "documents.renameFolderFailed": "Der Ordner konnte nicht umbenannt werden.",
      "documents.renameFolderHint": "Nur der Ordnername wird geändert. Die Dokumente darin bleiben unverändert.",
      "documents.renameType": "{type} umbenennen",
      "documents.renameTypeHint": "Nur der Name in der LubaNote-Bibliothek wird geändert. Der Inhalt von {type} bleibt unverändert.",
      "documents.restoreFailed": "Das Dokument konnte nicht wiederhergestellt werden.",
      "documents.restoreFromTrash": "Aus Papierkorb wiederherstellen",
      "documents.saveAs": "Speichern unter",
      "documents.saveFailed": "Das Dokument konnte nicht gespeichert werden.",
      "documents.saveHtml": "HTML – Formatierung beibehalten",
      "documents.savePdf": "PDF – fertiges Dokument",
      "documents.saveTxt": "TXT – Nur-Text",
      "documents.searchEmpty": "Für „{query}“ wurde kein passendes Dokument gefunden.",
      "documents.secretExternalOpenBlocked": "Externe Dokumente sind im Secret-Modus nicht verfügbar. Secret bleibt getrennt.",
      "documents.secretExternalSaveBlocked": "Eine Secret-Notiz kann nicht in einem externen Dokument gespeichert werden. Der Secret-Modus bleibt getrennt.",
      "documents.secretExternalSaveBlockedShort": "Eine Secret-Notiz kann nicht in einem externen Dokument gespeichert werden.",
      "documents.sqlCopied": "Das gesamte SQL-Skript wurde kopiert.",
      "documents.sqlDescription": "wird lokal schreibgeschützt als Quellcode geöffnet",
      "documents.sqlEmpty": "Die SQL-Datei ist leer.",
      "documents.sqlOpenFailed": "Die SQL-Datei konnte nicht geöffnet werden.",
      "documents.sqlReadFailed": "Die SQL-Datei konnte nicht gelesen werden.",
      "documents.sqlReadOnly": "SQL · NUR LESEN",
      "documents.sqlScript": "SQL-Skript",
      "documents.sqlTooLarge": "SQL ist zu groß. Die maximale Größe beträgt 10 MB.",
      "documents.targetFolderUnavailable": "Der Zielordner ist nicht mehr verfügbar.",
      "documents.textDocument": "Textdokument",
      "documents.trashEmpty": "Papierkorb ist leer",
      "documents.trashEmptyHint": "In den Papierkorb verschobene Dokumente erscheinen hier und können wiederhergestellt oder dauerhaft gelöscht werden.",
      "documents.trashMoveFailed": "Das Dokument konnte nicht in den Papierkorb verschoben werden.",
      "documents.unsafeElement": "Das Dokument enthält ein Element, das Core V2 nicht sicher importieren kann. Die Daten wurden nicht geändert.",
      "documents.unsupportedType": "Dieser Dateityp wird noch nicht unterstützt. Wähle PDF, DOCX, DOC, EPUB oder SQL.",
      "documents.wordReadOnly": "WORD · NUR LESEN",
      "editor.tasks": "Aufgaben",
      "learning.addWord": "Wort hinzufügen",
      "learning.addWordLanguage": "Wort hinzufügen · {language}",
      "learning.addWordLanguageDot": "Wort hinzufügen · {language}",
      "learning.alreadyInDictionary": "Dieses Wort ist bereits in deinem Lernwörterbuch.",
      "learning.changeLanguage": "Sprache ändern",
      "learning.close": "Sprachlernen schließen",
      "learning.closeTranslation": "Übersetzung schließen",
      "learning.contextOptional": "Kontext (optional)",
      "learning.dictionary": "Wörterbuch",
      "learning.dontKnow": "Weiß ich nicht",
      "learning.duplicate": "Dieses Wort gibt es in dieser Sprache bereits.",
      "learning.editWord": "Wort bearbeiten",
      "learning.empty": "Noch keine Wörter vorhanden.",
      "learning.enterOrSelectTerm": "Gib zuerst ein Wort oder eine Phrase ein oder wähle sie aus.",
      "learning.errorDifferentLanguages": "Quell- und Zielsprache müssen unterschiedlich sein.",
      "learning.errorOnlineRequired": "Für die Übersetzung ist eine Internetverbindung erforderlich.",
      "learning.errorSelectTerm": "Wähle ein Wort oder eine Phrase aus.",
      "learning.errorShorterTerm": "Wähle für die Übersetzung ein kürzeres Wort oder eine kürzere Phrase.",
      "learning.errorTranslateAuto": "Die automatische Übersetzung konnte nicht abgerufen werden. Du kannst sie manuell eingeben.",
      "learning.errorTranslateUnavailable": "Die Online-Übersetzung ist derzeit nicht verfügbar. Du kannst sie manuell eingeben.",
      "learning.fillOrTranslate": "Gib eine Übersetzung ein oder tippe auf Übersetzen.",
      "learning.fillTerm": "Gib ein Wort oder eine Phrase ein.",
      "learning.fillTranslation": "Gib eine Übersetzung ein oder tippe auf Übersetzen.",
      "learning.fillTranslationFirst": "Gib zuerst die Übersetzung ein.",
      "learning.know": "Gewusst",
      "learning.languageLearningLanguage": "Sprachlernen · {language}",
      "learning.manualAdd": "Wort hinzufügen",
      "learning.noMistakesYet": "Noch keine Fehler",
      "learning.onlineTranslationPrivacy": "Online-Übersetzung · {direction} · nur der ausgewählte Ausdruck wird gesendet.",
      "learning.playPronunciation": "Aussprache abspielen",
      "learning.playPronunciationLanguage": "Aussprache abspielen · {language}",
      "learning.playPronunciationTerm": "Wortaussprache abspielen",
      "learning.practiceEmpty": "Nichts zum Üben.",
      "learning.practiceLanguage": "{language} üben",
      "learning.practiceLanguageAria": "Sprache {language} üben",
      "learning.practiceWrongOnly": "Nur Wörter üben, die ich nicht kenne",
      "learning.saveChanges": "Änderungen speichern",
      "learning.saveFailed": "Das Wort konnte nicht gespeichert werden.",
      "learning.saveToDictionary": "＋ Im Wörterbuch speichern",
      "learning.savedToLearning": "Im Sprachlernen gespeichert.",
      "learning.search": "Wort suchen…",
      "learning.showTranslation": "Übersetzung anzeigen",
      "learning.sourceManual": "Manuell hinzugefügt",
      "learning.sourceNote": "Notiz",
      "learning.sourceOptional": "Quelle (optional)",
      "learning.sourceSeed": "LubaNote-Testsatz",
      "learning.statsDue": "Zum Üben fällig",
      "learning.statsMastered": "Gelernt",
      "learning.statsReviews": "Wiederholungen",
      "learning.statsSaved": "Gespeichert",
      "learning.tabPractice": "Training",
      "learning.tabStats": "Statistik",
      "learning.tabWords": "Wörter",
      "learning.termOrPhrase": "Wort / Phrase",
      "learning.trainingAllOk": "Training abgeschlossen 🥳 Alle Wörter waren OK.",
      "learning.translate": "Übersetzen",
      "learning.translateFailed": "Die Übersetzung konnte nicht abgerufen werden.",
      "learning.translating": "Wird übersetzt…",
      "learning.translatingDirection": "Übersetzen · {direction}…",
      "learning.translation": "Übersetzung",
      "learning.translationDictionary": "Übersetzung und Wörterbuch",
      "learning.translationDirection": "Übersetzung · {direction}",
      "learning.translationEditable": "Du kannst die Übersetzung vor dem Speichern bearbeiten.",
      "learning.translationPlaceholder": "Übersetzung…",
      "learning.updateInDictionary": "Im Wörterbuch aktualisieren",
      "learning.wordUpdated": "Wort wurde aktualisiert.",
      "pdf.androidPickerHint": "Android öffnet nur die Auswahl der Zieldatei.",
      "pdf.chooseAndroidDestination": "Nach der Bestätigung wählst du den Zielort in Android.",
      "pdf.chooseFileName": "Wähle den Namen der PDF-Datei.",
      "pdf.chooseOtherLocation": "Anderen Speicherort wählen…",
      "pdf.close": "PDF schließen",
      "pdf.directCreateFailed": "Das direkte PDF konnte nicht erstellt werden.",
      "pdf.directDownloadInfoHtml": "Das PDF wird ohne weiteres Dialogfenster unter <strong>Downloads/LubaNote</strong> gespeichert.",
      "pdf.directSaveHint": "Wird sofort ohne weiteres Systemfenster gespeichert.",
      "pdf.directSaveNoPreview": "Das PDF wird direkt unter Downloads/LubaNote ohne System-Druckvorschau gespeichert.",
      "pdf.directTest": "Direktes PDF TEST",
      "pdf.directTestHint": "Dieselbe Android-Druck-Engine, aber ohne Systemvorschau.",
      "pdf.document": "PDF-Dokument",
      "pdf.doubleTapFullscreen": "Doppeltippen → Vollbild",
      "pdf.doubleTapFullscreenHint": "Doppeltippen schaltet die maximale PDF-Ansicht um.",
      "pdf.exitMaxView": "Maximalansicht verlassen",
      "pdf.fitWidth": "An Breite anpassen",
      "pdf.fitWidthAria": "PDF an Breite anpassen",
      "pdf.fullscreen": "Vollbild",
      "pdf.generatingTest": "PDF TEST wird erstellt…",
      "pdf.landscape": "Querformat",
      "pdf.loading": "PDF wird geladen…",
      "pdf.maxView": "Maximale PDF-Ansicht",
      "pdf.nextPage": "Nächste Seite",
      "pdf.pageDisplayFailed": "Die Seite konnte nicht angezeigt werden.",
      "pdf.portrait": "Hochformat",
      "pdf.preview": "Vorschau",
      "pdf.previewFailed": "Die PDF-Vorschau konnte nicht erstellt werden.",
      "pdf.previewNamed": "Vorschau • {name}",
      "pdf.previousPage": "Vorherige Seite",
      "pdf.rememberZoom": "Letzten Zoom merken",
      "pdf.rememberZoomHint": "Das nächste PDF wird mit demselben Zoom geöffnet.",
      "pdf.saveCopy": "PDF-Kopie speichern",
      "pdf.saveFailed": "Das PDF konnte nicht gespeichert werden.",
      "pdf.savePdf": "PDF speichern",
      "pdf.savePreview": "PDF-Vorschau speichern",
      "pdf.savedChosenLocation": "PDF wurde am ausgewählten Ort gespeichert.",
      "pdf.savedDirect": "PDF wurde direkt unter Downloads/LubaNote gespeichert.",
      "pdf.savedDownloads": "PDF wurde unter Downloads/LubaNote gespeichert.",
      "pdf.settings": "PDF-Einstellungen",
      "pdf.settingsHint": "Gilt für den PDF-Viewer in LubaNote.",
      "pdf.systemPreviewShouldNotOpen": "Die Systemvorschau sollte sich nicht öffnen.",
      "pdf.viewer": "PDF-Viewer",
      "pdf.whereSave": "Wo PDF speichern",
      "pdf.whereSaveShort": "Speicherort",
      "pdf.zoomIn": "PDF vergrößern",
      "pdf.zoomOut": "PDF verkleinern",
      "planner.changeFutureFirst": "Setze den Termin der Aufgabe zuerst in die Zukunft.",
      "planner.futureRequired": "Der Termin muss in der Zukunft liegen.",
      "planner.reminderOff": "Erinnerung: aus",
      "planner.reminderOn": "Erinnerung: an",
      "reader.addBookmarkHere": "Lesezeichen hier hinzufügen",
      "reader.addNote": "Notiz hinzufügen",
      "reader.airy": "Luftig",
      "reader.alignment": "Ausrichtung",
      "reader.background": "Hintergrund",
      "reader.book": "Buch",
      "reader.bookmarks": "Lesezeichen",
      "reader.bookmarksHighlights": "Lesezeichen und Markierungen",
      "reader.chapterEmpty": "Das Kapitel enthält keinen darstellbaren Text.",
      "reader.chapterNumber": "Kapitel {count}",
      "reader.closeBook": "Buch schließen",
      "reader.closeContents": "Inhalt schließen",
      "reader.closeSettings": "Einstellungen schließen",
      "reader.contents": "Inhalt",
      "reader.contentsAria": "Buchinhalt",
      "reader.dark": "Dunkel",
      "reader.decreaseFont": "Schrift verkleinern",
      "reader.deleteBookmark": "Lesezeichen löschen",
      "reader.deleteHighlight": "Markierung löschen",
      "reader.editNote": "Notiz bearbeiten",
      "reader.font": "Schriftart",
      "reader.fontSize": "Schriftgröße",
      "reader.highlight": "Markierung",
      "reader.highlightBlue": "Blaue Markierung",
      "reader.highlightColor": "Markierungsfarbe",
      "reader.highlightGreen": "Grüne Markierung",
      "reader.highlightNote": "Notiz zur Markierung",
      "reader.highlightViolet": "Violette Markierung",
      "reader.highlightYellow": "Gelbe Markierung",
      "reader.highlights": "Markierungen",
      "reader.increaseFont": "Schrift vergrößern",
      "reader.justify": "Blocksatz",
      "reader.left": "Links",
      "reader.light": "Hell",
      "reader.lineHeight": "Zeilenabstand",
      "reader.margins": "Textränder",
      "reader.narrow": "Schmal",
      "reader.noBookmarks": "Noch keine Lesezeichen.",
      "reader.noHighlights": "Noch keine Markierungen.",
      "reader.normal": "Normal",
      "reader.note": "Notiz",
      "reader.notePlaceholder": "Eigene Notiz schreiben…",
      "reader.openingEpub": "EPUB wird geöffnet…",
      "reader.preparingBook": "Buch wird vorbereitet…",
      "reader.preparingBookCount": "Buch wird vorbereitet… {current} / {total}",
      "reader.removeHighlight": "Markierung entfernen",
      "reader.resetDefaults": "Standardwerte wiederherstellen",
      "reader.sans": "Serifenlos",
      "reader.sepia": "Sepia",
      "reader.serif": "Serifenschrift",
      "reader.settings": "Leseeinstellungen",
      "reader.smaller": "Kleiner",
      "reader.tapRemoveHighlight": "Tippen, um die Markierung zu entfernen",
      "reader.wide": "Breit",
      "reader.withNote": "Mit Notiz",
      "recurring.nextOccurrence": "Nächstes Vorkommen",
      "recurring.nextScheduled": "Nächste Wiederholung geplant",
      "recurring.previousOccurrence": "Vorheriges Vorkommen",
      "recurring.ruleAt": "{rule} um {time}",
      "recurring.start": "Beginn der Wiederholung",
      "recurring.turnOff": "Wiederholung ausschalten",
      "reminders.channelDescription": "Benachrichtigungen für geplante Notizen und Aufgaben",
      "reminders.channelName": "LubaNote-Erinnerungen",
      "reminders.deletePlannedTitle": "Geplante Aufgabe löschen?",
      "reminders.deletePlannerTaskTitle": "Aufgabe aus dem Plan löschen?",
      "reminders.deleteReminderTitle": "Erinnerung löschen?",
      "reminders.disabled": "Erinnerung aus",
      "reminders.enabled": "Erinnerung an",
      "reminders.exactMessage": "Erlaube unter Android genaue Alarme, sonst kann das System die Benachrichtigung verzögern.",
      "reminders.exactTitle": "Genaue Erinnerungen",
      "reminders.futureRequired": "Die Erinnerung muss in der Zukunft liegen.",
      "reminders.noteCompleted": "Notiz erledigt",
      "reminders.remind": "Erinnern",
      "reminders.removeNoteFromPlanTitle": "Notiz aus dem Plan entfernen?",
      "reminders.turnOffFailed": "Die Erinnerung konnte nicht sicher ausgeschaltet werden.",
      "reminders.turnOffShort": "Ausschalten",
      "reminders.turningOff": "Erinnerung wird ausgeschaltet…",
      "settings.choice1": "1. Auswahl",
      "settings.choice2": "2. Auswahl",
      "settings.choice3": "3. Auswahl",
      "settings.choice4": "4. Auswahl",
      "settings.snoozeHours": "{count} Std.",
      "settings.snoozeMinutes": "{count} Min.",
      "status.preparing": "Wird vorbereitet…",
      "status.saved": "Gespeichert ✓",
      "status.savedCheck": "Gespeichert ✓",
      "status.updated": "Aktualisiert ✓",
      "tags.duplicate": "Ein Tag mit diesem Namen existiert bereits.",
      "tags.maxTwo": "Eine Notiz kann höchstens 2 Tags haben. Entferne zuerst einen.",
      "timePicker.now": "Jetzt",
      "timePicker.set": "Festlegen",
      "secret.deviceUnlockTitle": "Dieses Gerät entsperren",
      "secret.createMainTitle": "Hauptpasswort erstellen",
      "secret.unlockContinue": "Entsperren und fortfahren",
      "secret.createContinue": "Erstellen und fortfahren",
      "secret.deviceUnlockDescription": "Dieses Konto hat bereits ein Hauptpasswort. Gib es einmal ein, damit LubaNote den geheimen Modus und E2E-Fotos auf diesem Gerät sicher vorbereiten kann. Erst danach startet die Synchronisierung.",
      "secret.createMainDescription": "Bevor du LubaNote verwendest, erstelle ein Hauptpasswort. Es schützt den geheimen Modus und E2E-verschlüsselte Fotos. Es ist nicht dein Anmeldepasswort und LubaNote speichert es nicht in der Cloud.",
      "secret.unlockMode": "Geheimen Modus entsperren",
      "secret.createMainForNotes": "Erstelle ein Hauptpasswort für geheime Notizen.",
      "secret.createPassword": "Passwort erstellen",
      "tags.deleting": "Tag wird gelöscht…",
      "tags.savingShort": "Wird gespeichert…",
      "tags.saving": "Tag wird gespeichert…",
      "tags.moveUp": "Tags nach oben verschieben",
      "tags.moveDown": "Tags nach unten verschieben",
      "tags.orderSaveFailed": "Die Reihenfolge der Tags konnte nicht gespeichert werden.",
      "tags.savingOrder": "Tag-Reihenfolge wird gespeichert…",
      "tags.colorAria": "Tag-Farbe {name}",
      "tags.setColorAria": "Tag-Farbe auf {color} setzen",
      "tags.renameAria": "Tag {name} umbenennen",
      "tags.renaming": "Tag wird umbenannt…",
      "tags.deleteAria": "Tag {name} löschen",
      "tags.deleteConfirm": "Möchtest du den Tag „{name}“ wirklich löschen?",
      "tags.unlockFirst": "Entsperre zuerst den geheimen Modus.",
      "tags.newSaveFailed": "Der neue Tag konnte nicht gespeichert werden.",
      "tags.newLocalSaveFailed": "Der neue lokale Tag konnte nicht gespeichert werden.",
      "tags.newSaveFailedConnection": "Der neue Tag konnte nicht gespeichert werden. Prüfe deine Verbindung und versuche es erneut.",
      "tags.longPressWorks": "Langes Drücken funktioniert.",
      "tags.assignedMany": "Tag „{name}“ wurde {count} Karten zugewiesen",
      "tags.color.cervena": "Rot",
      "tags.color.oranzova": "Orange",
      "tags.color.zluta": "Gelb",
      "tags.color.zelena": "Grün",
      "tags.color.tyrkysova": "Türkis",
      "tags.color.modra": "Blau",
      "tags.color.fialova": "Violett",
      "tags.color.ruzova": "Rosa",
      "documents.addedType": "Hinzugefügt: {type} „{name}“.",
      "documents.addFailed": "Das Dokument konnte nicht hinzugefügt werden.",
      "documents.selectedNotType": "Die ausgewählte Datei ist keine {type}-Datei.",
      "documents.addFailedType": "{type} konnte nicht hinzugefügt werden.",
      "documents.selectedNotLegacyDoc": "Die ausgewählte Datei ist keine alte Word-DOC-Datei."
    },

    texty: {
      ...anglicky.texty,
      "Přihlášení vypršelo. Přihlas se znovu, aby mohla pokračovat synchronizace. Tvoje lokální data zůstala zachována.": "Deine Anmeldung ist abgelaufen. Melde dich erneut an, damit die Synchronisierung fortgesetzt werden kann. Deine lokalen Daten bleiben erhalten.",
      "Nepodařilo se připojit k synchronizaci. Zkus to znovu po připojení k internetu.": "Die Synchronisierung konnte nicht verbunden werden. Versuche es erneut, sobald du online bist.",
      "Ověření přihlášení se nepodařilo.": "Die Anmeldung konnte nicht überprüft werden.",
      "První přihlášení vyžaduje připojení k internetu.": "Die erste Anmeldung erfordert eine Internetverbindung.",
      "Ověřuji přihlášení…": "Anmeldung wird überprüft…",
      "Vyplň e-mail i heslo.": "Gib E-Mail und Passwort ein.",
      "Přihlášení vyžaduje internet. Lokální aplikace funguje offline až po prvním úspěšném přihlášení.": "Die Anmeldung erfordert Internet. Der Offline-Modus ist nach der ersten erfolgreichen Anmeldung verfügbar.",
      "Přihlašuji…": "Anmeldung läuft…",
      "Přihlášení se nezdařilo. Zkontroluj e-mail, heslo a připojení.": "Anmeldung fehlgeschlagen. Prüfe E-Mail, Passwort und Verbindung.",
      "Světlý": "Hell",
      "Tmavý": "Dunkel",
      "Původní ikony": "Klassische Symbole",
      "SVG ikony": "SVG-Symbole",
      "Pracovní": "Arbeit",
      "Soukromé": "Privat",
      "Bez názvu": "Ohne Titel",
      "Žádná odpovídající poznámka": "Keine passende Notiz",
      "⚠ Smazaná poznámka": "⚠ Gelöschte Notiz",
      "Tajný režim": "Geheimer Modus",
      "Tajný režim byl zamčen.": "Der geheime Modus wurde gesperrt.",
      "Tajný režim byl automaticky zamčen.": "Der geheime Modus wurde automatisch gesperrt.",
      "Tajný režim je odemčený.": "Der geheime Modus ist entsperrt.",
      "Tajný režim se nepodařilo odemknout.": "Der geheime Modus konnte nicht entsperrt werden.",
      "Tajný režim není odemčený.": "Der geheime Modus ist nicht entsperrt.",
      "Zadej hlavní heslo.": "Gib das Hauptpasswort ein.",
      "Hlavní heslo není správné.": "Das Hauptpasswort ist falsch.",
      "Hlavní heslo musí mít alespoň 8 znaků.": "Das Hauptpasswort muss mindestens 8 Zeichen lang sein.",
      "Hlavní heslo se nepodařilo vytvořit.": "Das Hauptpasswort konnte nicht erstellt werden.",
      "Upozornění": "Hinweis",
      "Nový štítek": "Neuer Tag",
      "Název štítku": "Tag-Name",
      "+ Nový štítek": "+ Neuer Tag",
      "Nový tajný štítek": "Neuer geheimer Tag",
    }
  });
})();
