/* LubaNote – Slovenčina · PATCH 676A */
window.LubaNoteLanguagePacks = window.LubaNoteLanguagePacks || [];

(() => {
  const anglicky = window.LubaNoteLanguagePacks.find((balicek) => balicek.id === "en") || { preklady: {}, texty: {} };

  window.LubaNoteLanguagePacks.push({
    id: "sk",
    nazev: "Slovenčina",
    kratkyNazev: "SK",
    vlajka: "🇸🇰",
    locale: "sk-SK",

    // Nejdřív bezpečný anglický fallback; přeložené produkční UI ho přepisuje níže.
    preklady: {
      ...anglicky.preklady,
      "language.label": "Jazyk",
      "language.choose": "Vyber jazyk",
      "login.splashSubtitle": "Poznámky • Plán • Dokumenty",
      "login.loading": "LubaNote sa načítava",
      "login.title": "Prihlásenie",
      "login.registerTitle": "Registrácia",
      "login.modeSignIn": "Prihlásenie",
      "login.modeRegister": "Registrácia",
      "login.email": "E-mail",
      "login.password": "Heslo",
      "login.passwordAgain": "Heslo znova",
      "login.submit": "Prihlásiť sa",
      "login.registerSubmit": "Registrovať",
      "login.checkStatus": "Skontrolovať stav",
      "login.modeAria": "Prihlásenie alebo registrácia",
      "login.downloadMyData": "Stiahnuť moje dáta",
      "login.deleteMyData": "Zmazať moje dáta",
      "login.clearThisDevice": "Vyčistiť toto zariadenie",
      "login.deleteMyDataTitle": "Zmazať moje dáta?",
      "login.clearThisDeviceTitle": "Vyčistiť toto zariadenie?",
      "login.clearWithoutBackup": "Vyčistiť bez zálohy",
      "login.pendingTitle": "Účet čaká na schválenie",
      "login.pendingText": "Registrácia je dokončená. Po schválení účtu správcom sa LubaNote odomkne.",
      "login.rejectedTitle": "Registrácia nebola schválená",
      "login.rejectedText": "Tento účet nebol schválený. Ak ide o omyl, kontaktuj správcu LubaNote.",
      "login.suspendedTitle": "Účet je pozastavený",
      "login.suspendedText": "Prístup do LubaNote je dočasne pozastavený.",
      "login.unavailableTitle": "Účet nie je dostupný",
      "login.unavailableText": "Prístup k účtu sa nepodarilo overiť. Skús to znova.",
      "login.enterCredentials": "Zadaj e-mail aj heslo.",
      "login.enterRegistration": "Zadaj e-mail, heslo a heslo znova.",
      "login.passwordMismatch": "Heslá sa nezhodujú.",
      "login.passwordTooShort": "Heslo musí mať aspoň 8 znakov.",
      "login.registrationOnline": "Registrácia vyžaduje pripojenie k internetu.",
      "login.registering": "Registrujem…",
      "login.registrationCreated": "Registrácia bola vytvorená. Potvrď e-mail a potom sa prihlás.",
      "login.emailConfirmed": "E-mail bol potvrdený. Teraz sa môžeš prihlásiť.",
      "login.emailLinkInvalid": "Potvrdzovací odkaz už bol použitý alebo vypršal. Ak je e-mail potvrdený, prihlás sa.",
      "login.stillPending": "Účet stále čaká na schválenie.",
      "login.alreadyRegistered": "Tento e-mail je už zaregistrovaný. Použi Prihlásenie.",
      "login.registrationFailed": "Registrácia zlyhala. Skontroluj e-mail, heslo a pripojenie.",
      "login.registrationRateLimited": "Bolo odoslaných príliš veľa potvrdzovacích e-mailov. Skús registráciu neskôr.",
      "login.signingIn": "Prihlasujem…",
      "login.signInFailed": "Prihlásenie zlyhalo. Skontroluj e-mail, heslo a pripojenie.",
      "login.emailNotConfirmed": "E-mail ešte nie je potvrdený. Otvor potvrdzovací odkaz v e-maile a potom sa prihlás znova.",
      "login.accountCheckFailed": "Stav účtu sa nepodarilo overiť. Skús to znova.",
      "login.localOwnerMismatch": "Táto inštalácia obsahuje lokálne dáta iného účtu LubaNote. Z bezpečnostných dôvodov nemožno účty miešať v jednej inštalácii.",
      "login.demoExpiredTitle": "Demo skončilo",
      "login.demoExpiredText": "Tvoje Demo skončilo {date}. Všetky dáta zostávajú bezpečne uložené. Na ďalšie používanie aplikácie bude potrebný plný prístup LubaNote.",
      "login.fullExpiredTitle": "Plný prístup skončil",
      "login.fullExpiredText": "Tvoje dáta zostávajú bezpečne uložené. LubaNote sa znova odomkne po obnovení plného prístupu.",
      "account.demoUntil": "Demo do {date}",
      "limits.notesTitle": "Dosiahnutý limit poznámok",
      "limits.notesText": "Tvoj plán povoľuje najviac {limit} poznámok. Novú poznámku teraz nemožno bezpečne uložiť. Existujúce dáta zostávajú zachované.",
      "nav.quick": "Rýchla navigácia",
      "nav.tools": "Nástroje",
      "nav.home": "Domov",
      "nav.allNotes": "Všetky poznámky",
      "nav.favorites": "Obľúbené",
      "nav.tags": "Štítky",
      "nav.settings": "Nastavenia",
      "nav.backup": "Záloha a obnova",
      "modules.aria": "Hlavné sekcie LubaNote",
      "modules.notes": "Poznámky",
      "storageScope.cloud": "Synchronizované",
      "storageScope.local": "Toto zariadenie",
      "storageScope.menu": "Úložisko",
      "storageScope.choose": "Kde sa majú poznámky ukladať?",
      "storageScope.localTitle": "Len toto zariadenie",
      "storageScope.localWarning": "Poznámky v tomto priestore sa nesynchronizujú. Pri strate alebo vymazaní zariadenia ich nemožno obnoviť z cloudu. Odporúčame pravidelné zálohy.",
      "storageScope.shareTitle": "Len toto zariadenie",
      "storageScope.shareBlocked": "Zdieľanie vyžaduje synchronizované úložisko. Táto poznámka zostáva len v tomto zariadení.",
      "modules.planner": "Plán",
      "modules.documents": "Dokumenty",
      "plannerTabs.calendar": "Kalendár",
      "modules.reminders": "Pripomienky",
      "sync.synced": "✓ Synchronizované",
      "sync.syncing": "⟳ Synchronizujem…",
      "sync.pending": "⏳ Čaká na synchronizáciu",
      "sync.localOnly": "📱 Len toto zariadenie",
      "sync.authExpired": "⚠ Prihlásenie vypršalo",
      "sync.conflict": "⚠ Konflikt",
      "search.placeholder": "Hľadať…",
      "search.aria": "Hľadať poznámky",
      "search.clear": "Vymazať hľadanie",
      "search.view": "Zmeniť rozloženie kariet",
      "search.menu": "Hlavné menu",
      "sort.labelNewest": "Nové karty: hore",
      "sort.labelOldest": "Nové karty: dole",
      "sort.title": "Umiestnenie novej karty",
      "sort.newest": "Nové karty hore",
      "sort.oldest": "Nové karty dole",
      "search.none": "Nenašli sa žiadne poznámky.",
      "menu.manageTags": "Spravovať štítky",
      "menu.about": "O aplikácii",
      "menu.logout": "Odhlásiť sa",
      "filter.aria": "Filtre poznámok",
      "filter.all": "Všetko",
      "filter.work": "Pracovné",
      "filter.private": "Súkromné",
      "filter.favorite": "Obľúbené poznámky",
      "filter.secret": "Tajné poznámky",
      "filter.finishSelection": "Dokončiť výber",
      "calendar.previousMonth": "Predchádzajúci mesiac",
      "calendar.nextMonth": "Nasledujúci mesiac",
      "calendar.selectedDay": "Vybraný deň",
      "calendar.addSelected": "Pridať úlohu na vybraný deň",
      "calendar.back": "Späť na kalendár",
      "calendar.addDay": "Pridať úlohu na tento deň",
      "calendar.week": "týždeň",
      "calendar.weekNumber": "Týždeň {value}",
      "weekday.mo": "Po",
      "weekday.tu": "Ut",
      "weekday.we": "St",
      "weekday.th": "Št",
      "weekday.fr": "Pi",
      "weekday.sa": "So",
      "weekday.su": "Ne",
      "recurring.title": "Opakovanie",
      "recurring.back": "Späť na pripomienky",
      "recurring.show": "Zobraziť opakované úlohy",
      "recurring.none": "Žiadne opakované úlohy.",
      "recurring.repeat": "Opakuje sa",
      "recurring.next": "Ďalej: {value}",
      "recurring.noNext": "Táto séria nemá ďalší výskyt.",
      "reminders.overdue": "Po termíne",
      "reminders.active": "Aktívne",
      "reminders.today": "Dnes",
      "reminders.none": "Žiadne pripomienky.",
      "reminders.noneOverdue": "Žiadne pripomienky po termíne.",
      "reminders.tomorrow": "Zajtra",
      "reminders.later": "Neskôr",
      "reminders.label": "Pripomienka",
      "reminders.untitled": "Bez názvu",
      "reminders.close": "Zavrieť",
      "reminders.tomorrow8": "Zajtra 8:00",
      "reminders.date": "Dátum",
      "reminders.time": "Čas",
      "reminders.selectDate": "Vybrať dátum pripomienky",
      "reminders.selectTime": "Vybrať čas pripomienky",
      "reminders.done": "Hotovo",
      "reminders.delete": "Zmazať",
      "reminders.openNote": "Otvoriť poznámku",
      "reminders.turnOff": "Vypnúť pripomienku",
      "editor.find": "Hľadať",
      "editor.findInNote": "Hľadať v tejto poznámke",
      "editor.findPrevious": "Predchádzajúci výsledok",
      "editor.findNext": "Nasledujúci výsledok",
      "editor.findClose": "Zavrieť hľadanie",
      "editor.openTools": "Otvoriť nástroje úprav",
      "editor.formatting": "Formátovanie poznámky",
      "editor.moreTools": "Ďalšie nástroje poznámky",
      "editor.undo": "Späť",
      "editor.redo": "Znova",
      "editor.bold": "Tučné",
      "editor.italic": "Kurzíva",
      "editor.underline": "Podčiarknuté",
      "editor.fontSize": "Veľkosť písma",
      "editor.textStyle": "Štýl textu",
      "editor.textColor": "Farba textu",
      "editor.white": "Biely text",
      "editor.black": "Čierny text",
      "editor.align": "Zarovnanie textu",
      "editor.alignLeft": "Zarovnať doľava",
      "editor.alignCenter": "Zarovnať na stred",
      "editor.alignRight": "Zarovnať doprava",
      "editor.insertImage": "Vložiť obrázok",
      "editor.insertWebLink": "Vložiť webový odkaz",
      "editor.webLink": "Webový odkaz",
      "editor.openDocument": "Otvoriť dokument",
      "editor.saveAs": "Uložiť ako",
      "editor.bullets": "Odrážkový zoznam",
      "editor.date": "Dátum",
      "editor.time": "Čas",
      "editor.selectDate": "Vybrať dátum",
      "editor.selectTime": "Vybrať čas",
      "editor.pin": "Pripnúť poznámku",
      "editor.reminder": "Pripomienka",
      "editor.backLink": "Späť na predchádzajúcu prepojenú poznámku",
      "editor.titleAria": "Názov poznámky",
      "editor.titlePlaceholder": "Názov poznámky",
      "editor.secret": "Tajná poznámka",
      "editor.tags": "Štítky",
      "editor.newTag": "Nový štítok",
      "editor.cancelNewTag": "Zrušiť nový štítok",
      "editor.saveClose": "Uložiť a zavrieť",
      "editor.area": "Oblasť poznámky",
      "editor.priority": "Priorita",
      "editor.color": "Farba",
      "editor.planSelection": "Naplánovať vybraný text",
      "editor.addTodo": "Pridať položku TODO",
      "editor.deleteNote": "Zmazať poznámku",
      "backlinks.aria": "Odkazy na túto poznámku",
      "backlinks.title": "Odkazy na túto poznámku ({count})",
      "backlinks.none": "Žiadne odkazy na túto poznámku",
      "actions.save": "Uložiť",
      "actions.discard": "Neukladať",
      "actions.ok": "OK",
      "status.done": "Hotovo",
      "secret.mainPassword": "Hlavné heslo",
      "secret.passwordAgain": "Heslo znova",
      "secret.enterMain": "Zadaj hlavné heslo.",
      "actions.term": "Termín",
      "actions.pin": "Pripnúť",
      "actions.delete": "Zmazať",
      "actions.more": "Ďalšie akcie",
      "actions.cancel": "Zrušiť",
      "actions.create": "Vytvoriť",
      "message.notice": "Upozornenie",
      "editor.notePlaceholder": "Napíš poznámku…",
      "tags.name": "Názov štítku",
      "tags.add": "Pridať",
      "deleteNote.message": "Naozaj chceš zmazať túto poznámku?",
      "deleteNote.title": "Zmazať poznámku?",
      "timePicker.title": "Vybrať čas",
      "timePicker.close": "Zavrieť výber času",
      "timePicker.clock": "Ciferník výberu času",
      "repeat.title": "Opakovanie",
      "repeat.aria": "Opakovanie úlohy",
      "repeat.no": "Nie",
      "repeat.daily": "Denne",
      "repeat.weekly": "Týždenne",
      "repeat.twoWeeks": "2 týždne",
      "repeat.monthly": "Mesačne",
      "repeat.none": "Neopakovať",
      "planner.plan": "Naplánovať",
      "planner.close": "Zavrieť plánovanie",
      "planner.selectDate": "Vybrať dátum plánovanej úlohy",
      "planner.selectTime": "Vybrať čas plánovanej úlohy",
      "sharing.settingsTitle": "Zdieľanie",
      "sharing.usernameLabel": "Používateľské meno",
      "sharing.usernameUnset": "Nastaviť",
      "sharing.usernameModalTitle": "Používateľské meno na zdieľanie",
      "sharing.usernameDescription": "Ostatní ťa nájdu iba podľa presného @používateľského mena. Tvoj e-mail sa pri zdieľaní nikdy nezobrazuje.",
      "sharing.usernamePlaceholder": "napr. Lubomir",
      "sharing.usernameSave": "Uložiť",
      "sharing.usernameCancel": "Zrušiť",
      "sharing.usernameInvalid": "Použi 3–30 znakov: písmená, čísla, bodku, pomlčku alebo podčiarkovník.",
      "sharing.usernameTaken": "Toto @používateľské meno už používa niekto iný.",
      "sharing.usernameOffline": "Nastavenie @používateľského mena vyžaduje internet.",
      "sharing.usernameSaving": "Ukladám…",
      "sharing.usernameSaveFailed": "Používateľské meno sa nepodarilo uložiť.",
      "sharing.usernameRequiredTitle": "Vytvor si @používateľské meno",
      "sharing.usernameRequiredDescription": "Pred používaním LubaNote si vytvor verejné @používateľské meno na zdieľanie a chat. Ostatní ťa nájdu iba podľa presného @používateľského mena; tvoj e-mail sa nezobrazuje.",
      "sharing.usernameRequiredSave": "Vytvoriť a pokračovať",
      "sharing.shareButton": "Zdieľať",
      "sharing.invitationsAria": "Pozvánky na zdieľanie",
      "sharing.shareModalTitle": "Zdieľať poznámku",
      "sharing.shareModalDescription": "Pozvi používateľa zadaním jeho presného @používateľského mena.",
      "sharing.shareInputPlaceholder": "napr. LubaNoteDemo",
      "sharing.shareSend": "Odoslať pozvánku",
      "sharing.shareSending": "Odosielam…",
      "sharing.shareSendSuccess": "Pozvánka bola odoslaná.",
      "sharing.shareSendFailed": "Pozvánku sa nepodarilo odoslať.",
      "sharing.shareInvalidUsername": "Zadaj platné @používateľské meno.",
      "sharing.shareOffline": "Zdieľanie vyžaduje internet.",
      "sharing.shareUsernameMissing": "Najprv si v Nastaveniach nastav vlastné @používateľské meno.",
      "sharing.shareUserNotFound": "Používateľ s týmto presným @používateľským menom sa nenašiel.",
      "sharing.shareSelf": "Poznámku nemôžeš zdieľať sám so sebou.",
      "sharing.shareAlreadyCollaborator": "Tento používateľ už na poznámke spolupracuje.",
      "sharing.shareAlreadyPending": "Pozvánka pre tohto používateľa už čaká.",
      "sharing.shareSecretBlocked": "Tajné poznámky zatiaľ nemožno zdieľať.",
      "sharing.shareNewNoteBlocked": "Najprv poznámku ulož, potom ju môžeš zdieľať.",
      "sharing.collaboratorsTitle": "Spolupracovníci",
      "sharing.collaboratorsEmpty": "Zatiaľ žiadni spolupracovníci.",
      "sharing.pendingTitle": "Čakajúce pozvánky",
      "sharing.pendingEmpty": "Žiadne čakajúce pozvánky.",
      "sharing.cancelInvitation": "Zrušiť",
      "sharing.cancelFailed": "Pozvánku sa nepodarilo zrušiť.",
      "sharing.cancel": "Zrušiť",
      "sharing.removeCollaborator": "Odstrániť",
      "sharing.removeCollaboratorConfirm": "Odstrániť {username} zo zdieľania?",
      "sharing.removeCollaboratorSuccess": "Spolupracovník bol odstránený.",
      "sharing.removeCollaboratorFailed": "Spolupracovníka sa nepodarilo odstrániť.",
      "sharing.removeCollaboratorMissing": "Tento používateľ už poznámku nezdieľa.",
      "sharing.manageNotOwner": "Túto akciu môže vykonať iba vlastník poznámky.",
      "sharing.manageModalUnavailable": "Potvrdzovací dialóg sa nepodarilo otvoriť.",
      "sharing.leaveSharedNote": "Opustiť zdieľanie",
      "sharing.leaveConfirm": "Opustiť zdieľanie tejto poznámky?",
      "sharing.leaveSuccess": "Zdieľanie bolo opustené.",
      "sharing.leaveFailed": "Zdieľanie sa nepodarilo opustiť.",
      "sharing.ownerCannotLeave": "Vlastník nemôže opustiť zdieľanie. Najprv odovzdaj vlastníctvo.",
      "sharing.ownerRole": "Vlastník",
      "sharing.editorRole": "Editor",
      "sharing.invitationsTitle": "Pozvánky na zdieľanie",
      "sharing.invitationsEmpty": "Nemáš žiadne čakajúce pozvánky.",
      "sharing.invitedBy": "Pozval používateľ {username}",
      "sharing.accept": "Prijať",
      "sharing.decline": "Odmietnuť",
      "sharing.responding": "Pracujem…",
      "sharing.invitationAccepted": "Pozvánka bola prijatá.",
      "sharing.invitationDeclined": "Pozvánka bola odmietnutá.",
      "sharing.invitationResponseFailed": "Pozvánku sa nepodarilo spracovať.",
      "sharing.refresh": "Obnoviť",
      "sharing.close": "Zavrieť",
      "sharing.loading": "Načítavam…",
      "sharing.loadFailed": "Dáta zdieľania sa nepodarilo načítať.",
      "sharing.sharedUntitled": "Bez názvu",
      "sharing.sharedCardMeta": "Zdieľané · {owner}",
      "sharing.readOnlyTitle": "Zdieľaná poznámka",
      "sharing.readOnlyMeta": "{owner} · zdieľaná poznámka",
      "sharing.readOnlyTodos": "Úlohy",
      "sharing.editShared": "Upraviť",
      "sharing.sharedEditorOffline": "Zdieľanú poznámku možno upravovať iba online.",
      "sharing.sharedEditorBusy": "{username} práve upravuje túto poznámku. Zatiaľ ju môžeš iba čítať.",
      "sharing.sharedEditorOpening": "Otváram zdieľaný editor…",
      "sharing.sharedEditorSaveFailed": "Zdieľanú poznámku sa nepodarilo bezpečne uložiť. Editor zostáva otvorený.",
      "sharing.sharedEditorConflict": "Na serveri existuje novšia verzia poznámky. Editor zostáva otvorený; zavri ho bez uloženia a poznámku otvor znova.",
      "sharing.sharedEditorLockLost": "Zámok editora už nie je platný. Zdieľaný editor bol bezpečne zatvorený.",
      "sharing.sharedEditorSaved": "Zdieľaná poznámka bola uložená.",
      "chat.buttonAria": "Správy",
      "chat.contactsTitle": "Správy",
      "chat.contactsEmpty": "Zatiaľ nemáš žiadne kontakty v chate. Kontakt vznikne po prijatí pozvánky na zdieľanie poznámky.",
      "chat.writeMessage": "Napísať správu",
      "chat.trustedContact": "Kontakt zo zdieľania",
      "chat.ready": "Môžete si písať",
      "chat.lastMessageAt": "Posledná správa {time}",
      "chat.messagePlaceholder": "Napíš správu…",
      "chat.send": "Odoslať",
      "chat.sending": "Odosielam…",
      "chat.sent": "Odoslané",
      "chat.read": "Prečítané",
      "chat.messagesEmpty": "Zatiaľ žiadne správy.",
      "chat.deletedPlaceholder": "Správa bola zmazaná",
      "chat.deleteMessage": "Zmazať správu",
      "chat.deleteTitle": "Zmazať správu?",
      "chat.deleteText": "Správa sa zmaže obom účastníkom a zostane iba zástupný text o zmazanej správe.",
      "chat.deleteForBoth": "Zmazať obom",
      "chat.deleting": "Mažem…",
      "chat.deleteFailed": "Správu sa nepodarilo zmazať.",
      "chat.sendFailed": "Správu sa nepodarilo odoslať.",
      "chat.loadFailed": "Chat sa nepodarilo načítať.",
      "chat.loadMessagesFailed": "Správy sa nepodarilo načítať.",
      "chat.loading": "Načítavam…",
      "chat.offline": "Chat vyžaduje internet.",
      "chat.blocked": "Chat je zablokovaný",
      "chat.contactNotFound": "Kontakt v chate zatiaľ nie je dostupný.",
      "chat.tooLong": "Správa je príliš dlhá.",
      "chat.close": "Zavrieť",
      "chat.back": "Späť",
      "chat.cancel": "Zrušiť",
      "chat.threadAria": "Chat",
      "settings.title": "Nastavenia",
      "settings.close": "Zavrieť nastavenia",
      "settings.appearance": "Vzhľad",
      "settings.fontSize": "Veľkosť písma",
      "settings.decreaseFont": "Zmenšiť písmo",
      "settings.increaseFont": "Zväčšiť písmo",
      "settings.theme": "Farebný motív",
      "settings.iconStyle": "Štýl ikon",
      "settings.keyboard": "Klávesnica editora",
      "settings.keyboardTitle": "Klávesnica editora",
      "settings.keyboardLuba": "LubaKeyboard (predvolená)",
      "settings.keyboardSystem": "Systémová",
      "settings.keyboardSystemLong": "Systémová klávesnica (Gboard / iOS)",
      "settings.reminders": "Pripomienky",
      "settings.quickDelay": "Rýchle odloženie",
      "settings.configure": "Nastaviť",
      "settings.overdueRetention": "Zmazať po termíne po",
      "settings.overdueNever": "Nikdy",
      "settings.overdueDays": "{count} dní",
      "settings.overdueConfirm": "potvrdiť",
      "settings.data": "Dáta",
      "settings.noteOpenPosition": "Pri otvorení poznámky",
      "settings.noteOpenStart": "Začiatok",
      "settings.noteOpenEnd": "Koniec",
      "settings.export": "Exportovať zálohu",
      "settings.import": "Importovať zálohu",
      "settings.about": "O aplikácii",
      "settings.version": "Verzia",
      "settings.appInfo": "Informácie o aplikácii",
      "settings.open": "Otvoriť",
      "theme.light": "Svetlý",
      "theme.dark": "Tmavý",
      "icons.classic": "Pôvodné ikony",
      "icons.svg": "SVG ikony",
      "about.close": "Zavrieť informácie o aplikácii",
      "about.description": "Poznámky, úlohy, plánovanie a pripomienky na jednom mieste.",
      "addNote": "Pridať poznámku",
      "tags.new": "Nový štítok",
      "tags.newSecret": "Nový tajný štítok",
      "tags.manage": "Spravovať štítky",
      "tags.closeManage": "Zavrieť správu štítkov",
      "tags.deleteTitle": "Zmazať štítok?",
      "secret.saveSecret": "Uložiť ako tajné",
      "secret.saveNormal": "Uložiť normálne",
      "secret.mode": "Tajný režim",
      "secret.close": "Zavrieť tajný režim",
      "secret.fingerprint": "Odomknúť odtlačkom prsta",
      "secret.nextFingerprint": "🫆 Nabudúce použiť odtlačok prsta",
      "secret.thisDevice": "Len na tomto zariadení",
      "secret.unlock": "Odomknúť",
      "secret.tags": "Tajné štítky",
      "secret.createTag": "Vytvoriť tajný štítok",
      "secret.disableFingerprint": "Vypnúť odomykanie odtlačkom",
      "secret.lock": "Zamknúť tajný režim",
      "selection.cut": "Vystrihnúť",
      "selection.copy": "Kopírovať",
      "selection.paste": "Vložiť",
      "selection.all": "Všetko",
      "noteLinks.noMatch": "Žiadna zodpovedajúca poznámka",
      "noteLinks.create": "+ Vytvoriť poznámku „{value}“",
      "noteLinks.deleted": "⚠ Zmazaná poznámka",
      "noteLinks.unavailable": "Cieľová poznámka už nie je dostupná.",
      "noteLinks.previous": "Predchádzajúca poznámka",
      "noteLinks.createFailed": "Prepojenú poznámku sa nepodarilo bezpečne vytvoriť.",
      "noteLinks.ariaTarget": "Interný odkaz na poznámku {value}",
      "noteLinks.ariaMissing": "Interný odkaz na nedostupnú poznámku",
      "noteLinks.dialogTitle": "Interný odkaz",
      "trash.title": "Kôš",
      "trash.secretTitle": "Tajný kôš",
      "trash.close": "Zavrieť Kôš",
      "trash.autoDeleteInfo": "Poznámky sa po 30 dňoch automaticky natrvalo zmažú.",
      "trash.empty": "Kôš je prázdny.",
      "trash.untitled": "Bez názvu",
      "trash.noPreview": "Bez náhľadu",
      "trash.moved": "V koši od",
      "trash.daysLeft": "Trvalé zmazanie o {count} dní",
      "trash.restore": "Obnoviť",
      "trash.deleteForever": "Zmazať natrvalo",
      "trash.deleteForeverTitle": "Zmazať natrvalo?",
      "trash.deleteConfirm": "Táto poznámka bude natrvalo zmazaná a nebude ju možné obnoviť.",
      "trash.moveTitle": "Presunúť do Koša?",
      "trash.moveMessage": "Poznámka sa presunie do Koša a neskôr ju možno obnoviť.",
      "trash.moveAction": "Presunúť do Koša",
      "trash.moveManyMessage": "Presunúť {count} vybraných poznámok do Koša?",
      "trash.movedMany": "Presunuté do Koša: {count} poznámok",
      "trash.normalTab": "Normálne",
      "trash.secretTab": "Tajné 🔒",
      "trash.typeTabsLabel": "Typ Koša",
      "trash.selectAll": "Označiť všetko",
      "trash.clearSelection": "Zrušiť výber",
      "trash.deleteSelected": "Zmazať natrvalo ({count})",
      "trash.deleteManyNormalConfirm": "Natrvalo zmazať {count} položiek z bežného Koša? Túto akciu nemožno vrátiť späť.",
      "trash.deleteManySecretConfirm": "Natrvalo zmazať {count} položiek z Tajného koša? Túto akciu nemožno vrátiť späť.",
      "trash.bulkDeletePreparing": "Pripravujem mazanie…",
      "trash.bulkDeleting": "Mažem…",
      "trash.bulkDeleteProgress": "Mažem položky… {done} / {total}",
      "trash.bulkDeleteSyncing": "Synchronizujem zmeny…",
      "trash.bulkDeleteDoneAction": "Hotovo",
      "trash.bulkDeletePending": "Zmazané v tomto zariadení. Synchronizácia sa dokončí automaticky.",
      "trash.bulkDeleteOffline": "Zmazané v tomto zariadení. Synchronizácia prebehne po návrate online.",
      "trash.bulkDeleteFailed": "Mazanie sa nepodarilo bezpečne dokončiť. Položky zostali v Koši.",
    },

    texty: {
      ...anglicky.texty,
      "Přihlášení vypršelo. Přihlas se znovu, aby mohla pokračovat synchronizace. Tvoje lokální data zůstala zachována.": "Prihlásenie vypršalo. Prihlás sa znova, aby synchronizácia mohla pokračovať. Tvoje lokálne dáta zostali zachované.",
      "Nepodařilo se připojit k synchronizaci. Zkus to znovu po připojení k internetu.": "Nepodarilo sa pripojiť k synchronizácii. Skús to znova po pripojení k internetu.",
      "Ověření přihlášení se nepodařilo.": "Overenie prihlásenia zlyhalo.",
      "První přihlášení vyžaduje připojení k internetu.": "Prvé prihlásenie vyžaduje pripojenie k internetu.",
      "Ověřuji přihlášení…": "Overujem prihlásenie…",
      "Vyplň e-mail i heslo.": "Vyplň e-mail aj heslo.",
      "Přihlášení vyžaduje internet. Lokální aplikace funguje offline až po prvním úspěšném přihlášení.": "Prihlásenie vyžaduje internet. Lokálna aplikácia funguje offline až po prvom úspešnom prihlásení.",
      "Přihlašuji…": "Prihlasujem…",
      "Přihlášení se nezdařilo. Zkontroluj e-mail, heslo a připojení.": "Prihlásenie zlyhalo. Skontroluj e-mail, heslo a pripojenie.",
      "Světlý": "Svetlý",
      "Tmavý": "Tmavý",
      "Původní ikony": "Pôvodné ikony",
      "SVG ikony": "SVG ikony",
      "Pracovní": "Pracovné",
      "Soukromé": "Súkromné",
      "Bez názvu": "Bez názvu",
      "Žádná odpovídající poznámka": "Žiadna zodpovedajúca poznámka",
      "⚠ Smazaná poznámka": "⚠ Zmazaná poznámka",
      "Tajný režim": "Tajný režim",
      "Tajný režim byl zamčen.": "Tajný režim bol zamknutý.",
      "Tajný režim byl automaticky zamčen.": "Tajný režim bol automaticky zamknutý.",
      "Tajný režim je odemčený.": "Tajný režim je odomknutý.",
      "Tajný režim se nepodařilo odemknout.": "Tajný režim sa nepodarilo odomknúť.",
      "Tajný režim není odemčený.": "Tajný režim nie je odomknutý.",
      "Zadej hlavní heslo.": "Zadaj hlavné heslo.",
      "Hlavní heslo není správné.": "Hlavné heslo nie je správne.",
      "Hlavní heslo musí mít alespoň 8 znaků.": "Hlavné heslo musí mať aspoň 8 znakov.",
      "Hlavní heslo se nepodařilo vytvořit.": "Hlavné heslo sa nepodarilo vytvoriť.",
      "Upozornění": "Upozornenie",
      "Nový štítek": "Nový štítok",
      "Název štítku": "Názov štítku",
      "+ Nový štítek": "+ Nový štítok",
      "Nový tajný štítek": "Nový tajný štítok",
    }
  });
})();
