/*
 * LubaNote – čeština
 *
 * Každý jazyk je samostatný root JS soubor.
 * Nový jazyk může zkopírovat strukturu tohoto souboru,
 * změnit id / locale / názvy a doplnit překlady.
 */
window.LubaNoteLanguagePacks =
  window.LubaNoteLanguagePacks || [];

window.LubaNoteLanguagePacks.push({
  id: "cs",
  nazev: "Čeština",
  kratkyNazev: "CZ",
  vlajka: "🇨🇿",
  locale: "cs-CZ",

  preklady: {
    "language.label": "Jazyk",
    "language.choose": "Vyber jazyk",

    "login.loading": "LubaNote se načítá",
    "login.title": "Přihlášení",
    "login.email": "E-mail",
    "login.password": "Heslo",
    "login.submit": "Přihlásit se",

    "nav.quick": "Rychlá navigace",
    "nav.tools": "Nástroje",
    "nav.home": "Domů",
    "nav.allNotes": "Všechny poznámky",
    "nav.favorites": "Oblíbené",
    "nav.tags": "Štítky",
    "nav.settings": "Nastavení",
    "nav.backup": "Záloha a obnova",

    "modules.aria": "Hlavní části LubaNote",
    "modules.notes": "Poznámky",
    "modules.planner": "Plán",
    "modules.reminders": "Připomínky",

    "sync.synced": "✓ Synchronizováno",
    "sync.syncing": "⟳ Synchronizuji…",
    "sync.authExpired": "⚠ Přihlášení vypršelo",
    "sync.conflict": "⚠ Konflikt",

    "search.placeholder": "Hledat poznámky...",
    "search.aria": "Hledat poznámky",
    "search.clear": "Vymazat hledání",
    "search.view": "Změnit zobrazení karet",
    "search.menu": "Hlavní nabídka",
    "sort.labelNewest": "Řazení: nejnovější nahoře",
    "sort.labelOldest": "Řazení: nejstarší nahoře",
    "sort.title": "Řazení karet",
    "sort.newest": "Nejnovější nahoře",
    "sort.oldest": "Nejstarší nahoře",
    "search.none": "Nenalezeny žádné poznámky.",

    "menu.manageTags": "Správa štítků",
    "menu.about": "O aplikaci",
    "menu.logout": "Odhlásit se",

    "filter.aria": "Filtr poznámek",
    "filter.all": "Vše",
    "filter.work": "Pracovní",
    "filter.private": "Soukromé",
    "filter.favorite": "Oblíbené poznámky",
    "filter.secret": "Tajné poznámky",
    "filter.finishSelection": "Ukončit výběr",

    "calendar.previousMonth": "Předchozí měsíc",
    "calendar.nextMonth": "Další měsíc",
    "calendar.selectedDay": "Vybraný den",
    "calendar.addSelected": "Přidat úkol na vybraný den",
    "calendar.back": "Zpět na kalendář",
    "calendar.addDay": "Přidat úkol na tento den",
    "calendar.week": "týden",
    "calendar.weekNumber": "{value}. týden",
    "weekday.mo": "Po",
    "weekday.tu": "Út",
    "weekday.we": "St",
    "weekday.th": "Čt",
    "weekday.fr": "Pá",
    "weekday.sa": "So",
    "weekday.su": "Ne",

    "recurring.title": "Opakující se",
    "recurring.back": "Zpět na připomínky",
    "recurring.show": "Zobrazit opakované úkoly",
    "recurring.none": "Žádné opakované úkoly.",
    "recurring.repeat": "Opakování",
    "recurring.next": "Příště: {value}",
    "recurring.noNext": "Série už nemá další termín.",

    "reminders.overdue": "Po termínu",
    "reminders.active": "Aktivní",
    "reminders.today": "Dnes",
    "reminders.none": "Žádné připomínky.",
    "reminders.noneOverdue": "Žádné připomínky po termínu.",
    "reminders.tomorrow": "Zítra",
    "reminders.later": "Později",
    "reminders.label": "Připomínka",
    "reminders.untitled": "Bez názvu",
    "reminders.close": "Zavřít",
    "reminders.tomorrow8": "Zítra 8:00",
    "reminders.date": "Datum",
    "reminders.time": "Čas",
    "reminders.selectDate": "Vybrat datum připomínky",
    "reminders.selectTime": "Vybrat čas připomínky",
    "reminders.done": "Hotovo",
    "reminders.delete": "Smazat",
    "reminders.openNote": "Otevřít poznámku",
    "reminders.turnOff": "Vypnout připomínku",

    "editor.openTools": "Otevřít editační nástroje",
    "editor.formatting": "Formátování poznámky",
    "editor.moreTools": "Další nástroje poznámky",
    "editor.undo": "Zpět",
    "editor.redo": "Znovu",
    "editor.bold": "Tučné písmo",
    "editor.italic": "Kurzíva",
    "editor.underline": "Podtržení",
    "editor.fontSize": "Velikost písma",
    "editor.textStyle": "Styl textu",
    "editor.textColor": "Barva textu",
    "editor.white": "Bílá barva textu",
    "editor.black": "Černá barva textu",
    "editor.align": "Zarovnání textu",
    "editor.alignLeft": "Zarovnat vlevo",
    "editor.alignCenter": "Zarovnat na střed",
    "editor.alignRight": "Zarovnat vpravo",
    "editor.insertImage": "Vložit obrázek",
    "editor.insertWebLink": "Vložit internetový odkaz",
    "editor.webLink": "Internetový odkaz",
    "editor.openDocument": "Otevřít dokument",
    "editor.saveAs": "Uložit jako",
    "editor.bullets": "Odrážkový seznam",
    "editor.date": "Datum",
    "editor.time": "Čas",
    "editor.selectDate": "Vybrat datum",
    "editor.selectTime": "Vybrat čas",
    "editor.pin": "Připnout poznámku",
    "editor.reminder": "Připomínka",
    "editor.backLink": "Zpět na předchozí propojenou poznámku",
    "editor.titleAria": "Název úkolu",
    "editor.titlePlaceholder": "Název úkolu",
    "editor.secret": "Tajná poznámka",
    "editor.tags": "Štítky",
    "editor.newTag": "Nový štítek",
    "editor.cancelNewTag": "Zrušit nový štítek",
    "editor.saveClose": "Uložit a zavřít",
    "editor.area": "Oblast poznámky",
    "editor.priority": "Priorita",
    "editor.color": "Barva",
    "editor.planSelection": "Naplánovat označený text",
    "editor.addTodo": "Přidat položku TODO",
    "editor.deleteNote": "Smazat poznámku",

    "backlinks.aria": "Zpětné odkazy na tuto poznámku",
    "backlinks.title": "Odkazy na tuto poznámku ({count})",
    "backlinks.none": "Žádné odkazy na tuto poznámku",

    "actions.save": "Uložit",
    "actions.discard": "Neukládat",
    "actions.ok": "OK",
    "status.done": "Hotovo",
    "secret.mainPassword": "Hlavní heslo",
    "secret.passwordAgain": "Heslo znovu",
    "secret.enterMain": "Zadej hlavní heslo.",
    "actions.term": "Termín",
    "actions.pin": "Připnout",
    "actions.delete": "Smazat",
    "actions.more": "Více akcí",
    "actions.cancel": "Zrušit",
    "actions.create": "Vytvořit",

    "message.notice": "Upozornění",
    "editor.notePlaceholder": "Napiš poznámku...",
    "tags.name": "Název štítku",
    "tags.add": "Přidat",
    "deleteNote.message": "Opravdu chceš tuto poznámku smazat?",
    "deleteNote.title": "Smazat poznámku?",

    "timePicker.title": "Vybrat čas",
    "timePicker.close": "Zavřít výběr času",
    "timePicker.clock": "Ciferník výběru času",
    "repeat.title": "Opakování",
    "repeat.aria": "Opakování úkolu",
    "repeat.no": "Ne",
    "repeat.daily": "Denně",
    "repeat.weekly": "Týdně",
    "repeat.twoWeeks": "2 týdny",
    "repeat.monthly": "Měsíčně",
    "repeat.none": "Neopakovat",

    "planner.plan": "Naplánovat",
    "planner.close": "Zavřít plánování",
    "planner.selectDate": "Vybrat datum plánovaného úkolu",
    "planner.selectTime": "Vybrat čas plánovaného úkolu",

    "settings.title": "Nastavení",
    "settings.close": "Zavřít nastavení",
    "settings.appearance": "Vzhled",
    "settings.fontSize": "Velikost písma",
    "settings.decreaseFont": "Zmenšit písmo",
    "settings.increaseFont": "Zvětšit písmo",
    "settings.theme": "Barevný motiv",
    "settings.iconStyle": "Styl ikon",
    "settings.reminders": "Připomínky",
    "settings.quickDelay": "Rychlé odložení",
    "settings.configure": "Nastavit",
    "settings.data": "Data",
    "settings.export": "Export zálohy",
    "settings.import": "Import zálohy",
    "settings.about": "O aplikaci",
    "settings.version": "Verze",
    "settings.appInfo": "Informace o aplikaci",
    "settings.open": "Otevřít",

    "theme.light": "Světlý",
    "theme.dark": "Tmavý",
    "icons.classic": "Původní ikony",
    "icons.svg": "SVG ikony",

    "about.close": "Zavřít informace o aplikaci",
    "about.description": "Poznámky, úkoly, plánování a připomínky na jednom místě.",
    "addNote": "Přidat poznámku",

    "tags.new": "Nový štítek",
    "tags.newSecret": "Nový tajný štítek",
    "tags.manage": "Správa štítků",
    "tags.closeManage": "Zavřít správu štítků",
    "tags.deleteTitle": "Smazat štítek?",

    "secret.saveSecret": "Uložit jako tajnou",
    "secret.saveNormal": "Uložit normálně",
    "secret.mode": "Tajný režim",
    "secret.close": "Zavřít tajný režim",
    "secret.fingerprint": "Odemknout otiskem",
    "secret.nextFingerprint": "🫆 Příště odemykat otiskem",
    "secret.thisDevice": "Jen na tomto zařízení",
    "secret.unlock": "Odemknout",
    "secret.tags": "Tajné štítky",
    "secret.createTag": "Vytvořit tajný štítek",
    "secret.disableFingerprint": "Zrušit odemykání otiskem",
    "secret.lock": "Zamknout tajný režim",

    "selection.cut": "Vyjmout",
    "selection.copy": "Kopírovat",
    "selection.paste": "Vložit",
    "selection.all": "Vše",

    "noteLinks.noMatch": "Žádná odpovídající poznámka",
    "noteLinks.create": "+ Vytvořit poznámku „{value}“",
    "noteLinks.deleted": "⚠ Smazaná poznámka",
    "noteLinks.unavailable": "Cílová poznámka už není dostupná.",
    "noteLinks.previous": "Předchozí poznámka",
    "noteLinks.createFailed": "Novou propojenou poznámku se nepodařilo bezpečně vytvořit.",
    "noteLinks.ariaTarget": "Interní odkaz na poznámku {value}",
    "noteLinks.ariaMissing": "Interní odkaz na nedostupnou poznámku",
    "noteLinks.dialogTitle": "Interní odkaz",

    "trash.title": "Koš",
    "trash.secretTitle": "Tajný koš",
    "trash.close": "Zavřít Koš",
    "trash.autoDeleteInfo": "Poznámky se po 30 dnech automaticky smažou trvale.",
    "trash.empty": "Koš je prázdný.",
    "trash.untitled": "Bez názvu",
    "trash.noPreview": "Bez náhledu",
    "trash.moved": "V koši od",
    "trash.daysLeft": "Automatické smazání za {count} dní",
    "trash.restore": "Obnovit",
    "trash.deleteForever": "Smazat trvale",
    "trash.deleteForeverTitle": "Smazat trvale?",
    "trash.deleteConfirm": "Tato poznámka bude smazána trvale a nepůjde obnovit.",
    "trash.moveTitle": "Přesunout do koše?",
    "trash.moveMessage": "Poznámka se přesune do Koše a můžeš ji později obnovit.",
    "trash.moveAction": "Do koše",
    "trash.moveManyMessage": "Přesunout {count} vybraných poznámek do Koše?",
    "trash.movedMany": "Přesunuto do Koše: {count} poznámek"
  },

  /*
   * Přesné věty používané dynamicky v JS.
   * Motor je umí přeložit přes prelozText().
   */
  texty: {}
});
