/*
 * LubaNote – čeština
 *
 * Každý jazyk je samostatný root JS soubor.
 * Nový jazyk může zkopírovat strukturu tohoto souboru,
 * změnit id / locale / názvy a doplnit překlady.
 */
window.LubaNoteLanguagePacks =
  window.LubaNoteLanguagePacks || [];

window.LubaNoteLanguagePacks.push({
  id: "cs",
  nazev: "Čeština",
  kratkyNazev: "CZ",
  vlajka: "🇨🇿",
  locale: "cs-CZ",

  preklady: {
    "language.label": "Jazyk",
    "language.choose": "Vyber jazyk",

    "login.splashSubtitle": "Poznámky • Plán • Dokumenty",
    "login.loading": "LubaNote se načítá",
    "login.title": "Přihlášení",
    "login.registerTitle": "Registrace",
    "login.modeSignIn": "Přihlášení",
    "login.modeRegister": "Registrace",
    "login.email": "E-mail",
    "login.password": "Heslo",
    "login.passwordAgain": "Heslo znovu",
    "login.submit": "Přihlásit se",
    "login.registerSubmit": "Registrovat",
    "login.checkStatus": "Zkontrolovat stav",
    "login.modeAria": "Přihlášení nebo registrace",
    "login.downloadMyData": "Stáhnout moje data",
    "login.deleteMyData": "Smazat moje data",
    "login.clearThisDevice": "Vyčistit toto zařízení",
    "login.deleteMyDataTitle": "Smazat moje data?",
    "login.clearThisDeviceTitle": "Vyčistit toto zařízení?",
    "login.clearWithoutBackup": "Vyčistit bez zálohy",
    "login.pendingTitle": "Účet čeká na schválení",
    "login.pendingText": "Registrace je hotová. Až správce účet schválí, LubaNote se odemkne.",
    "login.rejectedTitle": "Registrace nebyla schválena",
    "login.rejectedText": "Tento účet nebyl schválen. Pokud je to omyl, kontaktuj správce LubaNote.",
    "login.suspendedTitle": "Účet je pozastavený",
    "login.suspendedText": "Přístup k LubaNote je dočasně pozastavený.",
    "login.unavailableTitle": "Účet není dostupný",
    "login.unavailableText": "Přístup k účtu se nepodařilo ověřit. Zkus kontrolu znovu.",
    "login.enterCredentials": "Vyplň e-mail i heslo.",
    "login.enterRegistration": "Vyplň e-mail, heslo i heslo znovu.",
    "login.passwordMismatch": "Zadaná hesla se neshodují.",
    "login.passwordTooShort": "Heslo musí mít alespoň 8 znaků.",
    "login.registrationOnline": "Registrace vyžaduje připojení k internetu.",
    "login.registering": "Registruji…",
    "login.registrationCreated": "Registrace byla vytvořena. Potvrď e-mail a potom se přihlas.",
    "login.emailConfirmed": "E-mail byl potvrzen. Teď se přihlas.",
    "login.emailLinkInvalid": "Potvrzovací odkaz už byl použit nebo vypršel. Pokud je e-mail potvrzený, přihlas se.",
    "login.stillPending": "Účet stále čeká na schválení.",
    "login.alreadyRegistered": "Tento e-mail už je zaregistrovaný. Použij Přihlášení.",
    "login.registrationFailed": "Registrace se nezdařila. Zkontroluj e-mail, heslo a připojení.",
    "login.registrationRateLimited": "Bylo odesláno příliš mnoho potvrzovacích e-mailů. Zkus registraci později.",
    "login.signingIn": "Přihlašuji…",
    "login.signInFailed": "Přihlášení se nezdařilo. Zkontroluj e-mail, heslo a připojení.",
    "login.emailNotConfirmed": "E-mail ještě není potvrzený. Otevři potvrzovací odkaz v e-mailu a pak se přihlas znovu.",
    "login.accountCheckFailed": "Stav účtu se nepodařilo ověřit. Zkus to znovu.",
    "login.localOwnerMismatch": "Toto zařízení obsahuje lokální data jiného LubaNote účtu. Kvůli bezpečnosti se účty na stejné instalaci nesmí míchat.",
    "login.demoExpiredTitle": "Demo skončilo",
    "login.demoExpiredText": "Tvoje Demo skončilo {date}. Všechna data zůstávají bezpečně uložená. Pro další používání bude potřeba aktivovat plnou verzi LubaNote.",
    "login.fullExpiredTitle": "Přístup k plné verzi skončil",
    "login.fullExpiredText": "Tvoje data zůstávají bezpečně uložená. Po obnovení plné verze se LubaNote znovu odemkne.",
    "account.demoUntil": "Demo do {date}",
    "limits.notesTitle": "Limit poznámek dosažen",
    "limits.notesText": "Tvůj plán umožňuje maximálně {limit} poznámek. Novou poznámku teď nelze bezpečně uložit. Tvoje stávající data zůstávají zachována.",

    "nav.quick": "Rychlá navigace",
    "nav.tools": "Nástroje",
    "nav.home": "Domů",
    "nav.allNotes": "Všechny poznámky",
    "nav.favorites": "Oblíbené",
    "nav.tags": "Štítky",
    "nav.settings": "Nastavení",
    "nav.backup": "Záloha a obnova",
    "admin.menu": "Admin Dashboard",
    "admin.title": "Admin Dashboard",
    "admin.pending": "Čeká",
    "admin.active": "Aktivní",
    "admin.demo": "Demo",
    "admin.pendingTab": "Čekající",
    "admin.allTab": "Všichni",
    "admin.refresh": "Obnovit uživatele",
    "admin.close": "Zavřít Admin Dashboard",
    "admin.syncTrafficTitle": "RX/TX/E panel",
    "admin.syncTrafficOn": "Zapnuto",
    "admin.syncTrafficOff": "Vypnuto",
    "admin.syncTrafficVisible": "Panel RX/TX/E je zobrazený",
    "admin.syncTrafficHidden": "Panel RX/TX/E je skrytý",

    "admin.notesVisualTitle": "Poznámky – vzhled",
    "admin.notesVisualDescription": "Vyber prvek a laď ho živě. Hodnoty zůstávají jen v tomto zařízení.",
    "admin.notesVisualFloatingButton": "🎛️ Otevřít plovoucí ladění",
    "admin.notesVisualOn": "Zapnuto",
    "admin.notesVisualOriginal": "Pův.",
    "admin.notesVisualOff": "Vypnuto",
    "admin.notesVisualTarget": "Prvek",
    "admin.notesSelectedSection": "Vybraný prvek",
    "admin.notesSelectedHint": "Border, barva, radius a velikost se mění pouze u vybraného prvku.",
    "admin.notesBorderToggle": "Border",
    "admin.notesBorderMode": "Odstín borderu",
    "admin.notesBorderModeDark": "Tmavší barva",
    "admin.notesBorderModeLight": "Světlejší barva",
    "admin.notesBorderModeLegacy": "Původní",
    "admin.notesBorderWidth": "Šířka borderu",
    "admin.notesBorderStrength": "Síla zesvětlení / ztmavení",
    "admin.notesBorderRadius": "Zaoblení rohů",
    "admin.notesSizeCards": "Vnitřní odsazení karty",
    "admin.notesSizeTags": "Výška štítku",
    "admin.notesSizePrimary": "Výška hlavního filtru",
    "admin.notesSizeSearch": "Výška hledání + ikon",
    "admin.notesSizeActions": "Výška hledání + ikon",
    "admin.notesSizeTraffic": "Minimální výška RX/TX/E panelu",
    "admin.notesSizeModules": "Výška modulového tlačítka",
    "admin.notesSizeFab": "Velikost plovoucího +",
    "admin.notesTargetCards": "Karty poznámek",
    "admin.notesTargetTags": "Vlastní štítky",
    "admin.notesTargetPrimary": "Hlavní filtry",
    "admin.notesTargetSearch": "Hledání",
    "admin.notesTargetActions": "Horní akční ikony",
    "admin.notesTargetTraffic": "RX/TX/E panel",
    "admin.notesTargetModules": "Poznámky / Plán / Dokumenty",
    "admin.notesTargetFab": "Plovoucí +",
    "admin.notesLayoutTitle": "Rozložení hlavního screenu",
    "admin.notesLayoutHint": "Jemné mezery a posuny bez zásahu do dat nebo logiky aplikace.",
    "admin.notesOffsetY": "Posun obsahu nahoru / dolů",
    "admin.notesActionsFiltersGap": "Mezera akce ↕ filtry",
    "admin.notesFilterGap": "Mezera hlavních filtrů",
    "admin.notesTagsGap": "Mezera mezi štítky",
    "admin.notesRowsGap": "Mezera filtry ↕ štítky",
    "admin.notesTagsCardsGap": "Mezera štítky ↕ karty",
    "admin.notesCardColumnGap": "Mezera mezi sloupci karet",
    "admin.notesCardRowGap": "Mezera pod kartami",
    "admin.notesVisualHint": "Tip: u karet lze samostatně sladit šířku borderu a radius; swipe vrstva používá správný vnitřní radius, takže rohy neprosvítají.",
    "admin.notesVisualResetSelected": "Reset prvku",
    "admin.notesVisualReset": "Vše výchozí",
    "admin.loading": "Načítám uživatele…",
    "admin.loadFailed": "Uživatele se nepodařilo načíst.",
    "admin.offline": "Admin Dashboard vyžaduje připojení k internetu.",
    "admin.noPending": "Žádné registrace nečekají na schválení.",
    "admin.noUsers": "Zatím nejsou žádní uživatelé.",
    "admin.registered": "Registrace",
    "admin.email": "E-mail",
    "admin.emailConfirmed": "potvrzen",
    "admin.emailUnconfirmed": "nepotvrzen",
    "admin.plan": "Plán",
    "admin.demoUntil": "Demo do",
    "admin.approveDemo": "Schválit Demo",
    "admin.reject": "Zamítnout",
    "admin.approveConfirm": "Schválit účet {email} jako Demo?",
    "admin.rejectConfirm": "Opravdu zamítnout registraci {email}?",
    "admin.approving": "Schvaluji účet…",
    "admin.rejecting": "Zamítám registraci…",
    "admin.approved": "Účet byl schválen jako Demo.",
    "admin.rejected": "Registrace byla zamítnuta.",
    "admin.actionFailed": "Akci se nepodařilo dokončit.",
    "admin.deleteUser": "Smazat účet",
    "admin.deleteUserConfirm": "Opravdu trvale smazat účet {email}? Tuto akci nelze vrátit zpět.",
    "admin.deletingUser": "Mažu účet…",
    "admin.userDeleted": "Účet byl trvale smazán.",
    "admin.deleteUserHasStorage": "Účet má ještě soubory ve Storage. Nejdřív je potřeba bezpečně odstranit přílohy.",
    "admin.deleteUserForbidden": "Tento účet nelze z Admin Dashboardu smazat.",
    "admin.status.pending": "Čeká",
    "admin.status.active": "Aktivní",
    "admin.status.rejected": "Zamítnut",
    "admin.status.suspended": "Pozastaven",
    "admin.plan.internal": "Interní",
    "admin.plan.full": "Full",
    "admin.plan.demo": "Demo",

    "modules.aria": "Hlavní části LubaNote",
    "modules.notes": "Poznámky",
    "storageScope.cloud": "Synchronizované",
    "storageScope.local": "Toto zařízení",
    "storageScope.menu": "Úložiště",
    "storageScope.choose": "Kam ukládat poznámky?",
    "storageScope.localTitle": "Pouze toto zařízení",
    "storageScope.localWarning": "Poznámky v tomto prostoru se nesynchronizují. Při ztrátě nebo vymazání zařízení je nelze obnovit z cloudu. Doporučujeme pravidelnou zálohu.",
    "storageScope.shareTitle": "Pouze toto zařízení",
    "storageScope.shareBlocked": "Sdílení vyžaduje synchronizované uložení. Tato poznámka zůstává pouze v tomto zařízení.",
    "modules.planner": "Plán",
    "modules.documents": "Dokumenty",
    "documents.eyebrow": "Dokumenty V1",
    "documents.title": "Dokumenty",
    "documents.addFile": "＋ Přidat soubor",
    "documents.folders": "Složky",
    "documents.newFolder": "Nová složka",
    "documents.files": "Soubory",
    "documents.allFiles": "Všechny soubory",
    "documents.searchPlaceholder": "Hledat…",
    "documents.searchAria": "Hledat soubory",
    "documents.clearSearch": "Vymazat hledání",
    "documents.filterAria": "Filtr dokumentů",
    "documents.filterAll": "Vše",
    "documents.trash": "Koš",
    "documents.folderFallback": "Složka",
    "documents.localAndroid": "Lokálně v tomto Android zařízení",
    "documents.localBrowser": "Lokálně v tomto prohlížeči",
    "documents.fileCount.one": "{count} soubor",
    "documents.fileCount.few": "{count} soubory",
    "documents.fileCount.many": "{count} souborů",
    "documents.fileCount.other": "{count} souborů",
    "plannerTabs.calendar": "Kalendář",
    "modules.reminders": "Připomínky",

    "sync.synced": "✓ Synchronizováno",
    "sync.syncing": "⟳ Synchronizuji…",
    "sync.pending": "⏳ Čeká na synchronizaci",
    "sync.localOnly": "📱 Pouze v zařízení",
    "sync.authExpired": "⚠ Přihlášení vypršelo",
    "sync.conflict": "⚠ Konflikt",

    "search.placeholder": "Hledat...",
    "search.aria": "Hledat poznámky",
    "search.clear": "Vymazat hledání",
    "search.view": "Změnit zobrazení karet",
    "search.menu": "Hlavní nabídka",
    "sort.labelNewest": "Nové karty: nahoře",
    "sort.labelOldest": "Nové karty: dole",
    "sort.title": "Umístění nových karet",
    "sort.newest": "Nové karty nahoru",
    "sort.oldest": "Nové karty dolů",
    "search.none": "Nenalezeny žádné poznámky.",

    "menu.manageTags": "Správa štítků",
    "menu.about": "O aplikaci",
    "menu.logout": "Odhlásit se",

    "filter.aria": "Filtr poznámek",
    "filter.all": "Vše",
    "filter.work": "Pracovní",
    "filter.private": "Soukromé",
    "filter.favorite": "Oblíbené poznámky",
    "filter.secret": "Tajné poznámky",
    "filter.finishSelection": "Ukončit výběr",

    "calendar.previousMonth": "Předchozí měsíc",
    "calendar.nextMonth": "Další měsíc",
    "calendar.selectedDay": "Vybraný den",
    "calendar.addSelected": "Přidat úkol na vybraný den",
    "calendar.back": "Zpět na kalendář",
    "calendar.addDay": "Přidat úkol na tento den",
    "calendar.week": "týden",
    "calendar.weekNumber": "Týden {value}",
    "weekday.mo": "Po",
    "weekday.tu": "Út",
    "weekday.we": "St",
    "weekday.th": "Čt",
    "weekday.fr": "Pá",
    "weekday.sa": "So",
    "weekday.su": "Ne",

    "recurring.title": "Opakující se",
    "recurring.back": "Zpět na připomínky",
    "recurring.show": "Zobrazit opakované úkoly",
    "recurring.none": "Žádné opakované úkoly.",
    "recurring.repeat": "Opakování",
    "recurring.next": "Příště: {value}",
    "recurring.noNext": "Série už nemá další termín.",

    "reminders.overdue": "Po termínu",
    "reminders.active": "Aktivní",
    "reminders.today": "Dnes",
    "reminders.none": "Žádné připomínky.",
    "reminders.noneOverdue": "Žádné připomínky po termínu.",
    "reminders.tomorrow": "Zítra",
    "reminders.later": "Později",
    "reminders.label": "Připomínka",
    "reminders.untitled": "Bez názvu",
    "reminders.close": "Zavřít",
    "reminders.tomorrow8": "Zítra 8:00",
    "reminders.date": "Datum",
    "reminders.time": "Čas",
    "reminders.selectDate": "Vybrat datum připomínky",
    "reminders.selectTime": "Vybrat čas připomínky",
    "reminders.done": "Hotovo",
    "reminders.delete": "Smazat",
    "reminders.openNote": "Otevřít poznámku",
    "reminders.turnOff": "Vypnout připomínku",

    "editor.find": "Hledat",
    "editor.findInNote": "Hledat v této poznámce",
    "editor.findPrevious": "Předchozí výsledek",
    "editor.findNext": "Další výsledek",
    "editor.findClose": "Zavřít hledání",
    "editor.openTools": "Otevřít editační nástroje",
    "editor.formatting": "Formátování poznámky",
    "editor.moreTools": "Další nástroje poznámky",
    "editor.undo": "Zpět",
    "editor.redo": "Znovu",
    "editor.bold": "Tučné písmo",
    "editor.italic": "Kurzíva",
    "editor.underline": "Podtržení",
    "editor.fontSize": "Velikost písma",
    "editor.textStyle": "Styl textu",
    "editor.textColor": "Barva textu",
    "editor.white": "Bílá barva textu",
    "editor.black": "Černá barva textu",
    "editor.align": "Zarovnání textu",
    "editor.alignLeft": "Zarovnat vlevo",
    "editor.alignCenter": "Zarovnat na střed",
    "editor.alignRight": "Zarovnat vpravo",
    "editor.insertImage": "Vložit obrázek",
    "editor.insertWebLink": "Vložit internetový odkaz",
    "editor.webLink": "Internetový odkaz",
    "editor.openDocument": "Otevřít dokument",
    "editor.saveAs": "Uložit jako",
    "editor.bullets": "Odrážkový seznam",
    "editor.date": "Datum",
    "editor.time": "Čas",
    "editor.selectDate": "Vybrat datum",
    "editor.selectTime": "Vybrat čas",
    "editor.pin": "Připnout poznámku",
    "editor.reminder": "Připomínka",
    "editor.backLink": "Zpět na předchozí propojenou poznámku",
    "editor.titleAria": "Název úkolu",
    "editor.titlePlaceholder": "Název úkolu",
    "editor.secret": "Tajná poznámka",
    "editor.tags": "Štítky",
    "editor.newTag": "Nový štítek",
    "editor.cancelNewTag": "Zrušit nový štítek",
    "editor.saveClose": "Uložit a zavřít",
    "editor.area": "Oblast poznámky",
    "editor.priority": "Priorita",
    "editor.color": "Barva",
    "editor.planSelection": "Naplánovat označený text",
    "editor.addTodo": "Přidat položku TODO",
    "editor.deleteNote": "Smazat poznámku",

    "backlinks.aria": "Zpětné odkazy na tuto poznámku",
    "backlinks.title": "Odkazy na tuto poznámku ({count})",
    "backlinks.none": "Žádné odkazy na tuto poznámku",

    "actions.save": "Uložit",
    "actions.discard": "Neukládat",
    "actions.ok": "OK",
    "status.done": "Hotovo",
    "secret.mainPassword": "Hlavní heslo",
    "secret.passwordAgain": "Heslo znovu",
    "secret.enterMain": "Zadej hlavní heslo.",
    "actions.term": "Termín",
    "actions.pin": "Připnout",
    "actions.delete": "Smazat",
    "actions.more": "Více akcí",
    "actions.cancel": "Zrušit",
    "actions.create": "Vytvořit",

    "message.notice": "Upozornění",
    "editor.notePlaceholder": "Napiš poznámku...",
    "tags.name": "Název štítku",
    "tags.add": "Přidat",
    "deleteNote.message": "Opravdu chceš tuto poznámku smazat?",
    "deleteNote.title": "Smazat poznámku?",

    "timePicker.title": "Vybrat čas",
    "timePicker.close": "Zavřít výběr času",
    "timePicker.clock": "Ciferník výběru času",
    "repeat.title": "Opakování",
    "repeat.aria": "Opakování úkolu",
    "repeat.no": "Ne",
    "repeat.daily": "Denně",
    "repeat.weekly": "Týdně",
    "repeat.twoWeeks": "2 týdny",
    "repeat.monthly": "Měsíčně",
    "repeat.none": "Neopakovat",

    "planner.plan": "Naplánovat",
    "planner.close": "Zavřít plánování",
    "planner.selectDate": "Vybrat datum plánovaného úkolu",
    "planner.selectTime": "Vybrat čas plánovaného úkolu",

    "sharing.settingsTitle": "Sdílení",
    "sharing.usernameLabel": "Uživatelské jméno",
    "sharing.usernameUnset": "Nastavit",
    "sharing.usernameModalTitle": "Uživatelské jméno pro sdílení",
    "sharing.usernameDescription": "Ostatní tě najdou pouze přes přesné @username. Tvůj e-mail se při sdílení nezobrazuje.",
    "sharing.usernamePlaceholder": "např. Lubomir",
    "sharing.usernameSave": "Uložit",
    "sharing.usernameCancel": "Zrušit",
    "sharing.usernameInvalid": "Použij 3–30 znaků: písmena, čísla, tečku, pomlčku nebo podtržítko.",
    "sharing.usernameTaken": "Toto @username už používá někdo jiný.",
    "sharing.usernameOffline": "Nastavení @username vyžaduje připojení k internetu.",
    "sharing.usernameSaving": "Ukládám…",
    "sharing.usernameSaveFailed": "Uživatelské jméno se nepodařilo uložit.",
    "sharing.usernameRequiredTitle": "Vytvoř @username",
    "sharing.usernameRequiredDescription": "Než začneš LubaNote používat, vytvoř si veřejné @username pro sdílení a chat. Ostatní tě najdou jen přes přesné @username; tvůj e-mail se nezobrazuje.",
    "sharing.usernameRequiredSave": "Vytvořit a pokračovat",
    "sharing.shareButton": "Sdílet",
    "sharing.invitationsAria": "Pozvánky ke sdílení",
    "sharing.shareModalTitle": "Sdílet poznámku",
    "sharing.shareModalDescription": "Pozvi uživatele zadáním přesného @username.",
    "sharing.shareInputPlaceholder": "např. LubaNoteDemo",
    "sharing.shareSend": "Poslat pozvánku",
    "sharing.shareSending": "Odesílám…",
    "sharing.shareSendSuccess": "Pozvánka byla odeslána.",
    "sharing.shareSendFailed": "Pozvánku se nepodařilo odeslat.",
    "sharing.shareInvalidUsername": "Zadej platné @username.",
    "sharing.shareOffline": "Sdílení vyžaduje připojení k internetu.",
    "sharing.shareUsernameMissing": "Nejdřív si v Nastavení nastav vlastní @username.",
    "sharing.shareUserNotFound": "Uživatel s tímto přesným @username nebyl nalezen.",
    "sharing.shareSelf": "Poznámku nemůžeš sdílet sám se sebou.",
    "sharing.shareAlreadyCollaborator": "Tento uživatel už poznámku sdílí.",
    "sharing.shareAlreadyPending": "Tomuto uživateli už čeká pozvánka.",
    "sharing.shareSecretBlocked": "Tajné poznámky se zatím sdílet nedají.",
    "sharing.shareNewNoteBlocked": "Nejdřív poznámku ulož, potom ji můžeš sdílet.",
    "sharing.collaboratorsTitle": "Spolupracovníci",
    "sharing.collaboratorsEmpty": "Zatím žádní spolupracovníci.",
    "sharing.pendingTitle": "Čekající pozvánky",
    "sharing.pendingEmpty": "Žádné čekající pozvánky.",
    "sharing.cancelInvitation": "Zrušit",
    "sharing.cancelFailed": "Pozvánku se nepodařilo zrušit.",
    "sharing.cancel": "Zrušit",
    "sharing.removeCollaborator": "Odebrat",
    "sharing.removeCollaboratorConfirm": "Odebrat {username} ze sdílení?",
    "sharing.removeCollaboratorSuccess": "Spolupracovník byl odebrán.",
    "sharing.removeCollaboratorFailed": "Spolupracovníka se nepodařilo odebrat.",
    "sharing.removeCollaboratorMissing": "Tento uživatel už poznámku nesdílí.",
    "sharing.manageNotOwner": "Tuto akci může provést pouze vlastník poznámky.",
    "sharing.manageModalUnavailable": "Potvrzovací okno se nepodařilo otevřít.",
    "sharing.leaveSharedNote": "Opustit sdílení",
    "sharing.leaveConfirm": "Opustit sdílení této poznámky?",
    "sharing.leaveSuccess": "Sdílení bylo opuštěno.",
    "sharing.leaveFailed": "Sdílení se nepodařilo opustit.",
    "sharing.ownerCannotLeave": "Vlastník nemůže sdílení opustit. Nejprve musí předat vlastnictví.",
    "sharing.ownerRole": "Vlastník",
    "sharing.editorRole": "Editor",
    "sharing.invitationsTitle": "Pozvánky ke sdílení",
    "sharing.invitationsEmpty": "Nemáš žádné čekající pozvánky.",
    "sharing.invitedBy": "Zve {username}",
    "sharing.accept": "Přijmout",
    "sharing.decline": "Odmítnout",
    "sharing.responding": "Zpracovávám…",
    "sharing.invitationAccepted": "Pozvánka byla přijata.",
    "sharing.invitationDeclined": "Pozvánka byla odmítnuta.",
    "sharing.invitationResponseFailed": "Pozvánku se nepodařilo zpracovat.",
    "sharing.refresh": "Obnovit",
    "sharing.close": "Zavřít",
    "sharing.loading": "Načítám…",
    "sharing.loadFailed": "Data sdílení se nepodařilo načíst.",
    "sharing.sharedUntitled": "Bez názvu",
    "sharing.sharedCardMeta": "Sdíleno · {owner}",
    "sharing.readOnlyTitle": "Sdílená poznámka",
    "sharing.readOnlyMeta": "{owner} · sdílená poznámka",
    "sharing.readOnlyTodos": "Úkoly",
    "sharing.editShared": "Upravit",
    "sharing.sharedEditorOffline": "Sdílenou poznámku lze upravovat jen online.",
    "sharing.sharedEditorBusy": "Poznámku právě upravuje {username}. Zatím ji můžeš pouze číst.",
    "sharing.sharedEditorOpening": "Otevírám sdílený editor…",
    "sharing.sharedEditorSaveFailed": "Sdílenou poznámku se nepodařilo bezpečně uložit. Editor zůstal otevřený.",
    "sharing.sharedEditorConflict": "Na serveru je novější verze poznámky. Editor zůstal otevřený; zavři jej bez uložení a otevři poznámku znovu.",
    "sharing.sharedEditorLockLost": "Editor lock už není platný. Sdílený editor byl bezpečně zavřen.",
    "sharing.sharedEditorSaved": "Sdílená poznámka byla uložena.",

    "chat.buttonAria": "Zprávy",
    "chat.contactsTitle": "Zprávy",
    "chat.contactsEmpty": "Zatím nemáš žádný chat kontakt. Kontakt vznikne po přijetí sdílení poznámky.",
    "chat.writeMessage": "Napsat zprávu",
    "chat.trustedContact": "Kontakt ze sdílení",
    "chat.ready": "Můžete si napsat",
    "chat.lastMessageAt": "Poslední zpráva {time}",
    "chat.messagePlaceholder": "Napsat zprávu…",
    "chat.send": "Odeslat",
    "chat.sending": "Odesílám…",
    "chat.sent": "Odesláno",
    "chat.read": "Přečteno",
    "chat.messagesEmpty": "Zatím tu nejsou žádné zprávy.",
    "chat.deletedPlaceholder": "Zpráva byla smazána",
    "chat.deleteMessage": "Smazat zprávu",
    "chat.deleteTitle": "Smazat zprávu?",
    "chat.deleteText": "Zpráva se smaže pro oba účastníky a zůstane po ní jen informace, že byla smazána.",
    "chat.deleteForBoth": "Smazat pro oba",
    "chat.deleting": "Mažu…",
    "chat.deleteFailed": "Zprávu se nepodařilo smazat.",
    "chat.sendFailed": "Zprávu se nepodařilo odeslat.",
    "chat.loadFailed": "Chat se nepodařilo načíst.",
    "chat.loadMessagesFailed": "Zprávy se nepodařilo načíst.",
    "chat.loading": "Načítám…",
    "chat.offline": "Chat vyžaduje připojení k internetu.",
    "chat.blocked": "Chat je blokovaný",
    "chat.contactNotFound": "Chat kontakt zatím není dostupný.",
    "chat.tooLong": "Zpráva je příliš dlouhá.",
    "chat.close": "Zavřít",
    "chat.back": "Zpět",
    "chat.cancel": "Zrušit",
    "chat.threadAria": "Chat",

    "settings.personalDictionary": "Můj slovník",
    "settings.languageLearning": "Výuka jazyků",
    "settings.manageDictionary": "Spravovat",
    "settings.openLearning": "Otevřít",
    "settings.wordsCount.one": "{count} slovo",
    "settings.wordsCount.few": "{count} slova",
    "settings.wordsCount.many": "{count} slov",
    "settings.wordsCount.other": "{count} slov",
    "settings.plannerReminderDefault": "Automaticky připomenout při plánování",
    "settings.enabled": "Zapnuto",
    "settings.disabled": "Vypnuto",
    "settings.planning": "Plánování",
    "settings.automaticReminder": "Automaticky připomenout",
    "settings.title": "Nastavení",
    "settings.close": "Zavřít nastavení",
    "settings.appearance": "Vzhled",
    "settings.fontSize": "Velikost písma",
    "settings.decreaseFont": "Zmenšit písmo",
    "settings.increaseFont": "Zvětšit písmo",
    "settings.theme": "Barevný motiv",
    "settings.iconStyle": "Styl ikon",
    "settings.keyboard": "Klávesnice editoru",
    "settings.keyboardTitle": "Klávesnice editoru",
    "settings.keyboardLuba": "LubaKeyboard (výchozí)",
    "settings.keyboardSystem": "Systémová",
    "settings.keyboardSystemLong": "Systémová klávesnice (Gboard / iOS)",
    "settings.reminders": "Připomínky",
    "settings.quickDelay": "Rychlé odložení",
    "settings.configure": "Nastavit",
    "settings.overdueRetention": "Mazat po termínu",
    "settings.overdueNever": "Nikdy",
    "settings.overdueDays": "{count} dní",
    "settings.overdueConfirm": "potvrdit",
    "settings.data": "Data",
    "settings.noteOpenPosition": "Po otevření poznámky",
    "settings.noteOpenStart": "Začátek",
    "settings.noteOpenEnd": "Konec",
    "settings.export": "Export zálohy",
    "settings.import": "Import zálohy",
    "settings.about": "O aplikaci",
    "settings.version": "Verze",
    "settings.appInfo": "Informace o aplikaci",
    "settings.open": "Otevřít",

    "theme.light": "Světlý",
    "theme.dark": "Tmavý",
    "icons.classic": "Původní ikony",
    "icons.svg": "SVG ikony",

    "about.close": "Zavřít informace o aplikaci",
    "about.description": "Poznámky, úkoly, plánování a připomínky na jednom místě.",
    "addNote": "Přidat poznámku",

    "tags.new": "Nový štítek",
    "tags.newSecret": "Nový tajný štítek",
    "tags.manage": "Správa štítků",
    "tags.closeManage": "Zavřít správu štítků",
    "tags.deleteTitle": "Smazat štítek?",

    "secret.saveSecret": "Uložit jako tajnou",
    "secret.saveNormal": "Uložit normálně",
    "secret.mode": "Tajný režim",
    "secret.close": "Zavřít tajný režim",
    "secret.fingerprint": "Odemknout otiskem",
    "secret.nextFingerprint": "🫆 Příště odemykat otiskem",
    "secret.thisDevice": "Jen na tomto zařízení",
    "secret.unlock": "Odemknout",
    "secret.tags": "Tajné štítky",
    "secret.createTag": "Vytvořit tajný štítek",
    "secret.disableFingerprint": "Zrušit odemykání otiskem",
    "secret.lock": "Zamknout tajný režim",

    "selection.cut": "Vyjmout",
    "selection.copy": "Kopírovat",
    "selection.paste": "Vložit",
    "selection.all": "Vše",
    "selection.dictionary": "Slovník",
    "selection.translate": "Přeložit",

    "noteLinks.noMatch": "Žádná odpovídající poznámka",
    "noteLinks.create": "+ Vytvořit poznámku „{value}“",
    "noteLinks.deleted": "⚠ Smazaná poznámka",
    "noteLinks.unavailable": "Cílová poznámka už není dostupná.",
    "noteLinks.previous": "Předchozí poznámka",
    "noteLinks.createFailed": "Novou propojenou poznámku se nepodařilo bezpečně vytvořit.",
    "noteLinks.ariaTarget": "Interní odkaz na poznámku {value}",
    "noteLinks.ariaMissing": "Interní odkaz na nedostupnou poznámku",
    "noteLinks.dialogTitle": "Interní odkaz",

    "trash.title": "Koš",
    "trash.secretTitle": "Tajný koš",
    "trash.close": "Zavřít Koš",
    "trash.autoDeleteInfo": "Poznámky se po 30 dnech automaticky smažou trvale.",
    "trash.empty": "Koš je prázdný.",
    "trash.untitled": "Bez názvu",
    "trash.noPreview": "Bez náhledu",
    "trash.moved": "V koši od",
    "trash.daysLeft": "Automatické smazání za {count} dní",
    "trash.restore": "Obnovit",
    "trash.deleteForever": "Smazat trvale",
    "trash.deleteForeverTitle": "Smazat trvale?",
    "trash.deleteConfirm": "Tato poznámka bude smazána trvale a nepůjde obnovit.",
    "trash.moveTitle": "Přesunout do koše?",
    "trash.moveMessage": "Poznámka se přesune do Koše a můžeš ji později obnovit.",
    "trash.moveAction": "Do koše",
    "trash.moveManyMessage": "Přesunout {count} vybraných poznámek do Koše?",
    "trash.movedMany": "Přesunuto do Koše: {count} poznámek",
    "trash.normalTab": "Normální",
    "trash.secretTab": "Tajné 🔒",
    "trash.typeTabsLabel": "Typ koše",
    "trash.selectAll": "Označit vše",
    "trash.clearSelection": "Zrušit označení",
    "trash.deleteSelected": "Trvale smazat ({count})",
    "trash.deleteManyNormalConfirm": "Opravdu chceš trvale smazat {count} položek z normálního koše? Tuto akci nepůjde vrátit.",
    "trash.deleteManySecretConfirm": "Opravdu chceš trvale smazat {count} položek z tajného koše? Tuto akci nepůjde vrátit.",
    "trash.bulkDeletePreparing": "Připravuji mazání…",
    "trash.bulkDeleting": "Mažu…",
    "trash.bulkDeleteProgress": "Mažu položky… {done} / {total}",
    "trash.bulkDeleteSyncing": "Synchronizuji změny…",
    "trash.bulkDeleteDoneAction": "Hotovo",
    "trash.bulkDeletePending": "Smazáno v zařízení. Synchronizace se dokončí automaticky.",
    "trash.bulkDeleteOffline": "Smazáno v zařízení. Synchronizace proběhne po připojení k internetu.",
    "trash.bulkDeleteFailed": "Smazání se nepodařilo bezpečně dokončit. Položky zůstaly v Koši.",
    "actions.apply": "Použít",
    "actions.close": "Zavřít",
    "actions.edit": "Upravit",
    "actions.next": "Další",
    "actions.open": "Otevřít",
    "actions.previous": "Předchozí",
    "actions.rename": "Přejmenovat",
    "actions.update": "Aktualizovat",
    "calendar.chooseMonth": "Vybrat měsíc",
    "choice.enterValue": "Zadejte hodnotu",
    "choice.maximum": "Maximum: {value}",
    "choice.minimum": "Minimum: {value}",
    "choice.selectOption": "Vyberte možnost",
    "choice.validNumber": "Zadej platné číslo.",
    "choice.value": "Hodnota",
    "datePicker.today": "Dnes",
    "dictionary.add": "Přidat",
    "dictionary.addOwn": "Přidat vlastní slovo…",
    "dictionary.empty": "Slovník je prázdný.",
    "dictionary.language": "Jazyk slovníku",
    "dictionary.search": "Hledat ve slovníku…",
    "documents.addDocument": "Přidat dokument",
    "documents.cannotOpenType": "Tento typ souboru zatím neumím otevřít.",
    "documents.chooseFileType": "Vyber typ souboru. Dokument zůstane jen v tomto zařízení.",
    "documents.closeDocument": "Zavřít dokument",
    "documents.contentUnsafe": "Obsah souboru není možné bezpečně načíst.",
    "documents.copyFailedLongPress": "Kopírování se nepodařilo. Zkus označit text dlouhým stiskem.",
    "documents.copySqlAria": "Kopírovat celý SQL skript",
    "documents.createFolderFailed": "Složku se nepodařilo vytvořit.",
    "documents.deleteEmptyFolder": "Složka „{name}“ je prázdná. Smaže se pouze složka.",
    "documents.deleteFolder": "Smazat složku",
    "documents.deleteFolderFailed": "Složku se nepodařilo bezpečně smazat.",
    "documents.deleteFolderTitle": "Smazat složku?",
    "documents.deleteFolderWithFiles": "Složka „{name}“ obsahuje {count}. Dokumenty se NESMAŽOU – přesunou se do „Všechny soubory“. Potom se smaže pouze složka.",
    "documents.deleteForeverFailed": "Dokument se nepodařilo trvale smazat.",
    "documents.deleteForeverMessage": "„{name}“ bude trvale odstraněn z tohoto zařízení. Tuto akci nelze vrátit zpět.",
    "documents.deleteForeverTitle": "Trvale smazat dokument?",
    "documents.docDescription": "lokální čtení textu starého formátu",
    "documents.docInvalid": "Soubor není platný Word DOC.",
    "documents.docNoReadableText": "DOC neobsahuje čitelný text nebo používá variantu, kterou viewer zatím neumí.",
    "documents.docNotLegacy": "Soubor není starý Word DOC (OLE/CFB).",
    "documents.docOldUnsupported": "Tento první DOC viewer podporuje Word 97–2003. Starší Word 6/95 zatím ne.",
    "documents.docOpenFailed": "DOC se nepodařilo otevřít. Podporovaný je Word 97–2003 a první verze zachovává hlavně čitelný text.",
    "documents.docReadOnly": "DOC · POUZE ČTENÍ",
    "documents.docTooLarge": "DOC je příliš velký. Maximální velikost je 24 MB.",
    "documents.docTooLarge24": "DOC je příliš velký. Maximální velikost je 24 MB.",
    "documents.docUnsupported": "Soubor není podporovaný Word DOC.",
    "documents.document": "Dokument",
    "documents.docxDescription": "otevře se jen ke čtení v Dokumentech",
    "documents.docxOpenFailed": "DOCX se nepodařilo otevřít. Soubor může být poškozený nebo používá prvek, který tento viewer ještě neumí.",
    "documents.docxReadOnly": "DOCX · POUZE ČTENÍ",
    "documents.docxTooLarge": "DOCX je příliš velký. Maximální velikost je 20 MB.",
    "documents.dragReorder": "Táhni pro změnu pořadí",
    "documents.dragToFolder": "Táhni na cílovou složku",
    "documents.dropInto": "Pustit do „{name}“",
    "documents.emptyDoc": "Zatím tu není žádný DOC",
    "documents.emptyDocument": "Zatím tu není žádný dokument",
    "documents.emptyDocx": "Zatím tu není žádný DOCX",
    "documents.emptyEpub": "Zatím tu není žádná kniha EPUB",
    "documents.emptyHint": "Přidej první PDF, DOCX, DOC, EPUB nebo SQL. SQL se otevře lokálně jen ke čtení.",
    "documents.emptyPdf": "Zatím tu není žádné PDF",
    "documents.emptySql": "Zatím tu není žádný SQL soubor",
    "documents.epubBook": "Elektronická kniha EPUB",
    "documents.epubDescription": "otevře se v lokálním LubaReaderu",
    "documents.epubEncryptedUnsupported": "Zašifrovaný EPUB není podporovaný.",
    "documents.epubInvalid": "Soubor není platný EPUB.",
    "documents.epubMissingPackage": "EPUB neobsahuje cestu k OPF balíčku.",
    "documents.epubNoChapters": "EPUB nemá čitelnou posloupnost kapitol.",
    "documents.epubOpenFailed": "EPUB se nepodařilo otevřít. Kniha může být poškozená nebo chráněná DRM.",
    "documents.epubReaderMissing": "EPUB čtečka není načtená.",
    "documents.epubTooLarge100": "EPUB je příliš velký. Maximální velikost je 100 MB.",
    "documents.epubWebViewUnsupported": "Tento WebView neumí rozbalit EPUB.",
    "documents.fileActions": "Akce souboru",
    "documents.fileActionsNamed": "Akce souboru {name}",
    "documents.fileName": "Název souboru",
    "documents.fileTooLarge20": "Soubor je příliš velký. Maximální velikost je 20 MB.",
    "documents.fileUnavailable": "Soubor už není dostupný.",
    "documents.folderActions": "Akce složky",
    "documents.folderActionsNamed": "Akce složky {name}",
    "documents.folderExists": "Složka „{name}“ už existuje.",
    "documents.folderLocalHint": "Složka je zatím pouze v tomto zařízení.",
    "documents.folderLocalMeta": "{count} · lokálně v zařízení",
    "documents.folderName": "Název složky",
    "documents.folderOrderFailed": "Pořadí složek se nepodařilo uložit.",
    "documents.inTrashTitle": "Dokument v koši",
    "documents.libraryLoadFailed": "Lokální knihovnu dokumentů se nepodařilo načíst.",
    "documents.loadFailed": "Dokument se nepodařilo načíst.",
    "documents.longPressMoveTitle": "Dlouhý stisk a táhni pro přesun",
    "documents.longPressReorderTitle": "Dlouhý stisk a táhni pro změnu pořadí",
    "documents.lubanoteNote": "LubaNote poznámka",
    "documents.metadataFallback": "Metadata LubaNote dokumentu nešla načíst, použiji běžný HTML import.",
    "documents.moveFailed": "Soubor se nepodařilo přesunout.",
    "documents.newDocument": "Nový dokument",
    "documents.noDisplayableContent": "Dokument neobsahuje zobrazitelný obsah.",
    "documents.noFolders": "Zatím nemáš žádnou složku.",
    "documents.noReadableText": "Dokument neobsahuje čitelný text.",
    "documents.nothingFound": "Nic jsme nenašli",
    "documents.nothingToCopy": "Není co kopírovat.",
    "documents.openDocument": "Otevřít dokument",
    "documents.openFailed": "Soubor se nepodařilo otevřít.",
    "documents.openNamed": "Otevřít {name}",
    "documents.openPdf": "Otevřít PDF",
    "documents.openingDoc": "Otevírám DOC…",
    "documents.openingDocument": "Otevírám dokument…",
    "documents.openingDocx": "Otevírám DOCX…",
    "documents.openingSql": "Otevírám SQL…",
    "documents.pdfDescription": "otevře se ve stávajícím PDF vieweru",
    "documents.pdfDisplayFailed": "PDF se nepodařilo zobrazit. Soubor může být poškozený nebo chráněný heslem.",
    "documents.pdfOpenFailed": "PDF se nepodařilo otevřít.",
    "documents.pdfTooLarge": "PDF je příliš velké. Maximální velikost je 100 MB.",
    "documents.pdfTooLargeWeb": "PDF je příliš velké. Maximální velikost ve webové verzi je 100 MB.",
    "documents.pdfViewerUnavailable": "PDF prohlížeč není dostupný.",
    "documents.renameDocument": "Přejmenovat dokument",
    "documents.renameDocumentHint": "Změní se pouze název v knihovně LubaNote. Obsah dokumentu zůstane beze změny.",
    "documents.renameFailed": "Dokument se nepodařilo přejmenovat.",
    "documents.renameFolder": "Přejmenovat složku",
    "documents.renameFolderFailed": "Složku se nepodařilo přejmenovat.",
    "documents.renameFolderHint": "Změní se pouze název složky. Dokumenty uvnitř zůstanou beze změny.",
    "documents.renameType": "Přejmenovat {type}",
    "documents.renameTypeHint": "Změní se pouze název v knihovně LubaNote. Obsah {type} zůstane beze změny.",
    "documents.restoreFailed": "Dokument se nepodařilo obnovit.",
    "documents.restoreFromTrash": "Obnovit z koše",
    "documents.saveAs": "Uložit jako",
    "documents.saveFailed": "Dokument se nepodařilo uložit.",
    "documents.saveHtml": "HTML – zachovat formátování",
    "documents.savePdf": "PDF – hotový dokument",
    "documents.saveTxt": "TXT – prostý text",
    "documents.searchEmpty": "Pro „{query}“ tu není žádný odpovídající dokument.",
    "documents.secretExternalOpenBlocked": "Externí dokumenty nejsou v Secret režimu dostupné. Secret zůstává oddělený.",
    "documents.secretExternalSaveBlocked": "Secret poznámku nelze ukládat do externího dokumentu. Secret režim zůstává oddělený.",
    "documents.secretExternalSaveBlockedShort": "Secret poznámku nelze ukládat do externího dokumentu.",
    "documents.sqlCopied": "Celý SQL skript byl zkopírován.",
    "documents.sqlDescription": "otevře se lokálně jen ke čtení jako zdrojový kód",
    "documents.sqlEmpty": "SQL soubor je prázdný.",
    "documents.sqlOpenFailed": "SQL se nepodařilo otevřít.",
    "documents.sqlReadFailed": "SQL se nepodařilo přečíst.",
    "documents.sqlReadOnly": "SQL · POUZE ČTENÍ",
    "documents.sqlScript": "SQL skript",
    "documents.sqlTooLarge": "SQL je příliš velký. Maximální velikost je 10 MB.",
    "documents.targetFolderUnavailable": "Cílová složka už není dostupná.",
    "documents.textDocument": "Textový dokument",
    "documents.trashEmpty": "Koš je prázdný",
    "documents.trashEmptyHint": "Dokumenty přesunuté do koše se zobrazí tady a půjdou obnovit nebo trvale smazat.",
    "documents.trashMoveFailed": "Dokument se nepodařilo přesunout do koše.",
    "documents.unsafeElement": "Dokument obsahuje prvek, který Core V2 neumí bezpečně importovat. Data nebyla změněna.",
    "documents.unsupportedType": "Tento typ souboru zatím není podporovaný. Vyber PDF, DOCX, DOC, EPUB nebo SQL.",
    "documents.wordReadOnly": "WORD · POUZE ČTENÍ",
    "editor.tasks": "Úkoly",
    "learning.addWord": "Přidat slovíčko",
    "learning.addWordLanguage": "Přidat slovíčko · {language}",
    "learning.addWordLanguageDot": "Přidat slovíčko · {language}",
    "learning.alreadyInDictionary": "Toto slovo už ve studijním slovníku máš.",
    "learning.changeLanguage": "Změnit jazyk",
    "learning.close": "Zavřít Výuku jazyků",
    "learning.closeTranslation": "Zavřít překlad",
    "learning.contextOptional": "Kontext (volitelné)",
    "learning.dictionary": "Slovník",
    "learning.dontKnow": "Neumím",
    "learning.duplicate": "Takové slovíčko už v tomto jazyku máš.",
    "learning.editWord": "Upravit slovíčko",
    "learning.empty": "Zatím tu nejsou žádná slovíčka.",
    "learning.enterOrSelectTerm": "Nejdřív napiš nebo vyber slovo či frázi.",
    "learning.errorDifferentLanguages": "Zdrojový a cílový jazyk musí být rozdílný.",
    "learning.errorOnlineRequired": "Překlad potřebuje připojení k internetu.",
    "learning.errorSelectTerm": "Vyber slovo nebo frázi.",
    "learning.errorShorterTerm": "Pro překlad vyber kratší slovo nebo frázi.",
    "learning.errorTranslateAuto": "Automatický překlad se nepodařilo získat. Překlad můžeš dopsat ručně.",
    "learning.errorTranslateUnavailable": "Online překlad teď není dostupný. Překlad můžeš dopsat ručně.",
    "learning.fillOrTranslate": "Doplň překlad nebo klepni na Přeložit.",
    "learning.fillTerm": "Doplň slovo nebo frázi.",
    "learning.fillTranslation": "Doplň překlad nebo klepni na Přeložit.",
    "learning.fillTranslationFirst": "Nejdřív doplň překlad.",
    "learning.know": "Umím",
    "learning.languageLearningLanguage": "Výuka jazyků · {language}",
    "learning.manualAdd": "Přidat slovo",
    "learning.noMistakesYet": "Zatím žádná chyba",
    "learning.onlineTranslationPrivacy": "Online překlad · {direction} · odesílá se jen vybraný výraz.",
    "learning.playPronunciation": "Přehrát výslovnost",
    "learning.playPronunciationLanguage": "Přehrát výslovnost · {language}",
    "learning.playPronunciationTerm": "Přehrát výslovnost slova",
    "learning.practiceEmpty": "Není co procvičovat.",
    "learning.practiceLanguage": "Procvičovat {language}",
    "learning.practiceLanguageAria": "Procvičovat jazyk {language}",
    "learning.practiceWrongOnly": "Procvičit jen slovíčka, která neumím",
    "learning.saveChanges": "Uložit změny",
    "learning.saveFailed": "Slovíčko se nepodařilo uložit.",
    "learning.saveToDictionary": "＋ Uložit do slovníku",
    "learning.savedToLearning": "Uloženo do Výuky jazyků.",
    "learning.search": "Hledat slovíčko…",
    "learning.showTranslation": "Ukázat překlad",
    "learning.sourceManual": "Ručně přidáno",
    "learning.sourceNote": "Poznámka",
    "learning.sourceOptional": "Zdroj (volitelné)",
    "learning.sourceSeed": "Testovací sada LubaNote",
    "learning.statsDue": "K procvičení",
    "learning.statsMastered": "Umím",
    "learning.statsReviews": "Opakování",
    "learning.statsSaved": "Uloženo",
    "learning.tabPractice": "Trénink",
    "learning.tabStats": "Statistiky",
    "learning.tabWords": "Slovíčka",
    "learning.termOrPhrase": "Slovo / fráze",
    "learning.trainingAllOk": "Trénink hotový 🥳 Všechna slovíčka byla OK.",
    "learning.translate": "Přeložit",
    "learning.translateFailed": "Překlad se nepodařilo získat.",
    "learning.translating": "Překládám…",
    "learning.translatingDirection": "Překládám · {direction}…",
    "learning.translation": "Překlad",
    "learning.translationDictionary": "Překlad a slovník",
    "learning.translationDirection": "Překlad · {direction}",
    "learning.translationEditable": "Překlad můžeš před uložením upravit.",
    "learning.translationPlaceholder": "Překlad…",
    "learning.updateInDictionary": "Aktualizovat ve slovníku",
    "learning.wordUpdated": "Slovíčko bylo aktualizováno.",
    "pdf.androidPickerHint": "Android otevře pouze výběr cílového souboru.",
    "pdf.chooseAndroidDestination": "Po potvrzení vybereš cílové místo v Androidu.",
    "pdf.chooseFileName": "Vyber název PDF souboru.",
    "pdf.chooseOtherLocation": "Vybrat jiné místo…",
    "pdf.close": "Zavřít PDF",
    "pdf.directCreateFailed": "Přímé PDF se nepodařilo vytvořit.",
    "pdf.directDownloadInfoHtml": "PDF se uloží bez dalšího okna do <strong>Stažené/LubaNote</strong>.",
    "pdf.directSaveHint": "Uloží se hned, bez dalšího systémového okna.",
    "pdf.directSaveNoPreview": "PDF se uloží přímo do Stažené/LubaNote bez systémového tiskového náhledu.",
    "pdf.directTest": "Přímé PDF TEST",
    "pdf.directTestHint": "Stejný Android tiskový engine, ale bez systémového náhledu.",
    "pdf.document": "PDF dokument",
    "pdf.doubleTapFullscreen": "2× tap → celá obrazovka",
    "pdf.doubleTapFullscreenHint": "Dvojtap přepne maximální zobrazení PDF.",
    "pdf.exitMaxView": "Opustit maximální zobrazení",
    "pdf.fitWidth": "Přizpůsobit na šířku",
    "pdf.fitWidthAria": "Přizpůsobit PDF na šířku",
    "pdf.fullscreen": "Celá obrazovka",
    "pdf.generatingTest": "Generuji PDF TEST…",
    "pdf.landscape": "Na šířku",
    "pdf.loading": "Načítám PDF…",
    "pdf.maxView": "Maximální zobrazení PDF",
    "pdf.nextPage": "Další strana",
    "pdf.pageDisplayFailed": "Stránku se nepodařilo zobrazit.",
    "pdf.portrait": "Na výšku",
    "pdf.preview": "Náhled",
    "pdf.previewFailed": "Náhled PDF se nepodařilo vytvořit.",
    "pdf.previewNamed": "Náhled • {name}",
    "pdf.previousPage": "Předchozí strana",
    "pdf.rememberZoom": "Zapamatovat poslední zoom",
    "pdf.rememberZoomHint": "Další PDF se otevře se stejným přiblížením.",
    "pdf.saveCopy": "Uložit kopii PDF",
    "pdf.saveFailed": "PDF se nepodařilo uložit.",
    "pdf.savePdf": "Uložit PDF",
    "pdf.savePreview": "Uložit náhled PDF",
    "pdf.savedChosenLocation": "PDF bylo uloženo do vybraného místa.",
    "pdf.savedDirect": "PDF bylo uloženo přímo do Stažené/LubaNote.",
    "pdf.savedDownloads": "PDF bylo uloženo do Stažené/LubaNote.",
    "pdf.settings": "Nastavení PDF",
    "pdf.settingsHint": "Platí pro PDF prohlížeč v LubaNote.",
    "pdf.systemPreviewShouldNotOpen": "Systémový náhled se nemá otevřít.",
    "pdf.viewer": "PDF prohlížeč",
    "pdf.whereSave": "Kam uložit PDF",
    "pdf.whereSaveShort": "Kam uložit",
    "pdf.zoomIn": "Zvětšit PDF",
    "pdf.zoomOut": "Zmenšit PDF",
    "planner.changeFutureFirst": "Nejdřív změň termín úkolu do budoucna.",
    "planner.futureRequired": "Termín musí být nastaven do budoucna.",
    "planner.reminderOff": "Připomenout: vypnuto",
    "planner.reminderOn": "Připomenout: zapnuto",
    "reader.addBookmarkHere": "Přidat záložku tady",
    "reader.addNote": "Přidat poznámku",
    "reader.airy": "Vzdušné",
    "reader.alignment": "Zarovnání",
    "reader.background": "Pozadí",
    "reader.book": "Kniha",
    "reader.bookmarks": "Záložky",
    "reader.bookmarksHighlights": "Záložky a označení",
    "reader.chapterEmpty": "Kapitola neobsahuje zobrazitelný text.",
    "reader.chapterNumber": "Kapitola {count}",
    "reader.closeBook": "Zavřít knihu",
    "reader.closeContents": "Zavřít obsah",
    "reader.closeSettings": "Zavřít nastavení",
    "reader.contents": "Obsah",
    "reader.contentsAria": "Obsah knihy",
    "reader.dark": "Tmavé",
    "reader.decreaseFont": "Zmenšit písmo",
    "reader.deleteBookmark": "Smazat záložku",
    "reader.deleteHighlight": "Smazat označení",
    "reader.editNote": "Upravit poznámku",
    "reader.font": "Písmo",
    "reader.fontSize": "Velikost písma",
    "reader.highlight": "Označení",
    "reader.highlightBlue": "Modré označení",
    "reader.highlightColor": "Barva označení",
    "reader.highlightGreen": "Zelené označení",
    "reader.highlightNote": "Poznámka k označení",
    "reader.highlightViolet": "Fialové označení",
    "reader.highlightYellow": "Žluté označení",
    "reader.highlights": "Označení",
    "reader.increaseFont": "Zvětšit písmo",
    "reader.justify": "Do bloku",
    "reader.left": "Vlevo",
    "reader.light": "Světlé",
    "reader.lineHeight": "Řádkování",
    "reader.margins": "Okraje textu",
    "reader.narrow": "Úzké",
    "reader.noBookmarks": "Zatím žádná záložka.",
    "reader.noHighlights": "Zatím žádné označení.",
    "reader.normal": "Normální",
    "reader.note": "Poznámka",
    "reader.notePlaceholder": "Napiš vlastní poznámku…",
    "reader.openingEpub": "Otevírám EPUB…",
    "reader.preparingBook": "Připravuji knihu…",
    "reader.preparingBookCount": "Připravuji knihu… {current} / {total}",
    "reader.removeHighlight": "Odstranit označení",
    "reader.resetDefaults": "Obnovit výchozí",
    "reader.sans": "Bezpatkové",
    "reader.sepia": "Sépie",
    "reader.serif": "Patkové",
    "reader.settings": "Nastavení čtení",
    "reader.smaller": "Menší",
    "reader.tapRemoveHighlight": "Klepnutím lze označení odstranit",
    "reader.wide": "Široké",
    "reader.withNote": "S poznámkou",
    "recurring.nextOccurrence": "Další výskyt",
    "recurring.nextScheduled": "Další opakování naplánováno",
    "recurring.previousOccurrence": "Předchozí výskyt",
    "recurring.ruleAt": "{rule} v {time}",
    "recurring.start": "Začátek opakování",
    "recurring.turnOff": "Vypnout opakování",
    "reminders.channelDescription": "Upozornění na naplánované poznámky a úkoly",
    "reminders.channelName": "Připomínky LubaNote",
    "reminders.deletePlannedTitle": "Smazat naplánovaný úkol?",
    "reminders.deletePlannerTaskTitle": "Smazat úkol z plánu?",
    "reminders.deleteReminderTitle": "Smazat připomínku?",
    "reminders.disabled": "Připomenutí vypnuto",
    "reminders.enabled": "Připomenutí zapnuto",
    "reminders.exactMessage": "Povol v Androidu přesné alarmy, jinak může systém upozornění zpozdit.",
    "reminders.exactTitle": "Přesné připomínky",
    "reminders.futureRequired": "Připomínka musí být nastavena do budoucna.",
    "reminders.noteCompleted": "Poznámka dokončena",
    "reminders.remind": "Připomenout",
    "reminders.removeNoteFromPlanTitle": "Odebrat poznámku z plánu?",
    "reminders.turnOffFailed": "Připomínku se nepodařilo bezpečně vypnout.",
    "reminders.turnOffShort": "Vypnout",
    "reminders.turningOff": "Vypínám připomínku…",
    "settings.choice1": "1. volba",
    "settings.choice2": "2. volba",
    "settings.choice3": "3. volba",
    "settings.choice4": "4. volba",
    "settings.snoozeHours": "{count} h",
    "settings.snoozeMinutes": "{count} min",
    "status.preparing": "Připravuji…",
    "status.saved": "Uloženo ✓",
    "status.savedCheck": "Uloženo ✓",
    "status.updated": "Aktualizováno ✓",
    "tags.duplicate": "Štítek s tímto názvem už existuje.",
    "tags.maxTwo": "Poznámka může mít maximálně 2 štítky. Nejdřív jeden odeber.",
    "timePicker.now": "Teď",
    "timePicker.set": "Nastavit",
    "secret.deviceUnlockTitle": "Odemkni toto zařízení",
    "secret.createMainTitle": "Vytvoř hlavní heslo",
    "secret.unlockContinue": "Odemknout a pokračovat",
    "secret.createContinue": "Vytvořit a pokračovat",
    "secret.deviceUnlockDescription": "Tento účet už hlavní heslo má. Zadej ho jednou, aby LubaNote bezpečně připravila Secret režim a E2E fotografie na tomto zařízení. Teprve potom se spustí synchronizace.",
    "secret.createMainDescription": "Než začneš LubaNote používat, vytvoř hlavní heslo. Chrání Secret režim a E2E šifrované fotografie. Není to přihlašovací heslo a LubaNote ho neukládá do cloudu.",
    "secret.unlockMode": "Odemknout tajný režim",
    "secret.createMainForNotes": "Vytvoř hlavní heslo pro tajné poznámky.",
    "secret.createPassword": "Vytvořit heslo",
    "tags.deleting": "Mažu štítek…",
    "tags.savingShort": "Ukládám…",
    "tags.saving": "Ukládám štítek…",
    "tags.moveUp": "Posunout štítky nahoru",
    "tags.moveDown": "Posunout štítky dolů",
    "tags.orderSaveFailed": "Pořadí štítků se nepodařilo uložit.",
    "tags.savingOrder": "Ukládám pořadí štítků…",
    "tags.colorAria": "Barva štítku {name}",
    "tags.setColorAria": "Nastavit barvu štítku na {color}",
    "tags.renameAria": "Přejmenovat štítek {name}",
    "tags.renaming": "Přejmenovávám štítek…",
    "tags.deleteAria": "Smazat štítek {name}",
    "tags.deleteConfirm": "Opravdu chceš smazat štítek „{name}“?",
    "tags.unlockFirst": "Nejdřív odemkni tajný režim.",
    "tags.newSaveFailed": "Nový štítek se nepodařilo uložit.",
    "tags.newLocalSaveFailed": "Nový lokální štítek se nepodařilo uložit.",
    "tags.newSaveFailedConnection": "Nový štítek se nepodařilo uložit. Zkontroluj připojení a zkus to znovu.",
    "tags.longPressWorks": "Dlouhý stisk funguje.",
    "tags.assignedMany": "Štítek „{name}“ přiřazen {count} kartám",
    "tags.color.cervena": "Červená",
    "tags.color.oranzova": "Oranžová",
    "tags.color.zluta": "Žlutá",
    "tags.color.zelena": "Zelená",
    "tags.color.tyrkysova": "Tyrkysová",
    "tags.color.modra": "Modrá",
    "tags.color.fialova": "Fialová",
    "tags.color.ruzova": "Růžová",
    "documents.addedType": "Přidáno: {type} „{name}“.",
    "documents.addFailed": "Dokument se nepodařilo přidat.",
    "documents.selectedNotType": "Vybraný soubor není {type}.",
    "documents.addFailedType": "{type} se nepodařilo přidat.",
    "documents.selectedNotLegacyDoc": "Vybraný soubor není starý Word DOC."
  },

  /*
   * Přesné věty používané dynamicky v JS.
   * Motor je umí přeložit přes prelozText().
   */
  texty: {}
});
