/* LubaNote – Slovenčina · PATCH 676A */
window.LubaNoteLanguagePacks = window.LubaNoteLanguagePacks || [];

(() => {
  const anglicky = window.LubaNoteLanguagePacks.find((balicek) => balicek.id === "en") || { preklady: {}, texty: {} };

  window.LubaNoteLanguagePacks.push({
    id: "sk",
    nazev: "Slovenčina",
    kratkyNazev: "SK",
    vlajka: "🇸🇰",
    locale: "sk-SK",

    // Nejdřív bezpečný anglický fallback; přeložené produkční UI ho přepisuje níže.
    preklady: {
      ...anglicky.preklady,
      "language.label": "Jazyk",
      "language.choose": "Vyber jazyk",
      "login.splashSubtitle": "Poznámky • Plán • Dokumenty",
      "login.loading": "LubaNote sa načítava",
      "login.title": "Prihlásenie",
      "login.registerTitle": "Registrácia",
      "login.modeSignIn": "Prihlásenie",
      "login.modeRegister": "Registrácia",
      "login.email": "E-mail",
      "login.password": "Heslo",
      "login.passwordAgain": "Heslo znova",
      "login.submit": "Prihlásiť sa",
      "login.registerSubmit": "Registrovať",
      "login.checkStatus": "Skontrolovať stav",
      "login.modeAria": "Prihlásenie alebo registrácia",
      "login.downloadMyData": "Stiahnuť moje dáta",
      "login.deleteMyData": "Zmazať moje dáta",
      "login.clearThisDevice": "Vyčistiť toto zariadenie",
      "login.deleteMyDataTitle": "Zmazať moje dáta?",
      "login.clearThisDeviceTitle": "Vyčistiť toto zariadenie?",
      "login.clearWithoutBackup": "Vyčistiť bez zálohy",
      "login.pendingTitle": "Účet čaká na schválenie",
      "login.pendingText": "Registrácia je dokončená. Po schválení účtu správcom sa LubaNote odomkne.",
      "login.rejectedTitle": "Registrácia nebola schválená",
      "login.rejectedText": "Tento účet nebol schválený. Ak ide o omyl, kontaktuj správcu LubaNote.",
      "login.suspendedTitle": "Účet je pozastavený",
      "login.suspendedText": "Prístup do LubaNote je dočasne pozastavený.",
      "login.unavailableTitle": "Účet nie je dostupný",
      "login.unavailableText": "Prístup k účtu sa nepodarilo overiť. Skús to znova.",
      "login.enterCredentials": "Zadaj e-mail aj heslo.",
      "login.enterRegistration": "Zadaj e-mail, heslo a heslo znova.",
      "login.passwordMismatch": "Heslá sa nezhodujú.",
      "login.passwordTooShort": "Heslo musí mať aspoň 8 znakov.",
      "login.registrationOnline": "Registrácia vyžaduje pripojenie k internetu.",
      "login.registering": "Registrujem…",
      "login.registrationCreated": "Registrácia bola vytvorená. Potvrď e-mail a potom sa prihlás.",
      "login.emailConfirmed": "E-mail bol potvrdený. Teraz sa môžeš prihlásiť.",
      "login.emailLinkInvalid": "Potvrdzovací odkaz už bol použitý alebo vypršal. Ak je e-mail potvrdený, prihlás sa.",
      "login.stillPending": "Účet stále čaká na schválenie.",
      "login.alreadyRegistered": "Tento e-mail je už zaregistrovaný. Použi Prihlásenie.",
      "login.registrationFailed": "Registrácia zlyhala. Skontroluj e-mail, heslo a pripojenie.",
      "login.registrationRateLimited": "Bolo odoslaných príliš veľa potvrdzovacích e-mailov. Skús registráciu neskôr.",
      "login.signingIn": "Prihlasujem…",
      "login.signInFailed": "Prihlásenie zlyhalo. Skontroluj e-mail, heslo a pripojenie.",
      "login.emailNotConfirmed": "E-mail ešte nie je potvrdený. Otvor potvrdzovací odkaz v e-maile a potom sa prihlás znova.",
      "login.accountCheckFailed": "Stav účtu sa nepodarilo overiť. Skús to znova.",
      "login.localOwnerMismatch": "Táto inštalácia obsahuje lokálne dáta iného účtu LubaNote. Z bezpečnostných dôvodov nemožno účty miešať v jednej inštalácii.",
      "login.demoExpiredTitle": "Demo skončilo",
      "login.demoExpiredText": "Tvoje Demo skončilo {date}. Všetky dáta zostávajú bezpečne uložené. Na ďalšie používanie aplikácie bude potrebný plný prístup LubaNote.",
      "login.fullExpiredTitle": "Plný prístup skončil",
      "login.fullExpiredText": "Tvoje dáta zostávajú bezpečne uložené. LubaNote sa znova odomkne po obnovení plného prístupu.",
      "account.demoUntil": "Demo do {date}",
      "limits.notesTitle": "Dosiahnutý limit poznámok",
      "limits.notesText": "Tvoj plán povoľuje najviac {limit} poznámok. Novú poznámku teraz nemožno bezpečne uložiť. Existujúce dáta zostávajú zachované.",
      "nav.quick": "Rýchla navigácia",
      "nav.tools": "Nástroje",
      "nav.home": "Domov",
      "nav.allNotes": "Všetky poznámky",
      "nav.favorites": "Obľúbené",
      "nav.tags": "Štítky",
      "nav.settings": "Nastavenia",
      "nav.backup": "Záloha a obnova",
      "modules.aria": "Hlavné sekcie LubaNote",
      "modules.notes": "Poznámky",
      "storageScope.cloud": "Synchronizované",
      "storageScope.local": "Toto zariadenie",
      "storageScope.menu": "Úložisko",
      "storageScope.choose": "Kde sa majú poznámky ukladať?",
      "storageScope.localTitle": "Len toto zariadenie",
      "storageScope.localWarning": "Poznámky v tomto priestore sa nesynchronizujú. Pri strate alebo vymazaní zariadenia ich nemožno obnoviť z cloudu. Odporúčame pravidelné zálohy.",
      "storageScope.shareTitle": "Len toto zariadenie",
      "storageScope.shareBlocked": "Zdieľanie vyžaduje synchronizované úložisko. Táto poznámka zostáva len v tomto zariadení.",
      "modules.planner": "Plán",
      "modules.documents": "Dokumenty",
      "documents.eyebrow": "Dokumenty V1",
      "documents.title": "Dokumenty",
      "documents.addFile": "＋ Pridať súbor",
      "documents.folders": "Priečinky",
      "documents.newFolder": "Nový priečinok",
      "documents.files": "Súbory",
      "documents.allFiles": "Všetky súbory",
      "documents.searchPlaceholder": "Hľadať…",
      "documents.searchAria": "Hľadať súbory",
      "documents.clearSearch": "Vymazať hľadanie",
      "documents.filterAria": "Filter dokumentov",
      "documents.filterAll": "Všetko",
      "documents.trash": "Kôš",
      "documents.folderFallback": "Priečinok",
      "documents.localAndroid": "Lokálne v tomto zariadení Android",
      "documents.localBrowser": "Lokálne v tomto prehliadači",
      "documents.fileCount.one": "{count} súbor",
      "documents.fileCount.few": "{count} súbory",
      "documents.fileCount.many": "{count} súborov",
      "documents.fileCount.other": "{count} súborov",
      "plannerTabs.calendar": "Kalendár",
      "modules.reminders": "Pripomienky",
      "sync.synced": "✓ Synchronizované",
      "sync.syncing": "⟳ Synchronizujem…",
      "sync.pending": "⏳ Čaká na synchronizáciu",
      "sync.localOnly": "📱 Len toto zariadenie",
      "sync.authExpired": "⚠ Prihlásenie vypršalo",
      "sync.conflict": "⚠ Konflikt",
      "search.placeholder": "Hľadať…",
      "search.aria": "Hľadať poznámky",
      "search.clear": "Vymazať hľadanie",
      "search.view": "Zmeniť rozloženie kariet",
      "search.menu": "Hlavné menu",
      "sort.labelNewest": "Nové karty: hore",
      "sort.labelOldest": "Nové karty: dole",
      "sort.title": "Umiestnenie novej karty",
      "sort.newest": "Nové karty hore",
      "sort.oldest": "Nové karty dole",
      "search.none": "Nenašli sa žiadne poznámky.",
      "menu.manageTags": "Spravovať štítky",
      "menu.about": "O aplikácii",
      "menu.logout": "Odhlásiť sa",
      "filter.aria": "Filtre poznámok",
      "filter.all": "Všetko",
      "filter.work": "Pracovné",
      "filter.private": "Súkromné",
      "filter.favorite": "Obľúbené poznámky",
      "filter.secret": "Tajné poznámky",
      "filter.finishSelection": "Dokončiť výber",
      "calendar.previousMonth": "Predchádzajúci mesiac",
      "calendar.nextMonth": "Nasledujúci mesiac",
      "calendar.selectedDay": "Vybraný deň",
      "calendar.addSelected": "Pridať úlohu na vybraný deň",
      "calendar.back": "Späť na kalendár",
      "calendar.addDay": "Pridať úlohu na tento deň",
      "calendar.week": "týždeň",
      "calendar.weekNumber": "Týždeň {value}",
      "weekday.mo": "Po",
      "weekday.tu": "Ut",
      "weekday.we": "St",
      "weekday.th": "Št",
      "weekday.fr": "Pi",
      "weekday.sa": "So",
      "weekday.su": "Ne",
      "recurring.title": "Opakovanie",
      "recurring.back": "Späť na pripomienky",
      "recurring.show": "Zobraziť opakované úlohy",
      "recurring.none": "Žiadne opakované úlohy.",
      "recurring.repeat": "Opakuje sa",
      "recurring.next": "Ďalej: {value}",
      "recurring.noNext": "Táto séria nemá ďalší výskyt.",
      "reminders.overdue": "Po termíne",
      "reminders.active": "Aktívne",
      "reminders.today": "Dnes",
      "reminders.none": "Žiadne pripomienky.",
      "reminders.noneOverdue": "Žiadne pripomienky po termíne.",
      "reminders.tomorrow": "Zajtra",
      "reminders.later": "Neskôr",
      "reminders.label": "Pripomienka",
      "reminders.untitled": "Bez názvu",
      "reminders.close": "Zavrieť",
      "reminders.tomorrow8": "Zajtra 8:00",
      "reminders.date": "Dátum",
      "reminders.time": "Čas",
      "reminders.selectDate": "Vybrať dátum pripomienky",
      "reminders.selectTime": "Vybrať čas pripomienky",
      "reminders.done": "Hotovo",
      "reminders.delete": "Zmazať",
      "reminders.openNote": "Otvoriť poznámku",
      "reminders.turnOff": "Vypnúť pripomienku",
      "editor.find": "Hľadať",
      "editor.findInNote": "Hľadať v tejto poznámke",
      "editor.findPrevious": "Predchádzajúci výsledok",
      "editor.findNext": "Nasledujúci výsledok",
      "editor.findClose": "Zavrieť hľadanie",
      "editor.openTools": "Otvoriť nástroje úprav",
      "editor.formatting": "Formátovanie poznámky",
      "editor.moreTools": "Ďalšie nástroje poznámky",
      "editor.undo": "Späť",
      "editor.redo": "Znova",
      "editor.bold": "Tučné",
      "editor.italic": "Kurzíva",
      "editor.underline": "Podčiarknuté",
      "editor.fontSize": "Veľkosť písma",
      "editor.textStyle": "Štýl textu",
      "editor.textColor": "Farba textu",
      "editor.white": "Biely text",
      "editor.black": "Čierny text",
      "editor.align": "Zarovnanie textu",
      "editor.alignLeft": "Zarovnať doľava",
      "editor.alignCenter": "Zarovnať na stred",
      "editor.alignRight": "Zarovnať doprava",
      "editor.insertImage": "Vložiť obrázok",
      "editor.insertWebLink": "Vložiť webový odkaz",
      "editor.webLink": "Webový odkaz",
      "editor.openDocument": "Otvoriť dokument",
      "editor.saveAs": "Uložiť ako",
      "editor.bullets": "Odrážkový zoznam",
      "editor.date": "Dátum",
      "editor.time": "Čas",
      "editor.selectDate": "Vybrať dátum",
      "editor.selectTime": "Vybrať čas",
      "editor.pin": "Pripnúť poznámku",
      "editor.reminder": "Pripomienka",
      "editor.backLink": "Späť na predchádzajúcu prepojenú poznámku",
      "editor.titleAria": "Názov poznámky",
      "editor.titlePlaceholder": "Názov poznámky",
      "editor.secret": "Tajná poznámka",
      "editor.tags": "Štítky",
      "editor.newTag": "Nový štítok",
      "editor.cancelNewTag": "Zrušiť nový štítok",
      "editor.saveClose": "Uložiť a zavrieť",
      "editor.area": "Oblasť poznámky",
      "editor.priority": "Priorita",
      "editor.color": "Farba",
      "editor.planSelection": "Naplánovať vybraný text",
      "editor.addTodo": "Pridať položku TODO",
      "editor.deleteNote": "Zmazať poznámku",
      "backlinks.aria": "Odkazy na túto poznámku",
      "backlinks.title": "Odkazy na túto poznámku ({count})",
      "backlinks.none": "Žiadne odkazy na túto poznámku",
      "actions.save": "Uložiť",
      "actions.discard": "Neukladať",
      "actions.ok": "OK",
      "status.done": "Hotovo",
      "secret.mainPassword": "Hlavné heslo",
      "secret.passwordAgain": "Heslo znova",
      "secret.enterMain": "Zadaj hlavné heslo.",
      "actions.term": "Termín",
      "actions.pin": "Pripnúť",
      "actions.delete": "Zmazať",
      "actions.more": "Ďalšie akcie",
      "actions.cancel": "Zrušiť",
      "actions.create": "Vytvoriť",
      "message.notice": "Upozornenie",
      "editor.notePlaceholder": "Napíš poznámku…",
      "tags.name": "Názov štítku",
      "tags.add": "Pridať",
      "deleteNote.message": "Naozaj chceš zmazať túto poznámku?",
      "deleteNote.title": "Zmazať poznámku?",
      "timePicker.title": "Vybrať čas",
      "timePicker.close": "Zavrieť výber času",
      "timePicker.clock": "Ciferník výberu času",
      "repeat.title": "Opakovanie",
      "repeat.aria": "Opakovanie úlohy",
      "repeat.no": "Nie",
      "repeat.daily": "Denne",
      "repeat.weekly": "Týždenne",
      "repeat.twoWeeks": "2 týždne",
      "repeat.monthly": "Mesačne",
      "repeat.none": "Neopakovať",
      "planner.plan": "Naplánovať",
      "planner.close": "Zavrieť plánovanie",
      "planner.selectDate": "Vybrať dátum plánovanej úlohy",
      "planner.selectTime": "Vybrať čas plánovanej úlohy",
      "sharing.settingsTitle": "Zdieľanie",
      "sharing.usernameLabel": "Používateľské meno",
      "sharing.usernameUnset": "Nastaviť",
      "sharing.usernameModalTitle": "Používateľské meno na zdieľanie",
      "sharing.usernameDescription": "Ostatní ťa nájdu iba podľa presného @používateľského mena. Tvoj e-mail sa pri zdieľaní nikdy nezobrazuje.",
      "sharing.usernamePlaceholder": "napr. Lubomir",
      "sharing.usernameSave": "Uložiť",
      "sharing.usernameCancel": "Zrušiť",
      "sharing.usernameInvalid": "Použi 3–30 znakov: písmená, čísla, bodku, pomlčku alebo podčiarkovník.",
      "sharing.usernameTaken": "Toto @používateľské meno už používa niekto iný.",
      "sharing.usernameOffline": "Nastavenie @používateľského mena vyžaduje internet.",
      "sharing.usernameSaving": "Ukladám…",
      "sharing.usernameSaveFailed": "Používateľské meno sa nepodarilo uložiť.",
      "sharing.usernameRequiredTitle": "Vytvor si @používateľské meno",
      "sharing.usernameRequiredDescription": "Pred používaním LubaNote si vytvor verejné @používateľské meno na zdieľanie a chat. Ostatní ťa nájdu iba podľa presného @používateľského mena; tvoj e-mail sa nezobrazuje.",
      "sharing.usernameRequiredSave": "Vytvoriť a pokračovať",
      "sharing.shareButton": "Zdieľať",
      "sharing.invitationsAria": "Pozvánky na zdieľanie",
      "sharing.shareModalTitle": "Zdieľať poznámku",
      "sharing.shareModalDescription": "Pozvi používateľa zadaním jeho presného @používateľského mena.",
      "sharing.shareInputPlaceholder": "napr. LubaNoteDemo",
      "sharing.shareSend": "Odoslať pozvánku",
      "sharing.shareSending": "Odosielam…",
      "sharing.shareSendSuccess": "Pozvánka bola odoslaná.",
      "sharing.shareSendFailed": "Pozvánku sa nepodarilo odoslať.",
      "sharing.shareInvalidUsername": "Zadaj platné @používateľské meno.",
      "sharing.shareOffline": "Zdieľanie vyžaduje internet.",
      "sharing.shareUsernameMissing": "Najprv si v Nastaveniach nastav vlastné @používateľské meno.",
      "sharing.shareUserNotFound": "Používateľ s týmto presným @používateľským menom sa nenašiel.",
      "sharing.shareSelf": "Poznámku nemôžeš zdieľať sám so sebou.",
      "sharing.shareAlreadyCollaborator": "Tento používateľ už na poznámke spolupracuje.",
      "sharing.shareAlreadyPending": "Pozvánka pre tohto používateľa už čaká.",
      "sharing.shareSecretBlocked": "Tajné poznámky zatiaľ nemožno zdieľať.",
      "sharing.shareNewNoteBlocked": "Najprv poznámku ulož, potom ju môžeš zdieľať.",
      "sharing.collaboratorsTitle": "Spolupracovníci",
      "sharing.collaboratorsEmpty": "Zatiaľ žiadni spolupracovníci.",
      "sharing.pendingTitle": "Čakajúce pozvánky",
      "sharing.pendingEmpty": "Žiadne čakajúce pozvánky.",
      "sharing.cancelInvitation": "Zrušiť",
      "sharing.cancelFailed": "Pozvánku sa nepodarilo zrušiť.",
      "sharing.cancel": "Zrušiť",
      "sharing.removeCollaborator": "Odstrániť",
      "sharing.removeCollaboratorConfirm": "Odstrániť {username} zo zdieľania?",
      "sharing.removeCollaboratorSuccess": "Spolupracovník bol odstránený.",
      "sharing.removeCollaboratorFailed": "Spolupracovníka sa nepodarilo odstrániť.",
      "sharing.removeCollaboratorMissing": "Tento používateľ už poznámku nezdieľa.",
      "sharing.manageNotOwner": "Túto akciu môže vykonať iba vlastník poznámky.",
      "sharing.manageModalUnavailable": "Potvrdzovací dialóg sa nepodarilo otvoriť.",
      "sharing.leaveSharedNote": "Opustiť zdieľanie",
      "sharing.leaveConfirm": "Opustiť zdieľanie tejto poznámky?",
      "sharing.leaveSuccess": "Zdieľanie bolo opustené.",
      "sharing.leaveFailed": "Zdieľanie sa nepodarilo opustiť.",
      "sharing.ownerCannotLeave": "Vlastník nemôže opustiť zdieľanie. Najprv odovzdaj vlastníctvo.",
      "sharing.ownerRole": "Vlastník",
      "sharing.editorRole": "Editor",
      "sharing.invitationsTitle": "Pozvánky na zdieľanie",
      "sharing.invitationsEmpty": "Nemáš žiadne čakajúce pozvánky.",
      "sharing.invitedBy": "Pozval používateľ {username}",
      "sharing.accept": "Prijať",
      "sharing.decline": "Odmietnuť",
      "sharing.responding": "Pracujem…",
      "sharing.invitationAccepted": "Pozvánka bola prijatá.",
      "sharing.invitationDeclined": "Pozvánka bola odmietnutá.",
      "sharing.invitationResponseFailed": "Pozvánku sa nepodarilo spracovať.",
      "sharing.refresh": "Obnoviť",
      "sharing.close": "Zavrieť",
      "sharing.loading": "Načítavam…",
      "sharing.loadFailed": "Dáta zdieľania sa nepodarilo načítať.",
      "sharing.sharedUntitled": "Bez názvu",
      "sharing.sharedCardMeta": "Zdieľané · {owner}",
      "sharing.readOnlyTitle": "Zdieľaná poznámka",
      "sharing.readOnlyMeta": "{owner} · zdieľaná poznámka",
      "sharing.readOnlyTodos": "Úlohy",
      "sharing.editShared": "Upraviť",
      "sharing.sharedEditorOffline": "Zdieľanú poznámku možno upravovať iba online.",
      "sharing.sharedEditorBusy": "{username} práve upravuje túto poznámku. Zatiaľ ju môžeš iba čítať.",
      "sharing.sharedEditorOpening": "Otváram zdieľaný editor…",
      "sharing.sharedEditorSaveFailed": "Zdieľanú poznámku sa nepodarilo bezpečne uložiť. Editor zostáva otvorený.",
      "sharing.sharedEditorConflict": "Na serveri existuje novšia verzia poznámky. Editor zostáva otvorený; zavri ho bez uloženia a poznámku otvor znova.",
      "sharing.sharedEditorLockLost": "Zámok editora už nie je platný. Zdieľaný editor bol bezpečne zatvorený.",
      "sharing.sharedEditorSaved": "Zdieľaná poznámka bola uložená.",
      "chat.buttonAria": "Správy",
      "chat.contactsTitle": "Správy",
      "chat.contactsEmpty": "Zatiaľ nemáš žiadne kontakty v chate. Kontakt vznikne po prijatí pozvánky na zdieľanie poznámky.",
      "chat.writeMessage": "Napísať správu",
      "chat.trustedContact": "Kontakt zo zdieľania",
      "chat.ready": "Môžete si písať",
      "chat.lastMessageAt": "Posledná správa {time}",
      "chat.messagePlaceholder": "Napíš správu…",
      "chat.send": "Odoslať",
      "chat.sending": "Odosielam…",
      "chat.sent": "Odoslané",
      "chat.read": "Prečítané",
      "chat.messagesEmpty": "Zatiaľ žiadne správy.",
      "chat.deletedPlaceholder": "Správa bola zmazaná",
      "chat.deleteMessage": "Zmazať správu",
      "chat.deleteTitle": "Zmazať správu?",
      "chat.deleteText": "Správa sa zmaže obom účastníkom a zostane iba zástupný text o zmazanej správe.",
      "chat.deleteForBoth": "Zmazať obom",
      "chat.deleting": "Mažem…",
      "chat.deleteFailed": "Správu sa nepodarilo zmazať.",
      "chat.sendFailed": "Správu sa nepodarilo odoslať.",
      "chat.loadFailed": "Chat sa nepodarilo načítať.",
      "chat.loadMessagesFailed": "Správy sa nepodarilo načítať.",
      "chat.loading": "Načítavam…",
      "chat.offline": "Chat vyžaduje internet.",
      "chat.blocked": "Chat je zablokovaný",
      "chat.contactNotFound": "Kontakt v chate zatiaľ nie je dostupný.",
      "chat.tooLong": "Správa je príliš dlhá.",
      "chat.close": "Zavrieť",
      "chat.back": "Späť",
      "chat.cancel": "Zrušiť",
      "chat.threadAria": "Chat",
      "settings.personalDictionary": "Môj slovník",
      "settings.languageLearning": "Výuka jazykov",
      "settings.manageDictionary": "Spravovať",
      "settings.openLearning": "Otvoriť",
      "settings.wordsCount.one": "{count} slovo",
      "settings.wordsCount.few": "{count} slová",
      "settings.wordsCount.many": "{count} slov",
      "settings.wordsCount.other": "{count} slov",
      "settings.plannerReminderDefault": "Automaticky pripomenúť pri plánovaní",
      "settings.enabled": "Zapnuté",
      "settings.disabled": "Vypnuté",
      "settings.planning": "Plánovanie",
      "settings.automaticReminder": "Automaticky pripomenúť",
      "settings.title": "Nastavenia",
      "settings.close": "Zavrieť nastavenia",
      "settings.appearance": "Vzhľad",
      "settings.fontSize": "Veľkosť písma",
      "settings.decreaseFont": "Zmenšiť písmo",
      "settings.increaseFont": "Zväčšiť písmo",
      "settings.theme": "Farebný motív",
      "settings.iconStyle": "Štýl ikon",
      "settings.keyboard": "Klávesnica editora",
      "settings.keyboardTitle": "Klávesnica editora",
      "settings.keyboardLuba": "LubaKeyboard (predvolená)",
      "settings.keyboardSystem": "Systémová",
      "settings.keyboardSystemLong": "Systémová klávesnica (Gboard / iOS)",
      "settings.reminders": "Pripomienky",
      "settings.quickDelay": "Rýchle odloženie",
      "settings.configure": "Nastaviť",
      "settings.overdueRetention": "Zmazať po termíne po",
      "settings.overdueNever": "Nikdy",
      "settings.overdueDays": "{count} dní",
      "settings.overdueConfirm": "potvrdiť",
      "settings.data": "Dáta",
      "settings.noteOpenPosition": "Pri otvorení poznámky",
      "settings.noteOpenStart": "Začiatok",
      "settings.noteOpenEnd": "Koniec",
      "settings.export": "Exportovať zálohu",
      "settings.import": "Importovať zálohu",
      "settings.about": "O aplikácii",
      "settings.version": "Verzia",
      "settings.appInfo": "Informácie o aplikácii",
      "settings.open": "Otvoriť",
      "theme.light": "Svetlý",
      "theme.dark": "Tmavý",
      "icons.classic": "Pôvodné ikony",
      "icons.svg": "SVG ikony",
      "about.close": "Zavrieť informácie o aplikácii",
      "about.description": "Poznámky, úlohy, plánovanie a pripomienky na jednom mieste.",
      "addNote": "Pridať poznámku",
      "tags.new": "Nový štítok",
      "tags.newSecret": "Nový tajný štítok",
      "tags.manage": "Spravovať štítky",
      "tags.closeManage": "Zavrieť správu štítkov",
      "tags.deleteTitle": "Zmazať štítok?",
      "secret.saveSecret": "Uložiť ako tajné",
      "secret.saveNormal": "Uložiť normálne",
      "secret.mode": "Tajný režim",
      "secret.close": "Zavrieť tajný režim",
      "secret.fingerprint": "Odomknúť odtlačkom prsta",
      "secret.nextFingerprint": "🫆 Nabudúce použiť odtlačok prsta",
      "secret.thisDevice": "Len na tomto zariadení",
      "secret.unlock": "Odomknúť",
      "secret.tags": "Tajné štítky",
      "secret.createTag": "Vytvoriť tajný štítok",
      "secret.disableFingerprint": "Vypnúť odomykanie odtlačkom",
      "secret.lock": "Zamknúť tajný režim",
      "selection.cut": "Vystrihnúť",
      "selection.copy": "Kopírovať",
      "selection.paste": "Vložiť",
      "selection.all": "Všetko",
      "selection.dictionary": "Slovník",
      "selection.translate": "Preložiť",
      "noteLinks.noMatch": "Žiadna zodpovedajúca poznámka",
      "noteLinks.create": "+ Vytvoriť poznámku „{value}“",
      "noteLinks.deleted": "⚠ Zmazaná poznámka",
      "noteLinks.unavailable": "Cieľová poznámka už nie je dostupná.",
      "noteLinks.previous": "Predchádzajúca poznámka",
      "noteLinks.createFailed": "Prepojenú poznámku sa nepodarilo bezpečne vytvoriť.",
      "noteLinks.ariaTarget": "Interný odkaz na poznámku {value}",
      "noteLinks.ariaMissing": "Interný odkaz na nedostupnú poznámku",
      "noteLinks.dialogTitle": "Interný odkaz",
      "trash.title": "Kôš",
      "trash.secretTitle": "Tajný kôš",
      "trash.close": "Zavrieť Kôš",
      "trash.autoDeleteInfo": "Poznámky sa po 30 dňoch automaticky natrvalo zmažú.",
      "trash.empty": "Kôš je prázdny.",
      "trash.untitled": "Bez názvu",
      "trash.noPreview": "Bez náhľadu",
      "trash.moved": "V koši od",
      "trash.daysLeft": "Trvalé zmazanie o {count} dní",
      "trash.restore": "Obnoviť",
      "trash.deleteForever": "Zmazať natrvalo",
      "trash.deleteForeverTitle": "Zmazať natrvalo?",
      "trash.deleteConfirm": "Táto poznámka bude natrvalo zmazaná a nebude ju možné obnoviť.",
      "trash.moveTitle": "Presunúť do Koša?",
      "trash.moveMessage": "Poznámka sa presunie do Koša a neskôr ju možno obnoviť.",
      "trash.moveAction": "Presunúť do Koša",
      "trash.moveManyMessage": "Presunúť {count} vybraných poznámok do Koša?",
      "trash.movedMany": "Presunuté do Koša: {count} poznámok",
      "trash.normalTab": "Normálne",
      "trash.secretTab": "Tajné 🔒",
      "trash.typeTabsLabel": "Typ Koša",
      "trash.selectAll": "Označiť všetko",
      "trash.clearSelection": "Zrušiť výber",
      "trash.deleteSelected": "Zmazať natrvalo ({count})",
      "trash.deleteManyNormalConfirm": "Natrvalo zmazať {count} položiek z bežného Koša? Túto akciu nemožno vrátiť späť.",
      "trash.deleteManySecretConfirm": "Natrvalo zmazať {count} položiek z Tajného koša? Túto akciu nemožno vrátiť späť.",
      "trash.bulkDeletePreparing": "Pripravujem mazanie…",
      "trash.bulkDeleting": "Mažem…",
      "trash.bulkDeleteProgress": "Mažem položky… {done} / {total}",
      "trash.bulkDeleteSyncing": "Synchronizujem zmeny…",
      "trash.bulkDeleteDoneAction": "Hotovo",
      "trash.bulkDeletePending": "Zmazané v tomto zariadení. Synchronizácia sa dokončí automaticky.",
      "trash.bulkDeleteOffline": "Zmazané v tomto zariadení. Synchronizácia prebehne po návrate online.",
      "trash.bulkDeleteFailed": "Mazanie sa nepodarilo bezpečne dokončiť. Položky zostali v Koši.",
      "actions.apply": "Použiť",
      "actions.close": "Zavrieť",
      "actions.edit": "Upraviť",
      "actions.next": "Ďalšie",
      "actions.open": "Otvoriť",
      "actions.previous": "Predchádzajúce",
      "actions.rename": "Premenovať",
      "actions.update": "Aktualizovať",
      "calendar.chooseMonth": "Vybrať mesiac",
      "choice.enterValue": "Zadajte hodnotu",
      "choice.maximum": "Maximum: {value}",
      "choice.minimum": "Minimum: {value}",
      "choice.selectOption": "Vyberte možnosť",
      "choice.validNumber": "Zadaj platné číslo.",
      "choice.value": "Hodnota",
      "datePicker.today": "Dnes",
      "dictionary.add": "Pridať",
      "dictionary.addOwn": "Pridať vlastné slovo…",
      "dictionary.empty": "Slovník je prázdny.",
      "dictionary.language": "Jazyk slovníka",
      "dictionary.search": "Hľadať v slovníku…",
      "documents.addDocument": "Pridať dokument",
      "documents.cannotOpenType": "Tento typ súboru zatiaľ neviem otvoriť.",
      "documents.chooseFileType": "Vyber typ súboru. Dokument zostane iba v tomto zariadení.",
      "documents.closeDocument": "Zavrieť dokument",
      "documents.contentUnsafe": "Obsah súboru nie je možné bezpečne načítať.",
      "documents.copyFailedLongPress": "Kopírovanie sa nepodarilo. Skús označiť text dlhým stlačením.",
      "documents.copySqlAria": "Kopírovať celý SQL skript",
      "documents.createFolderFailed": "Priečinok sa nepodarilo vytvoriť.",
      "documents.deleteEmptyFolder": "Priečinok „{name}“ je prázdny. Zmaže sa iba priečinok.",
      "documents.deleteFolder": "Zmazať priečinok",
      "documents.deleteFolderFailed": "Priečinok sa nepodarilo bezpečne zmazať.",
      "documents.deleteFolderTitle": "Zmazať priečinok?",
      "documents.deleteFolderWithFiles": "Priečinok „{name}“ obsahuje {count}. Dokumenty sa NEZMAŽÚ – presunú sa do „Všetky súbory“. Potom sa zmaže iba priečinok.",
      "documents.deleteForeverFailed": "Dokument sa nepodarilo trvalo zmazať.",
      "documents.deleteForeverMessage": "„{name}“ bude trvalo odstránený z tohto zariadenia. Túto akciu nie je možné vrátiť späť.",
      "documents.deleteForeverTitle": "Trvalo zmazať dokument?",
      "documents.docDescription": "lokálne čítanie textu starého formátu",
      "documents.docInvalid": "Súbor nie je platný Word DOC.",
      "documents.docNoReadableText": "DOC neobsahuje čitateľný text alebo používa variant, ktorý prehliadač zatiaľ nevie spracovať.",
      "documents.docNotLegacy": "Súbor nie je starý Word DOC (OLE/CFB).",
      "documents.docOldUnsupported": "Tento prvý DOC prehliadač podporuje Word 97–2003. Starší Word 6/95 zatiaľ nie.",
      "documents.docOpenFailed": "DOC sa nepodarilo otvoriť. Podporovaný je Word 97–2003 a prvá verzia zachováva hlavne čitateľný text.",
      "documents.docReadOnly": "DOC · IBA NA ČÍTANIE",
      "documents.docTooLarge": "DOC je príliš veľký. Maximálna veľkosť je 24 MB.",
      "documents.docTooLarge24": "DOC je príliš veľký. Maximálna veľkosť je 24 MB.",
      "documents.docUnsupported": "Súbor nie je podporovaný Word DOC.",
      "documents.document": "Dokument",
      "documents.docxDescription": "otvorí sa iba na čítanie v Dokumentoch",
      "documents.docxOpenFailed": "DOCX sa nepodarilo otvoriť. Súbor môže byť poškodený alebo používa prvok, ktorý tento prehliadač ešte nevie spracovať.",
      "documents.docxReadOnly": "DOCX · IBA NA ČÍTANIE",
      "documents.docxTooLarge": "DOCX je príliš veľký. Maximálna veľkosť je 20 MB.",
      "documents.dragReorder": "Potiahni pre zmenu poradia",
      "documents.dragToFolder": "Potiahni do cieľového priečinka",
      "documents.dropInto": "Pustiť do „{name}“",
      "documents.emptyDoc": "Zatiaľ tu nie je žiadny DOC",
      "documents.emptyDocument": "Zatiaľ tu nie je žiadny dokument",
      "documents.emptyDocx": "Zatiaľ tu nie je žiadny DOCX",
      "documents.emptyEpub": "Zatiaľ tu nie je žiadna kniha EPUB",
      "documents.emptyHint": "Pridaj prvý PDF, DOCX, DOC, EPUB alebo SQL. SQL sa otvorí lokálne iba na čítanie.",
      "documents.emptyPdf": "Zatiaľ tu nie je žiadne PDF",
      "documents.emptySql": "Zatiaľ tu nie je žiadny SQL súbor",
      "documents.epubBook": "Elektronická kniha EPUB",
      "documents.epubDescription": "otvorí sa v lokálnom LubaReaderi",
      "documents.epubEncryptedUnsupported": "Zašifrovaný EPUB nie je podporovaný.",
      "documents.epubInvalid": "Súbor nie je platný EPUB.",
      "documents.epubMissingPackage": "EPUB neobsahuje cestu k balíčku OPF.",
      "documents.epubNoChapters": "EPUB nemá čitateľnú postupnosť kapitol.",
      "documents.epubOpenFailed": "EPUB sa nepodarilo otvoriť. Kniha môže byť poškodená alebo chránená DRM.",
      "documents.epubReaderMissing": "EPUB čítačka nie je načítaná.",
      "documents.epubTooLarge100": "EPUB je príliš veľký. Maximálna veľkosť je 100 MB.",
      "documents.epubWebViewUnsupported": "Tento WebView nevie rozbaliť EPUB.",
      "documents.fileActions": "Akcie súboru",
      "documents.fileActionsNamed": "Akcie súboru {name}",
      "documents.fileName": "Názov súboru",
      "documents.fileTooLarge20": "Súbor je príliš veľký. Maximálna veľkosť je 20 MB.",
      "documents.fileUnavailable": "Súbor už nie je dostupný.",
      "documents.folderActions": "Akcie priečinka",
      "documents.folderActionsNamed": "Akcie priečinka {name}",
      "documents.folderExists": "Priečinok „{name}“ už existuje.",
      "documents.folderLocalHint": "Priečinok je zatiaľ iba v tomto zariadení.",
      "documents.folderLocalMeta": "{count} · lokálne v zariadení",
      "documents.folderName": "Názov priečinka",
      "documents.folderOrderFailed": "Poradie priečinkov sa nepodarilo uložiť.",
      "documents.inTrashTitle": "Dokument v koši",
      "documents.libraryLoadFailed": "Lokálnu knižnicu dokumentov sa nepodarilo načítať.",
      "documents.loadFailed": "Dokument sa nepodarilo načítať.",
      "documents.longPressMoveTitle": "Dlho stlač a potiahni pre presun",
      "documents.longPressReorderTitle": "Dlho stlač a potiahni pre zmenu poradia",
      "documents.lubanoteNote": "LubaNote poznámka",
      "documents.metadataFallback": "Metadáta dokumentu LubaNote sa nepodarilo načítať, použijem bežný HTML import.",
      "documents.moveFailed": "Súbor sa nepodarilo presunúť.",
      "documents.newDocument": "Nový dokument",
      "documents.noDisplayableContent": "Dokument neobsahuje zobraziteľný obsah.",
      "documents.noFolders": "Zatiaľ nemáš žiadny priečinok.",
      "documents.noReadableText": "Dokument neobsahuje čitateľný text.",
      "documents.nothingFound": "Nič sme nenašli",
      "documents.nothingToCopy": "Nie je čo kopírovať.",
      "documents.openDocument": "Otvoriť dokument",
      "documents.openFailed": "Súbor sa nepodarilo otvoriť.",
      "documents.openNamed": "Otvoriť {name}",
      "documents.openPdf": "Otvoriť PDF",
      "documents.openingDoc": "Otváram DOC…",
      "documents.openingDocument": "Otváram dokument…",
      "documents.openingDocx": "Otváram DOCX…",
      "documents.openingSql": "Otváram SQL…",
      "documents.pdfDescription": "otvorí sa v existujúcom PDF prehliadači",
      "documents.pdfDisplayFailed": "PDF sa nepodarilo zobraziť. Súbor môže byť poškodený alebo chránený heslom.",
      "documents.pdfOpenFailed": "PDF sa nepodarilo otvoriť.",
      "documents.pdfTooLarge": "PDF je príliš veľké. Maximálna veľkosť je 100 MB.",
      "documents.pdfTooLargeWeb": "PDF je príliš veľké. Maximálna veľkosť vo webovej verzii je 100 MB.",
      "documents.pdfViewerUnavailable": "PDF prehliadač nie je dostupný.",
      "documents.renameDocument": "Premenovať dokument",
      "documents.renameDocumentHint": "Zmení sa iba názov v knižnici LubaNote. Obsah dokumentu zostane bez zmeny.",
      "documents.renameFailed": "Dokument sa nepodarilo premenovať.",
      "documents.renameFolder": "Premenovať priečinok",
      "documents.renameFolderFailed": "Priečinok sa nepodarilo premenovať.",
      "documents.renameFolderHint": "Zmení sa iba názov priečinka. Dokumenty vnútri zostanú bez zmeny.",
      "documents.renameType": "Premenovať {type}",
      "documents.renameTypeHint": "Zmení sa iba názov v knižnici LubaNote. Obsah {type} zostane bez zmeny.",
      "documents.restoreFailed": "Dokument sa nepodarilo obnoviť.",
      "documents.restoreFromTrash": "Obnoviť z koša",
      "documents.saveAs": "Uložiť ako",
      "documents.saveFailed": "Dokument sa nepodarilo uložiť.",
      "documents.saveHtml": "HTML – zachovať formátovanie",
      "documents.savePdf": "PDF – hotový dokument",
      "documents.saveTxt": "TXT – obyčajný text",
      "documents.searchEmpty": "Pre „{query}“ tu nie je žiadny zodpovedajúci dokument.",
      "documents.secretExternalOpenBlocked": "Externé dokumenty nie sú v režime Secret dostupné. Secret zostáva oddelený.",
      "documents.secretExternalSaveBlocked": "Secret poznámku nie je možné ukladať do externého dokumentu. Režim Secret zostáva oddelený.",
      "documents.secretExternalSaveBlockedShort": "Secret poznámku nie je možné ukladať do externého dokumentu.",
      "documents.sqlCopied": "Celý SQL skript bol skopírovaný.",
      "documents.sqlDescription": "otvorí sa lokálne iba na čítanie ako zdrojový kód",
      "documents.sqlEmpty": "SQL súbor je prázdny.",
      "documents.sqlOpenFailed": "SQL sa nepodarilo otvoriť.",
      "documents.sqlReadFailed": "SQL sa nepodarilo prečítať.",
      "documents.sqlReadOnly": "SQL · IBA NA ČÍTANIE",
      "documents.sqlScript": "SQL skript",
      "documents.sqlTooLarge": "SQL je príliš veľký. Maximálna veľkosť je 10 MB.",
      "documents.targetFolderUnavailable": "Cieľový priečinok už nie je dostupný.",
      "documents.textDocument": "Textový dokument",
      "documents.trashEmpty": "Kôš je prázdny",
      "documents.trashEmptyHint": "Dokumenty presunuté do koša sa zobrazia tu a bude ich možné obnoviť alebo trvalo zmazať.",
      "documents.trashMoveFailed": "Dokument sa nepodarilo presunúť do koša.",
      "documents.unsafeElement": "Dokument obsahuje prvok, ktorý Core V2 nevie bezpečne importovať. Údaje neboli zmenené.",
      "documents.unsupportedType": "Tento typ súboru zatiaľ nie je podporovaný. Vyber PDF, DOCX, DOC, EPUB alebo SQL.",
      "documents.wordReadOnly": "WORD · IBA NA ČÍTANIE",
      "editor.tasks": "Úlohy",
      "learning.addWord": "Pridať slovíčko",
      "learning.addWordLanguage": "Pridať slovíčko · {language}",
      "learning.addWordLanguageDot": "Pridať slovíčko · {language}",
      "learning.alreadyInDictionary": "Toto slovo už v študijnom slovníku máš.",
      "learning.changeLanguage": "Zmeniť jazyk",
      "learning.close": "Zavrieť Výuku jazykov",
      "learning.closeTranslation": "Zavrieť preklad",
      "learning.contextOptional": "Kontext (voliteľné)",
      "learning.dictionary": "Slovník",
      "learning.dontKnow": "Neviem",
      "learning.duplicate": "Takéto slovíčko už v tomto jazyku máš.",
      "learning.editWord": "Upraviť slovíčko",
      "learning.empty": "Zatiaľ tu nie sú žiadne slovíčka.",
      "learning.enterOrSelectTerm": "Najprv napíš alebo vyber slovo či frázu.",
      "learning.errorDifferentLanguages": "Zdrojový a cieľový jazyk musia byť rozdielne.",
      "learning.errorOnlineRequired": "Preklad potrebuje pripojenie k internetu.",
      "learning.errorSelectTerm": "Vyber slovo alebo frázu.",
      "learning.errorShorterTerm": "Na preklad vyber kratšie slovo alebo frázu.",
      "learning.errorTranslateAuto": "Automatický preklad sa nepodarilo získať. Preklad môžeš dopísať ručne.",
      "learning.errorTranslateUnavailable": "Online preklad teraz nie je dostupný. Preklad môžeš dopísať ručne.",
      "learning.fillOrTranslate": "Doplň preklad alebo klepni na Preložiť.",
      "learning.fillTerm": "Doplň slovo alebo frázu.",
      "learning.fillTranslation": "Doplň preklad alebo klepni na Preložiť.",
      "learning.fillTranslationFirst": "Najprv doplň preklad.",
      "learning.know": "Viem",
      "learning.languageLearningLanguage": "Výuka jazykov · {language}",
      "learning.manualAdd": "Pridať slovo",
      "learning.noMistakesYet": "Zatiaľ žiadna chyba",
      "learning.onlineTranslationPrivacy": "Online preklad · {direction} · odosiela sa iba vybraný výraz.",
      "learning.playPronunciation": "Prehrať výslovnosť",
      "learning.playPronunciationLanguage": "Prehrať výslovnosť · {language}",
      "learning.playPronunciationTerm": "Prehrať výslovnosť slova",
      "learning.practiceEmpty": "Nie je čo precvičovať.",
      "learning.practiceLanguage": "Precvičovať {language}",
      "learning.practiceLanguageAria": "Precvičovať jazyk {language}",
      "learning.practiceWrongOnly": "Precvičiť iba slovíčka, ktoré neviem",
      "learning.saveChanges": "Uložiť zmeny",
      "learning.saveFailed": "Slovíčko sa nepodarilo uložiť.",
      "learning.saveToDictionary": "＋ Uložiť do slovníka",
      "learning.savedToLearning": "Uložené do Výuky jazykov.",
      "learning.search": "Hľadať slovíčko…",
      "learning.showTranslation": "Ukázať preklad",
      "learning.sourceManual": "Ručne pridané",
      "learning.sourceNote": "Poznámka",
      "learning.sourceOptional": "Zdroj (voliteľné)",
      "learning.sourceSeed": "Testovacia sada LubaNote",
      "learning.statsDue": "Na precvičenie",
      "learning.statsMastered": "Viem",
      "learning.statsReviews": "Opakovania",
      "learning.statsSaved": "Uložené",
      "learning.tabPractice": "Tréning",
      "learning.tabStats": "Štatistiky",
      "learning.tabWords": "Slovíčka",
      "learning.termOrPhrase": "Slovo / fráza",
      "learning.trainingAllOk": "Tréning hotový 🥳 Všetky slovíčka boli OK.",
      "learning.translate": "Preložiť",
      "learning.translateFailed": "Preklad sa nepodarilo získať.",
      "learning.translating": "Prekladám…",
      "learning.translatingDirection": "Prekladám · {direction}…",
      "learning.translation": "Preklad",
      "learning.translationDictionary": "Preklad a slovník",
      "learning.translationDirection": "Preklad · {direction}",
      "learning.translationEditable": "Preklad môžeš pred uložením upraviť.",
      "learning.translationPlaceholder": "Preklad…",
      "learning.updateInDictionary": "Aktualizovať v slovníku",
      "learning.wordUpdated": "Slovíčko bolo aktualizované.",
      "pdf.androidPickerHint": "Android otvorí iba výber cieľového súboru.",
      "pdf.chooseAndroidDestination": "Po potvrdení vyberieš cieľové miesto v Androide.",
      "pdf.chooseFileName": "Vyber názov PDF súboru.",
      "pdf.chooseOtherLocation": "Vybrať iné miesto…",
      "pdf.close": "Zavrieť PDF",
      "pdf.directCreateFailed": "Priame PDF sa nepodarilo vytvoriť.",
      "pdf.directDownloadInfoHtml": "PDF sa uloží bez ďalšieho okna do <strong>Stiahnuté/LubaNote</strong>.",
      "pdf.directSaveHint": "Uloží sa hneď, bez ďalšieho systémového okna.",
      "pdf.directSaveNoPreview": "PDF sa uloží priamo do Stiahnuté/LubaNote bez systémového náhľadu tlače.",
      "pdf.directTest": "Priame PDF TEST",
      "pdf.directTestHint": "Rovnaký tlačový engine Androidu, ale bez systémového náhľadu.",
      "pdf.document": "PDF dokument",
      "pdf.doubleTapFullscreen": "2× ťuknutie → celá obrazovka",
      "pdf.doubleTapFullscreenHint": "Dvojité ťuknutie prepne maximálne zobrazenie PDF.",
      "pdf.exitMaxView": "Opustiť maximálne zobrazenie",
      "pdf.fitWidth": "Prispôsobiť na šírku",
      "pdf.fitWidthAria": "Prispôsobiť PDF na šírku",
      "pdf.fullscreen": "Celá obrazovka",
      "pdf.generatingTest": "Generujem PDF TEST…",
      "pdf.landscape": "Na šírku",
      "pdf.loading": "Načítavam PDF…",
      "pdf.maxView": "Maximálne zobrazenie PDF",
      "pdf.nextPage": "Ďalšia strana",
      "pdf.pageDisplayFailed": "Stranu sa nepodarilo zobraziť.",
      "pdf.portrait": "Na výšku",
      "pdf.preview": "Náhľad",
      "pdf.previewFailed": "Náhľad PDF sa nepodarilo vytvoriť.",
      "pdf.previewNamed": "Náhľad • {name}",
      "pdf.previousPage": "Predchádzajúca strana",
      "pdf.rememberZoom": "Zapamätať posledný zoom",
      "pdf.rememberZoomHint": "Ďalšie PDF sa otvorí s rovnakým priblížením.",
      "pdf.saveCopy": "Uložiť kópiu PDF",
      "pdf.saveFailed": "PDF sa nepodarilo uložiť.",
      "pdf.savePdf": "Uložiť PDF",
      "pdf.savePreview": "Uložiť náhľad PDF",
      "pdf.savedChosenLocation": "PDF bolo uložené do vybraného miesta.",
      "pdf.savedDirect": "PDF bolo uložené priamo do Stiahnuté/LubaNote.",
      "pdf.savedDownloads": "PDF bolo uložené do Stiahnuté/LubaNote.",
      "pdf.settings": "Nastavenia PDF",
      "pdf.settingsHint": "Platí pre PDF prehliadač v LubaNote.",
      "pdf.systemPreviewShouldNotOpen": "Systémový náhľad sa nemá otvoriť.",
      "pdf.viewer": "PDF prehliadač",
      "pdf.whereSave": "Kam uložiť PDF",
      "pdf.whereSaveShort": "Kam uložiť",
      "pdf.zoomIn": "Zväčšiť PDF",
      "pdf.zoomOut": "Zmenšiť PDF",
      "planner.changeFutureFirst": "Najprv zmeň termín úlohy do budúcnosti.",
      "planner.futureRequired": "Termín musí byť nastavený do budúcnosti.",
      "planner.reminderOff": "Pripomenúť: vypnuté",
      "planner.reminderOn": "Pripomenúť: zapnuté",
      "reader.addBookmarkHere": "Pridať záložku sem",
      "reader.addNote": "Pridať poznámku",
      "reader.airy": "Vzdušné",
      "reader.alignment": "Zarovnanie",
      "reader.background": "Pozadie",
      "reader.book": "Kniha",
      "reader.bookmarks": "Záložky",
      "reader.bookmarksHighlights": "Záložky a označenia",
      "reader.chapterEmpty": "Kapitola neobsahuje zobraziteľný text.",
      "reader.chapterNumber": "Kapitola {count}",
      "reader.closeBook": "Zavrieť knihu",
      "reader.closeContents": "Zavrieť obsah",
      "reader.closeSettings": "Zavrieť nastavenia",
      "reader.contents": "Obsah",
      "reader.contentsAria": "Obsah knihy",
      "reader.dark": "Tmavé",
      "reader.decreaseFont": "Zmenšiť písmo",
      "reader.deleteBookmark": "Zmazať záložku",
      "reader.deleteHighlight": "Zmazať označenie",
      "reader.editNote": "Upraviť poznámku",
      "reader.font": "Písmo",
      "reader.fontSize": "Veľkosť písma",
      "reader.highlight": "Označenie",
      "reader.highlightBlue": "Modré označenie",
      "reader.highlightColor": "Farba označenia",
      "reader.highlightGreen": "Zelené označenie",
      "reader.highlightNote": "Poznámka k označeniu",
      "reader.highlightViolet": "Fialové označenie",
      "reader.highlightYellow": "Žlté označenie",
      "reader.highlights": "Označenia",
      "reader.increaseFont": "Zväčšiť písmo",
      "reader.justify": "Do bloku",
      "reader.left": "Vľavo",
      "reader.light": "Svetlé",
      "reader.lineHeight": "Riadkovanie",
      "reader.margins": "Okraje textu",
      "reader.narrow": "Úzke",
      "reader.noBookmarks": "Zatiaľ žiadna záložka.",
      "reader.noHighlights": "Zatiaľ žiadne označenie.",
      "reader.normal": "Normálne",
      "reader.note": "Poznámka",
      "reader.notePlaceholder": "Napíš vlastnú poznámku…",
      "reader.openingEpub": "Otváram EPUB…",
      "reader.preparingBook": "Pripravujem knihu…",
      "reader.preparingBookCount": "Pripravujem knihu… {current} / {total}",
      "reader.removeHighlight": "Odstrániť označenie",
      "reader.resetDefaults": "Obnoviť predvolené",
      "reader.sans": "Bezpatkové",
      "reader.sepia": "Sépia",
      "reader.serif": "Pätkové",
      "reader.settings": "Nastavenia čítania",
      "reader.smaller": "Menšie",
      "reader.tapRemoveHighlight": "Klepnutím možno označenie odstrániť",
      "reader.wide": "Široké",
      "reader.withNote": "S poznámkou",
      "recurring.nextOccurrence": "Ďalší výskyt",
      "recurring.nextScheduled": "Ďalšie opakovanie naplánované",
      "recurring.previousOccurrence": "Predchádzajúci výskyt",
      "recurring.ruleAt": "{rule} o {time}",
      "recurring.start": "Začiatok opakovania",
      "recurring.turnOff": "Vypnúť opakovanie",
      "reminders.channelDescription": "Upozornenia na naplánované poznámky a úlohy",
      "reminders.channelName": "Pripomienky LubaNote",
      "reminders.deletePlannedTitle": "Zmazať naplánovanú úlohu?",
      "reminders.deletePlannerTaskTitle": "Zmazať úlohu z plánu?",
      "reminders.deleteReminderTitle": "Zmazať pripomienku?",
      "reminders.disabled": "Pripomenutie vypnuté",
      "reminders.enabled": "Pripomenutie zapnuté",
      "reminders.exactMessage": "Povoľ v Androide presné alarmy, inak môže systém upozornenie oneskoriť.",
      "reminders.exactTitle": "Presné pripomienky",
      "reminders.futureRequired": "Pripomienka musí byť nastavená do budúcnosti.",
      "reminders.noteCompleted": "Poznámka dokončená",
      "reminders.remind": "Pripomenúť",
      "reminders.removeNoteFromPlanTitle": "Odobrať poznámku z plánu?",
      "reminders.turnOffFailed": "Pripomienku sa nepodarilo bezpečne vypnúť.",
      "reminders.turnOffShort": "Vypnúť",
      "reminders.turningOff": "Vypínam pripomienku…",
      "settings.choice1": "1. voľba",
      "settings.choice2": "2. voľba",
      "settings.choice3": "3. voľba",
      "settings.choice4": "4. voľba",
      "settings.snoozeHours": "{count} h",
      "settings.snoozeMinutes": "{count} min",
      "status.preparing": "Pripravujem…",
      "status.saved": "Uložené ✓",
      "status.savedCheck": "Uložené ✓",
      "status.updated": "Aktualizované ✓",
      "tags.duplicate": "Štítok s týmto názvom už existuje.",
      "tags.maxTwo": "Poznámka môže mať maximálne 2 štítky. Najprv jeden odober.",
      "timePicker.now": "Teraz",
      "timePicker.set": "Nastaviť",
      "secret.deviceUnlockTitle": "Odomkni toto zariadenie",
      "secret.createMainTitle": "Vytvor hlavné heslo",
      "secret.unlockContinue": "Odomknúť a pokračovať",
      "secret.createContinue": "Vytvoriť a pokračovať",
      "secret.deviceUnlockDescription": "Tento účet už hlavné heslo má. Zadaj ho raz, aby LubaNote bezpečne pripravila Secret režim a E2E fotografie na tomto zariadení. Až potom sa spustí synchronizácia.",
      "secret.createMainDescription": "Skôr než začneš LubaNote používať, vytvor hlavné heslo. Chráni Secret režim a E2E šifrované fotografie. Nie je to prihlasovacie heslo a LubaNote ho neukladá do cloudu.",
      "secret.unlockMode": "Odomknúť tajný režim",
      "secret.createMainForNotes": "Vytvor hlavné heslo pre tajné poznámky.",
      "secret.createPassword": "Vytvoriť heslo",
      "tags.deleting": "Mažem štítok…",
      "tags.savingShort": "Ukladám…",
      "tags.saving": "Ukladám štítok…",
      "tags.moveUp": "Posunúť štítky nahor",
      "tags.moveDown": "Posunúť štítky nadol",
      "tags.orderSaveFailed": "Poradie štítkov sa nepodarilo uložiť.",
      "tags.savingOrder": "Ukladám poradie štítkov…",
      "tags.colorAria": "Farba štítku {name}",
      "tags.setColorAria": "Nastaviť farbu štítku na {color}",
      "tags.renameAria": "Premenovať štítok {name}",
      "tags.renaming": "Premenúvam štítok…",
      "tags.deleteAria": "Zmazať štítok {name}",
      "tags.deleteConfirm": "Naozaj chceš zmazať štítok „{name}“?",
      "tags.unlockFirst": "Najprv odomkni tajný režim.",
      "tags.newSaveFailed": "Nový štítok sa nepodarilo uložiť.",
      "tags.newLocalSaveFailed": "Nový lokálny štítok sa nepodarilo uložiť.",
      "tags.newSaveFailedConnection": "Nový štítok sa nepodarilo uložiť. Skontroluj pripojenie a skús to znova.",
      "tags.longPressWorks": "Dlhé podržanie funguje.",
      "tags.assignedMany": "Štítok „{name}“ priradený {count} kartám",
      "tags.color.cervena": "Červená",
      "tags.color.oranzova": "Oranžová",
      "tags.color.zluta": "Žltá",
      "tags.color.zelena": "Zelená",
      "tags.color.tyrkysova": "Tyrkysová",
      "tags.color.modra": "Modrá",
      "tags.color.fialova": "Fialová",
      "tags.color.ruzova": "Ružová",
      "documents.addedType": "Pridané: {type} „{name}“.",
      "documents.addFailed": "Dokument sa nepodarilo pridať.",
      "documents.selectedNotType": "Vybraný súbor nie je {type}.",
      "documents.addFailedType": "{type} sa nepodarilo pridať.",
      "documents.selectedNotLegacyDoc": "Vybraný súbor nie je starý Word DOC."
    },

    texty: {
      ...anglicky.texty,
      "Přihlášení vypršelo. Přihlas se znovu, aby mohla pokračovat synchronizace. Tvoje lokální data zůstala zachována.": "Prihlásenie vypršalo. Prihlás sa znova, aby synchronizácia mohla pokračovať. Tvoje lokálne dáta zostali zachované.",
      "Nepodařilo se připojit k synchronizaci. Zkus to znovu po připojení k internetu.": "Nepodarilo sa pripojiť k synchronizácii. Skús to znova po pripojení k internetu.",
      "Ověření přihlášení se nepodařilo.": "Overenie prihlásenia zlyhalo.",
      "První přihlášení vyžaduje připojení k internetu.": "Prvé prihlásenie vyžaduje pripojenie k internetu.",
      "Ověřuji přihlášení…": "Overujem prihlásenie…",
      "Vyplň e-mail i heslo.": "Vyplň e-mail aj heslo.",
      "Přihlášení vyžaduje internet. Lokální aplikace funguje offline až po prvním úspěšném přihlášení.": "Prihlásenie vyžaduje internet. Lokálna aplikácia funguje offline až po prvom úspešnom prihlásení.",
      "Přihlašuji…": "Prihlasujem…",
      "Přihlášení se nezdařilo. Zkontroluj e-mail, heslo a připojení.": "Prihlásenie zlyhalo. Skontroluj e-mail, heslo a pripojenie.",
      "Světlý": "Svetlý",
      "Tmavý": "Tmavý",
      "Původní ikony": "Pôvodné ikony",
      "SVG ikony": "SVG ikony",
      "Pracovní": "Pracovné",
      "Soukromé": "Súkromné",
      "Bez názvu": "Bez názvu",
      "Žádná odpovídající poznámka": "Žiadna zodpovedajúca poznámka",
      "⚠ Smazaná poznámka": "⚠ Zmazaná poznámka",
      "Tajný režim": "Tajný režim",
      "Tajný režim byl zamčen.": "Tajný režim bol zamknutý.",
      "Tajný režim byl automaticky zamčen.": "Tajný režim bol automaticky zamknutý.",
      "Tajný režim je odemčený.": "Tajný režim je odomknutý.",
      "Tajný režim se nepodařilo odemknout.": "Tajný režim sa nepodarilo odomknúť.",
      "Tajný režim není odemčený.": "Tajný režim nie je odomknutý.",
      "Zadej hlavní heslo.": "Zadaj hlavné heslo.",
      "Hlavní heslo není správné.": "Hlavné heslo nie je správne.",
      "Hlavní heslo musí mít alespoň 8 znaků.": "Hlavné heslo musí mať aspoň 8 znakov.",
      "Hlavní heslo se nepodařilo vytvořit.": "Hlavné heslo sa nepodarilo vytvoriť.",
      "Upozornění": "Upozornenie",
      "Nový štítek": "Nový štítok",
      "Název štítku": "Názov štítku",
      "+ Nový štítek": "+ Nový štítok",
      "Nový tajný štítek": "Nový tajný štítok",
    }
  });
})();
