/* LubaNote – English */
window.LubaNoteLanguagePacks =
  window.LubaNoteLanguagePacks || [];

window.LubaNoteLanguagePacks.push({
  id: "en",
  nazev: "English",
  kratkyNazev: "EN",
  vlajka: "🇬🇧",
  locale: "en-GB",

  preklady: {
    "language.label": "Language",
    "language.choose": "Choose language",

    "login.loading": "LubaNote is loading",
    "login.title": "Sign in",
    "login.registerTitle": "Register",
    "login.modeSignIn": "Sign in",
    "login.modeRegister": "Register",
    "login.email": "Email",
    "login.password": "Password",
    "login.passwordAgain": "Password again",
    "login.submit": "Sign in",
    "login.registerSubmit": "Register",
    "login.checkStatus": "Check status",
    "login.pendingTitle": "Account waiting for approval",
    "login.pendingText": "Registration is complete. LubaNote will unlock after an administrator approves the account.",
    "login.rejectedTitle": "Registration was not approved",
    "login.rejectedText": "This account was not approved. If this is a mistake, contact the LubaNote administrator.",
    "login.suspendedTitle": "Account suspended",
    "login.suspendedText": "Access to LubaNote is temporarily suspended.",
    "login.unavailableTitle": "Account unavailable",
    "login.unavailableText": "Account access could not be verified. Try checking again.",
    "login.enterCredentials": "Enter both email and password.",
    "login.enterRegistration": "Enter email, password and password again.",
    "login.passwordMismatch": "The passwords do not match.",
    "login.passwordTooShort": "Password must be at least 8 characters long.",
    "login.registrationOnline": "Registration requires an internet connection.",
    "login.registering": "Registering…",
    "login.registrationCreated": "Registration was created. Confirm your email, then sign in.",
    "login.alreadyRegistered": "This email is already registered. Use Sign in.",
    "login.registrationFailed": "Registration failed. Check your email, password and connection.",
    "login.signingIn": "Signing in…",
    "login.signInFailed": "Sign-in failed. Check your email, password and connection.",
    "login.emailNotConfirmed": "Your email has not been confirmed yet. Open the confirmation link in your email, then sign in again.",
    "login.accountCheckFailed": "Account status could not be verified. Try again.",
    "login.localOwnerMismatch": "This installation contains local data from another LubaNote account. For safety, accounts cannot be mixed in the same installation.",

    "nav.quick": "Quick navigation",
    "nav.tools": "Tools",
    "nav.home": "Home",
    "nav.allNotes": "All notes",
    "nav.favorites": "Favorites",
    "nav.tags": "Tags",
    "nav.settings": "Settings",
    "nav.backup": "Backup and restore",
    "admin.menu": "Admin Dashboard",
    "admin.title": "Admin Dashboard",
    "admin.pending": "Pending",
    "admin.active": "Active",
    "admin.demo": "Demo",
    "admin.pendingTab": "Pending",
    "admin.allTab": "All",
    "admin.refresh": "Refresh users",
    "admin.close": "Close Admin Dashboard",
    "admin.loading": "Loading users…",
    "admin.loadFailed": "Users could not be loaded.",
    "admin.offline": "Admin Dashboard requires an internet connection.",
    "admin.noPending": "No registrations are waiting for approval.",
    "admin.noUsers": "There are no users yet.",
    "admin.registered": "Registered",
    "admin.email": "Email",
    "admin.emailConfirmed": "confirmed",
    "admin.emailUnconfirmed": "not confirmed",
    "admin.plan": "Plan",
    "admin.demoUntil": "Demo until",
    "admin.approveDemo": "Approve Demo",
    "admin.reject": "Reject",
    "admin.approveConfirm": "Approve {email} as Demo?",
    "admin.rejectConfirm": "Reject the registration for {email}?",
    "admin.approving": "Approving account…",
    "admin.rejecting": "Rejecting registration…",
    "admin.approved": "The account was approved as Demo.",
    "admin.rejected": "The registration was rejected.",
    "admin.actionFailed": "The action could not be completed.",
    "admin.status.pending": "Pending",
    "admin.status.active": "Active",
    "admin.status.rejected": "Rejected",
    "admin.status.suspended": "Suspended",
    "admin.plan.internal": "Internal",
    "admin.plan.full": "Full",
    "admin.plan.demo": "Demo",

    "modules.aria": "Main LubaNote sections",
    "modules.notes": "Notes",
    "modules.planner": "Planner",
    "modules.reminders": "Reminders",

    "sync.synced": "✓ Synced",
    "sync.syncing": "⟳ Syncing…",
    "sync.authExpired": "⚠ Sign-in expired",
    "sync.conflict": "⚠ Conflict",

    "search.placeholder": "Search notes...",
    "search.aria": "Search notes",
    "search.clear": "Clear search",
    "search.view": "Change card layout",
    "search.menu": "Main menu",
    "sort.labelNewest": "Sort: newest first",
    "sort.labelOldest": "Sort: oldest first",
    "sort.title": "Card sorting",
    "sort.newest": "Newest first",
    "sort.oldest": "Oldest first",
    "search.none": "No notes found.",

    "menu.manageTags": "Manage tags",
    "menu.about": "About",
    "menu.logout": "Sign out",

    "filter.aria": "Note filters",
    "filter.all": "All",
    "filter.work": "Work",
    "filter.private": "Private",
    "filter.favorite": "Favorite notes",
    "filter.secret": "Secret notes",
    "filter.finishSelection": "Finish selection",

    "calendar.previousMonth": "Previous month",
    "calendar.nextMonth": "Next month",
    "calendar.selectedDay": "Selected day",
    "calendar.addSelected": "Add task for selected day",
    "calendar.back": "Back to calendar",
    "calendar.addDay": "Add task for this day",
    "calendar.week": "week",
    "calendar.weekNumber": "Week {value}",
    "weekday.mo": "Mon",
    "weekday.tu": "Tue",
    "weekday.we": "Wed",
    "weekday.th": "Thu",
    "weekday.fr": "Fri",
    "weekday.sa": "Sat",
    "weekday.su": "Sun",

    "recurring.title": "Recurring",
    "recurring.back": "Back to reminders",
    "recurring.show": "Show recurring tasks",
    "recurring.none": "No recurring tasks.",
    "recurring.repeat": "Repeats",
    "recurring.next": "Next: {value}",
    "recurring.noNext": "This series has no next occurrence.",

    "reminders.overdue": "Overdue",
    "reminders.active": "Active",
    "reminders.today": "Today",
    "reminders.none": "No reminders.",
    "reminders.noneOverdue": "No overdue reminders.",
    "reminders.tomorrow": "Tomorrow",
    "reminders.later": "Later",
    "reminders.label": "Reminder",
    "reminders.untitled": "Untitled",
    "reminders.close": "Close",
    "reminders.tomorrow8": "Tomorrow 8:00",
    "reminders.date": "Date",
    "reminders.time": "Time",
    "reminders.selectDate": "Choose reminder date",
    "reminders.selectTime": "Choose reminder time",
    "reminders.done": "Done",
    "reminders.delete": "Delete",
    "reminders.openNote": "Open note",
    "reminders.turnOff": "Turn off reminder",

    "editor.openTools": "Open editing tools",
    "editor.formatting": "Note formatting",
    "editor.moreTools": "More note tools",
    "editor.undo": "Undo",
    "editor.redo": "Redo",
    "editor.bold": "Bold",
    "editor.italic": "Italic",
    "editor.underline": "Underline",
    "editor.fontSize": "Font size",
    "editor.textStyle": "Text style",
    "editor.textColor": "Text color",
    "editor.white": "White text",
    "editor.black": "Black text",
    "editor.align": "Text alignment",
    "editor.alignLeft": "Align left",
    "editor.alignCenter": "Align center",
    "editor.alignRight": "Align right",
    "editor.insertImage": "Insert image",
    "editor.insertWebLink": "Insert web link",
    "editor.webLink": "Web link",
    "editor.openDocument": "Open document",
    "editor.saveAs": "Save as",
    "editor.bullets": "Bullet list",
    "editor.date": "Date",
    "editor.time": "Time",
    "editor.selectDate": "Choose date",
    "editor.selectTime": "Choose time",
    "editor.pin": "Pin note",
    "editor.reminder": "Reminder",
    "editor.backLink": "Back to previous linked note",
    "editor.titleAria": "Note title",
    "editor.titlePlaceholder": "Note title",
    "editor.secret": "Secret note",
    "editor.tags": "Tags",
    "editor.newTag": "New tag",
    "editor.cancelNewTag": "Cancel new tag",
    "editor.saveClose": "Save and close",
    "editor.area": "Note area",
    "editor.priority": "Priority",
    "editor.color": "Color",
    "editor.planSelection": "Plan selected text",
    "editor.addTodo": "Add TODO item",
    "editor.deleteNote": "Delete note",

    "backlinks.aria": "Backlinks to this note",
    "backlinks.title": "Links to this note ({count})",
    "backlinks.none": "No links to this note",

    "actions.save": "Save",
    "actions.discard": "Don’t save",
    "actions.ok": "OK",
    "status.done": "Done",
    "secret.mainPassword": "Main password",
    "secret.passwordAgain": "Password again",
    "secret.enterMain": "Enter the main password.",
    "actions.term": "Due date",
    "actions.pin": "Pin",
    "actions.delete": "Delete",
    "actions.more": "More actions",
    "actions.cancel": "Cancel",
    "actions.create": "Create",

    "message.notice": "Notice",
    "editor.notePlaceholder": "Write a note...",
    "tags.name": "Tag name",
    "tags.add": "Add",
    "deleteNote.message": "Do you really want to delete this note?",
    "deleteNote.title": "Delete note?",

    "timePicker.title": "Choose time",
    "timePicker.close": "Close time picker",
    "timePicker.clock": "Time picker clock face",
    "repeat.title": "Repeat",
    "repeat.aria": "Task recurrence",
    "repeat.no": "No",
    "repeat.daily": "Daily",
    "repeat.weekly": "Weekly",
    "repeat.twoWeeks": "2 weeks",
    "repeat.monthly": "Monthly",
    "repeat.none": "Do not repeat",

    "planner.plan": "Plan",
    "planner.close": "Close planning",
    "planner.selectDate": "Choose planned task date",
    "planner.selectTime": "Choose planned task time",

    "settings.title": "Settings",
    "settings.close": "Close settings",
    "settings.appearance": "Appearance",
    "settings.fontSize": "Font size",
    "settings.decreaseFont": "Decrease font size",
    "settings.increaseFont": "Increase font size",
    "settings.theme": "Color theme",
    "settings.iconStyle": "Icon style",
    "settings.reminders": "Reminders",
    "settings.quickDelay": "Quick snooze",
    "settings.configure": "Configure",
    "settings.overdueRetention": "Delete overdue after",
    "settings.overdueNever": "Never",
    "settings.overdueDays": "{count} days",
    "settings.overdueConfirm": "confirm",
    "settings.data": "Data",
    "settings.export": "Export backup",
    "settings.import": "Import backup",
    "settings.about": "About",
    "settings.version": "Version",
    "settings.appInfo": "App information",
    "settings.open": "Open",

    "theme.light": "Light",
    "theme.dark": "Dark",
    "icons.classic": "Classic icons",
    "icons.svg": "SVG icons",

    "about.close": "Close app information",
    "about.description": "Notes, tasks, planning and reminders in one place.",
    "addNote": "Add note",

    "tags.new": "New tag",
    "tags.newSecret": "New secret tag",
    "tags.manage": "Manage tags",
    "tags.closeManage": "Close tag management",
    "tags.deleteTitle": "Delete tag?",

    "secret.saveSecret": "Save as secret",
    "secret.saveNormal": "Save normally",
    "secret.mode": "Secret mode",
    "secret.close": "Close secret mode",
    "secret.fingerprint": "Unlock with fingerprint",
    "secret.nextFingerprint": "🫆 Use fingerprint next time",
    "secret.thisDevice": "Only on this device",
    "secret.unlock": "Unlock",
    "secret.tags": "Secret tags",
    "secret.createTag": "Create secret tag",
    "secret.disableFingerprint": "Disable fingerprint unlock",
    "secret.lock": "Lock secret mode",

    "selection.cut": "Cut",
    "selection.copy": "Copy",
    "selection.paste": "Paste",
    "selection.all": "All",

    "noteLinks.noMatch": "No matching note",
    "noteLinks.create": "+ Create note “{value}”",
    "noteLinks.deleted": "⚠ Deleted note",
    "noteLinks.unavailable": "The target note is no longer available.",
    "noteLinks.previous": "Previous note",
    "noteLinks.createFailed": "The linked note could not be created safely.",
    "noteLinks.ariaTarget": "Internal link to note {value}",
    "noteLinks.ariaMissing": "Internal link to unavailable note",
    "noteLinks.dialogTitle": "Internal link",

    "trash.title": "Trash",
    "trash.secretTitle": "Secret trash",
    "trash.close": "Close Trash",
    "trash.autoDeleteInfo": "Notes are permanently deleted automatically after 30 days.",
    "trash.empty": "Trash is empty.",
    "trash.untitled": "Untitled",
    "trash.noPreview": "No preview",
    "trash.moved": "In trash since",
    "trash.daysLeft": "Permanent deletion in {count} days",
    "trash.restore": "Restore",
    "trash.deleteForever": "Delete forever",
    "trash.deleteForeverTitle": "Delete forever?",
    "trash.deleteConfirm": "This note will be permanently deleted and cannot be restored.",
    "trash.moveTitle": "Move to Trash?",
    "trash.moveMessage": "The note will be moved to Trash and can be restored later.",
    "trash.moveAction": "Move to Trash",
    "trash.moveManyMessage": "Move {count} selected notes to Trash?",
    "trash.movedMany": "Moved to Trash: {count} notes"
  },

  texty: {
    "Přihlášení vypršelo. Přihlas se znovu, aby mohla pokračovat synchronizace. Tvoje lokální data zůstala zachována.": "Your sign-in expired. Sign in again so synchronization can continue. Your local data has been preserved.",
    "Nepodařilo se připojit k synchronizaci. Zkus to znovu po připojení k internetu.": "Could not connect to sync. Try again when you are online.",
    "Ověření přihlášení se nepodařilo.": "Sign-in verification failed.",
    "První přihlášení vyžaduje připojení k internetu.": "Your first sign-in requires an internet connection.",
    "Ověřuji přihlášení…": "Verifying sign-in…",
    "Vyplň e-mail i heslo.": "Enter both email and password.",
    "Přihlášení vyžaduje internet. Lokální aplikace funguje offline až po prvním úspěšném přihlášení.": "Sign-in requires internet. Offline mode is available after the first successful sign-in.",
    "Přihlašuji…": "Signing in…",
    "Přihlášení se nezdařilo. Zkontroluj e-mail, heslo a připojení.": "Sign-in failed. Check your email, password and connection.",
    "Světlý": "Light",
    "Tmavý": "Dark",
    "Původní ikony": "Classic icons",
    "SVG ikony": "SVG icons",
    "Pracovní": "Work",
    "Soukromé": "Private",
    "Bez názvu": "Untitled",
    "Žádná odpovídající poznámka": "No matching note",
    "⚠ Smazaná poznámka": "⚠ Deleted note",
    "Tajný režim": "Secret mode",
    "Tajný režim byl zamčen.": "Secret mode was locked.",
    "Tajný režim byl automaticky zamčen.": "Secret mode was locked automatically.",
    "Tajný režim je odemčený.": "Secret mode is unlocked.",
    "Tajný režim se nepodařilo odemknout.": "Secret mode could not be unlocked.",
    "Tajný režim není odemčený.": "Secret mode is not unlocked.",
    "Zadej hlavní heslo.": "Enter the main password.",
    "Hlavní heslo není správné.": "The main password is incorrect.",
    "Hlavní heslo musí mít alespoň 8 znaků.": "The main password must be at least 8 characters long.",
    "Hlavní heslo se nepodařilo vytvořit.": "The main password could not be created.",
    "Upozornění": "Notice",
    "Nový štítek": "New tag",
    "Název štítku": "Tag name",
    "+ Nový štítek": "+ New tag",
    "Nový tajný štítek": "New secret tag"
  }
});
